devopsdays/devopsdays-web

- data/events/2022-raleigh.yml
[rdu-2022] remove timezone from program
> [rdu-2022] remove timezone from program

- content/events/2022-zurich/sponsor.md
> [ZRH-2022] changed sponsoring packages to sold out

- content/events/2022-raleigh/program/chris-evich.md
[rdu-2022] chris-evich talk title spelling correction
> [rdu-2022] chris-evich talk title spelling correction

- data/events/2022-geneva.yml
> [GE-2022] remove sponsor

- static/events/2022-krakow/organizers/Jakub_Barc.png:Zone.Identifier
A file with a colon had inadvertently been brought into the project. Removing.
> Remove file with colon

- data/events/2022-zurich.yml
> [ZRH-2022] Update Bio of Martin Thalmann

- content/events/2022-portugal/welcome.md
- data/events/2022-portugal.yml
* Remove newsletter from welcome page
> [PT-2022] Remove newsletter

- data/events/2022-raleigh.yml
> [Rdu-2022] schedule updates

- data/events/2022-zurich.yml
> [ZRH-2022] Add sponsor Checkmarx

- content/events/2022-boise/sponsor.md
adding the prospectus for details on sponsorship
> [BOI-2022] adding a link to the prospectus

- data/events/2022-raleigh.yml
[rdu-2022] added pnap as gold sponsor
> [rdu-2022] added pnap as gold sponsor

- data/events/2022-krakow.yml
Hey, we're updating the registration link - old one does not exist.
> [KRK-2022] update registration link

- data/events/2022-los-angeles.yml
[la 2022] remove komodor from LA 2022
> [la 2022] remove komodor from LA 2022

- content/events/2022-krakow/welcome.md
Hey again with the link, I thought `registration_link` in the yaml was responsible for this link and missed it. Sorry for duplication.
> [KRK-2022] update registration link (again)

- data/events/2022-raleigh.yml
[rdu-2022] add nirmata as sponsor
> [rdu-2022] add nirmata as sponsor

- content/events/2022-dallas/welcome.md
- data/events/2022-dallas.yml
- Update Russell's bio 
- Remove odd characters in Meghan's bio
> [DFW-2022] Update Organizer Bios & Remove COVID banner

- data/events/2022-tampa.yml
> [TPA-2022] Updated CFP End Date

- content/blog/support-for-ukraine.md
Since I'm doing a yolo commit here, I am doing a PR to get a deploy preview
> Add aliases for ukraine blog post

- data/events/2022-chicago.yml
> [CHI-2022] Updating Gold Sponsorship

- data/events/2022-chicago.yml
> [CHI-2022] Sponsorship Update

- content/events/2022-chicago/sponsor.md
- data/events/2022-chicago.yml
> [CHI-2022] Update with new dates

- content/events/2022-amsterdam/registration.md
- data/events/2022-amsterdam.yml
This PR updates the AMS 2022 event with:
- Start of the ticket sale ( Early Bird now live )
- Add all sponsor tears with amount of slots
- Add first sponsors
> AMS 2022 bulk update

- data/events/2022-raleigh.yml
> [rdu-2022] adding dynatrace

- content/events/2022-medellin/sponsor.md
- content/events/2022-medellin/welcome.md
- data/events/2022-medellin.yml
[MDE-2022] Adding Call for papers button in Welcome Page
> [MDE-2022] Adding Call for papers button in Welcome Page

- content/events/2022-tampa/sponsor.md
- data/events/2022-tampa.yml
> [TPA] Updated Sponsorship Diamond Amount

- data/events/2022-seattle.yml
> [SEA-2022] Add DoDSea 2022 sponsors

- content/events/2022-portugal/propose.md
- content/events/2022-portugal/welcome.md
- data/events/2022-portugal.yml
> PT-2022 Open CFP

- data/events/2022-raleigh.yml
[rdu-2022] adding nirmata as sponsor
> [rdu-2022] adding nirmata as sponsor

- data/events/2022-raleigh.yml
[rdu-2022] remove neuvector sponsor
> [rdu-2022] remove neuvector sponsor

- content/events/2022-birmingham-uk/welcome.md
our CFP is closed and talks picked
> [BHX-UK-2022] Remove propose talk link

- content/events/2022-london/conduct.md
We're doing a sort of hybrid setup with online tickets so we won't
entirely be identifiable with t-shirts alone and therefore this line
needs to change.
> [LDN-2022] Minor conduct changes

- data/events/2022-zurich.yml
> [ZRH-2022] Added youstream as sponsor

- content/events/2022-geneva/sponsor.md
- content/events/2022-geneva/welcome.md
[[GE-2022] change document link + remove COVID](https://github.com/devopsdays/devopsdays-web/commit/fe6448cfab5897d01eb1fc4e3893243580bcf372)
> [GE-2022] change document link + remove COVID

- content/events/2022-charlotte/conduct-fr.md
- content/events/2022-charlotte/conduct-pt-br.md
- content/events/2022-charlotte/conduct.md
- content/events/2022-charlotte/contact.md
- content/events/2022-charlotte/location.md
- content/events/2022-charlotte/propose.md
- content/events/2022-charlotte/registration.md
- content/events/2022-charlotte/sponsor.md
- content/events/2022-charlotte/welcome.md
- data/events/2022-charlotte.yml
- static/_redirects
We have a confirmed venue and dates and are adding the 2022 Charlotte event! Updates to come as we kick off the planning for this year but wanted to go ahead and get the event with just the dates and location up.
> [CLT-2022] Venue secured, add new event for Charlotte 2022

- data/events/2022-zurich.yml
> [ZRH-2022] Add cloudscale as silver sponsor

- content/events/2022-atlanta/program.md
- data/events/2022-atlanta.yml
Minimum viable schedule
- Added color-coding key for schedule
- 2-day plain text schedule (i.e. no references to talk abstracts or speaker bios)
> [ATL-2022] Atlanta initial schedule in plain text

- data/events/2022-birmingham-uk.yml
Announce our latest sponsor teleport
> [BHX-2022] enable sponsor

- content/events/2022-atlanta/program/ajuna-kyaruzi.md
- content/events/2022-atlanta/program/amber-vanderburg.md
- content/events/2022-atlanta/program/andre-henry.md
- content/events/2022-atlanta/program/jj-ashgar.md
- content/events/2022-atlanta/program/lesley-cordero.md
- content/events/2022-atlanta/program/martin-rojas.md
- content/events/2022-atlanta/program/mason-egger.md
- content/events/2022-atlanta/program/nivia-henry.md
- content/events/2022-atlanta/program/rain-leander.md
- content/events/2022-atlanta/program/rob-richardson.md
- content/events/2022-atlanta/program/waldo-grunenwald.md
- content/events/2022-atlanta/speakers/ajuna-kyaruzi.md
- content/events/2022-atlanta/speakers/amber-vanderburg.md
- content/events/2022-atlanta/speakers/andre-henry.md
- content/events/2022-atlanta/speakers/jj-ashgar.md
- content/events/2022-atlanta/speakers/john-willis.md
- content/events/2022-atlanta/speakers/lesley-cordero.md
- content/events/2022-atlanta/speakers/martin-rojas.md
- content/events/2022-atlanta/speakers/mason-egger.md
- content/events/2022-atlanta/speakers/nivia-henry.md
- content/events/2022-atlanta/speakers/rain-leander.md
- content/events/2022-atlanta/speakers/rob-richardson.md
- content/events/2022-atlanta/speakers/waldo-grunenwald.md
Filled in content for the schedule
- Talk abstracts
- Speaker bios
> [ATL-2022] Schedule content

- data/events/2022-raleigh.yml
[rdu-2022] add edge delta as sponsor
> [rdu-2022] add edge delta as sponsor

- content/events/2022-dallas/sponsor.md
Add paypal links for DFW 2022 to sponsor page
> [DFW-2022] add paypal links

- content/events/2022-zurich/covid.md
- content/events/2022-zurich/welcome.md
> [ZRH-2022] adapted covid concept

- data/events/2022-chicago.yml
> [CHI-2022] Modifying Sponsorship

- data/events/2022-raleigh.yml
[rdu-2022] added aviatrix as happy hour sponsor
> [rdu-2022] added aviatrix as happy hour sponsor

- data/events/2022-nashville.yml
Changing the 2022 date to TBD while we work on a new date
> [NASH-2022] Changing 2022 event date to TBD

- data/events/2021-minneapolis.yml
- data/events/2022-minneapolis.yml
Correction of typo that existed last year as well.
> [MSP 2022] Correction of typo

- data/events/2022-amsterdam.yml
Removing the propose button since our CFP is closed.
> [ams-22] Remove propose element

- data/events/2022-raleigh.yml
> [rdu-2022] remove crowdstrike

- data/events/2022-los-angeles.yml
> [la 22] add buildkite

- data/events/2022-los-angeles.yml
> [la22] add d2iq

- data/events/2022-birmingham-uk.yml
Add new sponsor, update existing sponsor to correct version!
> [BHX-2022] add sponsor

- data/events/2022-birmingham-uk.yml
> [BHX-2022] announce buildkite

- content/events/2022-zurich/speakers/jochen-decker.md
> [ZRH-2022] adapted speaker profile of Jochen Decker

- data/events/2022-amsterdam.yml
> [AMS 2022] Ams sponsor update

- content/events/2022-zurich/program/charity-majors.md
- content/events/2022-zurich/speakers/charity-majors.md
> [ZRH-2022] added abstract and bio for Charity Majors

- content/events/2022-denver/welcome.md
- data/events/2022-denver.yml
> [DEN-2022] Update sponsors and covid policy.

- data/events/2022-birmingham-uk.yml
announce our afternoon schedule and add our latest confirmed sponsor! WOOOO
> [BHX-2022] Add afternoon schedule and sponsor

- data/events/2022-denver.yml
> [DEN-2022] Remove duplicate sponsor, add circleci

- data/events/2022-tampa.yml
> [TPA-2022] Updated Date to Oct 7th

- content/events/2022-aarhus/speakers/nicolas-narbais.md
> [AARHUS-2022] Add speaker bio

- data/events/2022-zurich.yml
> [ZRH-2022] Added Snyk as sponsor

- data/events/2022-seattle.yml
> [SEA-2022] Add 2 sponors

- content/events/2022-atlanta/program/crux-conception.md
- content/events/2022-atlanta/speakers/crux-conception.md
- data/events/2022-atlanta.yml
- Add keynote speaker bio
- Add keynote speaker talk description
- Update keynote timeslot in schedule
- Removed cancelled sessions
> [ATL-2022] Updating keynotes

- content/events/2022-zurich/speakers/jochen-decker.md
> [ZRH-2022] changed bio of Jochen Decker

- content/events/2022-atlanta/location.md
- content/events/2022-atlanta/program/amitai-romanelli.md
- content/events/2022-atlanta/program/cassie-parlotto.md
- content/events/2022-atlanta/program/chris-gruel.md
- content/events/2022-atlanta/program/jade-west.md
- content/events/2022-atlanta/program/lesley-cordero.md
- content/events/2022-atlanta/program/manjula-subramanian.md
- content/events/2022-atlanta/program/ravi-lachhman.md
- content/events/2022-atlanta/program/tonya-jackson.md
- content/events/2022-atlanta/program/waldo-grunenwald-ignite.md
- content/events/2022-atlanta/speakers/amitai-romanelli.md
- content/events/2022-atlanta/speakers/cassie-parlotto.md
- content/events/2022-atlanta/speakers/chris-gruel.md
- content/events/2022-atlanta/speakers/jade-west.md
- content/events/2022-atlanta/speakers/manjula-subramanian.md
- content/events/2022-atlanta/speakers/ravi-lachhman.md
- content/events/2022-atlanta/speakers/tonya-jackson.md
- data/events/2022-atlanta.yml
Schedule updates
- Updated SRE track talk title
- Rearranged talks in schedule
- Added evening event time and link
- Ignite speaker bios and talks
- Ignites in schedule
Bonus
- Location's COVID-19 policy
> [ATL-2022] Schedule updates

- content/events/2022-birmingham-uk/program/luigi-zoso.md
> [BHX-2022] Fix incorect speaker title

- content/events/2022-tampa/location.md
- data/events/2022-tampa.yml
> [TPS-2022] Update location and sponsor

- data/events/2022-los-angeles.yml
> [la 22] add sonatype

- data/events/2022-los-angeles.yml
> [la 22] add gitlab

- content/events/2022-zurich/registration.md
> [ZRH-2022] removed Covid information

- content/events/2022-raleigh/speakers/ashina-sipiora.md
> [2022-RDU] update speaker twitter

- content/events/2022-austin/speakers.md
* including a card based layout instead of just text
> [ATX-2022] Updating speaker list

- content/events/2022-portugal/sponsor.md
- data/events/2022-portugal.yml
> [PT2022] Sponsorship program

- content/events/2022-portugal/welcome.md
- data/events/2022-portugal.yml
* update welcome with sponsors
> [PT2022] update welcome with sponsors

- themes/devopsdays-theme/layouts/events/single.html
this fixes the /events page to remove canceled events
> Fix cancel event list for events page

- data/events/2022-chicago.yml
> [CHI-2022] Adding Sponsor

- content/events/2022-atlanta/program/brooks-townsend.md
- content/events/2022-atlanta/program/david-laribee.md
- content/events/2022-atlanta/program/rob-gordick.md
- content/events/2022-atlanta/speakers/brooks-townsend.md
- content/events/2022-atlanta/speakers/david-laribee.md
- content/events/2022-atlanta/speakers/rob-gordick.md
- data/events/2022-atlanta.yml
- Add ignite
- Add track talk
- Add keynote
> [ATL-2022]

- content/events/2022-tampa/sponsor.md
> Updated Number of Plat

- data/events/2022-montreal.yml
Fixed sponsor categories and added link to sponsorship deck
> Montreal 2022

- content/events/2022-eindhoven/sponsor.md
- data/events/2022-eindhoven.yml
Add the prospectus and the sponsor options for EHV 2022.
> [EHV 2022] Setup sponsor options

- data/events/2022-denver.yml
> [DEN-2022] Add OpsCruise as Supporter Sponsor

- data/events/2022-aarhus.yml
> [AARHUS-2022] Update program

- data/events/2022-boston.yml
We were (finally!) able to lock in dates with our venue.
> [BOS-2022] Updating Boston's date

- data/events/2022-minneapolis.yml
[MSP-2022] Added Clumio as Silver Sponsor
> [MSP-2022] Added Clumio as Silver Sponsor

- content/events/2022-birmingham-uk/covid.md
- data/events/2022-birmingham-uk.yml
Amend schedule and update covid policy
> [BHX-2022] amend shedule and update covid policy

- content/events/2022-dallas/welcome.md
- data/events/2022-dallas.yml
open cfp 
update bio for jessica sabugo
> [DFW-2022] open cfp

- data/events/2022-dallas.yml
> [DFW-2022] Opening CFP dates

- data/events/2022-tampa.yml
> [TPA-2022] Adding Clumio as Plat Sponsor

- content/events/2022-detroit/conduct-fr.md
- content/events/2022-detroit/conduct-pt-br.md
- content/events/2022-detroit/conduct.md
- content/events/2022-detroit/contact.md
- content/events/2022-detroit/location.md
- content/events/2022-detroit/propose.md
- content/events/2022-detroit/registration.md
- content/events/2022-detroit/sponsor.md
- content/events/2022-detroit/welcome.md
- data/events/2022-detroit.yml
- static/_redirects
> [DET-2022] adding 2022 event

- data/events/2022-seattle.yml
Adding the following sponsors
- Kong
- Blameless
- Clumio
> [SEA-2022] Add sponsors

- data/events/2022-zurich.yml
> [ZRH-2022] change talks of Itiel and Lian

- content/events/2022-denver/welcome.md
> [DEN-2022] Add Livestream Link

- data/events/2022-zurich.yml
> [ZRH-2022] added powercoders as sponsor

- content/events/2022-aarhus/welcome.md
- data/events/2022-aarhus.yml
> [AARHUS-2022] Update frontpage and program

- data/events/2022-chicago.yml
> [CHI-2022] Adding Silver Sponsor Clumio

- content/events/2022-portugal/propose.md
- content/events/2022-portugal/welcome.md
- data/events/2022-portugal.yml
Couple of updates:
* fixed some of the organizers company names
*  organized the welcome page
*  added mailchimp mailing list subscription form on welcome page
*  added a few buttons on the propose page
> [PORTUGAL-2022] Update welcome, contacts and propose pages

- data/events/2022-portugal.yml
> [PT-2022] - Changing Julia Lamenza's Bio

- data/events/2022-chicago.yml
> [CHI-2022] Updating Sponsorship Details

- content/events/2022-denver/welcome.md
- data/events/2022-denver.yml
> [DEN-2022] Day 2 Replay Link

- content/events/2022-boise/welcome.md
Cleans up the Boise `welcome.md` by removing `propose` and unhiding `location`.
Thank you @mattstratton for catching this one!
> [BOI-2022] removes `propose` and unhides `location` on `welcome.md`

- data/events/2022-boise.yml
Moves speaker to a different room.
> [BOI-2022] moves speaker to different room

- content/events/2022-berlin/welcome.md
- data/events/2022-berlin.yml
Added everything necessary to start this year's CfP for Berlin 2022.
> [BLN-2022] Start CfP on May 1st

- content/events/2022-berlin/propose.md
> [BLN-2022] Add pretalx link to 'propose' page

- data/events/2022-minneapolis.yml
Giving folks a teensy bit more time!
> [MSP 2022] Extending CFP

- data/events/2022-seattle.yml
> [SEA-2022] Add 2 new sponsors

- content/events/2022-zurich/diversity.md
> [ZRH-2022] updated diversity page

- content/events/2022-zurich/speakers/lian-li.md
> [ZRH-2022] updated Lian Li profile

- content/events/2022-geneva/program/stephanie-fischer.md
> [GE-2022] update program

- data/events/2022-zurich.yml
> [ZRH-2022] add Splunk as sponsor

- content/events/2022-portugal/registration.md
- data/events/2022-portugal.yml
* Added registration (only blind tickets)
> [PT2022] Added registration

- data/events/2022-amsterdam.yml
> [AMS 2022] Sponsor update

- content/events/2022-seattle/program/aja-hammerly.md
- content/events/2022-seattle/sponsor.md
- data/events/2022-seattle.yml
Add new sponsor
update Aja's talk
add a la carte
> [SEA-2022] sponsor and other updates

- content/events/2022-birmingham-uk/welcome.md
- data/events/2022-birmingham-uk.yml
Change to add new speaker, and add our openspace web link
> BHX-2022 new speaker and link

- content/events/2022-minneapolis/propose.md
- content/events/2022-minneapolis/welcome.md
- data/events/2022-minneapolis.yml
> [MSP 2022] close CFP

- data/events/2022-tampa.yml
[TPA-2022] Added Env0 as Plat Sponsor
> [TPA-2022] Added Env0 as Plat Sponsor

- content/events/2022-detroit/location.md
- content/events/2022-detroit/welcome.md
- data/events/2022-detroit.yml
> [DET-2022] added propose link and location information

- data/events/2022-minneapolis.yml
> [MSP 2022] Adding sponsors

- data/events/2022-dallas.yml
> [DFW-2022] Adding 4 new sponsors

- content/events/2022-amsterdam/welcome.md
When you all copied from Chicago, you made a typo :)
> [2022-AMS] Fix typo

- content/events/2022-tampa/sponsor.md
- data/events/2022-tampa.yml
[TPA-2022] Added Sponsor Spectro Cloud
> [TPA-2022] Added Sponsor Spectro Cloud

- data/events/2022-minneapolis.yml
> [MSP-2022] Added SpectroCloud as Gold Sponsor

- data/events/2022-dallas.yml
> [DFW-2022] Adding cprime as a Sponsor

- data/events/2022-seattle.yml
> [SEA-2022] Add sponsor

- content/events/2022-chicago/sponsor.md
> [CHI-2022] Sold out of gold and silver

- data/events/2022-zurich.yml
> [ZRH-2022] add Dynatrace as sponsor

- data/events/2022-chicago.yml
adding new relic, opscruise and circleci sponsor logos
> [CHI-2022] sponsor logo add

- content/events/2022-boston/sponsor.md
Truing this text up with what's in our PDF prospectus (the source of truth).
> [BOS-2022] Update sponsor page to drop "virtual" reference.

- content/events/2022-washington-dc/sponsor.md
Update sponsor page with slots and attendee info
> [DC-2022] Update sponsor page with slots and attendee info

- content/events/2022-dallas/welcome.md
> [DFW-2022] Adding generic COVID-19 Policy

- data/events/2022-charlotte.yml
add spectrocloud at gold level
> [CLT-2022] Add spectrocloud as gold sponsor for charlotte-2022

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Gitlab and Cloudbees as Sponsors

- data/events/2022-chicago.yml
> [CHI-2022] activate registration

- data/events/2022-washington-dc.yml
> [DC-2022] - Turn on the "Propose" navigation link

- data/events/2022-dallas.yml
> [DFW-2022] Adding 2 new Silver sponsors

- data/events/2022-seattle.yml
> [SEA-2022] add sponsors:

- content/events/2022-zurich/location.md
- content/events/2022-zurich/program/andrew-martin.md
- content/events/2022-zurich/program/joseph-katsioloudes.md
- content/events/2022-zurich/program/m-psych.md
- content/events/2022-zurich/program/mark-heistek.md
- content/events/2022-zurich/program/ricardo-castro.md
- data/events/2022-zurich.yml
> [ZRH-2022] changes of cw20

- data/events/2022-prague.yml
> [PRG-2022] Add Pure Storage as a sponsor

- content/events/2022-detroit/sponsor-registration.md
- content/events/2022-detroit/sponsor.md
- data/events/2022-detroit.yml
> [DET-2022] adding initial sponsorship level information

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Replicated As Silver Sponsor

- content/events/2022-seattle/sponsor-info.md
> [SEA-2022] Add a sponsor-info page

- data/events/2022-chicago.yml
adding trendmicro as silver sponsor
> [CHI-2022] trend as silver

- content/events/2020-salt-lake-city/welcome.md
- data/events/2020-salt-lake-city.yml
Apparently I pushed this to my fork, but never created a PR for upstream. Not really relevant now, but for historical purposes I'm updating this. 2022 dates coming next!
> [SLC-2020] Postpone event due to COVID-19 concerns

- data/events/2022-charlotte.yml
> [CLT-2022] add 42crunch gold sponsor for charlotte 2022

- content/events/2022-zurich/program/joseph-katsioloudes.md
> [ZRH-2022] Changed workshop description for Joseph

- content/events/2022-tampa/sponsor.md
[TPA-2022] Adding details to sponsor page
> [TPA-2022] Adding details to sponsor page

- content/events/2022-amsterdam/program/ws-suzanne-lagerweij.md
- data/events/2022-amsterdam.yml
Glenn will not be able to give his workshop.
> [AMS 2022] removed Glenn from schedule

- data/events/2022-zurich.yml
> [ZRH-2022] Change Time of Workshop from Joseph K.

- data/events/2022-zurich.yml
> [ZRH-2022] moved Anands workshop

- data/events/2022-chicago.yml
Updates spacelift's level and closes gold and silver links (maybe, lol)
> [CHI-2022] Update spacelift to silver

- data/events/2022-washington-dc.yml
Also, remove apparent cruft from `sponsors` that's already in `sponsor_levels`
> [DC-2022] Add Spectrocloud, tweak pburkholder

- data/events/2022-washington-dc.yml
- data/sponsors/spacelift.yml
Correct case, URL, add Twitter for spacelift.io
Add Spacelift as Platinum sponsor
> [DC-2022] Add Spacelift as Platinum sponsor, also fix spacelift data

- content/events/2022-eindhoven/registration.md
- content/events/2022-eindhoven/welcome.md
- data/events/2022-eindhoven.yml
Signed-off-by: yvovandoorn <yvo.vandoorn@gmail.com>
- iframe for ticket sales
- add covid text
- add homepage text
> [EHV-2022] Launch Eindhoven registration and links

- data/events/2022-charlotte.yml
adding cfp / registration dates & links for charlotte 2022
> [CLT-2022] Add cfp and registration for clt-2022

- content/events/2022-amsterdam/program/nathen-amanda.md
There are six things in this numbered list, not 5
This fixes a small typo in the list.
> [AMS-2022] Fix issue with numbered list

- data/events/2022-dallas.yml
[DFW2022] add gold sponsor bitdefender and trendmicro
> [DFW2022] add gold sponsor bitdefender and Trend Micro

- content/events/2022-tampa/sponsor.md
- data/events/2022-tampa.yml
[TPA-2022] Adding 42 Crunch as Diamond Sponsor
> [TPA-2022] Adding 42 Crunch as Diamond Sponsor

- content/events/2022-fortaleza/sponsor.md
> [FOR2022] - Update info sponsor

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Medtronic as Silver Sponsor

- content/events/2022-chicago/covid-19-policy.md
- content/events/2022-chicago/welcome.md
- data/events/2022-chicago.yml
> [CHI-2022] Add Covid policy

- data/events/2022-los-angeles.yml
> [la 22] add stormforge

- content/events/2022-amsterdam/sponsor.md
- data/events/2022-amsterdam.yml
> [AMS-22] Stop accepting sponsorships and redirect sponsors to Eindhoven

- content/events/2023-los-angeles/conduct-fr.md
- content/events/2023-los-angeles/conduct-pt-br.md
- content/events/2023-los-angeles/conduct.md
- content/events/2023-los-angeles/contact.md
- content/events/2023-los-angeles/location.md
- content/events/2023-los-angeles/propose.md
- content/events/2023-los-angeles/registration.md
- content/events/2023-los-angeles/sponsor.md
- content/events/2023-los-angeles/welcome.md
- data/events/2023-los-angeles.yml
> [la 2023] add website for 2023

- content/events/2022-amsterdam/program/keynote-job-van-der-voort.md
- content/events/2022-amsterdam/program/keynote-liz-rice.md
Updates to the keynotes from Liz and Job.
> [AMS 2022] Updates to the keynotes

- data/events/2022-vitoria.yml
> [VIX-2022] change of sponsors

- content/events/2022-charlotte/propose.md
- content/events/2022-charlotte/registration.md
- content/events/2022-charlotte/welcome.md
- data/events/2022-charlotte.yml
Updating these pages to make registration and propose links easier to find
> [CLT-2022] Update welcome/propose/registation pages

- data/events/2022-detroit.yml
> [DET-2022] fix capitalization

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Sonatype as Gold Sponsor

- content/events/2022-seattle/sponsor-info.md
- data/events/2022-seattle.yml
Add A/V contact info to sponsor-info page
Add sponsors
pure-storage
site24x7
seattle-coffeeops
seattle-devops-meetup
> [SEA-2022] Sponsor updates

- content/events/2022-amsterdam/conduct.md
- data/events/2022-amsterdam.yml
Add Albert Heijn as bronze sponsor
Update the code of conduct to mention the freedom to use a protective mask if you'd like and not made fun of.
> [AMS 2022] Multiple updates

- content/events/2022-buffalo/welcome.md
- data/events/2022-buffalo.yml
- Add registration for 2022
- Remove link to CFP as that is now over
> [BUF-2022] Add Registration

- content/events/2022-dallas/sponsor.md
> [DFW2022] close sponsorships

- data/events/2022-dallas.yml
> [DFW-2022] Adding Nirmata and CircleCI as a sponsors

- data/events/2022-montreal.yml
Adding the first set of sponsors
> [Montreal-2022] Add Dynatrace and SUSE as sponsors

- data/events/2022-charlotte.yml
Adding PhoenixNAP at silver level for Charlotte 2022
> [CLT-2022] Add a sponsor

- data/events/2022-charlotte.yml
Another sponsor just came through shortly after my last PR. Adding tonic at gold level for Charlotte 2022.
> [CLT-2022] Adding a sponsor

- content/events/2022-rio-de-janeiro/sponsor.md
> RIO/2022 - new tickets informations

- content/events/2022-amsterdam/program/ws-wolter-kamphuis.md
Got an updated description for Wolter's workshop.
> [AMS 2022] update description of Wolter's workshop

- data/events/2022-washington-dc.yml
Add sponsor macstadium for Washington DC - Gold
> [DC-2022] Add sponsor macstadium for Washington DC

- content/events/2022-des-moines/sponsor.md
- data/events/2022-des-moines.yml
> [DSM-2022] Add sponsorship information

- content/events/2022-des-moines/sponsor.md
Add options to pay via WaveApp for Gold and Social sponsorships
> [DSM-2022] Add sponsorship pay buttons

- data/events/2022-london.yml
They've now paid so we'll add their branding to the website!
> [LDN-2022] Add Harness as Silver Sponsor

- content/events/2022-detroit/sponsor.md
Note:  This PR **SHOULD NOT** be merged until this `devopsdays-assets` PR is merged: https://github.com/devopsdays/devopsdays-assets/pull/134
> [DET-2022]Adding sponsor prospectus/package information

- data/events/2022-amsterdam.yml
Last minute changes, who doesn't love those? Me, I don't like those.
> [AMS 2022] Update workshop sched

- data/events/2022-dallas.yml
Adding 2 new Community spponsors.
> [DFW-2022] Add Octopus as a sponsor

- data/events/2022-buffalo.yml
Add M&T and CircleCi as sponsors.
> [BUF-2022] Add M&T and CircleCi as sponsors

- data/sponsors/gologic.yml
> [Montreal 2022] Fix Gologic link

- data/events/2022-washington-dc.yml
Adding registration link and registration dates.
> [DC-2022] Add registration link

- data/events/2022-washington-dc.yml
> [DC-2022] Welcome Gold Sponsor Sicura

- content/events/2022-amsterdam/welcome.md
Do not merge without @yvovandoorn approval (please confirm link)
> [2022-AMS] Add livestream link

- content/events/2022-amsterdam/welcome.md
I need to be better at testing.
> [AMS-2022] fix the livestream link

- data/events/2022-washington-dc.yml
Uncommented "register" in yml file to add "Registration" option to navigation for the event.
> [DC-2022] Add registration to top nav

- content/events/2022-eindhoven/welcome.md
Remove all references to dod AMS
> [EHV 2022] Update Eindhoven welcome page

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Tonic as Gold sponsor

- content/events/2022-los-angeles/program.md
- content/events/2022-los-angeles/program/brian-scott.md
- content/events/2022-los-angeles/program/dan-lines.md
- content/events/2022-los-angeles/program/hannah-henderson.md
- content/events/2022-los-angeles/program/jeremy-meiss.md
- content/events/2022-los-angeles/program/matty-stratton.md
- content/events/2022-los-angeles/program/ryder-damen.md
- content/events/2022-los-angeles/program/steve-pereira.md
- content/events/2022-los-angeles/program/tony-loehr.md
- content/events/2022-los-angeles/speakers.md
- content/events/2022-los-angeles/speakers/brian-scott.md
- content/events/2022-los-angeles/speakers/dan-lines.md
- content/events/2022-los-angeles/speakers/hannah-henderson.md
- content/events/2022-los-angeles/speakers/jay-medrano.md
- content/events/2022-los-angeles/speakers/jeremy-meiss.md
- content/events/2022-los-angeles/speakers/justice-london.md
- content/events/2022-los-angeles/speakers/kevin-nelson.md
- content/events/2022-los-angeles/speakers/matty-stratton.md
- content/events/2022-los-angeles/speakers/ryder-damen.md
- content/events/2022-los-angeles/speakers/steve-pereira.md
- content/events/2022-los-angeles/speakers/tony-loehr.md
- content/events/2022-los-angeles/welcome.md
- data/events/2022-los-angeles.yml
- Adding program
- Adding speakers
- Adding nav links
**Tested:**
> [LA 2022] Adding program and speakers

- data/events/2022-amsterdam.yml
We direct people to the website for the must up to date schedule. Please merge at your earliest convenience.
> [AMS 2022] Update schedule to reflect changes

- content/events/2022-dallas/sponsor.md
add gold and silver sponsorships back to site
> [DFW-2022] add gold and silver sponsorships back to site

- data/events/2022-portugal.yml
> [PT2022] Fixing duplicate sponsors

- content/events/2022-dallas/speakers/andrew-clay-shafer.md
- content/events/2022-dallas/speakers/john-willis.md
- content/events/2022-dallas/speakers/michael-cote.md
- content/events/2022-dallas/speakers/nigel-thurlow.md
- content/events/2022-dallas/speakers/patrick-debois.md
- content/events/2022-dallas/speakers/thomas-j-sweet.md
> [DFW-2022] Making changes to descriptions for speakers

- data/events/2022-dallas.yml
> [DFW-2022] Changing organizer employer names

- data/events/2022-dallas.yml
> [DFW-2022] Updating 1 more organizer employer

- data/events/2022-berlin.yml
> [BER-2022]update cpanato affiliation

- content/events/2022-portugal/speakers/ara-pulido.md
> [PT2022] Added speaker - Ara Pulido

- content/events/2022-chicago/registration.md
> [CHI-2022] Add reg page just in case

- data/events/2022-washington-dc.yml
- data/sponsors/vivanti.yml
[DC-2022] Add vivanti to DC, and their twitter handle
> [DC-2022] Add vivanti to DC, and their twitter handle

- content/events/2022-eindhoven/propose.md
- data/events/2022-eindhoven.yml
- Remove emailing as a web to submit
- Add sessionize
- Add CFP announce date
> [EHV-2022] Add sessionize link &  CFP announce date. 

- data/events/2022-fortaleza.yml
> [FOR-2022] feat: add cfp fortaleza 2022

- data/events/2022-rio-de-janeiro.yml
> [RIO-2022] Link for CFP

- content/events/2022-rio-de-janeiro/welcome.md
- data/events/2022-rio-de-janeiro.yml
> [RIO/2022] Program add and cfp update

- content/events/2022-rio-de-janeiro/program.md
- content/events/2022-rio-de-janeiro/welcome.md
> [RIO/2022] add page program

- data/events/2022-boston.yml
Also tweaked sponsorship levels to be in line with reality.
> [BOS-2022] New Boston sponsors

- data/events/2022-minneapolis.yml
> [MSP 2022] Adding SPS and Octopus

- data/events/2022-houston.yml
[HOU-2022] Added sponsor, corrected sponsor levels
> [HOU-2022] Added sponsor, corrected sponsor levels

- data/events/2022-buffalo.yml
Add Vivanti as Silver sponsor.
> [BUF-2022] Add Vivanti as Silver sponsor.

- data/events/2022-dallas.yml
> {DFW-2022] Adding mattermost as a sponsor

- data/events/2022-charlotte.yml
> [CLT-2022] Add sponsors for Charlotte 2022

- content/events/2022-fortaleza/sponsor.md
- data/events/2022-fortaleza.yml
> [FOR-2022] Add link registration event

- content/events/2022-dallas/location.md
> [DFW-2022] Minor cosmetic changes to Location page

- data/events/2022-los-angeles.yml
> [la22] add snyk

- data/events/2022-tampa.yml
[TPA-2022] Added DataDog as sponsor
> [TPA-2022] Added DataDog as sponsor

- data/events/2022-los-angeles.yml
> [la22] add firehydrant

- data/events/2022-los-angeles.yml
> [LA-2022] update sponsors

- data/events/2022-houston.yml
[HOU-2022] Added Edge Delta as Platinum sponsor
> [HOU-2022] Added Edge Delta as Platinum sponsor

- data/sponsors/kosli.yml
You can check at https://twitter.com/_kosli/
> [DC-2022] Fix Kosli's twitter

- data/events/2022-boston.yml
> [BOS-2022] Mattermost sponsorship

- content/events/2022-minneapolis/program/noelle-notermann.md
Workshopped title and talk and tightened it up.
> Updating Noelle's talk based on her email

- content/events/2022-minneapolis/speakers/keith-mattix.md
> [MSP-2022] Update keithmattix bio

- data/core.toml
> Add Floor Drees and Jason Yee to core

- content/events/2022-seattle/sponsor-info.md
- content/events/2022-seattle/welcome.md
- data/events/2022-seattle.yml
- fix type in sponsor-info
- Remove sponsor us links
> [SEA-2022] more updates

- data/events/2022-rio-de-janeiro.yml
> [RIO/2022] LinuxTips sponsoring

- data/events/2022-dallas.yml
> [DFW-2022] Adding Snyk as new sponsor

- data/events/2022-houston.yml
> [HOU-2022] Extended CFP

- content/page/organizing.md
same thing as https://github.com/devopsdays/devopsdays-web/pull/8957 but a dash instead of an apostrophe. So I am also fixing this :)
> Remove dash in video recording and streaming header on organizing guide

- data/events/2022-minneapolis.yml
> Adjustments and fixes to MSP schedule

- data/sponsors/mnclude.yml
> [MSP 2022] Fixing link that has changed

- content/events/2022-cairo/sponsor.md
- content/events/2022-cairo/welcome.md
- data/events/2022-cairo.yml
Updating sponsorship and welcome page
> [CAI-22] Updating sponsorship and welcome page

- data/events/2022-minneapolis.yml
> [MSP-2022] Added DataDog and Snyk as Silver and Gold sponsors

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Couchbase and LaunchDarkly as Silver sponsors

- data/events/2022-beijing.yml
The conference was postponed to August due to COVID-19.
> [PEK-2022]The conference was postponed to August due to COVID-19.

- data/events/2022-berlin.yml
> [BER-2022] Add CircleCI as sponsor

- data/events/2022-berlin.yml
Sorry for adding sponsors one after the other, but we're going strictly
by money getting to our bank :)
> [BER-2022] - Add polar squad as a sponsor

- content/events/2022-minneapolis/speakers/noelle-notermann.md
> [MSP 2022] Speaker bio update

- content/events/2022-minneapolis/program.md
- content/events/2022-minneapolis/welcome.md
Adding Livestream and Open Space Schedule links to both the welcome and program pages.
> [MSP 2022] Add Livestream and Daily Open Spaces Schedule Links

- content/events/2022-minneapolis/speakers/sophia-stratton.md
> [2022-MSP] Update Sophia bio

- content/events/2022-minneapolis/covid-19-policy.md
- data/events/2022-minneapolis.yml
Adding more detail to the mask + vax policy; adding sponsor.
> [MSP 2022] Adding sponsor and clarifying mask plus vax policy

- content/events/2022-los-angeles/covid.md
- content/events/2022-los-angeles/welcome.md
- data/events/2022-los-angeles.yml
- Added new COVID-19 page
- Created a link in the welcome page
- COVID-19 policy taken from SCALE19x [website](https://www.socallinuxexpo.org/blog/scale-19x-and-covid-19)
**Tested:**
> [LA 2022] Adding updated COVID-19 policy page

- content/events/2022-los-angeles/program/brian-scott.md
- content/events/2022-los-angeles/program/jeremy-meiss.md
- data/events/2022-los-angeles.yml
- Changing talk's title and abstract
- Updating talk's starting time
**Tested:**
> [LA 2022] Small program updates

- content/events/2022-fortaleza/welcome.md
- data/events/2022-fortaleza.yml
> [FOR-2022] - Update info and Add Sponsor

- data/events/2022-detroit.yml
Added Dynatrace as a silver sponsor
> [DET-2022] Add Dynatrace as a sponsor

- content/events/2022-chicago/volunteer.md
- data/events/2022-chicago.yml
> [CHI-2022] Add volunteer page

- content/events/2022-minneapolis/registration.md
- content/events/2022-minneapolis/sponsor.md
- content/events/2022-minneapolis/welcome.md
- data/events/2022-minneapolis.yml
Sponsorships and registration are now closed.
> [MSP 2022] MSP has closed registration and sponsorships.

- content/events/2022-chicago/speaker-info.md
(yes, I know it's not in the navigation. this is by design)
> [CHI-2022] Add speaker info page

- content/events/2022-dallas/sponsor.md
> [DFW-2022] closing sponsorship for 2022

- content/events/2022-chicago/volunteer.md
> [CHI-2022] fix typo on volunteer form

- data/events/2022-minneapolis.yml
> [MSP 2022] Tonic sponsor needed to cancel

- content/events/2022-los-angeles/program/tony-fatouros.md
- content/events/2022-los-angeles/speakers/tony-fatouros.md
- data/events/2022-los-angeles.yml
- Last minute program update
- Canceling workshop due to COVID
- Updating speaker talk/bio
**Tested:**
> [LA 2022] Program update due to COVID

- content/events/2022-detroit/speakers/matty-stratton.md
Remove outdated bio and update headshot
> [DET-2022] Update Matty bio

- data/events/2022-berlin.yml
> [BER-2022] Add elastic as sponsor

- content/events/2022-minneapolis/welcome.md
> [MSP 2022] Updating Slack invite link

- content/events/2022-minneapolis/program/keith-mattix.md
- content/events/2022-minneapolis/speakers/michelle-dhanani.md
> [MSP 2022] Editing errors

- data/events/2022-dallas.yml
> [DFW-2022] Adding new sponsor

- content/events/2022-minneapolis/program/rukia-sheikh-mohamed.md
Added based on Rukia's practice talk.
> [MSP-2022] Add talk description for Rukia

- data/events/2022-dallas.yml
> [DFW-2022] Add new Silver sponsor

- data/events/2022-chicago.yml
> [CHI-2022] Updating Sponsorship

- content/events/2022-recife/local.md
- content/events/2022-recife/welcome.md
- data/events/2022-recife.yml
Add Recife call for paper and event location
> Add Recife 2022 cfp and location

- data/events/2022-bengaluru.yml
Add Prateek as organiser of Bengaluru 2022 event.
cc @vjdhama
> [Bengaluru-2022] Add Prateek as organiser

- content/events/2022-dallas/program/andrew-john-talk.md
> [DFW-2022] Talk update

- content/events/2022-tampa/sponsor.md
> [TPA-2022] Updated remaining sponsorships

- data/events/2023-salt-lake-city.yml
This is my suggested temporary patch for the problem noted in https://github.com/devopsdays/devopsdays-web/issues/11555. @Clait or another SLC organizer will need to approve this PR before it is merged.
> [SLC 2023] Fixing the SLC code of conduct link

- data/events/2022-tel-aviv.yml
> [TLV-2022] Sponsors Fix

- content/events/2022-chicago/sponsor-info.md
> [CHI-2022] Add sponsor-info page

- data/events/2022-dallas.yml
> [DFW-2022] Removing navbar for Propose & Sponsor

- data/events/2022-dallas.yml
> Revert "[DFW-2022] Removing navbar for Propose & Sponsor"

- data/events/2022-berlin.yml
> [BLN-2022] add cloudbees as sponsor

- data/events/2022-cairo.yml
> [CAI-22] Extending CFP

- content/events/2022-chicago/sponsor-info.md
> [CHI-2022] update sponsor info

- data/events/2022-chicago.yml
> [CHI-2022] Editing Sponsorhip

- content/events/2022-eindhoven/welcome.md
- Remove Propose link
- Add links to Program & Speakers
> [EHV-2022] Add program & speakers page to welcome page

- content/events/2022-dallas/program/patrick-debois.md
> [DFW-2022] Updating Talk Abstract for Patrick

- content/events/2022-london/location.md
- content/events/2022-london/speakers/kief-morris.md
- data/events/2022-london.yml
We noticed that we had all male speakers for the first day so we had to
re-arrange a few things.
To do this we wrote a simple shuffler, put names in and then got the
output.
Kief morris also required some changes to his bio so I've copy pasted these.
> [LDN-2022] Alter ignite speakers and order.

- content/events/2022-tampa/location.md
- content/events/2022-tampa/registration.md
- content/events/2022-tampa/welcome.md
- data/events/2022-tampa.yml
[TPA 2022] Added Registration and Location
> [TPA 2022] Added Registration and Location

- data/events/2022-rio-de-janeiro.yml
> [RIO-2022] new sponsor: zivra

- content/events/2022-chicago/sponsor-info.md
> [CHI-2022] Add AV rental form

- data/events/2022-boston.yml
So that we do not have a break, a talk, and then lunch.
> [BOS-2022] Move lunch later in the day

- data/events/2022-washington-dc.yml
* Add community tier
* Add Harness and F5-nginx
* Diamanti to Gold
> [DC-2022] Add community tier

- content/events/2022-portugal/program/manuel-pais.md
- content/events/2022-portugal/program/mark-schwartz.md
* Program update - mark schwartz: speed and control
> [PT2022] Program update - mark schwartz: speed and control

- content/events/2022-dallas/program/michael-cote.md
- content/events/2022-dallas/program/nigel-thurlow.md
> [DFW-2022] Speaker updates

- content/events/2022-berlin/program.md
- content/events/2022-berlin/program/andriy-bilous.md
- content/events/2022-berlin/program/christian-hueser.md
- content/events/2022-berlin/program/ewelina-wilkosz.md
- content/events/2022-berlin/program/florian-haas.md
- content/events/2022-berlin/program/iris-hunkeler.md
- content/events/2022-berlin/program/jemma-bolland.md
- content/events/2022-berlin/program/jorge-castro.md
- content/events/2022-berlin/program/kris-buytaert.md
- content/events/2022-berlin/program/marcel-britsch.md
- content/events/2022-berlin/program/philipp-krenn.md
- content/events/2022-berlin/program/radovan-bacovic.md
- content/events/2022-berlin/program/schlomo-schapiro.md
- content/events/2022-berlin/program/swathi-poddar.md
- content/events/2022-berlin/program/to-be-announced-ignite.md
- content/events/2022-berlin/program/to-be-announced.md
- content/events/2022-berlin/speakers.md
- content/events/2022-berlin/speakers/ewelina-wilkosz.md
- content/events/2022-berlin/speakers/swathi-poddar.md
- content/events/2022-berlin/speakers/to-be-announced-ignite.md
- content/events/2022-berlin/speakers/to-be-announced.md
- data/events/2022-berlin.yml
First version of the program goes online, one speaker has been added and all the program/speaker.md files are new.
> [BER-2022] First version of the schedule is online

- data/events/2022-berlin.yml
> [BER-2022] Urgent fix: Forgot to add one ignite

- content/events/2022-portugal/program/antoine-craske.md
- content/events/2022-portugal/program/ara-pulido.md
- content/events/2022-portugal/program/bruno-amaro.md
- content/events/2022-portugal/program/filipi-pires.md
- content/events/2022-portugal/program/manuel-pais.md
- content/events/2022-portugal/program/matheus-paes.md
- content/events/2022-portugal/program/naomi-kriger.md
- content/events/2022-portugal/program/philipp-krenn.md
- content/events/2022-portugal/program/rinor-maloku.md
- content/events/2022-portugal/program/sarjeel-yusuf.md
adopted Wikipedia title casing rules (I hope) to gain some consistency
> [PT-2022] fixed title casing on talks

- content/events/2022-chicago/speakers/abby-allen.md
> [CHI-2022] Update Abby Allen bio

- data/events/2022-chicago.yml
pending approval from chicago sponsor team
> [CHI-2022] Set evening event max

- data/sponsors/kanbanize.yml
> [ZRH-2023] Fixed link of sponsor kanbanize

- content/events/2022-tampa/location.md
- content/events/2022-tampa/welcome.md
- data/events/2022-tampa.yml
> [TPA-2022]Updating Location and Welcome Page

- data/events/2022-charlotte.yml
> [CLT-2022] Add acorn as gold sponsor for Charlotte 2022

- content/events/2022-tampa/registration.md
[TPA-2022] Missing Div on Registration
> [TPA-2022] Missing Div on Registration

- data/events/2022-houston.yml
[HOU-2022] Added anjuna as Silver sponsor
> [HOU-2022] Added anjuna as Silver sponsor

- data/sponsors/progresschef.yml
https://github.com/devopsdays/devopsdays-web/issues/11750
> Propose change to address Issue #11750

- data/events/2022-charlotte.yml
add cloudbees at gold for charlotte 2022
> [CLT-2022] add sponsor for charlotte 2022

- content/events/2022-chicago/volunteer.md
- data/events/2022-chicago.yml
- Removes the link to the volunteer page
- Updates page to remove form and say we are full on volunteers
> [CHI-2022] Close volunteers

- content/events/2022-minneapolis/program/anusha-malledi.md
- content/events/2022-minneapolis/program/dormain-drewitz.md
- content/events/2022-minneapolis/program/dylan-miracle.md
- content/events/2022-minneapolis/program/ian-malpass.md
- content/events/2022-minneapolis/program/keith-mattix.md
- content/events/2022-minneapolis/program/kelsey-hightower.md
- content/events/2022-minneapolis/program/marino-wijay.md
- content/events/2022-minneapolis/program/michelle-dhanani.md
- content/events/2022-minneapolis/program/nocnica-mellifera.md
- content/events/2022-minneapolis/program/noelle-notermann.md
- content/events/2022-minneapolis/program/rukia-sheikh-mohamed.md
- content/events/2022-minneapolis/program/sigstore.md
- content/events/2022-minneapolis/program/sophia-stratton.md
- content/events/2022-minneapolis/program/taylor-barnett.md
- content/events/2022-minneapolis/program/trip-longworth.md
- content/events/2022-minneapolis/program/xander-grzywinski.md
Adding links to videos (and fixing a talk title that was missing characters).
> [MSP 2022] Adding videos for MSP 2022

- data/events/2022-boston.yml
Truing up a process fail on our part - they paid and didn't get onto the site.
> [BOS-2022] More sponsors

- content/events/2022-des-moines/welcome.md
Added link to program for 2022 event
> [DSM-2022] Update program link

- netlify.toml
changing from xenial to focal, just running a test PR and then merge.
> unnecessary whitespace to kick off a netlify build

- content/events/2022-washington-dc/sponsor.md
- data/events/2022-washington-dc.yml
- data/sponsors/acorn.yml
- data/sponsors/cloudbees.yml
- data/sponsors/googlecloud.yml
* Add gitlab and cloudbees
* Reorder sponsors so I can be sure there are 15, 6, 2 (there are)
* Close sponsors
* Update sponsor page with Closed or Sold Out
* Fix URLS for cloudbees and acorn
> [DC-2022] Sponsor updates

- data/events/2022-houston.yml
> [HOU-2022] Correcting sponsor

- data/events/2022-charlotte.yml
some schedule changes for tomorrow
> [CLT-2022] Charlotte 2022 schedule updates

- content/events/2022-washington-dc/accessibility.md
- data/events/2022-washington-dc.yml
- Added Accessibility page for Washington DC 2022
> [DC-2022] Added Accessibility Page

- data/events/2022-boston.yml
We had a technical issue push our schedule out.
> [BOS-2022] URGENT - day-of schedule change

- data/events/2022-boston.yml
Following #11835, this is hopefully the last time we'll need to modify the schedule - lunch should get us back on track.
> [BOS-2022] Post-lunch schedule update for open spaces

- content/events/2022-tampa/sponsor.md
- data/events/2022-tampa.yml
[TPA-2022] Moved env0 from plat to lanyard
> [TPA-2022] Moved env0 from plat to lanyard

- content/events/2022-tampa/program/aaron-rinehart-kn.md
- content/events/2022-tampa/program/marcos-diez-t1.md
- content/events/2022-tampa/speakers/aaron-rinehart.md
- content/events/2022-tampa/speakers/marcos-diez.md
- data/events/2022-tampa.yml
[TPA-2022] Updated Program and Speakers
> [TPA-2022] Updated Program and Speakers

- data/events/2022-berlin.yml
- [BER-2022] add gold sponsor to 2022 berlin
cc @range
> [BER-2022] add gold sponsor to 2022 berlin

- data/events/2022-cairo.yml
> [CAI-22] Agenda & location

- data/events/2022-chicago.yml
- Updates Brian Andersen's employer
> [CHI-2022] Update Brian Andersen employer

- content/events/2022-chicago/sponsor-info.md
> [CHI-2022] Update Sponsor  info pages

- content/events/2022-chicago/location.md
> [CHI-2022] Add parking and transit info

- content/events/2023-indianapolis/sponsor.md
> [INDY-2023] Add sponsorship info

- utilities/add_program.sh
- utilities/add_speakers.sh
This is an attempt to #11608. At least to just agree on a common way to fire off the scripts.
> Use a common way to cd into the directory for utilities scripts

- data/events/2022-tampa.yml
[TPA-2022] Updated Sponsor Logo
> [TPA-2022] Updated Sponsor Logo

- content/events/2022-chicago/program.md
- content/events/2022-chicago/welcome.md
> [CHI-2022] Update stream links

- data/events/2022-portugal.yml
* added devoteam as silver sponsor
> [PT-2022] added devoteam as sponsor

- content/events/2022-cairo/welcome.md
> [CAI-22] Fixing welcome page

- content/events/2022-london/location.md
- content/events/2022-london/welcome.md
Update covid policy info
update location details
> [LDN-2022] covid and location updates

- content/events/2022-portugal/location.md
> [PT-2022] Fix URL for Google Maps link

- content/events/2022-portugal/program/philipp-krenn2.md
- data/events/2022-portugal.yml
Filipi couldn't make it and Philipp was kind enough to propose a talk at dinner! :D
> [PT-2022] last minute update to day 2 schedule

- data/events/2022-buffalo.yml
> [BUF-2022] Update conference end time.

- data/events/2022-eindhoven.yml
- Fix schedule error
- Add Wemanity as sponsor
> [EHV-2022] Multiple updates

- content/events/2022-eindhoven/conduct.md
Add Suzanne to Code of Conduct team
> [AMS-2022] Add Suzanne Daniels details to COC

- themes/devopsdays-theme/layouts/events/single.html
- themes/devopsdays-theme/layouts/index.html
- themes/devopsdays-theme/layouts/partials/future.html
attempt to fix the sorting issue on event listing page
> prebuild slices to avoid sorting issue due to invalid date on event

- data/events/2022-chattanooga.yml
Signed-off-by: Aaron Sachs <98627+asachs01@users.noreply.github.com>
Adding Unum & Tidelift
> [CHA-2022] Adding sponsors

- content/events/2022-houston/faq.md
- content/events/2022-houston/program/david-stokes.md
- content/events/2022-houston/program/mark-freydl.md
[HOU-2022] Added prereqs for a workshop, added missing talk description
> [HOU-2022] Added prereqs for a workshop, added missing talk description

- data/events/2023-goiania.yml
> [GYN-2023] Add missing GA tracking ID

- content/events/2022-tampa/sponsor.md
- content/events/2022-tampa/welcome.md
- data/events/2022-tampa.yml
[TPA-2022] Updated Latest New Section
> [TPA-2022] Updated Latest New Section

- content/blog/is-devopsdays-still-relevant.md
I wanted to share some insight from a recent amsterdam meeting that I think would benefit the community. 
Article builds up the case on why folks are asking if devopsdays is still relevant, shares some opinions and then concludes.
> [BLOG] Add new blog post on devopsdays

- content/events/2022-tampa/speakers/tito-martinez.md
> [TPA-2022] Updated Tito

- content/events/2022-rio-de-janeiro/speakers/tainara-almeida.md
Update Speaker Info - Tainara Almeida
> [RIO-2022] Update Speaker Info - Tainara Almeida

- content/events/2022-eindhoven/program/toshaan-bharvani.md
- content/events/2022-eindhoven/speakers/toshaan-bharvani.md
- data/events/2022-eindhoven.yml
* add ignite "POWER your Cloud"
* slides mailed to  @KrisBuytaert
Signed-off-by: Toshaan Bharvani <toshaan@vantosh.com>
> [EHV-022] -  add my last minute ignite

- data/events/2022-eindhoven.yml
we might need to switch to an updated schedule.
> [EHV-2022] Last minute sched changes

- data/events/2022-tampa.yml
Updating schedule
added breakfast and registration
adjusted closing times
> [TPA-2022] updated scheduled times

- data/events/2022-tampa.yml
> [TPA-2022] Updated Times due to delay

- data/events/2022-montreal.yml
> Sponsor update for Montreal 2022

- content/events/2023-zurich/propose.md
- data/events/2023-zurich.yml
> [ZRH-2023] Add call for proposal

- content/events/2022-montreal/program.md
- data/events/2022-montreal.yml
We want to have a fast way to update the schedule in case we have some last-minute changes.
We'll roll back to the static schedule after the event is over.
(and sorry, some meaningless commits trying to fix local stuff)
> [Montreal-2022] "Dynamic" program added

- content/events/2022-montreal/program/kevork-sayad.md
> [Montreal-2022] Added technologies for workshop

- content/events/2022-montreal/program.md
- data/events/2022-montreal.yml
Removed the registration link and rolled back to the static program.
> [Montreal-2022] Post event cleanup

- data/events/2022-oslo.yml
> [OSL-2022] added microsoft as sponsor, changed url for Safespring

- data/events/2023-los-angeles.yml
[la 2023] remove mac stadium as sponsor
> [la 2023] remove mac stadium as sponsor

- content/events/2023-prague/location.md
- content/events/2023-prague/welcome.md
- data/events/2023-prague.yml
> [PRG-2023] Add date and location, plus minor update

- content/events/2023-zurich/registration.md
- data/events/2023-zurich.yml
> [ZRH-2023] Add registration

- content/events/2023-zurich/sponsor.md
- data/events/2023-zurich.yml
Please note the dependency to https://github.com/devopsdays/devopsdays-assets/pull/137
> [ZRH-2023] Add sponsoring

- data/events/2023-amsterdam.yml
- themes/devopsdays-theme/layouts/partials/google_tag_manager.html
- themes/devopsdays-theme/layouts/partials/head_includes.html
- themes/devopsdays-theme/reference.md
- utilities/README.md
Adds support for Google Tag Manager which is Google Analytics v4.
> [theme] Add gtm aka google analytics v4 support

- content/events/2023-denver/propose.md
- content/events/2023-denver/sponsor.md
- content/events/2023-denver/welcome.md
- data/events/2023-denver.yml
* Added CFP link
* Added Sponsor prospectus
* Added ticket and registration link
> [DEN-2023] Added sponsor prospectus, CFP links and Ticket links.

- data/events/2023-geneva.yml
> [GE-2023] new sponsors

- content/events/2023-zurich/sponsor.md
- data/events/2023-zurich.yml
> [ZRH-2023] added swisscom as gold sponsor

- content/events/2023-prague/sponsor.md
- data/events/2023-prague.yml
> [PRG-2023] Sponsor added and minor sponsor page updates

- content/events/2023-raleigh/conduct-fr.md
- content/events/2023-raleigh/conduct-pt-br.md
- content/events/2023-raleigh/conduct.md
- content/events/2023-raleigh/contact.md
- content/events/2023-raleigh/location.md
- content/events/2023-raleigh/propose.md
- content/events/2023-raleigh/registration.md
- content/events/2023-raleigh/sponsor.md
- content/events/2023-raleigh/welcome.md
- data/events/2023-raleigh.yml
- static/_redirects
[rdu-2023] initial event commit
> [rdu-2023] initial event commit

- content/events/2023-zurich/sponsor.md
- data/events/2023-zurich.yml
> [ZRH-2023] Add sponsors exoscale and adnovum

- data/events/2023-los-angeles.yml
> [LA23] Add CircleCI

- content/events/2023-amsterdam/sponsor.md
- content/events/2023-amsterdam/welcome.md
- data/events/2023-amsterdam.yml
- Add prospectus to sponsor website
- Add sponsor packages
- Enable sponsor links
- Enable registration links
> [AMS-2023] Add prospectus & enable sponsor and reg links

- content/events/2023-birmingham-uk/welcome.md
- data/events/2023-birmingham-uk.yml
Add CFP link and amend organisers info
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
> [BHX-2023] Add CFP and amend organisers info

- data/events/2023-los-angeles.yml
[la23] add kubeevents as a sponsor
> [la23] add kubeevents as a sponsor

- data/events/2023-amsterdam.yml
> [AMS-2023] Add roles for Floor

- data/events/2023-raleigh.yml
> [rdu-2023] add propose link

- content/events/2023-austin/conduct.md
- content/events/2023-austin/location.md
- content/events/2023-austin/sponsor.md
- updates sponsor verbiage
- adds prospectus
- updates miscellaneous verbiage with correct year (2023)
> [ATX-2023] Update sponsor page

- content/events/2023-austin/welcome.md
- data/events/2023-austin.yml
Signed-off-by: tracypholmes <12778804+tracypholmes@users.noreply.github.com>
- updates "Welcome" page with Sponsors link ("Sponsor the conference!")
- updates "Welcome" page nav with Sponsor slug
> [ATX-2023] Update welcome page

- data/events/2023-amsterdam.yml
- Add finance responsibility for Joep.
> [AMS-2023] Add additional role for Joep

- content/events/2023-indianapolis/volunteer.md
- data/events/2023-indianapolis.yml
Adds volunteer page for devopsdays Indianapolis 2023
> [IND-2023] add volunteer form

- content/events/2023-aracaju/sponsor.md
- content/events/2023-aracaju/welcome.md
- data/events/2023-aracaju.yml
data/events/2023-aracaju.yml - changed event date
content/events/2023-aracaju/welcome.md - date modified
content/events/2023-aracaju/sponsor.md - sponsorship program
> [AJU-2023] changing date and adding sponsorship program

- data/events/2023-melbourne.yml
- Added ticket/registration data
- Added direct links for ticket and call for papers in navigation
> [MEL-2023] Add ticket information

- content/events/2023-prague/propose.md
- content/events/2023-prague/sponsor.md
- content/events/2023-prague/welcome.md
- data/events/2023-prague.yml
> [PRG-2023] Open CFP

- content/events/2023-austin/conduct.md
- content/events/2023-austin/contact.md
- content/events/2023-austin/covid.md
- content/events/2023-austin/sponsor.md
- data/events/2023-austin.yml
- adds "COVID" page
- updates "Welcome" page nav with COVID slug
- updates miscellaneous verbiage with correct year (2023)
- corrects COVID misspelling on "Conduct" page
> [ATX-2023] Add 2023 COVID page

- data/events/2023-indianapolis.yml
Add learnk8s as a community sponsor
> [INDY-2023] Add learnk8s as a community sponsor

- data/events/2023-zurich.yml
> [ZRH-2023] Add Cognizant as bronze sponsor

- content/events/2023-goiania/location.md
- content/events/2023-goiania/registration.md
- data/events/2023-goiania.yml
- Update CFP info
- Update location info
- Update registration info
> [GYN-2023] Update event info

- data/events/2023-organizer-summit.yml
Update to add Core to Floor Drees on the contact page
> [ORG-2023] update floor 

- content/events/2023-chicago/propose.md
- content/events/2023-chicago/welcome.md
- data/events/2023-chicago.yml
This opens the CFP for DODCHI.
Keep in draft until we are sure about the pretalx setup!
> [CHI-2023] Open CFP

- data/events/2023-los-angeles.yml
[la 2023] add buildkite and manage engine
> [la-2023] add buildkite and manage engine

- data/events/2023-los-angeles.yml
> [la-2023] add sponsor

- content/events/2023-copenhagen/location.md
- content/events/2023-copenhagen/welcome.md
- data/events/2023-copenhagen.yml
This PR will add venue information for DevOpsDays Copenhagen 2023
> [CPH-2023] Add venue information

- content/events/2023-amsterdam/registration.md
@yvovandoorn could you please have a look / change copy if you feel we need to - but let's get this in front of people ❤️
> [AMS-2023] Add scholarship option

- data/events/2023-austin.yml
> [ATX-2023] added CFP for Austin 2023

- data/events/2023-raleigh.yml
> [rdu-2023] Added sponsors kubeevents and kubecareers

- data/events/2023-amsterdam.yml
- change `png` extension to `jpg` extension.
> [AMS-2023] fix image. extensions are hard

- content/events/2023-copenhagen/welcome.md
- data/events/2023-copenhagen.yml
- Adding stickermule as community sponsor
- Updating the welcome page
> [CPH-2023] Add sponsor and update welcome page

- data/events/2023-chicago.yml
> [CHI-2023] Add CircleCI as gold

- content/events/2023-geneva/sponsor.md
- data/events/2023-geneva.yml
[GE-2023] remove Mug sponsor level
> [GE-2023] remove Mug sponsor level

- data/events/2023-chicago.yml
> [CHI-2023] Add Dell as gold sponsor

- content/events/2023-prague/registration.md
- content/events/2023-prague/welcome.md
- data/events/2023-prague.yml
> [PRG-2023] Open registration and a couple of sponsors

- content/events/2023-los-angeles/program.md
- content/events/2023-los-angeles/program/bryan-cantrill.md
- content/events/2023-los-angeles/program/chris-travers.md
- content/events/2023-los-angeles/program/john-willis.md
- content/events/2023-los-angeles/program/kat-gaines.md
- content/events/2023-los-angeles/program/nathan-handler.md
- content/events/2023-los-angeles/program/paige-cruz.md
- content/events/2023-los-angeles/program/rich-horace.md
- content/events/2023-los-angeles/program/ryan-taylor.md
- content/events/2023-los-angeles/speakers/bryan-cantrill.md
- content/events/2023-los-angeles/speakers/chris-travers.md
- content/events/2023-los-angeles/speakers/dan-oboyle.md
- content/events/2023-los-angeles/speakers/john-willis.md
- content/events/2023-los-angeles/speakers/kat-gaines.md
- content/events/2023-los-angeles/speakers/nathan-handler.md
- content/events/2023-los-angeles/speakers/paige-cruz.md
- content/events/2023-los-angeles/speakers/rich-horace.md
- content/events/2023-los-angeles/speakers/ryan-taylor.md
- data/events/2023-los-angeles.yml
- Adding program
- Removing CFP link
- Adding speakers
**Tested:**
> [LA-2023] Adding program

- data/events/2023-geneva.yml
> [GE-2023] add new sponsor

- data/core.toml
Adds new core team member Sharone
> CORE - add Sharone Zitzman to core

- content/events/2023-baltimore/propose.md
- content/events/2023-baltimore/sponsor.md
- data/events/2023-baltimore.yml
This PR opens up our call for proposals, as well as sponsors. Ticketing will be opened in the next few days. Thanks!
> [BALT-2023] Open cfp and sponsors

- data/events/2023-zurich.yml
> [ZRH-2023] added BIT as sponsor

- content/events/2023-aracaju/sponsor.md
- data/events/2023-aracaju.yml
data/events/2023-aracaju.yml - Publish CFP Open and Registration Open
content/events/2023-aracaju/sponsor.md - Midia kit Adjustments
> [AJU-2023] Publishing CFP and Registration

- data/events/2023-los-angeles.yml
[la23] adjust sponsorship levels
> [la23] adjust sponsorship levels

- content/events/2023-nashville/welcome.md
- data/events/2023-nashville.yml
Closes call for proposals and update bio
> [NSH-2023] Closing call for proposals

- content/events/2023-aracaju/contact.md
- content/events/2023-aracaju/sponsor.md
- content/events/2023-aracaju/welcome.md
content/events/2023-aracaju/sponsor.md - Fixed wrong City name
content/events/2023-aracaju/contact.md - Changed caps of devopsdadys word
content/events/2023-aracaju/welcome.md - Changed caps of devopsdadys word
> [AJU-2023] Fix Sponsor Page and Small Adjustments

- content/events/2023-goiania/sponsor.md
- data/events/2023-goiania.yml
* Add new bronze sponsor
* Update sponsorship benefit
> [GYN-2023] Update sponsors

- data/events/2023-washington-dc.yml
I sent an email to info-at-devopsdays.org with all the info for the email list and the Slack channel.
> [DC-2023] Update DC organizers for Slack and email distro

- content/blog/is-devopsdays-still-relevant.md
* Received feedback on my blog post that I thought was relevant enough to go back and update it.
> [BLOG] be more specific on type of conference

- content/events/2023-baltimore/registration.md
- content/events/2023-baltimore/welcome.md
- data/events/2023-baltimore.yml
Open ticket purchasing for Baltimore 2023!!!
> [BALT-2023] Open tickets

- themes/devopsdays-theme/layouts/partials/past.html
> Update max year to include 2023 events in PAST

- data/events/2023-organizer-summit.yml
> [ORG-2023] Add link to CFP

- data/events/2023-los-angeles.yml
- One of our sponsors requested to update the logo as they re-branded
**Testing:**
- Locally using Hugo server
> [LA-2023] Update sponsor

- data/events/2023-melbourne.yml
- Added existing sponsors ANZ and CircleCI as Gold teir sponsors
> [MEL-2023] Added sponsors ANZ and CircleCI

- data/events/2023-zurich.yml
> [ZRH-2023] add sonarsource and julius baer as sponsors

- content/events/2023-melbourne/program.md
- data/events/2023-melbourne.yml
- Added program page from template
- Added program navigation item
- Added basic agenda (using all custom types) minus speaker details
> [MEL-2023] Added agenda for event

- content/events/2023-medellin/sponsor.md
- data/events/2023-medellin.yml
[MDE-2023] Adding Sponsor Page and updating prices
> [MDE-2023] Adding Sponsor Page and updating prices

- data/events/2023-amsterdam.yml
* Adds CircleCI & Wiz to 2023 event
> [AMS-2023] Add CircleCI & Wiz to 2023 Amsterdam

- data/events/2023-amsterdam.yml
* Adds fullstaq
* Minor: Move from http -> https for URLs in data file.
> [AMS-2023] Add Fullstaq to 2023 Amsterdam

- content/events/2023-chicago/registration.md
- data/events/2023-chicago.yml
> [CHI-2023] Open Registration

- data/events/2023-zurich.yml
> [ZRH-2023] add VSHN as sponsor

- data/events/2023-los-angeles.yml
- Removing two items from the program
**Tested:**
- Locally using Hugo server
> [LA-2023] Updating program

- data/events/2023-copenhagen.yml
This pr will add a sponsor to the CPH 2023 event.
> [CPH-2023] Add sponsor

- data/events/2023-amsterdam.yml
* Adds mkdev as sponsor to Amsterdam
> [AMS-2023] Add mkdev to Amsterdam 2023

- data/events/2023-amsterdam.yml
* Adjust Greater to be Coffee sponsor
> [AMS-2023] Fix greater sponsorship level

- content/events/2023-organizer-summit/registration.md
- data/events/2023-organizer-summit.yml
This switches to use a pre-filled voucher for the organizer summit
> [ORG-2023] Update reg page

- data/events/2023-amsterdam.yml
> [AMS-2023] Add github as gold sponsor

- data/events/2023-baltimore.yml
Adding sponsor entries for kube careers and kube events.
> [BALT-2023] kube careers and kube events sponsor data entries in baltimore 2023

- content/events/2023-seattle/location.md
- content/events/2023-seattle/propose.md
- content/events/2023-seattle/sponsor-info.md
- content/events/2023-seattle/welcome.md
- data/events/2023-seattle.yml
- Add organizer Mia Villasenor
- Add location
- Add Dates
- Add "hidden" sponsor-info page
> [SEA-2023]  Location updates etc

- data/events/2023-raleigh.yml
> [rdu-2023] Added cloudbees as gold sponsor

- data/events/2023-zurich.yml
> [ZRH-2023] add red hat as sponsor

- data/events/2023-seattle.yml
Fix the Accent on Mias Last Name
> [SEA-2023] fix accent on Mias Name

- content/events/2023-aracaju/welcome.md
- data/events/2023-aracaju.yml
> [AJU-2023] Activate Sponsor

- content/events/2023-melbourne/program/damian-brady.md
- content/events/2023-melbourne/program/dylan-mccarthy.md
- content/events/2023-melbourne/program/javier-turegano.md
- content/events/2023-melbourne/program/peter-chestna.md
- content/events/2023-melbourne/speakers.md
- content/events/2023-melbourne/speakers/damian-brady.md
- content/events/2023-melbourne/speakers/dylan-mccarthy.md
- content/events/2023-melbourne/speakers/javier-turegano.md
- content/events/2023-melbourne/speakers/peter-chestna.md
- data/events/2023-melbourne.yml
Updated program to announce speakers including:
- Added speakers navigation item
- Added speaker data
- Updated program with speaker data
Added other misc updates:
- Added BuildKite as bronze sponsor
- Fixed ANZ sponsor to link to AU URL
> [MEL-2023] Added speakers, BuildKite sponsor

- content/events/2023-organizer-summit/welcome.md
- data/events/2023-organizer-summit.yml
adds link to the health and safety policy for dedvopsdays chicago 
> [ORG-2023] Add link to health and safety policy

- data/events/2023-los-angeles.yml
> [la23] remove saucelabs

- data/events/2023-los-angeles.yml
Stickermule requested to be removed.
> [la23] remove stickermule

- data/events/2023-raleigh.yml
Added New Relic as a Gold Sponsor 
Thanks!
> [rdu-2023] Added New Relic as Gold Sponsor

- content/events/2023-melbourne/program/dylan-mccarthy.md
- content/events/2023-melbourne/program/mirco-hering.md
- content/events/2023-melbourne/speakers/mirco-hering.md
- data/events/2023-melbourne.yml
- Added keynote speaker for day 1
- Adjusted open spaces talks type to the built-in type per https://github.com/devopsdays/devopsdays-web/pull/12259#discussion_r1108475811
> [MEL-2023] Add keynote speaker

- content/events/2023-seattle/propose.md
- content/events/2023-seattle/welcome.md
- data/events/2023-seattle.yml
Add links to CFP, CFP now open
> [SEA-2023] Add links to CFP, CFP now open

- data/events/2023-raleigh.yml
Added four companies as gold level sponsors:
dragondropcloud
Vmware Tanzu
transition-technologies-psc
SumoLogic
thanks!
> [rdu-2023] Added four gold sponsors

- data/events/2023-copenhagen.yml
This PR will add Lego as a sponsor.
> [CPH-2023] Add Lego as a sponsor

- content/events/2023-raleigh/location.md
makes use of https://github.com/devopsdays/devopsdays-assets/pull/147
> [RDU-2023] updated location page to add hotel info

- static/_redirects
> [DFW-2023] Updating City Redirect

- data/events/2023-geneva.yml
> [GE-2023] add sponsor

- data/events/2023-nashville.yml
> [NASH-2023] Updating sponsor logo

- data/events/2023-salt-lake-city.yml
> [SLC-2023] Add registration and location data and update job title

- data/events/2023-melbourne.yml
Added Pagerduty as Gold tier sponsor
> [MEL-2023] Add Pagerduty as sponsor

- data/events/2023-los-angeles.yml
> [la23] add palo alto

- data/events/2023-geneva.yml
[GE-2023] add community sponsor
> [GE-2023] add community sponsor

- content/events/2023-chicago/sponsor.md
> [chi-2023] update sponsorship

- content/events/2023-zurich/program/marc-sallin.md
> [ZRH2023] Change Marc Sallins Talk

- content/events/2023-baltimore/welcome.md
> [BMORE-2023] Remove proposal link from welcome page

- content/events/2023-raleigh/speakers/jen-wike-huger.md
Updated Speaker Bio for Jen Wike Huger.
> [rdu-2023] Updated Speaker Bio

- data/events/2023-raleigh.yml
Added SumoLogic as a gold sponsor for Raleigh.
> [rdu-2023] Added SumoLogic as gold sponsor

- content/events/2023-los-angeles/speakers/john-willis.md
- Updating John Willis' bio
**Tested:**
> [LA-2023] Updating speaker's bio

- data/events/2023-amsterdam.yml
> [AMS-2023] Add pronouns for speaker team

- data/events/2023-aracaju.yml
> [Aracaju-2023] CFP closed

- data/events/2023-amsterdam.yml
* Add Kosli as Gold
* Add SBP as Lanyard
> [AMS-2023] Add Kosli & SBP to sponsors

- data/events/2023-chicago.yml
Add chicago AWS user group and chicago devops meetup as community sponsors
> [CHI-2023] Add community sponsors

- data/events/2023-baltimore.yml
> [BMORE-2023] new relic sponsor

- content/events/2023-melbourne/location.md
- data/events/2023-melbourne.yml
- Added existing sponsor REA Group to community tier
- Adjusted schedule to include evening event
- Updated location page to include information on evening event
> [MEL-2023] Added community ticket sponsor + evening event info

- data/events/2023-baltimore.yml
> [BMORE-2023] update slack link

- data/events/2023-melbourne.yml
- updating evening event to when its actually happening! :)
- changing name of pitch sessions
> [MEL-2023] Updating Melbourne program

- data/events/2023-melbourne.yml
- Ever so slightly adjusted evening event hours to prevent attendees possibly turning up too early
> [MEL-2023] Slightly adjusted evening event hours

- data/events/2023-geneva.yml
[GE-2023] Change sponsor level
> [GE-2023] Change sponsor level

- content/events/2023-raleigh/welcome.md
deleted some lines that were disabling the twitter button on our welcome page.
> [rdu-2023] Updated welcome.md

- content/events/2023-zurich/location.md
> [ZRH-2023] added floor plan

- data/events/2023-london.yml
London 2023 - Adding socials for organiser Ethan Sumner
> [LDN-2023] Updated Socials - Ethan

- content/events/2023-juiz-de-fora/sponsor.md
- data/events/2023-juiz-de-fora.yml
Abertura do plano de patrocínio.
> [jf-2023] update plan sponsor

- data/core.toml
* Move Mine to Emeritus per their own request.
> [Core] Move Mine to Emeritus per request

- data/events/2023-copenhagen.yml
> [CPH-2023] Fix year for agenda

- content/events/2023-copenhagen/welcome.md
- data/events/2023-copenhagen.yml
Add sponsor and link to the program from the welcome page.
> [CPH-2023] Add sponsor and link to program

- themes/devopsdays-theme/layouts/speaker/single.html
If speaker has mastodon set, it was not displaying. this fixes that.
> [FIX] Fix bug with speaker mastodon display

- content/events/2023-phoenix/sponsor.md
- data/events/2023-phoenix.yml
- Add sponsor prospectus PDF link to sponsor page
- Add attendee registration link
> [phx-2023] update registration and sponsor links

- data/events/2023-raleigh.yml
Updated our sponsors and modified our program :shipit:
> [RDU-2023] Sponsor/Program Update

- data/events/2023-rio-de-janeiro.yml
> [RIO/2023] C4P opening and tickets selling

- content/events/2023-rio-de-janeiro/sponsor.md
- data/events/2023-rio-de-janeiro.yml
> [RIO-2023] New Sponsorship Proposal

- content/events/2023-zurich/registration.md
> [ZRH-2023] bump ti.to integration to v2

- content/events/2023-zurich/sponsor.md
> [ZRH-2023] add sponsor subscription form

- data/events/2023-zurich.yml
> [ZRH-2023] shorten open spaces & workshops by 15 min on day 1

- data/events/2023-raleigh.yml
https://devopsdays.slack.com/archives/CDCDD7319/p1679946807722819
> [RDU-23] Remove DataDog as a sponsor.

- data/events/2023-chicago.yml
Adds trend micro and sumo logic as gold, honeycomb as bronze
> [CHI-2023] Add sponsors

- data/events/2023-baltimore.yml
> [BMORE-2023] gitlab sponsor

- data/events/2023-baltimore.yml
> [BMORE-2023] fearless plat sponsor

- content/events/2023-rio-de-janeiro/sponsor.md
- data/events/2023-rio-de-janeiro.yml
> [RIO-2023] - Fix Price Sponsor and Add new sponsor

- content/events/2023-rio-de-janeiro/sponsor.md
> [RIO-2023] Fix Sponsor Page

- data/events/2023-amsterdam.yml
* Add Sysdig
* Adjust end time of Ignites day 1
> [AMS-2023] Add sysdig as sponsor, fix one time

- content/events/2023-raleigh/speakers/aaron-suggs.md
> [RDU-2023] update speaker bio 

- data/events/2023-denver.yml
One of our speakers didn't get linked properly.
> [DEN-2023] Fixed the day two schedule to properly have all our speakers.

- content/events/2023-zurich/program/thomas-stein.md
> [ZRH-2023] - changed title of Thomas Stein talk

- data/events/2023-rio-de-janeiro.yml
> [RIO-2023]-New sponsors

- content/events/2023-austin/conduct.md
- content/events/2023-austin/covid.md
- content/events/2023-austin/welcome.md
- data/events/2023-austin.yml
- Addedadditional Gold sponsors
- Updated COVID policy
- Updated talk proposal link on Welcome page
> [ATX-2023] Update COVID policy and sponsors

- data/events/2023-zurich.yml
> [ZRH2023] Add sponsor ciklum

- content/events/2023-montreal/location.md
- content/events/2023-montreal/welcome.md
- data/events/2023-montreal.yml
... plus minor look and feel tweaks
> [Montreal-2023] CFP open

- content/events/2023-chicago/sponsor.md
Removes the reference to the $1,000 early payment discount.
please do not merge this prior to 31 March.
(I have pre-staged this as a draft PR prior to 31 March as it needs to be merged on 31 March but I will be on a plane/traveling on that day)
> [CHI-2023] Sponsor discount over

- data/events/2023-baltimore.yml
> [BMORE-2023] move happy hour to bottom

- content/events/2023-denver/program/daniel-sada-caraveo.md
- data/events/2023-denver.yml
> [DEN-2023] Tweak schedule details

- content/events/2023-aracaju/location.md
- content/events/2023-aracaju/welcome.md
- data/events/2023-aracaju.yml
content/events/2023-aracaju/location.md - adding the event location
content/events/2023-aracaju/welcome.md - Adding place
data/events/2023-aracaju.yml - adding new sponsors
> [AJU-2023] adding new sponsors and event location

- content/events/2023-juiz-de-fora/welcome.md
- data/events/2023-juiz-de-fora.yml
Estou incluindo Kube Careers e Kube Events como patrocinadores que ajudam a comunidade :) .
> [jf-2023] Adding Kube Careers and Kube Events as community sponsor

- data/events/2023-chicago.yml
also some tweaks to alphabetize sponsors
> [CHI-2023] Add Acorn as Gold

- data/events/2023-baltimore.yml
> [BMORE-2023] lightstep plat sponsor

- content/events/2023-austin/schedule.md
- content/events/2023-austin/speakers.md
- data/events/2023-austin.yml
Assuming my team is ok with this, lets add it!
(please wait for at least one +1 on this)
> [2023-Austin] Added Schedule to site

- data/events/2023-prague.yml
> [PRG-2023] program and sponsor update

- data/events/2023-new-york-city.yml
Adds the URL for the CFP to the data file.
> [NYC] Add links to the CFP

- data/events/2023-dallas.yml
> [DFW-2023] add redgate sponsor

- content/events/2023-denver/location.md
> [DEN-2023] Fix Pre-reg date/time

- content/events/2023-raleigh/program.md
- data/events/2023-raleigh.yml
- adds `InsightFinder` as  GOLD sponsor
- add link to open space ghseet sched to main program
> [RDU-23] last min tweaks

- data/events/2023-amsterdam.yml
* Add Isovalent as Gold sponsor
> [AMS-2023] Add Isovalent as Gold sponsor

- content/events/2023-raleigh/program.md
adds our youtube live feed to the main program for day 1
> [RDU-2023] add live feed url to main program for day 1.

- content/events/2023-raleigh/program.md
Our live feed failed and we had to restart it, this just adds a link to our main program for reference for anyone watching online with us :)
> [RDU-2023]  updated live feed urls 

- data/sponsors/yuccasolutions.yaml
[GE-2023] fix issue with sponsor URL
> [GE-2023] fix issue with sponsor URL

- data/events/2023-copenhagen.yml
Adding pagerduty as gold and community sponsor.
> [CPH-2023] Add pagerduty as sponsor

- data/events/2023-phoenix.yml
Add subscribed sponsors to our event page
> [PHX-2023] add/update sponsors

- content/events/2023-tampa/location.md
- data/events/2023-tampa.yml
> [TPA-2023] Updated Date and Location

- data/events/2023-amsterdam.yml
* Adds Zesty as a gold sponsor
> [AMS-2023] Add Zesty

- content/events/2023-seattle/sponsor.md
I put in a bad link to the prospectus in assets. fixed now
> [SEA-2023] fix the link to the prospectus

- content/events/2023-raleigh/welcome.md
Added Thank you message on our page.
> [rdu-2023] Update welcome.md

- content/events/2023-denver/welcome.md
> [DEN-2023] Add livestream

- data/events/2023-kyiv.yml
We weren't able to collect enough sponsors even to cover operational costs.
So, we are moving the dates to September. Maybe the situation with sponsors' budgets is going to be better.
> [KYIV-2023] move dates to September

- content/events/2023-denver/welcome.md
> [DEN-2023] Update livestream url

- content/events/2023-new-york-city/welcome.md
- data/events/2023-new-york-city.yml
- Add observe inc at silver level
- Add dragon drop at startup level
- Fix link on welcome page
- disable unused sponsor tiers
> [NYC-2023] Add sponsors

- data/events/2023-rio-de-janeiro.yml
> [RIO-2023]New Sponsor - AWS

- data/events/2023-baltimore.yml
> [BALT-2023] Remove Gitlab as Sponsor

- content/events/2023-raleigh/welcome.md
Moved Thank you Message further down in welcome.md. Where I had it before bricked the page and presented a 404.
> [rdu-2023] Moved Thank you Message

- content/events/2023-denver/welcome.md
> [DEN-2023] Update livestream for day 2

- content/events/2023-aracaju/program/ana-virginia.md
- content/events/2023-aracaju/speakers/ana-virginia.md
- data/events/2023-aracaju.yml
data/events/2023-aracaju.yml - Added new speaker
content/events/2023-aracaju/program/ana-virginia.md - new speaker file
content/events/2023-aracaju/speakers/ana-virginia.md - new speaker file
> [AJU-2023] adding last speaker to program

- content/events/2023-seattle/sponsor.md
adding payment links for sponsors
> [SEAS-2023] adding payment links for sponsors

- content/events/2023-london/welcome.md
https://trello.com/c/6XaJcNQt/47-update-covid-policy-not-asking-for-proof-of-vaccination
> [LDN-2023] Revise the COVID policy - not checking vaccinations

- content/events/2023-indianapolis/welcome.md
- data/events/2023-indianapolis.yml
extends CFP end date to June 1st and adds a banner on the welcome page
**wait until May 1st to merge**
> [IND-2023] extend CFP end date - Merge May 1st

- content/events/2023-washington-dc/welcome.md
- data/events/2023-washington-dc.yml
- Added CFP links to sessionize for DevOpsDays DC 2023
> [DC-2023] feat: added CFP info for DC-2023

- content/events/2023-new-york-city/registration.md
- content/events/2023-new-york-city/welcome.md
- data/events/2023-new-york-city.yml
- Enable registration page
- Add link to welcome page
- Add eventbrite iframe to registration page
> [NYC-2023] Open registration

- content/events/2023-copenhagen/welcome.md
Ad a wrap up section on the frontpage that also includes link to all the photos that hs been taken during the conference.
> [CPH-2023] Add wrap up section

- data/events/2023-zurich.yml
> [ZRH-2023] last minute change to workshop timeslots

- content/events/2023-washington-dc/sponsor.md
- Update Gold with direct link to PayPal
- Change to Sponsor-specific contact email
> [DC-2023] Update sponsor.md with gold PayPal

- content/events/2023-washington-dc/sponsor.md
> [DC-2023] Fix trailing /form

- content/events/2023-amsterdam/speakers/thiago-de-faria.md
Thiago changed jobs - I changed bios
Congrats, @thiagoavadore
> [AMS-2023] Update Thiago bio

- data/events/2023-phoenix.yml
- Add GitLab to sponsors
- Add Harness to sponsors
> [phx-2023]: add silver sponsors

- data/events/2023-london.yml
mkdev have chosen to go with silver and need adding to the sponsors list on the website.
> [LDN-2023] Add mkdev as a silver sponsor

- content/events/2023-vilnius/welcome.md
- data/events/2023-vilnius.yml
> [VLN-2023] Add registration link

- data/events/2023-rio-de-janeiro.yml
> [RIO-2023]New Sponsor

- content/events/2023-des-moines/sponsor.md
Forgot to include this change in [#12697](https://github.com/devopsdays/devopsdays-web/pull/12697)
> [DSM-2023] Update available sponsorships

- data/events/2023-baltimore.yml
> [BMORE-2023] Adding harness as a sponsor

- content/events/2023-vilnius/location.md
- data/events/2023-vilnius.yml
> [VLN-2023] Fix location address

- data/events/2023-new-york-city.yml
- Add sumo logic as silver sponsor
> [NYC-2023] Add sumo logic as silver sponsor

- data/events/2023-phoenix.yml
- Add sponsor areas - snacks, coffee
- Add sponsors to new areas
> [phx-2023]: update sponsor list

- content/events/2023-tampa/propose.md
- content/events/2023-tampa/sponsor.md
- data/events/2023-tampa.yml
[TPA-2023] - Enabled sponsor and cfp
> [TPA-2023] - Enabled sponsor and cfp

- content/events/2023-organizer-summit/guide-to-chicago.md
- content/events/2023-organizer-summit/welcome.md
- data/events/2023-chicago.yml
First attempt at a guide to Chicago
> [ORG-2023] Working guide to chicago

- content/events/2023-phoenix/program/andrew-clay-shafer.md
> [phx-2023]: update keynote abstract

- content/events/2023-tampa/sponsor.md
> [TPA-2023] Updated swagbag

- data/events/2023-fortaleza.yml
> [FOR-2023] feat: add mew sponsors linuxtips dod fortaleza

- content/events/2023-dallas/speakers/topo-pal.md
> [DFW_2023] update topo's bio

- data/events/2023-fortaleza.yml
> [FOR-2023] FIX gtm tag version

- data/events/2023-tampa.yml
> [TPA-2023] - Fixed Proposed

- content/events/2023-phoenix/location.md
- data/events/2023-phoenix.yml
- Add location link to event config page
- Add event links and maps to location page
> [PHX-2023] Update location details

- content/events/2023-juiz-de-fora/speakers/marcos-diez.md
Correção do link do github de um dos palestrantes que estava errado
> [jf-2023] github speaker fix

- data/events/2023-fortaleza.yml
> [FOR-2023] update link registration link events

- content/events/2023-baltimore/program/aaron-brooks.md
- data/events/2023-baltimore.yml
> [BMORE-2023] Updating wednesday schedule to condense an hour

- content/events/2023-rio-de-janeiro/program.md
- data/events/2023-rio-de-janeiro.yml
> [RIO-2023] Program

- content/events/2023-eindhoven/welcome.md
- data/events/2023-eindhoven.yml
The prospectus change is merged: https://github.com/devopsdays/devopsdays-assets/pull/160
> [EHV-2023] Add the sponsor levels and sponsor prospectus

- content/events/2023-montreal/sponsor.md
Sponsors can now pay directly in our web site
> [Montreal-2023] We know take PayPal payments

- data/events/2024-baltimore.yml
> [BMORE-2024] Add code and coffee sponsor; remove ADO

- content/events/2023-amsterdam/registration.md
- data/events/2023-amsterdam.yml
* Portworx is sponsoring platinum
* reducing scholarship to €20/€30
> [AMS-2023] declare platinum sponsor, relax scholarship costs

- data/events/2023-new-york-city.yml
- data/sponsors/glassbox.yml
> [NYC-2023] Update glassbox global link and nyc link

- data/events/2023-dallas.yml
remove ntx gitlab community sponsor
> [DFW-2023] remove ntx gitlab community sponsor

- content/events/2023-ljubljana/conduct-fr.md
- content/events/2023-ljubljana/conduct-pt-br.md
- content/events/2023-ljubljana/conduct.md
- content/events/2023-ljubljana/contact.md
- content/events/2023-ljubljana/location.md
- content/events/2023-ljubljana/propose.md
- content/events/2023-ljubljana/registration.md
- content/events/2023-ljubljana/sponsor.md
- content/events/2023-ljubljana/welcome.md
- data/events/2023-ljubljana.yml
- static/_redirects
We would be delighted to have DOD Ljubljana, so in accordance to the contributing.md file, opening up a PR.
There will be updates, this is the _just_ the first push
> [LJU-2023] Add ljubljana 2023 event

- content/events/2023-zurich/welcome.md
- content/events/2024-zurich/welcome.md
> [ZRH-2024] Add new after show video

- content/events/2023-chicago/covid-19-policy.md
Removes reference to international visitors requiring vaccination proof to enter the country
> [CHI-2o23] [ORG-2023] Update covid policy

- data/events/2023-tampa.yml
[TPA-2023] Updated Registration
> [TPA-2023] Updated Registration

- content/events/2023-new-york-city/welcome.md
- data/events/2023-new-york-city.yml
Venue needs us out of the theater before the clock strikes noon.
> [NYC-2023] Program update

- content/events/2023-madrid/sponsor.md
> [MAD] fix: date for sponsorship

- content/events/2023-amsterdam/program/ws-jessica-rose-ritah-nabukalu.md
- Update workshop per Jessica's request.
> [AMS2023] Update Jessica & Ritah's workshop

- content/events/2023-tel-aviv/propose.md
- content/events/2023-tel-aviv/welcome.md
- data/events/2023-tel-aviv.yml
> [TLV-2023] - New Logos + CFP Close

- data/events/2023-amsterdam.yml
Adds Wemanity as a bronze level sponsor - happy to have them again this year!
> [AMS-2023] Add Wemanity as Bronze sponsor

- content/events/2023-des-moines/sponsor.md
- data/events/2023-des-moines.yml
Also alphabetized the sponsor list
> [DSM-2023] Add Trility as a sponsor

- content/events/2023-amsterdam/program.md
- data/events/2023-amsterdam.yml
Adds online/interview slots to the program, add color keys to program page to aid readability.
> [AMS-2023] Add online/interview slots, add color keys

- data/events/2023-birmingham-uk.yml
> [BHX-2023] swap speakers

- content/events/2023-birmingham-uk/program/amanda-brock.md
- data/events/2023-birmingham-uk.yml
Change our evening venue for Thursday, update Amanda's talk
> [BHX-2023] Change schedule and speaker

- data/events/2023-vilnius.yml
> [VLN-2023] Add bronze sponsor

- content/events/2023-amsterdam/program/julie-starling.md
* Modify Julie's abstract per her request
> [AMS-2023] Modify abstract per request

- data/events/2023-birmingham-uk.yml
- This now matches the emails that have been going out.
> [BHX-2023] Fix pre-conf social times

- content/events/2023-seattle/program/ana-margarita-medina.md
- content/events/2023-seattle/program/kendra-ash.md
- content/events/2023-seattle/program/zoe-steinkamp.md
- data/events/2023-seattle.yml
Fix group talk with Ana and Julie
swap time slots for Zoe and Kendra
> [SEA-2023] Speaker Updates

- content/events/2023-birmingham-uk/program/daniel-oates-lee.md
- data/events/2023-birmingham-uk.yml
fix typo and move the talks that swapped today
> [BHX-2023] change schedule for speakers

- data/events/2023-dallas.yml
> [DFW-2023] Adding ClickHouse as a sponsor

- data/events/2023-amsterdam.yml
> [AMS-2023] add closing on day 1data/events/2023-amsterdam.yml

- content/events/2023-amsterdam/location.md
* OVpay makes using public transportation about 100 times easier in NL.
> [AMS-2023] Update AMS public transport info

- content/events/2023-oslo/welcome.md
> [Oslo-2023] Removed mini-bio under images, no good on mobile rendering

- content/events/2023-amsterdam/program/ws-luben-alexandrov.md
- Change workshop talk name per request of speaker
> [AMS-2023] change Luben's workshop title per request

- data/events/2023-amsterdam.yml
> [AMS-2023] Add gitlab

- content/events/2023-amsterdam/program/ws-julia-sullivan.md
- data/events/2023-amsterdam.yml
* adjust workshop to be clear about participation maximum
> [AMS-2023] Be clear about max for workshop

- content/events/2023-rio-de-janeiro/program/bernardo-lopes.md
- content/events/2023-rio-de-janeiro/speakers/bernardo-lopes.md
> [RIO-2023] Update Program

- content/events/2023-amsterdam/conduct.md
- data/events/2023-amsterdam.yml
Changes Expo/Workspace/Outside
Adds Telegram contact for Jos
> [AMS-2023] Change ws rooms, add coc contact

- content/events/2023-boston/welcome.md
- data/events/2023-boston.yaml
I also took the opportunity to clean up our welcome page and sponsor banners a bit.
> [BOS-2023] Dell sponsorship

- data/events/2023-beijing.yml
> [PEK-2023]update date and address

- data/events/2023-amsterdam.yml
Adding recorded interviews to the `Online` schedule so that they can tell their moms when they're on!
> [AMS-2023] Add recorded interviews to sched

- data/events/2023-amsterdam.yml
Stuff happens. The show must go on.
> [AMS-2023] Removing ignite

- content/events/2023-london/welcome.md
> [LDN-2023] CfP is closed; program is viewable.

- data/events/2023-dallas.yml
> [DFW-2023] Addng Cloudbees as sponsor

- data/events/2023-tampa.yml
[TPA-2023] Added AWS User Group
> [TPA-2023] Added AWS User Group

- content/events/2023-chicago/sponsor-info.md
> [CHI-2023] Sponsor info page

- data/events/2023-tampa.yml
[TPA-2023] Added Women In Linux as Community Partner
> [TPA-2023] Added Women In Linux as Community Partner

- content/events/2023-london/program/kat-samperi.md
- content/events/2023-london/speakers/kat-samperi.md
We didn't have this until now.
A simple copy pasta with an extra end of file fix added on the bio.
> [LDN-2023] Add Kat Samperi's Ignite talk.

- content/events/2023-tampa/welcome.md
[TPA-2023] Updated pricing image
> [TPA-2023] Updated pricing image

- content/events/2023-organizer-summit/speaker-info.md
Update slides info / communal laptop.
> [ORG-2023] Update speaker-info.md

- content/events/2023-eindhoven/location.md
Correct the address [venue](https://www.hightechcampus.com/conference-center) for Eindoven conference.
> [EHV-2023] Fix address venue Eindhoven

- content/events/2023-chicago/speaker-info.md
Add Corey & practice sessions, update some dates.
> [CHI-2023] Update speaker-info.md

- data/events/2023-dallas.yml
add launch darkly as gold sponsor
> [DFW-2023] add launch darkly as gold sponsor

- data/events/2023-fortaleza.yml
Add new sponsor in DOD Fortaleza 2023.
> FOR-2023 feat: add alura sponsor for2023

- themes/devopsdays-theme/layouts/partials/footer.html
Kind of messy and maybe could look a little nicer, but since it’s broken anyway…
> Remove twitter from the footer

- content/events/2023-philadelphia/sponsor.md
- data/events/2023-philadelphia.yml
Added paypal buttons to sponsorship page
Added AppDynamics as silver sponsor
> [PHL-2023] Sponsorship updates
