content/events/2023-chicago/sponsor-info.md

Update to match the new graphic w/ 1-30 numbers.

[CHI-2023] Update Sponsor Table Layout with 1-30 floorplan numbers

---

data/events/2023-amsterdam.yml

This is a fix for the comment made by @phrawzty in https://github.com/devopsdays/devopsdays-web/pull/13026#pullrequestreview-1535218535

[AMS-2023] Fix missing talk from Monika in schedule

---

content/events/2023-florianopolis/welcome.md
data/events/2023-florianopolis.yml

[FLN-2023] Add Link for buy tickets

---

data/events/2023-atlanta.yml

Adds registration for DOD Atlanta

[ATL-2023] Add reg link and dates

---

content/events/2023-chicago/sponsor-info.md
content/events/2023-chicago/sponsor.md

CHI-23 update community booth, mark Gold as sold out

[CHI-23] update community booth, mark Gold as sold out

---

data/events/2023-dallas.yml

add britive and datadog as gold sponsors

[DFW-2023] add britive and datadog as gold sponsors

---

data/events/2023-chicago.yml

[CHI-2023] Slight schedule change

---

data/events/2023-madrid.yml

[MAD-2023] feat: 2 gold sponsors

---

content/events/2023-bengaluru/sponsor.md
content/events/2023-bengaluru/welcome.md
data/events/2023-bengaluru.yml

Add links to CFP, Tickets and Sponsorship Prospectus. 
Add Nancy and Rohit as Organizers.

[BLR-2023]  Update Bengaluru 2023 event

---

content/events/2023-chicago/sponsor.md
data/events/2023-chicago.yml

Close bronze 
Close all sponsorship

[CHI-2023] Close bronze sponsorship 

---

content/events/2023-washington-dc/sponsor.md
data/events/2023-washington-dc.yml

vmware-tanzu platinum
scout gold
excella silver

[DC-2023] Add 3 sponsors

---

data/events/2023-london.yml

- As the title says. Need to check the Netlify preview to make sure it looks good though.

[LDN-2023] Add breaks and the 'ten years of DODL' talk to the schedule

---

content/events/2023-washington-dc/program.md
content/events/2023-washington-dc/welcome.md
data/events/2023-washington-dc.yml

- Add Program link to Welcome page
- Make Program nav available
- Add code to embed schedule from Sessionize

[DC-2023] Announce program for the event

---

content/events/2023-des-moines/speakers/kristen-cross.md

[DSM-2023] Update Kristen Cross Bio

---

content/events/2023-des-moines/program/josh-angolano.md
content/events/2023-des-moines/program/matt-vincent.md
content/events/2023-des-moines/schedule.md

Principal wanted all rights revered in their title.
Matt Vincent thought his title was too large and wanted his photo zoomed in.

Update talk titles and Matt Vincent Photo

---

content/events/2023-des-moines/program/kristen-cross.md

Kristen asked that we remove her talk description and just keep the elevator pitch.

remove description from Kristens talk

---

data/events/2023-chicago.yml

Small change, just because of an AV thing!
Holding as draft until confirmed by @kevinreedy

[CHI-2023] Move Jacquie to first ignite

---

data/events/2023-organizer-summit.yml

Removes Community recognitions to end earlier.

[ORG-2023] Update 2023-organizer-summit.yml

---

content/events/2023-montreal/welcome.md
data/events/2023-montreal.yml

Will remove from draft when I get the OK from the rest of the team

[Montreal-2023] Registration open

---

content/events/2024-berlin/registration.md
content/events/2024-berlin/sponsor.md
data/events/2024-berlin.yml

We opened registration for the event. We also raised the sponsoring "costs" a bit.

[BER-2024] Add registration, raise sponsoring prices

---

content/events/2023-philadelphia/welcome.md
data/events/2023-philadelphia.yml

[PHL-2023] Update with links to registration

---

data/events/2023-fortaleza.yml

[FOR2023] feat: add scheduler fortaleza 23

---

content/events/2023-montreal/location.md
content/events/2023-montreal/sponsor.md

[Montreal-2023] Style for sold out sponsor categories

---

content/events/2024-berlin/welcome.md

Small change only, forgot to add the link at a more prominent level on the page.

[BER-2024] Add registration link also to welcome.md

---

content/events/2023-chicago/welcome.md
data/events/2023-chicago.yml

[CHI-2023]

---

data/events/2023-dallas.yml

[DFW-2023] add sponsor progresschef

---

data/events/2023-montreal.yml

sorry, will rebase for next push

[Montreal-2023] new sponsor

---

content/events/2023-dallas/program/tyler-mcvety.md
content/events/2023-dallas/speakers/tyler-mcvety.md
data/events/2023-dallas.yml

add speaker, update program and add sponsor

[DFW-2023] add speaker, update program and add sponsor

---

data/events/2023-indianapolis.yml

[IND-2023] final order for talks

---

data/events/2023-london.yml

Added Puppet with gold sponsorship and Contino with bronze sponsorship

[LDN-2023] Add Puppet and Contino

---

data/events/2023-dallas.yml

[DFW-2023] modify program schedule

---

data/events/2023-dallas.yml

[DFW-2023] Minor Program Changes

---

content/events/2023-london/welcome.md

[LDN-2023] Update COVID policy - no mandatory LFTs

---

data/events/2023-boise.yml

Hello reviewers 👋🏼 
This PR updates the program for Boise 2023

[BOI-2023] updates program

---

data/events/2023-london.yml

[2023-LDN] DoIT upgraded from Silver to Gold sponsorship

---

content/events/2023-cairo/sponsor.md
content/events/2023-cairo/welcome.md
data/events/2023-cairo.yml

Opening registration & updating sponsorship packages

[CAI-23] Opening registration & updating sponsorship packages

---

content/events/2023-washington-dc/sponsor.md
data/events/2023-washington-dc.yml

Add Puppet by Perforce and CloudBees.
Reduce count of available slots

[DC-2023] Sponsor updates

---

data/events/2023-washington-dc.yml

[DC-2023] Fix puppet yaml

---

content/events/2023-tampa/program.md
content/events/2023-tampa/speakers.md
content/events/2023-tampa/welcome.md
data/events/2023-tampa.yml

[TPA-2023] Updated and Published Speakers

[TPA-2023] Updated and Published Speakers 

---

data/events/2023-atlanta.yml

A huge thanks to cloudbees, vmware, observe, and pagerduty!

[ATL-2023] Adding gold sponsors for Atlanta

---

content/events/2023-tampa/welcome.md
data/events/2023-tampa.yml

[TPA-2023] Added Vmware Tanzu as Sponsor

[TPA-2023] Added Vmware Tanzu as Sponsor

---

data/events/2023-boston.yaml

We are running a 101 track this year, and are delineating that second track in yellow.

[BOS-2023] New sponsors; set aside 101 track

---

data/events/2024-los-angeles.yml

- Add myself to list of organizers
**Tested:**
@omargohan - Can you vouch for me :D

[LA-2024] Add Sharif to organizers list

---

data/events/2023-fortaleza.yml

[FOR-2023] add redhat as a sponsor

---

data/events/2023-fortaleza.yml

[FOR-2023] fix: change employer Rafa's

---

static/_redirects

add a redirect from the 2023 event that was reschedueld

[2024 - PHL]

---

data/events/2023-indianapolis.yml

we need to be out of the venue before 5.  move day 2 events back 15 minutes.

[IND-2023] change day 2 close time

---

data/core.toml

@phrawzty @yvovandoorn @MikeRosTX

Move Mike from Active to Emeritus

---

content/events/2023-dallas/program.md

[DFW-2023] Adding link for Photo Album

---

content/events/2023-des-moines/schedule.md

DSM - 2023 Added Rooms

---

content/events/2023-dallas/program.md

[DFW-2023] Adding links for full (8-hour) days 

---

content/events/2023-boston/speakers/alexandre-pauwels.md
content/events/2023-boston/speakers/caito-scherr.md
content/events/2023-boston/speakers/chris-gallivan.md
content/events/2023-boston/speakers/colleen-delvecchio.md
content/events/2023-boston/speakers/dotan-horovits.md
content/events/2023-boston/speakers/jeff-brainerd.md
content/events/2023-boston/speakers/jon-bass.md
content/events/2023-boston/speakers/kyle-benson.md
content/events/2023-boston/speakers/matt-surabian.md
content/events/2023-boston/speakers/neil-davies.md
content/events/2023-boston/speakers/pete-cheslock.md
content/events/2023-boston/speakers/sharon-goldberg.md
content/events/2023-boston/speakers/talia-nassi.md

Updating Speaker profiles to have sharing image

[BOS-2023] Adding sharing image to Speaker profiles for socials

---

content/events/2023-tampa/welcome.md
data/events/2023-tampa.yml

[TPA-2023] - Added Sponsor

---

content/events/2024-los-angeles/sponsor.md
data/events/2024-los-angeles.yml

**Summary of changes**
- Adding two media sponsors
- Adding more visibility to sponsor prospectus
**Tested**

[LA-2024] Adding media sponsors

---

content/events/2022-eindhoven/registration.md
content/events/2023-amsterdam/registration.md
content/events/2023-detroit/registration.md
content/events/2023-eindhoven/registration.md
content/events/2023-organizer-summit/financial-help.md
content/events/2023-organizer-summit/registration.md
content/events/2023-prague/registration.md
content/events/2024-amsterdam/registration.md
data/events/2023-eindhoven.yml

- changing pretix to utilize tickets.devopsdays.org

[core] update all shops using devops.foundation to use use devopsdays.org

---

content/events/2023-eindhoven/program/claude-warren2.md
content/events/2023-eindhoven/speakers/claude-warren2.md
data/events/2023-eindhoven.yml

Move Lian's session from an Ignite to a full talk session (we'll backfill that Ignite slot), reflect both of Claude's talks, move Lesley to the morning sessions.

[EHV-2023] Finalizing the schedule (promised)

---

content/events/2023-montreal/welcome.md
data/events/2023-montreal.yml

We have a new date for May 2024

[Montreal-2023] Let's say rescheduled instead of canceled

---

content/events/2023-porto-alegre/conduct-fr.md
content/events/2023-porto-alegre/conduct-pt-br.md
content/events/2023-porto-alegre/conduct.md
content/events/2023-porto-alegre/contact.md
content/events/2023-porto-alegre/location.md
content/events/2023-porto-alegre/propose.md
content/events/2023-porto-alegre/registration.md
content/events/2023-porto-alegre/sponsor.md
content/events/2023-porto-alegre/welcome.md
data/events/2023-porto-alegre.yml
static/_redirects

[POA/BR] new event in porto alegre

---

data/events/2023-london.yml

[2023-LDN] Add PagerDuty and CircleCI as sponsors

---

content/events/2023-montreal/welcome.md

This pull request is about fixing some typos on the montreal 2023 page

[MTL-2023] fix some typos in welcome page

---

data/events/2023-london.yml

We've had a bit of a last minute change and switched the first talks around due to illness.

[LDN-2023] Switch two main talks around

---

data/events/2023-porto-alegre.yml

[POA] new details of event

---

content/events/2023-ljubljana/welcome.md

Followup to https://github.com/devopsdays/devopsdays-web/pull/13347 - approved on devopsdays Slack by @nimatel.

Add Program and Speaker links for 2023-ljubljana

---

utilities/add_speakers.sh
utilities/common_code

add_speakers:  updated sed delimiter to _, allowing / in bio, title, and abstract.
reworked logic for adding speaker images, letting you pre-load speaker images into static/events folder.

updated utilities/add_speakers.sh.  Allow / in bio, title, abstract.   update speaker images logic. 

---

content/events/2023-eindhoven/location.md

- It's correct on the main page, thankfully, but not the location page.

[2023-EIN] Fix the location on the location page

---

content/events/2023-florianopolis/program/henrique-dalssaso.md
content/events/2023-florianopolis/program/jeferson-fernando.md

Fix the title of the talks. The name of the speakers is duplicated.

[FLN-2023] Fix program

---

content/events/2023-boston/program.md
data/events/2023-boston.yaml

[BOS-2023] Update Program to include open spaces and after-hours logistics

---

content/events/2024-zurich/propose.md
content/events/2024-zurich/registration.md
content/events/2024-zurich/sponsor.md
content/events/2024-zurich/welcome.md
data/events/2024-zurich.yml

[ZRH-2024] added sponsoring & CFP info

---

data/events/2024-los-angeles.yml

- Added FAUN as community sponsor
**Tested:**

[LA-2024] Adding a community sponsor

---

content/events/2023-tel-aviv/program.md
content/events/2023-tel-aviv/speakers.md
data/events/2023-tel-aviv.yml

[TLV-2023] New dates + edits

---

data/events/2024-los-angeles.yml

**Summary of changes**:
- Adding NADOG as community sponsor
**Tested:**

[LA-2024] Adding NADOG as sponsor

---

content/events/2023-la-paz/speakers/pablo-pacheco.md
data/events/2023-la-paz.yml

[LPZ-2023]some corretions on speakers

---

content/events/2023-eindhoven/program/alessandro-vozza.md
content/events/2023-eindhoven/program/april-edwards.md
content/events/2023-eindhoven/program/ben-dechrai.md
content/events/2023-eindhoven/program/ben-gamble.md
content/events/2023-eindhoven/program/boriss-mejias.md
content/events/2023-eindhoven/program/bram-vogelaar.md
content/events/2023-eindhoven/program/claude-warren.md
content/events/2023-eindhoven/program/claude-warren2.md
content/events/2023-eindhoven/program/david-terol.md
content/events/2023-eindhoven/program/debarshi-basak.md
content/events/2023-eindhoven/program/dominik-de-smit.md
content/events/2023-eindhoven/program/feu-mourek.md
content/events/2023-eindhoven/program/jelle-pelgrims.md
content/events/2023-eindhoven/program/lena-thompson.md
content/events/2023-eindhoven/program/lesley-cordero.md
content/events/2023-eindhoven/program/lian-li.md
content/events/2023-eindhoven/program/marc-duiker.md
content/events/2023-eindhoven/program/marjolein-pilon.md
content/events/2023-eindhoven/program/michiel-valk.md
content/events/2023-eindhoven/program/phani-bhushan-tom-slenders.md
content/events/2023-eindhoven/program/popoff-michka.md
content/events/2023-eindhoven/program/robin-gilijamse.md
content/events/2023-eindhoven/program/sevi-karakulak.md
content/events/2023-eindhoven/program/silvia-longo-jeremy-hartley.md
content/events/2023-eindhoven/program/stefan-holdermans.md
content/events/2023-eindhoven/program/suzanne-daniels.md

This PR adds the YT recordings from all the talks

[EHV 2023] Add YT recordings

---

content/events/2024-geneva/sponsor.md
content/events/2024-geneva/welcome.md
data/events/2024-geneva.yml

[GE-2024] add sponsors pack

---

static/_redirects

[CAI-24] Update _redirects

---

data/events/2024-los-angeles.yml

[LA-2024] Add NADOG sponsor URL

---

content/events/2024-geneva/sponsor.md

[GE-2024] modifiy sponsors pack

[GE-2024] modifiy sponsors pack

---

data/events/2023-florianopolis.yml

[FLN-2023] Fix program and talks

---

data/events/2024-zurich.yml

[ZRH-2024] Fix the CFP End Date

---

static/_redirects

[ZRH-2024] Change redirect to 2024

---

data/events/2024-zurich.yml

[ZRH-2024] Change bio of Flavio

---

data/events/2023-chattanooga.yml

Also, remove unused sponsor levels

[CHA-2023] Add AWS sponsor

---

content/events/2023-recife/local.md
content/events/2023-recife/welcome.md
data/events/2023-recife.yml

[REC-2023] Update venue and sponsors

---

content/events/2024-baltimore/welcome.md

BMORE-2024/justify center for logo and message

---

content/events/2024-baltimore/propose.md
content/events/2024-baltimore/welcome.md
data/events/2024-baltimore.yml

[BMORE-2024] Open CFP

---

content/events/2024-zurich/sponsor.md
data/events/2024-zurich.yml

[ZRH-2024] Added eficode & elastic as sponsors

---

content/events/2024-baltimore/welcome.md

[BMORE-2024] Update welcome page

---

data/events/2023-chattanooga.yml

Add TVA, BlueCross BlueShield of Tennessee, and StratusGrid as sponsors

[CHA-2023] Add sponsors

---

content/events/2024-amsterdam/sponsor-info.md

updated sponsor info for devopsdays Amsterdam 2024

[AMS-2024] created sponsor info

---

content/events/2024-zurich/sponsor.md
data/events/2024-zurich.yml

[ZRH-2024] Add sponsors cloudscale and exoscale

---

content/events/2024-raleigh/sponsor.md

Add link to Raleigh's Sponsorship Package added with https://github.com/devopsdays/devopsdays-assets/pull/174

[rdu-2024] added sponsorship prospectus

---

data/events/2024-los-angeles.yml

- Adding a new gold sponsor
**Tested:**
- Using Hugo

[LA-2024] Adding gold sponsor

---

content/events/2024-kansas-city/sponsor.md

Per suggestion from @jyee , adjusting sponsors pitches

[KC-2024] update sponsors pitches

---

data/events/2024-denver.yml

- [DEN-2024] increase max sponsors to match actual 2023 numbers
- [DEN-2024] add community sponsors kubecareers/kubeevents/nadog

[DEN-2024] increase max sponsors to match actual 2023 numbers

---

content/events/2024-amsterdam/sponsor.md
data/events/2024-amsterdam.yml

Adds the sponsorship prospectus for Devopsdays Amsterdam 2024. Let's GO!

[AMS-24] Add sponsorship prospectus

---

data/events/2023-salvador.yml

[SSA-2023] add sponsors

---

data/events/2024-seattle.yml

[SEA-2024] Fix address

---

content/events/2023-salvador/program.md
content/events/2023-salvador/program/hanna-camelo.md
content/events/2023-salvador/program/hugo-marques.md
content/events/2023-salvador/program/jess-felix.md
content/events/2023-salvador/program/talk-cfp.md
content/events/2023-salvador/speakers/cfp.md
content/events/2023-salvador/speakers/hanna-camelo.md
content/events/2023-salvador/speakers/hugo-marques.md
content/events/2023-salvador/speakers/jess-felix.md
data/events/2023-salvador.yml

[SSA-2023] add initial program

---

content/events/2023-tel-aviv/welcome.md
data/events/2023-tel-aviv.yml

- Note on homepage about dates
- Removed sponsors

[TLV-2023] Home page updates + removed sponsors

---

data/events/2024-amsterdam.yml

Enabled ticket sales and uncommented the registration link.

 [AMS-2024] publish ticket sales

---

content/events/2024-amsterdam/welcome.md

Add links and buttons for sponsoring and registration to the welcome page.

[AMS-2024 ]Added links on welcome page

---

content/events/2023-salvador/program/jess-felix.md

[SSA-2023] add Jess talk title and description

---

data/events/2024-denver.yml
data/sponsors/aptible.yml

add sponsors - yay markdown :)

[DEN-2024] add elastic/aptible gold sponsors

---

data/events/2024-seattle.yml

Should have picked this up in #13508

[SEA-2024] Show Sponsorship in nav

---

data/core.toml

Updating Core list to reflect current[1] reality.
[1] December 2023

[core] update Core list for year-end 2023

---

static/_redirects

- Added 302 redirect to the pretalx cfp
- Fixed some spacing in the _redirect too

[AUS-2024] Added 302 redirect for CFP for Austin

---

content/events/2024-austin/propose.md
data/events/2024-austin.yml

depends on #13518 (please merge that first; thanks!)

[ATX-2024] Add CFP and Aptible as first gold sponsor

---

data/events/2024-denver.yml

Quick sponsor update -- thanks :)

[DEN-2024] Add webriot as Supporter sponsor

---

data/events/2024-zurich.yml

[ZRH-2024] Change the CFP to the correct date

---

data/events/2024-los-angeles.yml

- Adding SolarWinds as gold sponsor
**Tested:**
- Locally using the Hugo server

[LA-2024] Adding a new gold sponsor

---

data/events/2024-los-angeles.yml

- Adding Honeycomb as gold sponsor
**Tested:**

[LA-2024] Adding Honeycomb as gold sponsor

---

content/events/2024-goiania/program.md
data/events/2024-goiania.yml
static/_redirects

* Add CFP info
* Add redirect to pretalx page
* Add program page

[GYN-2024] Add CFP info

---

content/events/2024-vancouver/conduct-fr.md
content/events/2024-vancouver/conduct-pt-br.md
content/events/2024-vancouver/conduct.md
content/events/2024-vancouver/contact.md
content/events/2024-vancouver/location.md
content/events/2024-vancouver/propose.md
content/events/2024-vancouver/registration.md
content/events/2024-vancouver/sponsor.md
content/events/2024-vancouver/welcome.md
data/events/2024-vancouver.yml
static/_redirects

Following up to #13544 - this PR is the initial commit for our event.
I used the script to generate the resource this time and tweaked the data with my best guesses.
Thanks!

[VAN-2024] Initial PR for Vancouver 2024

---

data/events/2024-london.yml

- I sent an email to info@ too.

[LDN-2024] Add Jen Mackown as a new organizer

---

data/sponsors/zkb.yml

[ZRH-2024] Changed the URL of ZKB to the URL of the IT of ZKB

---

data/events/2024-los-angeles.yml

[LA 2024] CFP has been closed since Nov 1

[LA 2024] CFP has been closed since Nov 1

---

content/events/2024-austin/welcome.md
data/events/2024-austin.yml

Updates in this weekly PR:
- Add Texas Mutual as Coffee Bar sponsor
- Fix the welcome page

[ATX-2024]: Weekly update

---

content/events/2024-geneva/propose.md
content/events/2024-geneva/welcome.md
data/events/2024-geneva.yml

[GE-2024] fix link in the welcome page and remove propose

[GE-2024] fix link in the welcome page and remove propose

---

data/events/2024-amsterdam.yml

Yay! Schuberg signed up for the recharge stations!

[AMS-24] Add Schuberg sponsor

---

data/events/2024-zurich.yml

[ZRH-2024] Fix the CFP announcement date

---

content/events/2024-vancouver/propose.md

We are using a Google Form to collect CFP submissions, as that worked quite well for us in 2021.

[VAN-2024] Add CFP details

---

utilities/README.md

Inspired by [this PR](https://github.com/devopsdays/devopsdays-web/pull/13577#issuecomment-1891055109), I just wanted to add some clarity around updating sponsor assets.

Clarify when and why to use change_sponsor_logo.sh

---

static/_redirects

- Updating redirect for /recife
- Including /recife/cfp for call for papers link

[REC-2024] Updating redirect for /recife and including /recife/cfp for call for papers link

---

data/core.toml

Personally I think the sort order should be randomised every time we push the site, but hey…

[minor] Sorting the contents of core.toml

---

content/events/2024-los-angeles/welcome.md

- Removing CFP from homepage
- Promoting the schedule in the homepage 
**Tested:**
- Locally using hugo server

[LA-2024] Minor changes to homepage

---

data/events/2024-los-angeles.yml

**Sumamry of changes:**
- Adding DNSimple as `gold` sponsor
**Tested:**
- Locally using hugo server

[LA-2024] Adding DNSimple as gold sponsor

---

data/events/2024-berlin.yml

Adding a platinum and a community sponsor, both confirmed this week.

[BER-2024] Two more sponsors

---

content/events/2024-seattle/registration.md
content/events/2024-seattle/welcome.md
data/events/2024-seattle.yml

- Close CFP
- Add link for ticket sales.

[SEA-2024] CFP close and open tickets 

---

data/events/2024-amsterdam.yml

Yay! E;astic joins us again this year as a Gold sponsor!

[AMS-24] Add Elastic gold sponsor

---

content/events/2024-salt-lake-city/sponsor.md
content/events/2024-salt-lake-city/welcome.md

Adding prospectus link to main and sponsor pages.

[SLC-2024] Add sponsor prospectus link

---

content/page/about.md

First pass at clarifying the nomenclature of "core" and "global core" (naming things is hard!).

Clarify "core" vs "global core" on About page

---

data/events/2024-denver.yml
data/sponsors/observeinc.yml

Some quick updates
- [DEN-2024] Upsert Observe Inc as sponsor
- [DEN-2024] Increase max supporter sponsors

[DEN-2024] Update Sponsors

---

data/events/2024-geneva.yml

[GE-2024] fix program date issue

[GE-2024] fix program date issue

---

data/events/2024-montreal.yml

[MTL-2024] New sponsor

---

content/events/2024-los-angeles/welcome.md

- Fixing typo in schedule link
**Tested:**
- Locally using Hugo server

[LA-2024] Fixing schedule link

---

data/events/2024-zurich.yml
data/sponsors/vshn.yml

[ZRH-2024 Add new sponsor VSHN]

---

data/events/2024-aracaju.yml

modified:   data/events/2024-aracaju.yml -- Cfp link and date of start and end

[AJU-2024]  Adding cfp link and date of start and end

---

content/events/2024-montreal/sponsor.md

I added 6 commits to make the changes a bit more readable for other organizers to review. Can this commit be squashed on merge? Or should I do something different at my end?
Changes:
- reformat sponsor html table
- remove lanyard sponsor
- add sustainable giveaway
- change prices for lunch, cocktail & coffee

[MTL-2024] update sponsership tarifs

---

content/events/2024-montreal/sponsor.md

Platinum & sustainable giveaway prices were swapped in the html table.

[MTL-2024] fix swag & platinum price swap

---

data/core.toml

Yvo has advised he is not advisory.

[CORE] Update core.toml

---

data/events/2024-dallas.yml

[DFW-2024] conference date change

---

data/events/2024-geneva.yml

[GE-2024] add Open Space Opening on second day

[GE-2024] add Open Space Opening on second day

---

content/events/2024-vancouver/sponsor.md

Added a couple of FAQ to help sponsors in their decisions.

[VAN-2024] Sponsor page details

---

data/events/2024-los-angeles.yml

- Adding SauceLabs as Gold sponsor
- Adding Couchbase as Silver sponsor
**Tested:**
- Locally

[LA-2024] Adding two more sponsors

---

static/_redirects

modified:   static/_redirects -- fix main aracaju page event redirect

[AJU-2024] Fix main aracaju page event redirect

---

data/events/2024-salt-lake-city.yml

Postponing event, new dates TBD.

[SLC-2024] Postponing event, new dates unknown.

---

content/events/2024-minneapolis/location.md
content/events/2024-minneapolis/propose.md
content/events/2024-minneapolis/registration.md
content/events/2024-minneapolis/sponsor.md
content/events/2024-minneapolis/welcome.md
data/events/2024-minneapolis.yml

This PR publishes our 2024 prospectus, opens the CFP and opens registration.

[MSP-2024] Add 2024 Minneapolis sponsorship prospectus, Open CFP, and Ticket Sales

---

content/events/2024-minneapolis/health-and-safety.md
content/events/2024-minneapolis/welcome.md
data/events/2024-minneapolis.yml

Add a Health and Safety statement about the event.

[MSP] Add Health and Safety page

---

content/events/2024-minneapolis/health-and-safety.md

[MSP] Fix typo with health and safety

---

content/events/2024-baltimore/welcome.md
data/events/2024-baltimore.yml

[BMORE-2024] Closing Proposals, Opening tickets

---

content/events/2024-sao-paulo/sponsor.md
data/events/2024-sao-paulo.yml

- update event venue
- update ticket link
- add link to sponsorship pdf
- update sponsorship pricing in usd
- fix typo on sponsor page

[SP-2024] Update event info

---

data/events/2024-raleigh.yml

[rdu-2024] Added Observe as Gold Sponsor

---

data/events/2024-amsterdam.yml

Adds Devoteam as our Gold sponsor!

Add gold sponsor devoteam

---

data/events/2024-geneva.yml

[GE-2024] add 2 sponsors

---

data/events/2024-austin.yml

[ATX-2024] 9 Feb 2024 Updates

---

content/events/2024-geneva/sponsor.md
data/sponsors/les-renverses.yml

[GE-2024] change bronze sponsor price to 1500

[GE-2024] change bronze sponsor price to 1500

---

data/events/2024-amsterdam.yml

Adding Mona to the Amsterdam 2024 Organizers

[AMS-2024] Add Mona to the team

---

content/events/2024-vilnius/welcome.md
data/events/2024-vilnius.yml

add venue sponsor
and few more words about event

[VLN-2024] Add venue sponsor

---

data/events/2024-organiser-summit.yml

[GHENT-2024] Updating the description of day0

---

content/events/2024-organiser-summit/welcome.md

this makes the path work int he URL

[2024-ORG] Fix path

---

data/events/2024-los-angeles.yml

- Adding everbridge as gold sponsor
**Tested:**
- Locally using hugo server

[LA-2024] Adding everbridge as gold sponsor

---

content/events/2024-austin/sponsor.md

- patch(pdf): change asset location

[ATX-2024] 16 Feb 2024 update

---

.github/workflows/pr.yml

Fixes issue with forks, I think

Add sync type for PR for action

---

data/events/2024-montreal.yml

Set registration dates (to open registration) and added reg link to eventbrite

[MTL-2024] add registration link / open reg

---

data/events/2024/amsterdam/main.yml

Yay, fullstaq is joining us as a Silver level sponsor 🎉

[AMS-2024] Add fullstaq as silver sponsor

---

data/events/2024/baltimore/main.yml

[BMORE-2024] Logos for clarity, rackn, pure storage, and observeinv

---

data/events/2014/bangalore/main.yml
data/events/2015/bangalore/main.yml
data/events/2016/bangalore/main.yml
data/events/2017/bangalore/main.yml
data/events/2018/bengaluru/main.yml
data/events/2019/bengaluru/main.yml
data/events/2022/bengaluru/main.yml
data/events/2023/bengaluru/main.yml
themes/devopsdays-theme/reference.md

Update Bengaluru and Bangalore to the same event group

---

content/events/2024-rio-de-janeiro/sponsor.md

*If you are adding or removing organizers, please email info@devopsdays.org with:*
- The details of who is being added and removed. 
- For members being added, please include the full names and email addresses of the new members.
The global team uses the above information to update Slack and the mailing list.
Up to date guidelines for pull requests can be found in the [contributing …

[RIO-2024]Sponsor update

---

.github/workflows/pr.yml

English and Portuguese are the two major languages used by people who interact with this code base, so hopefully this helps. 👍 
(adding the word Bluth to trigger the workflow)

[site] Add pt_BR text to the PR check message

---

content/events/2024-tampa/conduct.md
content/events/2024-tampa/contact.md
content/events/2024-tampa/contributers.md
content/events/2024-tampa/location.md
content/events/2024-tampa/program.md
content/events/2024-tampa/propose.md
content/events/2024-tampa/registration.md
content/events/2024-tampa/speakers.md
content/events/2024-tampa/sponsor.md
content/events/2024-tampa/welcome.md
data/events/2024/tampa/main.yml
static/_redirects

[TPA-2024] Add event

---

content/events/2024-amsterdam/conduct.md

Created a new CoC for Amsterdam together with @FloorD

[AMS-2024] updated code of conduct

---

content/events/2024-vancouver/propose.md
content/events/2024-vancouver/welcome.md

Annoucment that PR window is closed and what happens next.

[VAN-2024] CFP Clouser annoucment

---

static/_redirects

Added org summit short link of cfp

[SUMMIT-2024] Added short link for org summit.

---

data/events/2024/philadelphia/main.yml

Add portworx as a silver sponsor

[PHL-2024] Add portworx as a silver sponsor

---

content/events/2024-montreal/sponsor.md

This change add an extra condition to our sustainable swag sponsorship item

[MTL-2024] add extra clause for sustainable swag sponsorship type

---

data/events/2024/salt-lake-city/main.yml

Adding dates and sponsorship levels.

[SLC-2024] Adding conference dates.

---

static/_redirects

Update the redirect for Aarhus 2025

[AARHUS-2025] splat for 2025

---

data/events/2024/ghent/main.yml
data/events/2024/organiser-summit/main.yml

Minor grammar and spelling tweaks to organiser summit and Ghent / Antwerp events

[2024-OrgSummit] Minor grammar and spelling tweaks

---

content/events/2024-raleigh/speakers/ethan-thomson.md
content/events/2024-raleigh/speakers/marino-wijay.md

Changed employment blurb for Marino Wijay
Changed title name for Ethan Thomason

[RDU-2024] Speaker Bio Edits

---

.github/PULL_REQUEST_TEMPLATE

Based on excellent feedback from @danquah. 🙇

[core] Update PR template re: organizer modifications

---

data/events/2024/amsterdam/main.yml

Bumped Schuberg from Recharge to Lanyard 👍
Up to date guidelines for pull requests can be found in the [contributing guide](https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#guidelines).

[AMS-2024] Update sponsor

---

content/events/2024-washington-dc/sponsor-info.md
content/events/2024-washington-dc/sponsor.md
data/events/2024/washington-dc/main.yml

2024 sponsor page ready to go live once we complete PayPal links....

[DC-2024] Add sponsors

---

content/events/2024-seattle/speakers/daniel-maher.md

[SEA-2024] update profile for Dan

---

content/events/2024-portugal/welcome.md
data/events/2024/portugal/main.yml

This PR improves the Welcome page and corrects the email address

[POR-2024] Improve welcome page

---

content/events/2024-austin/welcome.md
data/events/2024/austin/main.yml

- Add link to discount ticket request form
- Add new happy hour sponsor: CAST AI

[ATX-2024] Updates for week of 8 March 2024

---

data/events/2024/berlin/main.yml

JFrog decided to upgrade from Gold to Platinum.

[BER-2024] Upgrade JFrog sponsorship level

---

content/events/2024-des-moines/sponsor.md
data/events/2024/des-moines/main.yml

Added 3 levels of paid sponsorships

[DSM-2024] Add Sponsorship Prospectus

---

content/events/2024-krakow/welcome.md
data/events/2024/krakow/main.yml

- updated date in the text
- added schedule links

[Kraków 2024] Updated texts and links

---

data/events/2024/philadelphia/main.yml

Add redgate as a silver sponsor

[PHL-2024] Add redgate as a silver sponsor

---

data/events/2024/raleigh/main.yml

Updated raleigh.yml with groundcover as gold sponsor

[RDU-2024} Added groundcover as gold sponsor

---

data/events/2024/zurich/main.yml

Changed timings of sessions to give more space to iginites & open space voting

[ZRH-2024] Changed timings of slots

---

data/events/2024/vilnius/main.yml

[VLN-2024] add cfp link

---

data/events/2024/houston/main.yml

Added Hashicorp as Platinum sponsor

[HOU-2024] Added Hashicorp as Platinum sponsor

---

content/events/2024-berlin/program/fagani-hajizada.md
content/events/2024-berlin/speakers/fagani-hajizada.md
data/events/2024/berlin/main.yml

[BER-2024] Adds Fagani Hajizada as Speaker

---

data/events/2024/amsterdam/main.yml

Changing room location for some workshops

[AMS-2024] Workshop Room Shuffle

---

content/events/2024-berlin/program/christina-kraus.md
content/events/2024-berlin/speakers/christina-kraus.md
data/events/2024/berlin/main.yml

Christina Kraus just confirmed as last speaker for the conference (non-ignites)

[BER-2024] Adds Christina Kraus as Speaker

---

content/events/2024-amsterdam/speakers/nathen-harvey.md

Adds a website link to Nathen's bio.

[AMS-2024] Update link in Nathen's bio

---

content/events/2024-vancouver/welcome.md

This update adds ticket sale link to the vancouver 2024 home page.

[VAN-2024] Tickets are on sale link

---

data/events/2024/amsterdam/main.yml

Progress Chef joins us as Beverage sponsor! DevHops!

[AMS-2024] Add Progress Chef as Beverage sponsor

---

content/events/2024-birmingham-al/welcome.md

* Adds message to welcome page for reschedule

[BHM-AL-2024] Update weclome page with reschedule message

---

data/events/2024/raleigh/main.yml

Updated raleigh.yml with Cloudbees as Gold Sponsor

[RDU-2024] Added Cloudbees as Gold Sponsor

---

content/events/2024-berlin/program/bill-mulligan.md
content/events/2024-berlin/speakers/bill-mulligan.md
data/events/2024/berlin/main.yml

Adding the last (ignite) speaker who submitted a proposal during the CfP.

[BER-2024] Adds final speaker from CfP, Bill Mulligan

---

content/events/2024-halifax/registration.md
data/events/2024/halifax/main.yml

This PR adds registration details for Halifax.

[Halifax-2024] Add registration details for Halifax.

---

content/events/2024-vancouver/welcome.md
data/events/2024/vancouver/main.yml

Fixing the eventbrite link for ticket sales 🎉

[VAN-2024] fix: Correct event links

---

data/events/2024/vilnius/main.yml

add new sponsors
add cfp link to main yml

[VLN-2024] Add new sponsors

---

data/events/2024/geneva/main.yml

[GE-2024] add gold sponsor

---

content/events/2024-berlin/program/stephan-louis-mousset.md
content/events/2024-berlin/speakers/stephan-louis-mousset.md
data/events/2024/berlin/main.yml

* Adding Stephan Mousset as ignite speaker
* Shuffling the schedule, the caterer needs more time

[BER-2024] Add SL Mousset as speaker, move ignites

---

content/events/2024-montreal/program.md
content/events/2024-montreal/speakers/timothy-mamo.md
data/events/2024/montreal/main.yml

Updated speaker's title and company per his request.
Also updated the program and linked the Google sheet we had in previous events for faster updating. 
After the event the program will be visible and the Google sheet will be gone.

[MTL-2024] Program update

---

content/events/2024-amsterdam/program/ig-marcel-britsch.md

[AMS-2024] Changing title for Marcel Britsch Ignite

---

content/events/2024-zurich/program/adam-genshaft.md
content/events/2024-zurich/program/bogdan-doroslovac.md
content/events/2024-zurich/program/daniel-bodky.md
content/events/2024-zurich/program/larry-maccherone.md
content/events/2024-zurich/program/laurence-kozera.md
content/events/2024-zurich/program/rabieh-fashwall.md

Added the prerequisites to the workshops

[ZRH-2024] Add prerequisites to the workshops

---

content/events/2024-berlin/speakers/azer-abdullaev.md

[BER-2024] Change company info fo Azer

---

content/events/2024-amsterdam/sponsor-info.md

@josvanschouten please check that I didn't forget anything?

[AMS-2024] Update sponsor-info.md

---

content/events/2024-amsterdam/speakers/aj.md
content/events/2024-amsterdam/speakers/alireza-chegini.md
content/events/2024-amsterdam/speakers/christiaan-hees.md
content/events/2024-amsterdam/speakers/cote.md
content/events/2024-amsterdam/speakers/dave-stanke.md
content/events/2024-amsterdam/speakers/eugene-romero.md
content/events/2024-amsterdam/speakers/fahd-ekadioin.md
content/events/2024-amsterdam/speakers/feu-mourek.md
content/events/2024-amsterdam/speakers/gerald-benischke.md
content/events/2024-amsterdam/speakers/gijs-van-der-voort.md
content/events/2024-amsterdam/speakers/heather-thacker.md
content/events/2024-amsterdam/speakers/henk-van-der-schuur.md
content/events/2024-amsterdam/speakers/hugo-trippaers.md
content/events/2024-amsterdam/speakers/jj-asghar.md
content/events/2024-amsterdam/speakers/katharina-sick.md
content/events/2024-amsterdam/speakers/kenny-baas-schwegler.md
content/events/2024-amsterdam/speakers/luc-van-donkersgoed.md
content/events/2024-amsterdam/speakers/marcel-britsch.md
content/events/2024-amsterdam/speakers/marcel-kornegoor.md
content/events/2024-amsterdam/speakers/marcy.md
content/events/2024-amsterdam/speakers/mike-kotsur.md
content/events/2024-amsterdam/speakers/onno-ceelen.md
content/events/2024-amsterdam/speakers/rania-mohamed.md
content/events/2024-amsterdam/speakers/robin-gilijamse.md
content/events/2024-amsterdam/speakers/sara-gerion.md
content/events/2024-amsterdam/speakers/sjoerd-westerhof.md
content/events/2024-amsterdam/speakers/sohan-maheshwar.md
content/events/2024-amsterdam/speakers/toshaan-bharvani.md
content/events/2024-amsterdam/speakers/wouter-lagerweij.md
content/events/2024-amsterdam/sponsor-info.md

Update socials for Marcy and added info for sponsors

[AMS-2024] Update socials and info for sponsors

---

data/events/2024/seattle/main.yml

Add sponsors:
- dragonfly
- oracle
- sentry
- tigera
- everbridge
- macstadium
- cloudbees

[SEA-2024] Adding sponsors

---

content/events/2024-london/sponsor.md

- This saves a human replying to the inquiry email with "please fill in the registration form" and chasing up, and then having to process the invoice and contract.
- Still allow questions via email.
- Also remove COVID-19 brackets and a commented out paragraph.

[LDN-2024] Update sponsorship page to link to the registration form

---

data/events/2024/juiz-de-fora/main.yml

Inclusion of link for registration

[jf-2024] Link to registration

---

content/events/2024-goiania/speakers/nathan-martins.md

[GYN-2024] Update speaker bio

---

data/events/2024/philadelphia/main.yml
static/events/2024-philadelphia/program/index.html

[PHL-2024] Adding initial schedule

---

content/events/2024-amsterdam/speakers/sara-gerion.md

Updating Sarah Gerion's profile and social

[AMS-2024] Updated Sara Gerion profile

---

content/events/2024-ghent/conduct.md

Redid the CoC page to reflect the changes made for Amsterdam 2024.

[BEL-2024] updated CoC page for 2024

---

data/events/2024/zurich/main.yml

- Exchanged John with Oleg
- Added Open Space Tracks

[ZRH-2024] Program changes week15

---

content/events/2024-tampa/location.md
content/events/2024-tampa/propose.md
content/events/2024-tampa/sponsor.md
data/events/2024/tampa/main.yml

Update CFP link and sponsorship details for devopsdays Tampa Bay 2024

[TPA-2024] Update CFP link and sponsorship details for devopsdays Tampa Bay 2024

---

content/events/2024-tampa/location.md
content/events/2024-tampa/propose.md
content/events/2024-tampa/sponsor.md
content/events/2024-tampa/welcome.md

[TPA-2024] Add "Propose a Talk" button to welcome page

[TPA-2024] Add "Propose a Talk" button to welcome page

---

content/events/2025-chicago/welcome.md

[CHI-2025] add date to welcome page 

---

content/events/2024-montreal/speakers/joyce-lin.md

[MTL-2024] Speaker bio update

---

data/events/2024/austin/main.yml

[ATX-2024] Updates for 12 April 2024

---

data/events/2024/baltimore/main.yml

setting cancel flag to true to prevent baltimore from showing as TBD

[BMORE-2024] Cancel flag

---

data/events/2024/des-moines/main.yml

**maintainer edit**:  [DSM-2024] Added Side Garage as a sponsor #13973

[DSM-2024] Added Side Garage as a sponsor

---

data/events/2024/rio-de-janeiro/main.yml

[RIO-2024]New Sponsor and C4P

---

content/events/2024-dallas/welcome.md
data/events/2024/dallas/main.yml

Added RackN as Gold sponsor
Updated and enabled registration links
Enabled menu links on welcome page

[DFW-2024] add RackN as sponsor and update registration link

---

content/events/2024-zurich/welcome.md
data/events/2024/zurich/main.yml

- Added new Video to the DevOpsDays Zürich 2024 Website

[ZRH-2024] Add new video of event

---

data/events/2024/geneva/main.yml

[GE-2024] Change Sponsor

---

data/events/2024/antwerp/main.yml

[ANT-2024] Update sponsors Antwerp

---

data/events/2024/philadelphia/main.yml

[PHILA-2024] Add Veracode as a sponsor

---

data/events/2024/washington-dc/main.yml

- Add Lanyard tier
- Add Excella as sponsor at that tier
- Delete Baltimore as community sponsor 😾

[DC-2024] Add Excella, rm Baltimore, add lanyard tier

---

data/events/2024/houston/main.yml

[HOU-2024] Added Corva.ai as Recruiting sponsor

[HOU-2024] Added Corva.ai as Recruiting sponsor

---

data/events/2024/berlin/main.yml

Just signed on Zoho Corp to sponsor site Site24x7 product with Gold level.

[BER-2024] Add site24x7 (zoho) as Gold sponsor

---

data/events/2024/des-moines/main.yml

* modified whitespace of sponsor list to align tabs
* added JetBrains as a community sponsor

[DSM-2024] Updated sponsors

---

content/events/2024-caceres/contact.md
content/events/2024-caceres/sponsor.md
content/events/2024-caceres/welcome.md
data/events/2024/caceres/main.yml
static/events/2024-caceres/main.css
static/events/2024-caceres/main.js

This PR adds the C4P dates and enables more call to action buttons for it.
It also adds some collaborators and community sponsors plus the sponsorship dossier link.
⚠️  Blocked by [#203](https://github.com/devopsdays/devopsdays-assets/pull/203) in assets repository.

[CAC-2024] DevOpsDays Caceres 2024 Call for papers

---

content/events/2024-philadelphia/program/aman-sharma.md

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)
Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to …

[PHL-2024] Update Aman's talk

---

data/events/2024/berlin/main.yml

- Fixes schedule for ignites on day 2
- Adds coffee breaks in the afternoon of both days.wq

[BER-2024] Fixes schedule for ignites, adds afternoon break

---

data/events/2024/dallas/main.yml

[DFW-2024] add RackN as gold sponsor

---

content/events/2024-des-moines/sponsor.md

Added a sponsorship prospectus, hosted in Google Drive.

[DSM-2024] Add link for sponsor prospectus

---

data/events/2024/montreal/main.yml

AppDynamics requested a new link for the event

[MTL-2024] New sponsor link 

---

content/events/2024-houston/faq.md
content/events/2024-houston/location.md
content/events/2024-houston/sponsor.md
data/events/2024/houston/main.yml

[HOU-2024] Added FAQ, added details to Sponsor FAQ

[HOU-2024] Added FAQ, added details to Sponsor FAQ

---

content/events/2024-des-moines/welcome.md
data/events/2024/des-moines/main.yml

[DSM-2024] Added registration link

---

content/events/2024-seattle/sponsor.md
data/events/2024/seattle/main.yml

schedule and formatting changes

[SEA-2024] schedule and formatting changes

---

content/events/2024-houston/speakers/mark-hahn.md
content/events/2024-houston/speakers/stephen-d-king.md

[HOU-2024] Added linkedin urls for speakers

[HOU-2024] Added linkedin urls for speakers

---

data/events/2024/portugal/main.yml

- Extending the CFP deadline until 12/05

[PT-2024] cfp extended until 12/05

---

data/events/2024/seattle/main.yml

remove platinum from sponsor levels

[SEA-2024] remove platinum from sponsor levels

---

content/events/2024-berlin/program/ahmed-siouani.md
content/events/2024-berlin/speakers/ahmed-siouani.md
data/events/2024/berlin/main.yml

* Adds Ahmed as speaker
* Fixes last schedule issues

[BER-2024] Adds last minute ignite

---

content/events/2024-houston/program.md
data/events/2024/houston/main.yml

[HOU-2024] Published first version of schedule

[HOU-2024] Published first version of schedule

---

content/events/2024-caceres/welcome.md
data/events/2024/caceres/main.yml

This PR adds the link to the Eventbrite event site where to buy the early birds tickets that opens up next May 8th.
It also adds a community sponsor.

[CAC-2024] DevOpsDays Caceres 2024 early bird tickets

---

content/events/2024-amsterdam/registration.md
data/events/2024/amsterdam/main.yml

- Updated the program to remove karaoke mention and only mention bingo and socials
- Updated URL's on the ticket page from 2023 to 2024

[AMS-2024] fixes to program and urls

---

data/events/2024/des-moines/main.yml

Added Source Allies as a sponsor

[DSM-2024] Added Source Allies as a sponsor

---

content/events/2024-montreal/speakers/renata-rocha.md

A speaker changed jobs since she submitted her talk

[MTL-2024] Speaker changed jobs

---

data/events/2024/amsterdam/main.yml

Adding Okta as a Gold sponsor for Amsterdam 🎉

[AMS-2024] Add Okta Gold sponsor

---

data/events/2024/amsterdam/main.yml

Added Splunk as platinum sponsor

[AMS-2024] Updated Platinum sponsor

---

content/page/organizing.md

Instead of brining it into devopsdays github, here's a link to the app to make organizers life easier.

A note about leveraging JJ's ignite karaoke app

---

data/events/2024/seattle/main.yml

move openspace pitches to before lunch

[SEA-2024] move openspace pitches to before lunch

---

content/events/2024-des-moines/sponsor.md
data/events/2024/des-moines/main.yml

Add Lean Techniques and reduce number of remaining gold sponsorships

[DSM-2024] Added Lean TECHniques as a sponsor

---

content/events/2024-seattle/program.md

link to openspaces google sheet

[SEA-2024] link to openspaces google sheet

---

data/events/2024/caceres/main.yml

This PR adds some old collaborators that we also have this year.

[CAC-2024] DevopsDays Cáceres - collaborators

---

data/events/2024/philadelphia/main.yml

[URGENT][PHILLY-2024] Fix end date of conference

---

data/events/2024/houston/main.yml

[HOU-2024] Add Cockroach Labs and Checkmarx as sponsors.

---

data/events/2024/washington-dc/main.yml

[DC-2024] Add Tremolo silver sponsor

---

content/events/2025-chicago/welcome.md

Updates the welcome page to use new mailing list form and also make prettier

[CHI-2025] Update Chicago welcome page

---

data/events/2024/montreal/main.yml

Also added Agile Montreal as Community Sponsor

[MTL-2024] Removed empty sponsors categories

---

content/events/2024-antwerp/registration.md
data/events/2024/antwerp/main.yml
themes/devopsdays-theme/layouts/shortcodes/tix.html

- add registration details
- open registration page
- create a shortcode for tix for future usage

[ANTWERP-2024] add registration

---

data/events/2024/houston/main.yml

[HOU-2024] Fixed keynote reference in the program

[HOU-2024] Fixed keynote reference in the program

---

data/events/2024/amsterdam/main.yml

Added Essent as Bronze sponsor

[AMS-2024] Adding bronze sponsor

---

content/events/2024-organiser-summit/registration.md
data/events/2024/organiser-summit/main.yml

- open registration for the Organizer Summit 2024 in Antwerp

[ORGANISERSUMMIT-2024] open registration

---

data/events/2024/minneapolis/main.yml

Adds Solarwinds as a sponsor for Minneapolis
No update required for logo 👍

[MSP-2024]: Add solarwinds as sponsor

---

data/events/2024/minneapolis/main.yml

Adding Hack the Gap community sponsor.
/cc @mrbobbytables @jeefy

[MSP 2024] Adding community sponsor

---

content/events/2024-birmingham-al/program.md

The dates have changed and this commit uses the current dates.

[BHM-AL-2024] Fix dates for Birmingham, AL 2024

---

content/events/2024-montreal/speakers/joyce-lin.md
content/events/2024-montreal/speakers/kat-gaines.md

[MTL-2024] Speaker changed job title

---

content/events/2024-montreal/speakers/sasha-rosenbaum.md

update speaker name on request

[MTL-2024] update speaker name

---

data/events/2024/amsterdam/main.yml

Added Komodor as silver sponsor.

[AMS-2024] add silver sponsor

---

content/events/2024-houston/program.md
data/events/2024/houston/main.yml

Fixed a custom link to the evening event location
Added color to the raffle time slot in the program

[HOU-2024] Fixed a custom program link and added color to the raffle time slot 

---

data/events/2024/london/main.yml

Add Matt Slane as a London organiser

[London-2024] Add Matt Slane as an organiser

---

data/events/2024/fortaleza/main.yml

[FOR-2024] - This pull request adds registration link and add saveincloud as sponsor.

[FOR-2024] - add registration link and add saveincloud as sponsor

---

content/events/2024-montreal/program.md
content/events/2024-montreal/welcome.md
data/events/2024/montreal/main.yml

Removed registration and made program static

[MTL-2024] Post event clean up

---

content/events/2024-nashville/welcome.md
data/events/2024/nashville/main.yml

Updates the welcome page with CFP closing and other information.

[NSH-2024] Updates for CFP and other info

---

data/events/2024/houston/main.yml

[HOU-2024] Added link to google sheet for Open Spaces scheduling

[HOU-2024] Added link to google sheet for Open Spaces scheduling

---

content/events/2024-amsterdam/speakers/sasha-rosenbaum.md

[AMS-2024] Changing Sasha Rosenbaum name

---

data/events/2024/portugal/main.yml

Adding registration to start selling tickets.

[PT-2024] Registration page

---

data/events/2024/london/main.yml

- The CfP is closed. Ticket sales are open.

[2024-LDN] Swap in "Registration" header item for "Propose"

---

data/events/2024/rio-de-janeiro/main.yml

[RIO-2024] New Sponsor

---

data/events/2024/houston/main.yml

houston is in flight today but fell off the page

[HOU-2024] Fix end time so event shows up

---

data/events/2024/rio-de-janeiro/main.yml

[RIO-2024] Fix Sponsor

---

data/events/2024/nashville/main.yml

Adds Shadow-Soft as a bronze sponsor

[NSH-2024] Adds bronze sponsor

---

content/events/2024-nashville/registration.md
content/events/2024-nashville/topics.md
content/events/2024-nashville/welcome.md
data/events/2024/nashville/main.yml

Creates a topics page while we work on the final schedule

[NSH-2024] Topics page

---

content/events/2024-nashville/topics.md

[NSH-2024] Topic update

---

content/events/2024-boston/welcome.md
data/events/2024/boston/main.yml

Open registration and the CFP for Boston.

[BOS-2024] Registration and CFP

---

content/blog/good-better-best.md

Adds some missing words to a sentence.
From:
But often the total number of attendees and how the event actually felt on the ground, including attendees, sponsors, and organizers.
To:
But don’t often have visibility into the total number of attendees and how the event actually felt on the ground, including attendees, sponsors, and organizers.
Preview:  https://deploy-preview-14173--devopsdays-web.netlify.app/blog/2024/06/06/good-better-best-how-to-budget-for-success/

[blog] Updates the Good, Better Best blog

---

content/events/2024-nashville/topics.md

[NSH-2024] Adds new topic to session list

---

content/events/2024-caceres/program.md
content/events/2024-caceres/welcome.md
data/events/2024/caceres/main.yml

This PR adds the initial version of the agenda structure so any participants can check the initial and end hours of the event.
It also adds a early bird tickets temporary banner to make it more visible in the welcome page.

[CAC-2024] DevopsDays Cáceres - agenda structure

---

content/events/2024-kerala/conduct-fr.md
content/events/2024-kerala/conduct-pt-br.md
content/events/2024-kerala/conduct.md
content/events/2024-kerala/contact.md
content/events/2024-kerala/location.md
content/events/2024-kerala/propose.md
content/events/2024-kerala/registration.md
content/events/2024-kerala/sponsor.md
content/events/2024-kerala/welcome.md
data/events/2024/kerala/main.yml
static/_redirects

-  [x] Add DevOpsDays Kerala 2024 to the event

[KER-2024] Add DevOpsDays Kerala 2024 Event

---

data/events/2025/chicago/main.yml

Add the registration link for Chicago 2025 - @mattstratton let me know if I missed anything here!

[CHI-2025] add registration link (thanks Corey!)

---

content/events/2025-chicago/location.md
content/events/2025-chicago/registration.md
content/events/2025-chicago/welcome.md
data/events/2025/chicago/main.yml

Adds location page and polishes up the welcome page
fyi @dexhorthy

[CHI-2025] update location page and add buttons

---

data/events/2024/london/main.yml

- When I uncommented the registration `nav_element` I did not realize that the start and end dates had to be set too.

[LDN-2024] Fix registration link

---

content/events/2024-london/conduct.md

Updating the London code of conduct based off the new Amsterdam one. Imitation, flattery, etc.

[London-2024] Updated CoC based on Amsterdam's rather good one

---

data/events/2024/campinas/main.yml

Fix LinkedIn profile link for Paula Santos.

[Campinas-2024] Fix organizer linkedIn profile link

---

content/events/2024-tampa/location.md
content/events/2024-tampa/sponsor.md
content/events/2024-tampa/welcome.md
data/events/2024/tampa/main.yml

Update event registration link for 2024 Tampa Bay event

[TPA-2024] Update event registration link for 2024 Tampa Bay event

---

data/events/2024/denver/main.yml

:tada:
LGTM:
https://deploy-preview-14238--devopsdays-web.netlify.app/events/2024-denver/welcome/

[DEN-2024] Add Flox @ Gold

---

content/events/2024-minneapolis/program.md
content/events/2024-minneapolis/program/ian-coldwater.md
content/events/2024-minneapolis/program/joel-tosi.md
content/events/2024-minneapolis/program/shilad-sen-susan-fox.md
content/events/2024-minneapolis/speakers/darnell-otterson.md
content/events/2024-minneapolis/welcome.md
data/events/2024/minneapolis/main.yml
data/events/2024/minneapolis/program.yml

Schedule created in consultation with @wiredferret & @anfleene.

[MSP 2024] Schedule/program updates

---

content/events/2024-portugal/propose.md

[PT2024] Close CFP button text

---

data/events/2024/washington-dc/main.yml

[DC-2024] Add Flox Platinum Sponsor

---

data/events/2024/denver/main.yml

[DEN-2024] Add Honeycomb @ Silver

---

content/events/2024-boston/sponsor.md
content/events/2024-boston/welcome.md
data/events/2024/boston/main.yml

What it says on the tin.
This PR depends on devopsdays/devopsdays-assets#210 before merging.

[BOS-2024] Open sponsorships for 2024

---

content/events/2024-antwerp/speakers/olivier-vernin.md

[ANTWERPEN-2024] typo

---

content/events/2024-halifax/sponsor.md

This pull request updates the sponsor packages and adds new special sponsorships for DevOpsDays Halifax 2024. The following changes have been made:

[HAL-2024] Update Sponsor Packages and Add New Special Sponsorships

---

data/events/2024/paris/main.yml

Add Dina to the local organising team 🫶 
(email sent to info@)

[Paris-2024] Add Dina

---

data/core.toml

Laura Santamaria is now part of the Global Core team! 🎉

[CORE] Adding Laura Santamaria to the core team

---

data/events/2024/halifax/main.yml

This PR adds a custom link for the speakers page.

[HALIFAX-2024] Add a custom link for the speakers page.

---

content/events/2024-belo-horizonte/location.md
content/events/2024-belo-horizonte/welcome.md
data/events/2024/belo-horizonte/main.yml

In this pull request I added the updated location of devopsdays belo Horizonte 2024 and also the event registration link

[BHZ-2024] Adding Registration Link and Location

---

data/events/2025/chicago/main.yml

Copied the address from `data/2023/chicago`

[CHI-2025] Add location address to welcome banner

---

content/events/2024-antwerp/program.md
content/events/2024-antwerp/program/a-decade-with-dora.md
content/events/2024-antwerp/program/ai-you-complete-me.md
content/events/2024-antwerp/program/beyond-the-genai-+-llm-hype--leveraging-data-platforms-for-devops-success.md
content/events/2024-antwerp/program/continuously-update-everything.md
content/events/2024-antwerp/program/culture-is-still-a-challenge.md
content/events/2024-antwerp/program/deming-to-devops-revisited-2024.md
content/events/2024-antwerp/program/developer-experience-can-drive-business-growth.md
content/events/2024-antwerp/program/devsecoops--15-years-of-devops-and-patching-is-still-horrible-but-should-you-care-.md
content/events/2024-antwerp/program/evolving-devops-teams-and-flexible-organizational-culture.md
content/events/2024-antwerp/program/fast-flow--blockers-and-pitfalls.md
content/events/2024-antwerp/program/green-code-on-the-cloud--integrating-sustainability-into-devops-practices.md
content/events/2024-antwerp/program/integer-programming-to-optimize-costs-in-kubernetes.md
content/events/2024-antwerp/program/low-growth-devops.md
content/events/2024-antwerp/program/never-ever-upgrade.md
content/events/2024-antwerp/program/platform-engineering-is-not-about-tech.md
content/events/2024-antwerp/program/platform-engineering-xxl.md
content/events/2024-antwerp/program/why-motivation-is-so-important-burnout-vs-de-motivation.md
content/events/2024-antwerp/program/wiring-for-flow.md
data/events/2024/antwerp/program.yml

Schedule updates for 2024-antwerp
Auto Release from Pretalx to DoD Schedule
***Conference Hook System***

[ANTWERP-2024] Pretalx => DoD Schedule Auto Update

---

content/events/2024-halifax/welcome.md

This PR to add Event Schedule button and fix Speakers button link in the Halifax 2024 event welcome page

[HAL-2024] Modify Welcome Page Buttons

---

themes/devopsdays-theme/reference.md

Adding the ```tix``` shortcode to the documentation

[DOCUMENTATION] add tix shortcode documentation #14312

---

data/events/2024/des-moines/main.yml

If you are changing sponsor information, be sure you are [following the guidelines](https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data).

DSM-2024 Add GitGuardian as a sponsor

---

data/events/2024/antwerp/main.yml

[ANTWERP-2024] Adding Github as sponsor

---

content/events/2024-brasilia/welcome.md
data/events/2024/brasilia/main.yml

Adds social media links and registration link

[BSB-2024] add social media

---

data/events/2024/curitiba/main.yml

Update event date and organizers, as well Call for Papers form link.

[CWB-2024] Update event date and organizers

---

data/events/2024/jakarta/main.yml

[JKT-2024] Change Location of DevOpsDays Jakarta 2024
- Change Location of DevOpsDays Jakarta 2024
- Remove commented line 
Thank you

[JKT-2024] Change Location of DevOpsDays Jakarta 2024

---

data/events/2024/portugal/main.yml

* CriticalTechWorks (Gold)
* DevOps Porto (Community)
* DevOps Lisbon (Community)

[PT-2024] Added gold and community sponsors

---

data/events/2024/cairo/main.yml

[CAI-24] Extend CfP

---

content/events/2024-washington-dc/program.md
content/events/2024-washington-dc/speakers.md
content/events/2024-washington-dc/welcome.md
data/events/2024/washington-dc/main.yml

- Add pages for program and speakers that include info in Sessionize
- Enable top-level nav for program and speakers
- Add speakers to welcome page

[DC-2024] Publish program

---

data/events/2024/portugal/main.yml

* added elastic as gold sponsor

[PT-2024] added elastic as gold sponsor

---

content/events/2024-antwerp/welcome.md

Make registration link more visible on the main Antwerp page.

[ANTWERP-2024] Make the registration link more visible on the main page

---

data/events/2024/florianopolis/main.yml

[FLN-2024] Update event date

---

content/events/2024-antwerp/welcome.md

[ANTWERP-2024] Add more info to Main page

---

data/events/2024/portugal/main.yml

* added bronze sponsors - relex

[PT-2024] added bronze sponsors - relex

---

data/events/2024/birmingham-al/main.yml

Adding in additional BHM-AL-2024 sponsors that have paid and onboarded

[BHM-AL-2024] Adding more sponsors

---

data/events/2024/minneapolis/main.yml

Add last round of sponsors
- komodor
- spacelift
- tailscale

MSP-2024: Add sponsors

---

content/events/2024-amsterdam/program/ig-nathen-harvey.md
content/events/2024-amsterdam/program/ws-nathen-harvey-amanda-lewis-dave-stanke.md

Linking to slides and video from two of the talks from DevOpsDays Amsterdam 2024

[AMS-2024] Add slides and video for Nathen's talks

---

content/events/2024-rio-de-janeiro/lgpd.md
data/events/2024/rio-de-janeiro/main.yml

[RIO-2024]New Info - LGPD

---

content/events/2024-rio-de-janeiro/lgpd.md

[RIO-2024]Fix LGPD Info

---

content/events/2024-london/speakers/daniel-phrawzty-maher.md

Update my bio as I am gainfully employed now :)

[London-2024] Update bio for Dan

---

content/events/2024-minneapolis/program.md
content/events/2024-minneapolis/welcome.md

* Adds OS Schedule links to program and welcome
* Adds Livestream links to program and welcome

[MSP 2024] Add 2024 Livestream and Open Space Schedule

---

content/events/2025-chicago/propose.md
content/events/2025-chicago/welcome.md
data/events/2025/chicago/main.yml

Adds propose page and enables reg etc

[CHI-2025] Add CFP

---

data/events/2025/chicago/main.yml

Adding Atono Gold Sponsor for Chicago 2025 Event

[CHI-2025] Adding Atono Gold Sponsor

---

content/events/2024-portugal/program/heather-thacker-ignite.md
content/events/2024-portugal/program/kris-buytaert-ignite.md

* added ignite from kris and heather.

[PT-2024] added ignite from kris and heather

---

data/events/2024/london/main.yml

- Checkly have sponsored us for Silver.

[2024-LDN] Add Checkly as a Silver sponsor

---

content/events/2024-chattanooga/program.md
content/events/2024-chattanooga/speakers.md

Adding sessionize links for 2024.

[CHATTANOOGA-2024] Add sessionize link for 2024

---

data/events/2024/fortaleza/main.yml

Adding nutanix and clearit as sponsors.

FORTALEZA-2024: add new sponsors

---

content/events/2024-birmingham-al/program/steve-hallman-talk.md
data/events/2024/birmingham-al/main.yml

[BHM-AL-2024] Program update

---

data/events/2024/tampa/main.yml

[TPA-2024] Add Codiac as a diamond sponsor for Tampa 2024 event

[TPA-2024] Add Codiac as a diamond sponsor for Tampa 2024 event

---

content/events/2024-montreal/welcome.md

Added a link to the recordings in YouTube

[MTL-2024] Recap and link to videos added

---

data/events/2024/boston/main.yml

[BOS-2024] CloudZero sponsorship

---

content/events/2024-florianopolis/location.md
content/events/2024-florianopolis/welcome.md
data/events/2024/florianopolis/main.yml

Add link tickets and event location.

Add: Include link ticket and location

---

content/events/2024-porto-alegre/location.md
content/events/2024-porto-alegre/sponsor.md
content/events/2024-porto-alegre/welcome.md
data/events/2024/porto-alegre/main.yml

This PR adds the following details for the upcoming DevOpsDays Porto Alegre event:
- Event location
- Event date
- Sponsorship Information
- Sponsorship levels and benefits

[POA-2024] Add data and location and update sponsor descriptions

---

data/events/2024/washington-dc/main.yml

We're updating the info for one organizer. Modified DC YAML file.
I'll send an email to make the update to our email distro, too.

[DC-2024] Update organizer info

---

content/events/2024-antwerp/conduct.md

[2024-ANTW] Adding COC contact details

---

data/events/2024/dallas/main.yml

add zeal it as silver sponsor
Update CapOne to gold sponsor

[DFW-2024] add zeal it as silver sponsor

---

data/events/2025/chicago/main.yml

[CHI-2025] Add Honeycomb as Gold Sponsor

---

content/events/2024-salvador/conduct-fr.md
content/events/2024-salvador/conduct-pt-br.md
content/events/2024-salvador/conduct.md
content/events/2024-salvador/contact.md
content/events/2024-salvador/location.md
content/events/2024-salvador/propose.md
content/events/2024-salvador/registration.md
content/events/2024-salvador/sponsor.md
content/events/2024-salvador/welcome.md
data/events/2024/salvador/main.yml
static/_redirects

We are starting the devopsdays Salvador 2024.

[SSA-2024] Começando Salvador

---

content/events/2024-portugal/speakers/valarie-regas.md

[PT-2024] fix valarie name

---

content/events/2024-portugal/speakers/valarie-regas.md
data/events/2024/portugal/main.yml

* Added sponsors: daimler and google

[PT-2024] sponsors daimler google

---

data/events/2024/salvador/main.yml

[SSA-2024] Fix Dara photo

---

content/events/2024-antwerp/program/a-decade-with-dora.md

Adds a link to Nathen's Decade with DORA slides
Preview - https://deploy-preview-14551--devopsdays-web.netlify.app/events/2024-antwerp/program/a-decade-with-dora

[ANTWERP-2024] Add link to Nathen's slides

---

content/events/2024-caceres/program.md

This PR just change one speaker company name and removes the second keynote from Friday.

[CAC-2024] DevopsDays Cáceres - small program fixes

---

data/events/2024/dallas/main.yml

Add sponsors:
- FireHydrant - Gold
- DevItJobs.com - Media

[DFW2024] Add Firehydrant and devitjobs as sponsors

---

content/events/2024-vilnius/program/dainius-aksinavicius.md

- change one ignite description requested by arrogant speaker (maybe will be canceled)

[VLN-2024] Change ignite

---

content/events/2024-tel-aviv/welcome.md

- Made some edits and refreshed some of the text on the home page

[TLV-2024] New text and udpates

---

data/events/2024/brasilia/main.yml

- Adds a new sponsor
- Put a link to sponsor's rules on navbar
- Changes details of one organizer

[BSB-2024] Sponsors, Navbar, Organizers

---

content/events/2024-porto-alegre/welcome.md
data/events/2024/porto-alegre/main.yml

This PR adds the following details for the upcoming DevOpsDays Porto Alegre event:
- C4P date
- C4P link

[POA-2024] Add C4P

---

content/page/organizing.md

I used the same language as for the Pretalx/Pretix references.

[site] mention Vaultwarden in organising doc

---

content/events/2024-denver/welcome.md

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)
Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to …

[DEN-2024] Add livestream link

---

content/events/2025-chicago/sponsor.md

[CHI-2025] Update sponsor tiers

---

data/events/2024/denver/main.yml

[DEN-2024] Update with times 

---

content/events/2024-dallas/speakers/tracy-bannon.md
data/events/2024/dallas/main.yml

update Tracy Bannon LinkedIn link
add Hashicorp as gold sponsor

[DFW-2024] update Tracy Bannon LinkedIn link and add Hashicorp as gold sponsor

---

data/events/2025/aarhus/main.yml

Added two new sponsors to the event.

[AARHUS-2025] add gold and community sponsors for Aarhus 2025

---

content/events/2025-geneva/welcome.md

[GE-2025] add linkedin link

---

content/events/2024-london/program/james-wynne.md

Talk title has changed for James' talk.

[LDN-2024] update talk title for james wynne

---

data/events/2025/raleigh/main.yml

- open [CFP for DevOpsDays Raleigh 2025](https://forms.gle/Pxqg1zmoRHHEDWDJ9)

[RDU-2025] open call for proposals

---

content/events/2024-cairo/sponsor.md
data/events/2024/cairo/main.yml

[CAI-24] Closing Sponsorship

---

data/events/2024/dallas/main.yml

Add Texas Workforce Commission as a Non-Profit sponsor
Add Codiac.io as a gold sponsor

[DFW-2024] add twc and codiac as sponsors

---

data/events/2024/washington-dc/main.yml

- Add Site24x7 as a new Gold sponsor
- Re-order the sponsor tiers

[DC-2024] Add new Gold sponsor

---

data/events/2024/portugal/program.yml

fix schedule typo at Portugal 2024 program

[PT-2024] fix schedule typo

---

data/events/2024/des-moines/main.yml

Adding silver sponsors for  2024 Des Moines

DSM-2024  Adding additional sponsors

---

content/events/2024-boston/location.md

* Removed extraneous content (venue description)
* Added Table of Contents
* Added new image to replace broken 2017 archived one
* Added styling/layout to make ToC and image responsive for mobile and desktop
* Added qualified accommodation options
* Double-checked all links (second commit to fix previously broken venue link)

[BOS-2024] Update location page layout and content to include accommodations

---

content/events/2025-zurich/sponsor.md

Added the sponsoring page. 
ATTENTION: You also need to approve https://github.com/devopsdays/devopsdays-assets/pull/214 these two pull requests depend on each other

[ZRH-2025] Add sponsoring prospectus for 2025

---

data/events/2024/boston/main.yml

ScaleOps coming in at Platinum.

[BOS-2024] ScaleOps sponsorship

---

content/events/2024-tel-aviv/welcome.md

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)
Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to …

Update program date - Tel Aviv 2024

---

content/events/2025-cairo/welcome.md

[CAI-25] Fixing welcome page

---

content/events/2024-boston/program/sanjita-gupta.md

[BOS-2024] Fix Sanjita's talk title

---

content/events/2025-zurich/sponsor.md
content/events/2025-zurich/welcome.md
data/events/2025/zurich/main.yml

- updated & enabled sponsoring page
- enabled cfp
- added sponsor cloudscale

[ZRH-2025] enabled sponsoring page & cfp

---

content/events/2024-caceres/program.md
content/events/2024-caceres/program/ai-boost.md

This Pr just updates one talk description as requested by the speaker.

[CAC-2024] DevopsDays Cáceres - last minute talk update

---

content/events/2024-london/welcome.md
data/events/2024/london/main.yml

We're still waiting for the ✅ for the recordings and photography so lets do this for now.

[LDN-2024] close off the conf for 2024

---

content/events/2024-antwerp/program.md
content/events/2024-antwerp/program/a-decade-with-dora.md
content/events/2024-antwerp/program/ai-you-complete-me.md
content/events/2024-antwerp/program/all-good-ends-can-be-worked-out-by-good-means-or-how-to-do-open-source-enterprise-software-as-a-mature-org.md
content/events/2024-antwerp/program/continuously-update-everything.md
content/events/2024-antwerp/program/culture-is-still-a-challenge.md
content/events/2024-antwerp/program/deming-to-devops-revisited-2024.md
content/events/2024-antwerp/program/developer-experience-can-drive-business-growth.md
content/events/2024-antwerp/program/devops-and-baking.md
content/events/2024-antwerp/program/devops-is-not-a-factory.md
content/events/2024-antwerp/program/devsecoops--15-years-of-devops-and-patching-is-still-horrible-but-should-you-care-.md
content/events/2024-antwerp/program/evolving-devops-teams-and-flexible-organizational-culture.md
content/events/2024-antwerp/program/failing-to-learn-vs-learning-to-fail.md
content/events/2024-antwerp/program/fast-flow--blockers-and-pitfalls.md
content/events/2024-antwerp/program/green-code-on-the-cloud--integrating-sustainability-into-devops-practices.md
content/events/2024-antwerp/program/integer-programming-to-optimize-costs-in-kubernetes.md
content/events/2024-antwerp/program/low-growth-devops.md
content/events/2024-antwerp/program/never-ever-upgrade.md
content/events/2024-antwerp/program/platform-engineering-is-not-about-tech.md
content/events/2024-antwerp/program/platform-engineering-xxl.md
content/events/2024-antwerp/program/welcome-to-devopsdays-15th.md
content/events/2024-antwerp/program/wiring-for-flow.md
content/events/2024-antwerp/speakers/dan-maher.md
data/events/2024/antwerp/program.yml

Adding Youtube video links to the program of the Antwerp 2024 event.

[Antwerp-2024] Add Youtube video links to program.

---

content/events/2024-dallas/welcome.md
data/events/2024/dallas/main.yml

Remove the link to call for papers

[DFW-2024] Remove the propse link

---

data/events/2024/chattanooga/main.yml

Adds our initial sponsors. All of them exist in `data/sponsors` already.

[CHATTANOOGA-2024] Add initial sponsors

---

themes/devopsdays-theme/layouts/shortcodes/list_organizers.html
themes/devopsdays-theme/layouts/speaker/single.html
themes/devopsdays-theme/layouts/speakers/single.html

Fixes a bug with the speaker and organizer images

Fix issue with organizer and speaker images

---

content/events/2024-caceres/program/platform-roi.md
content/events/2024-caceres/welcome.md
data/events/2024/caceres/main.yml

This PR includes some minor post-event changes:
- One talk slide deck links
- Spotify shared playlist link created by the presenter

[CAC-2024] DevopsDays Cáceres - post event changes

---

data/events/2024/salvador/main.yml

[SSA-2024] Add CFP

---

data/events/2024/salvador/main.yml

[SSA-2024] - Add registration and location with date

[SSA-2024] - Add registration and location with date

---

data/events/2024/boston/main.yml

[BOS-2024] Dryrun Security sponsorship

---

data/events/2024/salvador/main.yml

The location is wrong. We need to change it.

[SSA-2024] fix location

---

content/events/2024-antwerp/program/all-good-ends-can-be-worked-out-by-good-means-or-how-to-do-open-source-enterprise-software-as-a-mature-org.md

[ANT-2024] Removing youtube link of speaker on his demand

---

content/events/2024-dallas/program/aditya-singh.md

remove product name from talk title per request

[DFW-2024] remove product name from talk title per request

---

data/events/2025/los-angeles/main.yml

- Adding kube events as media sponsor
- Adding kube careers as media sponsor
**Tested:**

[LA-2025] Adding media sponsors

---

content/events/2024-paris/welcome.md
data/events/2024/paris/main.yml

- Add registration link
- Add link to main event site

[2024-paris] small updates to welcome and main

---

content/events/2025-geneva/newsletter.md
content/events/2025-geneva/welcome.md
data/events/2025/geneva/main.yml

[GE-2025] add newsletter

---

content/events/2025-los-angeles/welcome.md

- Adding more text to the welcome page
- Looking for more speakers
**Tested:**

[LA-2025] Improving welcome page

---

content/events/2025-los-angeles/welcome.md

- Fixing typos DevOpsDay vs DevOpsDays
**Tested:**

[LA-2025] Fixing typos

---

content/events/2024-boston/program.md

Add to program page:
- open spaces form
- additional activities link
- scavenger hunt info
- lightning talk form

[BOS-2024] Update Program with day-of extra logistics

---

data/events/2025/raleigh/main.yml

Added the pretix link for DevOpsDays Raleigh

[Raleigh-2025] Added Pretix registration link.

---

data/events/2025/raleigh/main.yml

I forgot to uncomment the registration_date_start and registration_date_end lines in main.yml
So I just did it.

[Raleigh-2025] Activated Registration_date_start in main.yml

---

data/events/2025/raleigh/main.yml

I forgot to uncomment the registration link. 
It's been a long day.....................

[Raleigh-2025] Updated Registration in main.yml

---

data/events/2025/raleigh/main.yml

Uncommented lines 42 and 43 so registration works.

[Raleigh-2025] More Registration updates, uggghhhh

---

content/events/2025-los-angeles/sponsor.md

- Fixing link on the sponsor's page

[LA-2025] Fixing sponsor page

---

content/events/2024-salvador/welcome.md
data/events/2024/salvador/main.yml

fix location and page style
add sponsor

[SSA-2024] fix location and page style

---

data/events/2024/brasilia/main.yml

[BSB-2024] add more sponsors

---

content/events/2025-geneva/propose.md
content/events/2025-geneva/welcome.md
data/events/2025/geneva/main.yml

[GE-2025] add cfp link

---

content/events/2025-zurich/sponsor.md
data/events/2025/zurich/main.yml

Added sponsors: 
- Cognizant 
- Eficode

[ZRH-2025] Add sponsors Cognizant and Eficode

---

content/events/2025-zurich/sponsor.md
data/events/2025/zurich/main.yml

Add sponsors: 
- BIT
- DBI Services

[ZRH-2025] Add sponsros BIT and DBI Services]

---

content/events/2024-porto-alegre/program/valeria-baptista.md
data/events/2024/porto-alegre/program.yml

This PR adds the following details for the upcoming DevOpsDays Porto Alegre event:
- Update Valeria Baptista's talk title
- Add speaker (Clayton Cavaleiro)

[POA-2024] Update speakers

---

content/events/2024-brasilia/welcome.md

[BSB-2024] add social media link

---

data/events/2025/aarhus/main.yml

Adds a new silver-level sponsor.

[AARHUS-2025] Add Systematic as a sponsor

---

content/events/2025-los-angeles/welcome.md
data/events/2025/los-angeles/main.yml

- Closing CFP
- Removing links
**Tested:**
- Locally using Hugo****

[LA-2025] Closing CFP

---

content/events/2025-prague/sponsor.md
data/events/2025/prague/main.yml
static/_redirects

- Adding sponsor levels
- Fixing default city redirect

[PRG-2025] Add sponsor levels

---

content/events/2025-zurich/registration.md
content/events/2025-zurich/sponsor.md
content/events/2025-zurich/welcome.md
data/events/2025/zurich/main.yml

- Add Elastic and Redgate as Gold Sponsors 
- and open registration
- Correct the resgistration and CFP dates

[ZRH-2025] Add Elastic and Redgate as Gold Sponsors and open registration

---

data/events/2024/salvador/main.yml

[SSA-2024] - Add sponsors

---

data/events/2025/chicago/main.yml

Add Relativity as a gold sponsor

[CHI-2025] Add relativity as gold

---

data/events/2025/los-angeles/main.yml

- Adding semaphore and honeycomb as gold sponsors
**Tested:**
- Locally

[LA-2025] Adding two more gold sponsors

---

content/events/2025-prague/propose.md
content/events/2025-prague/sponsor.md
data/events/2025/prague/main.yml

Open CFP
Improve sponsor page  - depends on https://github.com/devopsdays/devopsdays-assets/pull/219

[PRG-2025] Open cfp and sponsor improvements

---

content/events/2025-chicago/health-and-safety.md
data/events/2025/chicago/main.yml

This PR:
- Commits the new 2025 Health & Safety policy
- Enables the link on the main page

[CHI-2025] Update 2025 health and safety policy

---

data/events/2025/amsterdam/main.yml

[AMS-2025] CfP live

---

data/events/2025/amsterdam/main.yml

[AMS-2025] Add first sponsor: Schuberg

---

content/events/2025-aarhus/welcome.md

Adds a section that links to our call for speakers form.

[aarhus-2025] Added a section that links to call for speakers.

---

data/events/2025/chicago/main.yml

Add FusionAuth and Cortex as gold

[CHI-2025] Add sponsors

---

content/events/2025-des-moines/sponsor.md

Added pricing and information for 2025  Des Moines sponsors

[Des Moines-2025] Updated the Sponsor Information  Page

---

content/events/2025-eindhoven/sponsor.md
data/events/2025/eindhoven/main.yml

[EHV-2025] link sponsor prospectus

---

content/events/2025-kansas-city/propose.md
data/events/2025/kansas-city/main.yml

- Update Registration code to have link directly to the DevOpsDays KC addon
- Update CFP description

[KC-2025] basic updates

---

data/events/2025/atlanta/main.yml

adding CFP link for ATL 2025 to devopsdays website.

[ATL-2025] adding CFP link 

---

data/events/2025/goiania/main.yml

- Update CfP dates and URL
- Update registration end date and URL

[GYN-2025] Update CfP and registration info

---

data/events/2025/los-angeles/main.yml

- Adding checkmarx as gold sponsor
**Tested:**

[LA-2025] Adding a gold sponsor

---

content/events/2024-los-angeles/program.md

- Adding video links for 2024 program
**Tested:**

[LA-2025] Adding video links for program 2024

---

content/events/2025-aarhus/welcome.md

Remove CFP section from frontpage now that we've passed the deadline.

[AARHUS-2025] Close cfp

---

data/events/2025/chicago/main.yml

[CHI-2025] Add program link

---

content/events/2025-zurich/sponsor.md
data/events/2025/zurich/main.yml

Added sponsors
- Exoscale
- Checkmarx

[ZRH-2025] Added sponsor checkmarx and exoscale

---

content/events/2025-prague/registration.md
content/events/2025-prague/welcome.md
data/events/2025/prague/main.yml

Open ticket sale for Prague 2025
Add propose link to the welcome page

[PRG-2025] Open registration

---

static/_redirects

- Updated the _redirect to point to the 2025 Vilnius event

[VLN-2025] updated _redirect

---

data/events/2025/amsterdam/main.yml

Adding elastic as gold sponsor

[AMS-2025] Add sponsor

---

content/events/2025-vilnius/sponsor.md
content/events/2025-vilnius/welcome.md
data/events/2025/vilnius/main.yml

- Add link to CFP
- Add community sponsors
- Add link to sponsorship prospectus

[VLN-2025] Add CFP and Sponsor info

---

data/events/2025/amsterdam/main.yml

[AMS-2025] Adding sponsor

---

content/events/2025-chicago/program/henrietta-dombrovskaya.md

[CHI-2025] Update with Hettie's talk title

---

content/events/2025-chicago/program/michael-stahnke.md

[CHI-2025] Fix description of talk

---

content/events/2025-chicago/program/heather-thacker.md
content/events/2025-chicago/speakers/heather-thacker.md
data/events/2025/chicago/program.yml

[CHI-2025] Add Heather details

---

content/events/2025-chicago/volunteer.md

This PR:
* Enables the 2025 volunteers page

[CHI-2025] Enable 2025 volunteer page

---

data/events/2025/chicago/main.yml

[CHI-2025] add couchbase as gold

---

data/events/2025/chicago/main.yml

[CHI-2025] Add checkmarx 

---

content/events/2025-detroit/conduct-fr.md
content/events/2025-detroit/conduct-pt-br.md
content/events/2025-detroit/conduct.md
content/events/2025-detroit/contact.md
content/events/2025-detroit/location.md
content/events/2025-detroit/propose.md
content/events/2025-detroit/registration.md
content/events/2025-detroit/sponsor.md
content/events/2025-detroit/welcome.md
data/events/2025/detroit/main.yml
static/_redirects

[DET-2025] Add Detroit 2025 event

---

data/events/2025/zurich/main.yml

[ZRH-2025] Adjust program times

---

data/events/2025/chicago/main.yml

[CHI-2025] Add Chicago meetups as sponsors

---

content/events/2025-eindhoven/conduct.md

Update CoC to bring it in line with the CoC Amsterdam and Antwerp adopted in 2024.

[EHV-2025] update coc

---

data/events/2025/vilnius/main.yml

[VLN-2025] Gold Sponsor Added

---

content/events/2025-chicago/sponsor.md

removing online payment since we are oversoldd almost

[CHI-2025] take down paypal links chicago

---

data/events/2025/chicago/main.yml

[CHI-2025] Add gitlab as gold

---

data/events/2025/chicago/main.yml

[CHI-2025] Add spacelift as gold

---

content/events/2025-goiania/sponsor.md
data/events/2025/goiania/main.yml

Updates to CFP dates, sponsors and sponsorship page

[GYN-2025] Update event

---

content/events/2025-geneva/welcome.md
data/events/2025/geneva/main.yml

[GE-2025] remove proposal

---

themes/devopsdays-theme/layouts/shortcodes/tix.html
themes/devopsdays-theme/reference.md

- add the variable option `info`
- if `info` is show, we display the event info in the widget

[SITE] add pretix display event info

---

data/events/2025/goiania/main.yml

Add 2 new `gold` sponsors and add `platinum` sponsor level

[GYN-2025] Add Gold sponsors

---

data/events/2025/chicago/main.yml

[CHI-2025] Add CastAI as gold

---

data/events/2025/amsterdam/main.yml

[AMS-2025] Added sponsorship level for FikaWorks

---

data/events/2025/chicago/main.yml

[CHI-2025] Add gold sponsor

---

data/events/2025/atlanta/main.yml

[ATL-2025] Adding spacelift as a gold sponsor

---

content/events/2025-chicago/welcome.md

some folks thought we might be selling our list :)

[CHI-2025] Slight update of email opt in

---

content/events/2025-zurich/program/alina-liburkina.md
content/events/2025-zurich/program/alvaro-revuelta-m.md
content/events/2025-zurich/program/marc-herren.md
content/events/2025-zurich/program/rabieh-fashwall.md
content/events/2025-zurich/program/stefan-pezzei.md
content/events/2025-zurich/program/thomas-krag.md
data/events/2025/zurich/main.yml

- Changed the workshop requirements for Krag
- Changed the number of participants for workshops
- Added sponsor zesty

[ZRH-2025] changes for week 8

---

data/events/2025/tel-aviv/main.yml

- Our CFP info didn't properly publish - help with fixing this quickly would be greatly appreciated.

[TLV-2025] Urgent CFP fix

---

data/events/2025/chicago/main.yml

[CHI-2025] Adding last9 as gold sponsor

---

content/events/2025-chicago/sponsor.md
data/events/2025/chicago/main.yml

Add postman as gold and lanyard

[CHI-2025] Add Postman

---

content/events/2025-zurich/program/alina-liburkina.md

- Add Workshop Prerequisits for Alina

[ZRH-2025] Add Workshop Prerequisits for Alina

---

data/events/2025/chicago/main.yml

Also moved Postman's Gold into the same section as the other golds (change to the site, just file organization)

[CHI-2025] Add IIT as community sponsor

---

content/events/2025-washington-dc/welcome.md
data/events/2025/washington-dc/main.yml

- Update welcome.md with info about the event
- Make the changes to main.yml to open the CFP

[DC-2025] Update welcome page and open CFP

---

content/events/2025-baltimore/sponsor.md

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)
Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to …

[bmore-2025] sponsor levels

---

data/events/2025/chicago/program.yml

[CHI-2025] Fix schedule error 

---

content/events/2025-zurich/speakers/rasmus-lystrom.md

- Fix wrong picture url of rasmus

[ZRH-2025] Fix wrong picture url of rasmus

---

content/events/2025-zurich/speakers/pia-wiedermayer.md

- Changed the company url of Pia

[ZRH-2025] Changed the company url of Pia

---

content/events/2025-chicago/program/henrietta-dombrovskaya.md
content/events/2025-chicago/program/keith-willoughby.md
content/events/2025-chicago/speakers/keith-willoughby.md

Added talk description for speakers Keith and Henrietta. Updated Keith's bio.

[CHI-2025] Add talk description for Keith and Henrietta

---

content/events/2025-los-angeles/welcome.md

- Updating welcome page
**Tested:**

[LA-2025] Updating welcome page

---

data/events/2025/geneva/main.yml
data/sponsors/hidora.yml

[GE-2025] add sponsors

---

content/events/2025-dallas/propose.md

Add link to CFP to the propose talks page

[DFW-2025] add cfp link to propose.md

---

data/events/2025/des-moines/main.yml

DSM 2025 - Opening Registration

DSM 2025 Open Registration

---

content/events/2025-chicago/sponsor-layout.md

the html tags should not be in there

[CHI-2025] Clean up page

---

data/events/2025/chicago/main.yml

[CHI-2025] Add peoplecert as gold

---

content/events/2025-chicago/sponsor-layout.md

[CHI-2025] Update sponsor-layout.md

---

content/events/2025-amsterdam/sponsor.md

Updates the prospectus to the latest version as we're entering crunch time. Might need a v4 as we production deadlines pass.
Thanks team!

[AMS-2025] v3 sponsorship prospectus

---

data/sponsors/peoplecert.yml

[CHI-2025] Update PeopleCert URL

---

content/events/2025-campinas/welcome.md
data/events/2025/campinas/main.yml

Added link of sponsorship document in main page.

[CPS-2025] Add sponsorship links

---

data/events/2025/atlanta/main.yml

Add Shadow-soft, Stateful and devops.com as Bronze sponsors

[ATL-2025] Add new sponsors

---

data/events/2025/istanbul/main.yml

- Update X username for Derya Sezen from 'derya_sezen' to 'DeryaDorian'.
- Add profile image for Dogukan Turan ('dogukan-turan.jpg').

[IST-2025] Update x user and profile images

---

content/events/2025-chicago/program/annie-hedgpeth.md
content/events/2025-chicago/program/michael-stahnke.md

[CHI-2025] Add link to Annie and Mike slides

---

content/events/2025-zurich/welcome.md
data/events/2025/zurich/main.yml

- Added after movie
- closed registration

[ZRH-2025] Add Aftermovie

---

content/events/2025-austin/speakers.md

Pretalx's "featured" system didn't work for us, so we're working around it until the schedule is finalized. This PR adds the talk details back to the speaker page.

[ATX-2025] Re-add talk details

---

data/events/2025/amsterdam/main.yml

Adds ServiceNow as a Bronze-level sponsor 🙏

[AMS-2025] Add ServiceNow as Bronze sponsor

---

data/events/2025/atlanta/main.yml

adding fianu, chef/progress as gold sponsors

[ATL-2025] adding fianu, chef/progress as gold sponsors

---

data/events/2025/atlanta/main.yml

[ATL-2025] adding gremlin as gold

---

content/events/2025-lima/location.md
content/events/2025-lima/sponsor.md
content/events/2025-lima/welcome.md
data/events/2025/lima/main.yml

This pull request includes several updates to the content and structure of the DevOpsDays Lima 2025 event pages. The changes focus on improving the event's presentation, updating sponsorship information, and providing detailed logistical information for attendees.
* [`content/events/2025-lima/location.md`](diffhunk://#diff-a4a849dfee0b8cd6081b86467f1e2369b615d4e8c7089a1d8a9138c9078d9de5L2-R31): Updated the event location details, including venue address, parking information, public transportation options, and accessibility features.
* [`content/events/2025-lima/sponsor.md`](diffhunk://#diff-710c35366b33a13cb971145c75d9a34bf74a0880aafcc77ca6ca3880ee15ba18L7-R163): Revamped the sponsorship section with detailed information on sponsorship benefits, packages, and community sponsorship …

[LIMA-2025] Add location and update date event 

---

data/events/2025/london/main.yml

- Also try a PR to kick this again after #15012 didn't actually build?

[LDN-2025] Update Issy's social media links

---

data/events/2025/washington-dc/main.yml

- Added DevItJobs as a Community Sponsor

[DC-2025] chore: added devitjobs as community sponsor

---

data/events/2025/des-moines/main.yml

Des Moines 2025 - Add Turnberry as a Sponsor
Adjust Sponsorship Levels

DSM-2025 Add Turnberry as a Sponsor

---

data/events/2025/vilnius/main.yml

[VLN-2025] Added Sponsor

---

content/events/2025-halifax/welcome.md
data/events/2025/halifax/main.yml

CfP extension and add sponsors.

[HALIFAX-2025] CfP extension and add sponsors.

---

data/events/2025/atlanta/main.yml

adding checkmarx and gruntwork

[ATL-2025] adding checkmarx and gruntwork as gold sponsors

---

data/events/2025/geneva/main.yml

[GE-2025] update sponsors

---

content/events/2025-aarhus/speakers/henning-kjaer.md
content/events/2025-aarhus/speakers/kasper-borg-nissen.md

[AARHUS-2025] Fix speaker description

---

data/events/2025/eindhoven/main.yml

[EHV-2025] Add Silver sponsor Exoscale

---

content/events/2025-sao-paulo/welcome.md
data/events/2025/sao-paulo/main.yml

removing the event date as it will be rescheduled and change the event description

[SP-2025] Remove event date and change event description

---

content/events/2025-feira-de-santana/welcome.md

- Add a link to the form for those interested in becoming a sponsor

[feira-de-santana-2025] Add a link to the form for those interested in becoming a sponsor

---

content/events/2025-amsterdam/sponsor.md

We're on v4 of the prospectus due to deadlines passed and re-prioritizing. Thanks!

[AMS-2025] v4 of the prospectus

---

data/events/2025/atlanta/main.yml

adding flox as gold and swapping Katie Anderson and ACS talk spots.

[ATL-2025] Adding flox as gold

---

data/events/2025/aarhus/main.yml

Add Stickermule (existing) as sponsor.

[AARHUS-2025] Add Stickermule as community sponsor

---

data/events/2025/atlanta/main.yml

Add Google as a Bronze sponsor

[ATL-2025] Add Google as a Bronze sponsor

---

data/events/2025/washington-dc/main.yml

* add Google Cloud as a Silver sponsor for 2025 DC event

[DC-2025] Add Google Cloud as a Silver Sponsor

---

data/events/2025/atlanta/main.yml

[ATL-2025] Adjust schedule

---

data/events/2025/vilnius/main.yml

-fix type-o in date
-add announcement date

[VILNIUS-2025] Fix CFP date

---

content/events/2025-feira-de-santana/welcome.md
data/events/2025/feira-de-santana/main.yml

Add the ticket url for the event

[feira-de-santana-2025] Add the ticket url

---

content/events/2025-amsterdam/sponsor-info.md

Adding something for the team to feedback on. Deliberately unlisted as this is for sponsors only.

[AMS-2025] Add unlisted sponsor info file

---

data/events/2025/tel-aviv/main.yml

- Added Komodor and CastAI to our sponsors

[TLV-2025] New sponsors added

---

content/events/2025-belem/local.md
content/events/2025-belem/regulamento-pcd.md
content/events/2025-belem/welcome.md
data/events/2025/belem/main.yml

- add participation instructions for people with disabilities PcD
- improve welcome page layout

[BELEM-2025] Add new instructions for PCDs and improve home layout

---

data/events/2025/austin/main.yml

- remove lanyard and swag bag - out of time
- add honeycomb

[ATX-2025] remove levels and add sponsor

---

content/events/2025-feira-de-santana/program.md
content/events/2025-feira-de-santana/welcome.md
data/events/2025/feira-de-santana/main.yml

- Add link to submit talk
- Add program page

[feira-de-santana-2025] Add link to submit talk and program page

---

static/_redirects

Update splats for Kyiv/Kiev/Ukraine for 2025.

[2025-ukraine] update splat

---

data/events/2025/sibiu/main.yml
data/sponsors/sibiu-it-cluster.yml
data/sponsors/sibiu-visma.yml

- Enabled the registration page, we'll go with event bride this year as well for Sibiu
- fixed sponsor URLs

[Sibiu-2025] Quick fixes & additions so we can promote registration

---

data/events/2025/sibiu/main.yml

This PR quickly adds the registration page to the nav bar.

[Sibiu-2025] Quick fix registration link

---

data/events/2025/atlanta/main.yml

Adding circleCI and peoplecert as gold, upgrading honeycomb to platinum

[ATL-2025] Adding and upgrading gold sponsors

---

content/events/2025-london/welcome.md

Added two links to the welcome page for London 2025

[LDN-2025] Add links to welcome page

---

content/events/2025-philadelphia/sponsor.md

[PHL-205] Update sponsor page for 2025

---

content/events/2025-philadelphia/sponsor.md

[PHL-2025] Link for sponsor prospectus

[PHL-2025] Link for sponsor prospectus

---

data/events/2025/aarhus/main.yml

[AARHUS-2025] Switch speakerslots

---

content/events/2025-atlanta/location.md
data/events/2025/atlanta/main.yml

Add information about the after party

[ATL-2025] After party information

---

content/events/2025-atlanta/program/nathen-harvey-ignite.md
data/events/2025/atlanta/main.yml

Adding a page for the slides
Preview URLs:
* https://deploy-preview-15139--devopsdays-web.netlify.app/events/2025-atlanta/speakers/nathen-harvey/
* https://deploy-preview-15139--devopsdays-web.netlify.app/events/2025-atlanta/program/nathen-harvey-ignite/
cc: @ecology-chris

[ATL-2025] Nathen gave an impromptu ignite.

---

content/events/2025-aarhus/welcome.md
data/events/2025/aarhus/main.yml

Post conference updates
* Drop registration link
* Simplify the welcome page and link to our LinkedIn group

[AARHUS-2025] Update the website now that the conference is done.

---

content/events/2025-denver/welcome.md
data/events/2025/denver/main.yml

- adds fairwinds sponsor to denver 2025

[DEN-2025] init fairwinds sponsors for Denver 2025

---

data/events/2025/prague/main.yml

Add czechitas as community sponsor

[PRG-2025] Add czechitas as community sponsor

---

content/events/2025-belem/regulamento-pcd.md
content/events/2025-belem/speakers.md
content/events/2025-belem/welcome.md
data/events/2025/belem/main.yml

[BEL-2025] Update Keynotes

---

content/events/2025-baltimore/sponsor.md
data/events/2025/baltimore/main.yml

* Added 1 sponsor
* Fixed a typo
* Removed untimely sponsorship options

[BMORE-2025] Add sponsor, remove untimely sponsorship options, fix typo

---

content/events/2025-campinas/welcome.md
data/events/2025/campinas/main.yml

Added date and location of event.

[CPS-2025] Add event date and location

---

content/events/2025-rio-de-janeiro/sponsor.md
data/events/2025/rio-de-janeiro/main.yml

[RIO-2025]Sponsors Page

---

content/events/2025-cairo/welcome.md
data/events/2025/cairo/main.yml

Updating date and welcome page

[CAI-25] Updating date and welcome page

---

content/events/2025-cairo/welcome.md
data/events/2025/cairo/main.yml

Updating CFP end, and sponsors

[CAI-25] Updating CFP end, and sponsors

---

content/events/2025-rio-de-janeiro/sponsor.md

[RIO-2025] Fix Sponsor value

---

data/events/2025/kansas-city/main.yml

Add Progress Chef + RedHat as sponsors

[KC-2025] add Progress Chef + Redhat

---

data/events/2025/denver/main.yml

- adds Robby B as an organizer to Denver. Email has already been sent to add him to the distro.

[DEN-2025] init new organizer

---

content/events/2025-sao-paulo/propose.md
content/events/2025-sao-paulo/welcome.md
data/events/2025/sao-paulo/main.yml

Just changing the open cfp date in the welcome page.

[SP 2025] Change the open cfp date

---

content/events/2025-geneva/speakers/aditya-manglik.md

[GE-2025] Update speaker bio

---

data/events/2025/philadelphia/main.yml

Remove arresteddevops and add Kube events

[PHL-2025] Remove/Add Sponsors

---

data/events/2025/amsterdam/main.yml

Adding Komodor as Gold level sponsor for Amsterdam 2025 🎉

[AMS-2025] Add Komodor Gold sponsor

---

data/events/2025/washington-dc/main.yml

Fixed the dates for CFP of Washington DC 2025

[DC-2025] fix dates for CFP Washington DC

---

content/events/2025-philadelphia/sponsor.md

Added info on sponsor application deadline, and refund request policy.

[PHILA-2025]: Added sponsor deadline and refund info

---

data/events/2025/feira-de-santana/main.yml

[FSA-2025]: Change program

---

data/events/2025/warsaw/main.yml

Updated the CFP date end to the new arranged deadline.

warsaw-2025 - updated CFP date to the new deadline

---

data/events/2025/des-moines/main.yml

Des Moines 2025 adding Lean Techniques as a gold sponsor

DSM-2025 Add Lean Techniques Gold Sponsor

---

content/events/2025-baltimore/speakers.md
content/events/2025-baltimore/welcome.md
data/events/2025/baltimore/main.yml

- **[bmore-2025] Fix speakers page**
- **[bmore-2025] Fix speaker js, update welcome page post-event**

[bmore-2025] Fix speaker js, update welcome page post-event

---

data/events/2025/campinas/main.yml

Add my bio information dor DoD Campinas.

[CAMPINAS-2025] Add Amaury Borges Souza bio information

---

content/events/2024-austin/speakers.md
content/events/2024-kansas-city/speakers.md
content/events/2025-austin/speakers.md
content/events/2025-baltimore/speakers.md

- Fix the speaker wall calls for Austin 2024, Austin 2025, and Kansas City 2024.
- Patch the no-script link for Baltimore 2025 as well.
cc @jerdog @bushong1

[Meta] Fix speaker wall API calls for Pretalx

---

themes/devopsdays-theme/layouts/shortcodes/tix.html

- Pretix has a new widget that next month will be replaced per https://pretix.eu/about/en/blog/20250530-release-2025-5-0/, this updates the core code to point to v2.

increment widget from v1 to v2

---

content/events/2025-brasilia/welcome.md
data/events/2025/brasilia/main.yml

[BSB-2025] Open CFP

---

content/events/2025-brasilia/sponsor.md

[BSB-2025] changes sponsors value

---

content/events/2025-tel-aviv/welcome.md
data/events/2025/tel-aviv/main.yml

* I have added the keynote speaker to our welcome page
* I have added a new sponsor ESL-Cloudbees

[TLV-2025] Keynote Announce + New Sponsor

---

content/events/2025-montreal/sponsor.md
utilities/add_speakers.sh

sponsors layers added
Link to asset's PR: https://github.com/devopsdays/devopsdays-assets/pull/249

[MTL-2025] Add sponsors price layers

---

content/events/2025-vilnius/program.md
content/events/2025-vilnius/speakers.md
data/events/2025/vilnius/main.yml

- add pretalx widgets for program and speakers

[VILNIUS-2025] add program

---

data/events/2025/amsterdam/main.yml

Adds Progress Chef as Coffee level sponsor. We should be done now with sponsors ;)

[AMS-2025] Add Progress Chef as coffee sponsor

---

content/events/2025-halifax/program.md
content/events/2025-halifax/welcome.md
data/events/2025/halifax/main.yml

Add schedule and tickets pages.

[HALIFAX-2025] Add schedule and tickets pages.

---

data/events/2025/des-moines/main.yml

2025 Des Moines Adding Principal as a Gold Sponsor

2025 - DSM Added Principal as a Gold Sponsor

---

data/sponsors/general-engineering--management-solutions.yml

Remove errant string from sponsor name

[site] fix error in GEMS sponsor profile

---

data/events/2025/rio-de-janeiro/main.yml

[RIO-2025]Add New Sponsor

---

data/events/2025/philadelphia/main.yml

Updated sponsor levels to match prospectus

[PHI-2025] Updated sponsor levels

---

content/events/2025-detroit/contact.md
content/events/2025-detroit/location.md
content/events/2025-detroit/propose.md
content/events/2025-detroit/registration.md
content/events/2025-detroit/sponsor.md
content/events/2025-detroit/welcome.md
data/events/2025/detroit/main.yml

Detroit 2025 - Canceling event.

[Detroit-2025] - Canceling

---

content/events/2025-des-moines/sponsor.md
data/events/2025/des-moines/main.yml

DSM-2025 Add a lanyard sponsor level

DSM-2025 Add a lanyard sponsor level

---

content/events/2025-florianopolis/conduct-pt-br.md
content/events/2025-florianopolis/contact.md
content/events/2025-florianopolis/location.md
content/events/2025-florianopolis/propose.md
content/events/2025-florianopolis/welcome.md
data/events/2025/florianopolis/main.yml

* Include event location 
* Fix patterns name

[FLN-2025] Add event location

---

content/events/2023-juiz-de-fora/welcome.md

[jf-2023] Social Media Icons Correction

---

content/events/2025-des-moines/schedule.md
data/events/2025/des-moines/main.yml

[DSM-2025] Release Schedule

---

content/events/2025-campinas/welcome.md
data/events/2025/campinas/main.yml

[CPS-2025] Open call for papers

---

data/events/2025/campinas/main.yml

[CPS-2025] Add Bosch as sponsor

---

content/events/2025-montreal/welcome.md
data/events/2025/montreal/main.yml

We have confirmed the Polytechnique Montreal and the dates (October 14th and 15th)

[MTL-2025] Dates and location confirmed

---

content/events/2025-vilnius/sponsor.md
data/events/2025/vilnius/main.yml

- add sponsor
- adjust sponsorship slots
- remove propose link

[VILNIUS-2025] Add sponsor

---

data/events/2025/denver/main.yml

- adds fluidattacks to silver sponsors for denver

[DEN-2025] init fluid attacks as silver sponsor

---

content/events/2025-halifax/location.md

Update location details for DevOpsDays Halifax 2025.

[HALIFAX-2025] Update location details.

---

content/events/2025-montreal/welcome.md
data/events/2025/montreal/main.yml

Added registration dates and link to eventbrite

[MTL-2025] Registration open

---

data/events/2025/philadelphia/main.yml

[PHL-25] Add registration dates

[PHL-25] Add registration dates

---

content/events/2025-dallas/program/vasu-andolu.md
data/events/2025/dallas/main.yml

update vasu talk title
add Dynatrace as Platinum sponsor

[DFW-2025]  update vasu talk title + dynatrace platinum sponsor

---

content/events/2025-halifax/convince-your-boss.md
content/events/2025-halifax/welcome.md

This PR addd a 'Convince Your Boss' letter for DevOpsDays Halifax 2025.

[HALIFAX-2025] Add 'Convince Your Boss' letter.

---

data/events/2025/des-moines/main.yml

DSM-2025 Add Sponsor - Side Garage

DSM-2025 Add Side Garage as Sponsor

---

data/events/2025/washington-dc/main.yml

Modify the main.yml file to add Elastic and Gruntwork as platinum sponsors.

[DC-2025] Add Elastic and Gruntwork as sponsors

---

content/events/2025-florianopolis/welcome.md
data/events/2025/florianopolis/main.yml

[FLN-2025] Add link to CFP

---

data/events/2025/rio-de-janeiro/main.yml

- Pedro Kaneto
- Alberico Filho

[RIO-2025] Update Program

---

data/events/2025/denver/main.yml

- adds dryrun security to denver 2025 silver sponsors

[DEN-2025] add dryrunsec to denver sponsors

---

content/events/2025-cairo/sponsor.md

[CAI-25] Update sponsorship deadline

---

content/events/2025-kansas-city/welcome.md
data/events/2025/kansas-city/main.yml

[kc-2025] End of Conference edits

---

content/events/2025-montreal/welcome.md

Removed the propose button in the welcome screen

[MTL-2025] CFP now closed

---

content/events/2025-london/program.md
data/events/2025/london/main.yml

This adds a new sponsor (Syntasso) along with including a fix for the program key to display correctly from previous years.

[LDN-2025] Update Sponsors and fix Program key layout

---

content/events/2025-denver/location.md

Update the parking details for 2025 Denver.

[DEN-2025] Update parking details.

---

data/events/2025/washington-dc/main.yml

* Add Grafana as a platinum sponsor for DC 2025 event

[DC-2025] Add Grafana Sponsor

---

data/events/2025/vilnius/main.yml

- Added link as embedding is not ideal

[VLN-2025] Change link to pretalx schedule

---

data/events/2025/dallas/main.yml

[DFW-2025] Add gold sponsor peoplecert

---

content/events/2026-los-angeles/volunteer.md

**Summary of changes**:
- Updating the volunteer's page
**Tested**:

[LA-2026] Updating volunteer page
