content/events/2018-columbus/welcome.md
Simple copy added for scholarship information next to registration link.
=> [Columbus-2018] Adding scholarship copy

data/events/2018-tel-aviv.yml
=> [TLV-2018] Appsflyer sponsor

data/events/2018-boston.yml
=> [BOS-2018]Swapped everbridge to platinum

content/events/2018-minneapolis/program/aditya-mukerjee.md, content/events/2018-minneapolis/program/amy-chen.md, content/events/2018-minneapolis/program/amy-patton.md, content/events/2018-minneapolis/program/lanice-sims.md, content/events/2018-minneapolis/program/ronnie-chen.md, content/events/2018-minneapolis/program/sharon-kennedy-vickers.md
Adding some of the slides and videos.
=> [MSP 2018] Adding some slides and videos

content/events/2018-minneapolis/program/ian-coldwater.md
=> [MSP 2018] Adding Ian's talk slides

content/events/2018-santa-maria/program/cristiano-diedrich.md, data/events/2018-santa-maria.yml
Updating description of a talk  and updating sponsor.
=> [SM-2018] Update Speaker and Sponsor

data/events/2018-hartford.yml
=> [HFD-2018] add compuware as bronze/mug sponsor for hfd

content/events/2018-minneapolis/program/tim-gross.md
Adding Tim's slides (and we don't support this kind of embed).
=> [MSP 2018] Adding Tim's slides

data/events/2018-riga.yml
Adding Alexander Yartsev as organiser for DOD Riga 2018
=> [RIGA-2018] Adding Alexander as organiser for DOD Riga

content/events/2018-london/program/matt-turner.md
I was wrong, Matt Turner's talk is actually Bash is Testing. He
submitted around 4 talks, I just put the incorrect one, then after
discussion in slack changed it, then changed it back. My mistake
=> [LDN-2018] Matt Turner back to Bash is Testing

data/events/2018-raleigh.yml
[RDU-2018] add mesosphere sponsor
=> [RDU-2018] add mesosphere sponsor

content/events/2018-boston/program/angel-rivera.md, content/events/2018-boston/program/garima-sharma.md, content/events/2018-boston/program/mike-rothman.md, content/events/2018-boston/program/tim-hartmann.md, content/events/2018-boston/speakers/angel-rivera.md, content/events/2018-boston/speakers/garima-sharma.md, content/events/2018-boston/speakers/mike-rothman.md, content/events/2018-boston/speakers/tim-hartmann.md, data/events/2018-boston.yml
=> [BOS-2018] added workshops for track 3

content/events/2018-london/program/andrew-bean.md, content/events/2018-london/speakers/andrew-bean.md
Minor requests from speaker to update talk information and bio
information.
=> [LDN-2018] Update Andrew Bean Speaker Page

data/events/2018-berlin.yml
Berlin 2018: Add my details as organizer.
=> [Berlin 2018] Add my organizer details

content/events/2018-boston/program/quintessence-anx.md, content/events/2018-boston/speakers/mike-rothman.md, content/events/2018-boston/speakers/quintessence-anx.md
=> [BOS-2018] fix a typo, and turns out an approved bio wasn't

content/events/2018-riga/program/anton-babenko-ignite-1.md, content/events/2018-riga/program/anton-babenko-talk-1.md, content/events/2018-riga/program/anton-babenko-workshop-1.md, content/events/2018-riga/program/antonio-pigna-workshop-1.md, content/events/2018-riga/program/philipp-krenn-workshop-1.md, content/events/2018-riga/program/scott-feinberg-workshop-1.md, data/events/2018-riga.yml
Workshops added and some schedule refinement
=> [Riga-2018] Workshops added

content/events/2018-galway/location.md, content/events/2018-galway/propose.md, data/events/2018-galway.yml
=> [GAL-2018] Galway setup for opening CFP

data/events/2018-raleigh.yml
[RDU-2018] added forty8fifty sponsor
=> [RDU-2018] added forty8fifty sponsor

data/events/2018-portland.yml
=> [PDX-2018] Added sponsors Puppet and OverOps

content/events/2018-galway/sponsor.md
=> [GAL-2018] Added sponsorship packages description to Galway 2018 page.

.travis.yml, CONTRIBUTING.md, netlify.toml
This updates the build to use hugo 0.46
=> Upgrade to hugo 0.46

content/events/2019-zurich/welcome.md
Forgot to enable logo on welcome page
=> [ZRH-2019] Enable logo display on welcome page

content/events/2018-minneapolis/welcome.md, data/events/2018-minneapolis.yml
Rephrasing a few places to indicate the event is past.
=> [MSP 2018] 2018 MSP to past

content/events/2018-boston/speakers/yulan-lin.md, data/events/2018-boston.yml
=> [BOS-2018] added 5 new sponsors and correct speaker name

content/events/2018-minneapolis/program/amy-chen.md
Slight correction to talk title
=> [MSP 2018] Talk title correction

content/events/2019-amsterdam/conduct.md, content/events/2019-amsterdam/contact.md, content/events/2019-amsterdam/location.md, content/events/2019-amsterdam/propose.md, content/events/2019-amsterdam/registration.md, content/events/2019-amsterdam/sponsor.md, content/events/2019-amsterdam/welcome.md, data/events/2019-amsterdam.yml
Hello everyone,
We'll be hosting yet another devopsdays in Amsterdam. 🎉
=> [AMS-2019] Initialize site for 2019

data/events/2018-montreal.yml
=> [MTL-2018] Added CGI as lunch sponsor

data/events/2018-raleigh.yml
[RDU-2018] Added netapp and sysdig as sponsors
=> [RDU-2018] Added netapp and sysdig as sponsors

data/events/2018-columbus.yml
Adding Morpheus and Chef as gold sponsors.
=> [Columbus 2018] Adding two gold sponsors.

content/events/2018-fortaleza/program/marcelo-bill.md, content/events/2018-fortaleza/speakers/marcelo-bill.md
=> [Fortaleza-2018] Removing Speaker

content/events/2018-singapore/sponsor.md
=> [SIN-18] Update Sponsorship details

content/events/2018-boston/program/austen-novis.md, content/events/2018-boston/program/flynn.md, content/events/2018-boston/program/garima-sharma.md, content/events/2018-boston/program/heidi-waterhouse.md, content/events/2018-boston/program/james-meickle.md, content/events/2018-boston/program/leena-s-n.md, content/events/2018-boston/program/matty-stratton.md, content/events/2018-boston/program/mike-rothman.md, content/events/2018-boston/program/oleg-chunikhin.md, content/events/2018-boston/program/paul-bruce.md, content/events/2018-boston/program/sarah-zelechoski.md, content/events/2018-boston/program/timothy-bonci.md, content/events/2018-boston/program/yegor-bugayenko.md
=> [BOS-2018] added day 2 abstracts

content/events/2018-raleigh/welcome.md
Registration only needed for capacity planning. No other data collection required.
=> [RDU-2018] Updated Happy Hour language.

data/events/2018-galway.yml
Add some more organizer bios and fix some minor typos
=> [GAL-2018] Add more organizer bios

content/events/2018-raleigh/welcome.md
[RDU-2018] Modified position of happy hour rsvp
=> [RDU-2018] Modified position of happy hour rsvp

content/events/2018-london/speakers/velvet-spors.md
Update Velvet Spors talk description
=> [LDN-2018] Update Velvet Talk Description

data/events/2018-salvador.yml
=> [SSA-2018] - Remove Ana from organization

data/events/2018-kansas-city.yml
=> [KC-2018] - Temporarily remove cerner as sponsor

content/events/2018-salvador/propose.md, data/events/2018-salvador.yml
=> [SSA-2018] Add propose menu item

data/events/2018-portland.yml
=> [PDX-2018] Added sponsor Nutanix

data/events/2018-raleigh.yml
[RDU-2018] Added Signal Science as sponsor
=> [RDU-2018] Added Signal Science as sponsor

data/events/2018-raleigh.yml
[RDU-2018] add dynatrace as sponsor
=> [RDU-2018] add dynatrace as sponsor

content/events/2018-chicago/program/emily-freeman.md
=> [CHI-2018] Update Emily Freeman ignite

data/events/2018-raleigh.yml
[RDU-2018] added puppet as sponsor
=> [RDU-2018] added puppet as sponsor

data/events/2018-detroit.yml
[DET-2018] Adding gold sponsor
=> [DET-2018] Adding gold sponsor

content/events/2018-porto-alegre/speakers/julia-lamenza.md
=> [POA-2018] Update Julia Lamenza bio

content/events/2018-chattanooga/registration.md, content/events/2018-chattanooga/sponsor.md, content/events/2018-chattanooga/welcome.md
Reverts devopsdays/devopsdays-web#5125
=> Revert "[CHA-2018] Adding registration link, specifying image dimensions"

content/events/2018-chattanooga/registration.md, content/events/2018-chattanooga/sponsor.md, content/events/2018-chattanooga/welcome.md
Fixes broken HTML from #5125 and un-reverts #5129.
cc @mattstratton @robscott @MikeRosTX
=> [CHA-2018] Adding registration link, specifying image dimensions

data/events/2019-johannesburg.yml
Added an additional organiser.
=> [JHB-2019] Added additional organiser

content/events/2018-london/program/jamie-tanna.md
Updating Jamie Tanna's talk description.
=> [LDN-2018] Update Jamie Tanna's talk description

data/events/2018-boston.yml
will email in adam's email address for slack and email
=> [BOS-2018] added two new sponsors and organizer

content/events/2018-dallas/program/karith-foster.md, content/events/2018-dallas/speakers/karith-foster.md
=> [DFW-2018] Minor speaker changes

content/events/2018-kansas-city/program/naresh-rayapati.md, content/events/2018-kansas-city/program/nick-coblentz.md
update two abstracts for Kansas City 2018.
=> [KC-2018] update two abstracts

content/events/2018-raleigh/location.md, content/events/2018-raleigh/welcome.md
Hi, @normalfaults - there are a couple places in the welcome template that aren't driven by the yaml. I've fixed these broken links for you, and made your location map show up correctly.
=> [Raleigh 2018] Fixing links for Raleigh

data/events/2018-taipei.yml
Hi, @thebrecht - I'm adding a link to the local site.
=> [Taipei 2018] Adding link to local site

content/events/2018-cairo/welcome.md, data/events/2018-cairo.yml
Hi @aameen79 - I noticed that your CFP is closed. This updates the website to say that the CFP is closed.
=> [Cairo 2018] CFP closed

content/events/2018-dallas/program/ivan-fan.md
=> [DFW-2018] Request from Ignite Talk Speaker to change talk abstract

content/events/2018-dallas/speakers/pam-dukes.md
=> [DFW-2018] Updating Speaker Bio as requested

content/events/2018-dallas/program/ivan-fan.md, content/events/2018-dallas/speakers/pam-dukes.md
=> [DFW-2018] Minor change request to bio by Speaker

data/events/2018-fortaleza.yml
=> [Fortaleza-2018] Add new sponsor

data/events/2018-chicago.yml
add GitHub as Silver sponsor
add CA as evening event sponsor
add Hashicorp as Lunch sponsor
=> [CHI-2018] add sponsors

content/events/2018-dallas/registration.md
=> [DFW-2018] Update Registration to add Waitlist

data/events/2018-cape-town.yml
Also removed the commented out example, as we know the structure of that yaml.
=> [Cape Town 2018] Add LPI as community sponsor

data/events/2018-fortaleza.yml
=> [2018-fortaleza] Add sponsor 4devops

data/events/2018-dallas.yml
=> [DFW-2018] Schedule Update

content/events/2018-portland/program/jennifer-davis.md, content/events/2018-portland/program/tbd.md, content/events/2018-portland/speakers/jennifer-davis.md, content/events/2018-portland/speakers/tbd.md, data/events/2018-portland.yml
=> [PDX-2018] Update the schedule - includes tbd speaker placeholder while we some confirm details.

content/events/2018-fortaleza/program/gabriela-dias.md, content/events/2018-fortaleza/speakers/gabriela-dias.md
Update speaker info and add talk title
=> 2018-fortaleza Update speaker info and add talk title

data/events/2018-chicago.yml
Update evening event details on program page
=> [CHI-2018] Add evening event details

data/events/2018-dallas.yml
=> [DFW-2018] Another update to organizer bio

content/events/2018-dallas/program/david-giambruno.md, data/events/2018-dallas.yml
=> [DFW-2018] Updating Keynote Title

README.md
This seems more clear to me, but I'm not 100% sure if it really is.
=> Attempt to make it clearer where the reference documentation lives

content/events/2018-fortaleza/speakers/camilla-martins.md
=> 2018 - Update camilla-martins.md

content/events/2018-dallas/program.md
=> [DFW-2018] Updating Slack registration link

content/events/2018-cape-town/program.md, content/events/2018-cape-town/welcome.md, data/events/2018-cape-town.yml
This isn't complete, we're waiting on confirmation from a few more
speakers. But it's ready to merge.
Thanks core devops person for the merge!
=> [Cape Town 2018] Add the program for Cape Town 2018

content/events/2018-dallas/program/mohamad-bayan.md
=> [DFW-2018] Updating talk title

content/events/2018-dallas/program/ragu-srinivasan.md
=> [DFW-2018] Talk title update

content/events/2018-columbus/leadershipsummit.md, data/events/2018-columbus.yml
This is a simple page with basic information for the Columbus Leadership Summit prior to the conference. May or may not receive some future updates as I get better instruction as to what to put on it.
=> Columbus 2018: Leadership summit

data/events/2018-columbus.yml
Simply adding google as a sponsor.
=> [Columbus-2018] Adding google sponsor

data/events/2018-raleigh.yml
[RDU-2018] added overops to gold
=> [RDU-2018] added overops to gold

data/events/2018-tel-aviv.yml
[TLV-2018] Microsoft as sponsor
=> [TLV-2018] Microsoft as sponsor

content/events/2018-fortaleza/program/marcelo-bill.md
=> 2018-fortaleza Update marcelo-bill.md

content/events/2018-london/program/denise-yu.md
Denise requested changed to her talk to make it much more accessible for
people who don't work on distributed systems all day.
=> [LDN-2018] Altering talk on request.

content/events/2018-philadelphia/program.md, content/events/2018-philadelphia/program/ryn-daniels.md, content/events/2018-philadelphia/speakers.md, content/events/2018-philadelphia/speakers/ryn-daniels.md, data/events/2018-philadelphia.yml
=> [Philly 2018] add keynote & program

content/events/2018-fortaleza/program/daniel-romero.md
Add talk title and description
=> 2018-fortaleza - Create daniel-romero.md

gulp/tasks/build.js, gulp/tasks/copy-static-files.js, gulp/tasks/default.js, gulp/tasks/development/bower.js, gulp/tasks/development/build-dev.js, gulp/tasks/development/javascript.js, gulp/tasks/development/local-imagemin.js, gulp/tasks/development/sass.js, gulp/tasks/development/watch.js, gulp/tasks/preprod.js, gulp/tasks/process-html.js, gulp/tasks/responsive-images.js, package.json
This should resolve some vulnerabilities in the gulp tasks, and maybe speed up the build?
=> Update gulp and npm packages

content/events/2018-chicago/program/donovan-brown.md, content/events/2018-chicago/program/quintessence-anx.md, content/events/2018-chicago/program/sonia-gupta.md, content/events/2018-chicago/program/tiffany-longworth.md
=> [CHI-2018] Add speaker slides

content/events/2018-cairo/location.md, content/events/2018-cairo/registration.md, data/events/2018-cairo.yml
Update location and open registration, and putting agenda, will make it better looking later :)
=> [CAI-2018] Update location and open registration

data/events/2018-galway.yml
Extend CFP for Galway by a week.
=> [GAL-2018] Extend CFP for Galway

content/events/2018-bengaluru/welcome.md, data/events/2011-bangalore.yml, data/events/2013-india.yml, data/events/2014-bangalore.yml, data/events/2015-bangalore.yml, data/events/2016-bangalore.yml, data/events/2017-bangalore.yml, data/events/2018-bengaluru.yml
- Linking past events
- Linking Twitter handle
- Linking proposal page
- Linking contact page
- Linking registration page
=> [Bengaluru 2018] Adding missing details

data/events/2018-columbus.yml, data/events/2018-kazan.yml, data/events/2018-montreal.yml, data/events/2018-riga.yml
- Removing "propose" links if the CFP is closed
- Linking to local site
=> Correcting links

utilities/examples/templates/program.md
This can be merged at any time, as the frontmatter in the template is backwards-compatible. However, since we aren't sure what the field will be named, let's hold off until the PR listed below is merged.
Ref: https://github.com/devopsdays/devopsdays-theme/pull/605
=> Update new program script with new frontmatter

data/events/2018-galway.yml
=> [GAL-2018] Add Cisco as sponsor

content/events/2017-chicago/program.md
=> Enable icons on 2017 Chicago program page

content/events/2017-cape-town/program.md
Got to get in on those awesome icons!
=> [Cape Town 2017] Turn on the icons for the schedule

content/events/2018-portland/program/aaron-aldrich-ignite.md, content/events/2018-portland/program/aaron-aldrich.md, data/events/2018-portland.yml
=> [2018-PDX] Separated Aaron's talk from the ignite

content/events/2018-portland/program/jennifer-davis.md, content/events/2018-portland/speakers/jennifer-davis.md
=> [2018-PDX] Update Jennifer's talk/bio deets

content/events/2018-philadelphia/program/nicholas-canzoneri.md, data/events/2018-philadelphia.yml
On the tin. Since this is adding a new organizer I will also be sending an email to info@devopsdays.org.
=> [PHILLY-2018] Update speaker and organizer.

data/events/2018-detroit.yml
[DET-2018] Adding rightbrain as a gold sponsor
=> [DET-2018] Adding rightbrain as a gold sponsor

content/events/2018-chicago/program/lilia-gutnik.md
=> [CHI-2018] Add Lilia slides

content/events/2018-cairo/cairo.md, content/events/2018-cairo/program.md, content/events/2018-cairo/program/ahmed-abdelaziz.md, content/events/2018-cairo/program/ahmed-bahaa.md, content/events/2018-cairo/program/ahmed-dahab.md, content/events/2018-cairo/program/andrew-shafer.md, content/events/2018-cairo/program/marcin-wielgus.md, content/events/2018-cairo/program/mina-fahmy.md, content/events/2018-cairo/program/mohamed-adawi.md, content/events/2018-cairo/program/mohamed-fawzy.md, content/events/2018-cairo/program/mohamed-galal.md, content/events/2018-cairo/program/reham-saleh.md, content/events/2018-cairo/program/roman-pickl.md, content/events/2018-cairo/speakers.md, content/events/2018-cairo/speakers/ahmed-abdelaziz.md, content/events/2018-cairo/speakers/ahmed-bahaa.md, content/events/2018-cairo/speakers/ahmed-dahab.md, content/events/2018-cairo/speakers/andrew-shafer.md, content/events/2018-cairo/speakers/marcin-wielgus.md, content/events/2018-cairo/speakers/mina-fahmy.md, content/events/2018-cairo/speakers/mohamed-adawi.md, content/events/2018-cairo/speakers/mohamed-fawzy.md, content/events/2018-cairo/speakers/mohamed-galal.md, content/events/2018-cairo/speakers/reham-saleh.md, content/events/2018-cairo/speakers/roman-pickl.md, data/events/2018-cairo.yml
This replaces https://github.com/devopsdays/devopsdays-web/pull/5335 with corrections.
=> [Cairo 2018] Cairo program

content/events/2018-galway/registration.md, data/events/2018-galway.yml
Enable registration for early bird tickets and suggestions on accommodation.
=> [GAL-2018] Enable registration page

data/events/2018-columbus.yml
Simply adding 3 additional sponsors.
=> [Columbus-2018] Sponsors: Cardinal, New Relic, and Elastic.

content/events/2018-fortaleza/program/rafael-gomes-aka-gomex.md
Add Talk title and description
=> 2018-fortaleza Update rafael-gomes-aka-gomex.md

data/events/2018-salvador.yml
=> [SSA-2018] Add registration menu item

content/events/2018-cairo/speakers/marcin-wielgus.md, content/events/2018-cairo/speakers/reham-saleh.md
I needed to change the referencing files as well as the extensions.
=> [Cairo 2018] Fixing typo

data/events/2018-montreal.yml
=> [MTL-2018] updating schedule

data/events/2018-philadelphia.yml
[PHL-2018] Adding New Relic as a sponsor
=> [PHL-2018] Adding New Relic as a sponsor

data/events/2009-ghent.yml, data/events/2010-sydney.yml
I noticed the dates weren't right for the first two events.
=> Correcting the dates for the first two events

content/page/events.md
Clarifying that recent videos are in a different place than old ones.
=> Clarifying where videos can be found

content/events/2018-detroit/sponsor.md
[DET-2018] Removing lanyard sponsor section.
=> [DET-2018] Removing lanyard sponsor section

content/events/2018-dallas/program.md
=> [DFW-2018] Adding photo links

content/blog/2017-kansas-city.md
=> [KC-2017][Blog] Recap of KC 2017 event

content/events/2018-phoenix/program/andy-lowe.md, content/events/2018-phoenix/program/carlos-nunez.md, content/events/2018-phoenix/program/chris-van-tuin.md, content/events/2018-phoenix/program/jasmine-hegman.md, content/events/2018-phoenix/program/mark-gunnels.md, content/events/2018-phoenix/program/nick-willever.md, content/events/2018-phoenix/program/rob-richardson-k8s.md, content/events/2018-phoenix/program/rob-richardson.md, content/events/2018-phoenix/program/wes-novack.md, content/events/2018-phoenix/speakers/andy-lowe.md, content/events/2018-phoenix/speakers/carlos-nunez.md, content/events/2018-phoenix/speakers/chris-van-tuin.md, content/events/2018-phoenix/speakers/jasmine-hegman.md, content/events/2018-phoenix/speakers/mark-gunnels.md, content/events/2018-phoenix/speakers/nick-willever.md, content/events/2018-phoenix/speakers/rob-richardson.md, content/events/2018-phoenix/speakers/wes-novack.md
Add speaker and talk details for first wave of accepted speakers.
=> [PHX-2018] Add dodphx 2018 speaker and talk details

data/events/2018-kansas-city.yml
=> [KC-2-18] add new relic as sponsor

content/events/2018-berlin/location.md, data/events/2018-berlin.yml
=> [BER-2018] Add location for evening event

data/events/2018-detroit.yml
[DET-2018] Adding StockX as silver sponsor
=> [DET-2018] Adding stockx as silver sponsor

data/events/2018-portland.yml
=> [2018-PDX] Fix the evening event time (whooops!)

themes/devopsdays-theme/layouts/index.html
attention @mattstratton - do we want to get this out as a hotfix? Testing it on the -web repo.
=> Insta-fix for today not still showing up on site

data/events/2018-cape-town.yml
He has a scheduling problem on Friday.
Also add Christo to the schedule
=> [Cape Town 2018] Move Mark's talk to Thursday

data/events/2018-boston.yml
=> [BOS-2018] added some alacartes. waiting on one more to finalize

data/events/2018-detroit.yml
[DET-2018] Adding pluralsight as silver sponsor
=> [DET-2018] Adding pluralsight as silver sponsor

content/events/2018-philadelphia/speakers/aaron-aldrich.md, content/events/2018-philadelphia/speakers/mike-rothman.md
=> Fix some speaker issues.

content/events/2019-seattle/welcome.md, data/events/2019-seattle.yml
=> [SEA-2019] adding cfp dates

data/events/2018-boston.yml
=> [BOS-2018] CA sponsored the evening event

content/events/2018-cairo/program/marcin-wielgus.md
=> [CAI] Update Marcin talk description

content/events/2018-london/accessibility.md, content/events/2018-london/welcome.md, data/events/2018-london.yml
Adds accessibility page to London 2018 pages
=> [LDN-2018] London 2018 accessibility information

data/events/2018-london.yml
minor programme change to add evening event to running order
=> [LDN-2018] added evening event to programme

content/events/2018-dallas/program/ignite-talks.md
=> [DFW-2018] Fixing broken urls

content/events/2018-dallas/program/ignite-talks.md
=> [DFW-2018] Fixing another broken link

data/events/2018-philadelphia.yml
[PHL-2018] Adding Chef as a sponsor
=> [PHL-2018] Adding Chef as a sponsor

data/events/2018-columbus.yml
=> [Columbus-2018]: Bio for JD

content/events/2018-detroit/sponsor.md
=> [Detroit 2018] Remove Platinum Sponsor

data/events/2018-kansas-city.yml
=> [KC-2018] - Add justification / convince your manager link

data/events/2018-kansas-city.yml
=> [KC-2018] - Add kaizenOps

content/events/2018-columbus/program/jim-shingler.md, data/events/2018-columbus.yml
Just adding an abstract and updating "after party" to "Happy Hour"
=> Columbus 2018: Last Second Updates: Abstract and Happy Hour

content/events/2019-cairo/welcome.md, data/events/2019-cairo.yml
=> [CAI-2019] Update dates

content/events/2019-salt-lake-city/conduct.md, content/events/2019-salt-lake-city/contact.md, content/events/2019-salt-lake-city/location.md, content/events/2019-salt-lake-city/propose.md, content/events/2019-salt-lake-city/registration.md, content/events/2019-salt-lake-city/sponsor.md, content/events/2019-salt-lake-city/welcome.md, data/events/2019-salt-lake-city.yml
We are submitting our official date for 2019!
=> [SLC 2019] - Initial Commit for 2019

data/events/2010-brazil.yml, data/events/2018-sao-paulo.yml
Adding an event group for São Paulo (as the first year filename's not that).
=> Adding event group for SP

content/events/2018-sao-paulo/conduta.md
Noticed this typo in the 2018 SP event.
=> [SP 2018] Fixing typo

content/events/2018-boston/speakers/jane-prusakova.md, data/events/2018-boston.yml
=> [BOS-2018] update bio for janep

content/events/2018-boston/program/garima-sharma.md, data/events/2018-boston.yml
=> [BOS-2018] update description of evening event

content/events/2018-minneapolis/program/ronnie-chen.md
=> [MSP 2018] Adding Ronnie Chen's slides

content/events/2018-panama/sponsor.md
I noticed a broken tag in the travis output: https://travis-ci.org/devopsdays/devopsdays-web/builds/432481222?utm_source=github_status&utm_medium=notification
=> [Panama 2018] Fixing broken tag

data/events/2018-boston.yml
=> [BOS-2018] last minute

content/events/2018-philadelphia/program/incident-response.md, data/events/2018-philadelphia.yml
=> [PHILLY-2018] Workshop change.

content/events/2018-porto-alegre/program/elias-nogueira.md, content/events/2018-porto-alegre/program/fernando-ike.md, content/events/2018-porto-alegre/program/fernando-silva.md, content/events/2018-porto-alegre/program/jairo-junior.md, content/events/2018-porto-alegre/program/julia-lamenza.md, content/events/2018-porto-alegre/program/kelvin-ronny.md, content/events/2018-porto-alegre/program/marco-junior.md, content/events/2018-porto-alegre/program/natalia-raythz.md, content/events/2018-porto-alegre/program/rodrigo-hurtado.md, content/events/2018-porto-alegre/program/wellington-silva.md
=>  [POA-2018] Add links to slides of most talks

content/events/2018-kansas-city/program.md, data/events/2018-kansas-city.yml
=> [KC-2018] add a legend to the program and bump new relic

data/events/2018-singapore.yml
[SIN-2018] added f5 as silver sponsor
=> [SIN-2018] added f5 as silver sponsor

content/events/2018-fortaleza/speakers/yuri-adams.md
=> 2018-fortaleza - correction on company name

content/events/2018-belem/patrocinio.md, data/events/2018-belem.yml
=> [Belem-2018] update organization email and fix html

content/events/2018-montreal/speakers/adam-hooper.md
=> [mtl-2018] speaker info update

data/events/2018-galway.yml
Informing proposers is behind schedule, so update to let anyone checking
know that it'll be a few more days.
Reached out to most, but yet inform all.
=> [GAL-2018] Correct date of informing proposers due to delays

content/events/2018-galway/contact.md, data/events/2018-galway.yml
=> [GAL-2018] Update organizers

content/events/2019-seattle/welcome.md
=> [SEA-2019] fixed cfp dates

content/events/2018-london/welcome.md, data/events/2018-london.yml
Add link to recordings, remove the registration page and sign the
welcome page off.
Signed-off-by: Chris M <millscj01@gmail.com>
=> [LDN-2018] Close the event

content/events/2018-edinburgh/program/gal-bashan.md, content/events/2018-edinburgh/speakers/gal-bashan.md
=> [EDI-2018] I got the bio and talk round the wrong way for Gal.

content/events/2018-columbus/welcome.md, data/events/2018-columbus.yml
Removing registration link as well.
=> [Columbus-2018] Adding in videos from conference. 

content/events/2019-seattle/propose.md, data/events/2019-seattle.yml
=> [SEA-2019] opening Seattle CFP

content/events/2018-riga/program/andrew-martin-talk-1.md, content/events/2018-riga/program/andrey-adamovich-talk-1.md, content/events/2018-riga/program/anton-arhipov-talk-1.md, content/events/2018-riga/program/antonio-pigna-talk-1.md, content/events/2018-riga/program/christina-aldan-talk-1.md, content/events/2018-riga/program/jan-de-vries-talk-1.md, content/events/2018-riga/program/joep-piscaer-talk-1.md, content/events/2018-riga/program/jon-hall-talk-1.md, content/events/2018-riga/program/jorge-hidalgo-ignite-1.md, content/events/2018-riga/program/karen-cohen-talk-1.md, content/events/2018-riga/program/ken-mugrage-talk-1.md, content/events/2018-riga/program/matty-stratton-ignite-1.md, content/events/2018-riga/program/matty-stratton-talk-1.md, content/events/2018-riga/program/michiel-rook-talk-1.md, content/events/2018-riga/program/neil-crawford-talk-1.md, content/events/2018-riga/program/philipp-krenn-ignite-1.md, content/events/2018-riga/program/philipp-krenn-talk-1.md, content/events/2018-riga/program/stas-zvinyatskovsky-talk-1.md, content/events/2018-riga/program/thiago-de-faria-talk-1.md, data/events/2018-riga.yml
Adding slides and full list of core organisers, who helped with conference organisation and planning.
=> [RIGA-2018] Adding slides and adittional organizers

content/events/2019-nashville/location.md, content/events/2019-nashville/welcome.md, data/events/2019-nashville.yml
=> [bna-2019] Updated venue, dates, and registration details

content/events/2018-cape-town/program/christo-goosen.md, content/events/2018-cape-town/program/joe-nuspl.md, content/events/2018-cape-town/program/mpho-mphego.md
Add a few more slides to some of the speaker's talks.
=> [Cape Town 2018] Add some more slides

content/events/2019-portugal/conduct.md, content/events/2019-portugal/contact.md, content/events/2019-portugal/location.md, content/events/2019-portugal/propose.md, content/events/2019-portugal/registration.md, content/events/2019-portugal/sponsor.md, content/events/2019-portugal/welcome.md, data/events/2019-portugal.yml
=> [PT-2019] First PR of devopsdays portugal 2019 edition

data/events/2019-charlotte.yml
=> [CLT-2019] Update event dates

content/events/2018-montreal/location.md
the venue official page change the address to wrong door.
event start in 2 h.
thanks
=> [mtl-2018] emergency address update of the venue

content/events/2018-kansas-city/program.md
=> [KC-2018] clarify program legend

data/events/2019-amsterdam.yml
Please let me know if we need any additional information to add Sheela to the local AMS org team.
=> [AMS-2019] Add Sheela as local organizer

themes/devopsdays-theme/layouts/partials/welcome.html
Discussed with @mattstratton - hotfixing what I submitted in https://github.com/devopsdays/devopsdays-theme/pull/664 until he has time to release a new theme with it.
=> Hotfix for dates issue

data/events/2018-amsterdam.yml
For the next edition we add a few sponsor options. The prospectus will be available later this month.
=> [AMS-2019] Update the available sponsor packages

data/events/2018-amsterdam.yml, data/events/2019-amsterdam.yml
I changed the 2018 edition instead of the 2019 one.
=> [AMS-2019] Sponsor updates

data/events/2019-zurich.yml
Please wait with merge until we give the final go! Thanks
=> [ZRH-2019] Open CfP

content/events/2019-charlotte/propose.md, content/events/2019-charlotte/registration.md, content/events/2019-charlotte/welcome.md, data/events/2019-charlotte.yml
=> [CLT-2019] Add registration and cfp links

content/events/2018-kansas-city/program/matty-stratton.md, content/events/2018-kansas-city/program/matty-stratton2.md, content/events/2018-kansas-city/speakers/matty-stratton.md
Updates for new talk for Matty Stratton.
=> [KC-2018] Update Matty talk for 2018 Kansas City

content/events/2018-edinburgh/sponsor.md, data/events/2018-edinburgh.yml
=> [EDI-2018] Adding the last gold sponsor.

content/events/2019-minneapolis/registration.md, content/events/2019-minneapolis/welcome.md, data/events/2019-minneapolis.yml
[MSP 2019] Adding MSP 2019 reg
=> [MSP 2019] Adding MSP 2019 reg

data/events/2018-boston.yml
Link to the images taken at the event
=> [BOS-2018] update to show pics from the event

content/events/2018-belem/programa.md, data/events/2018-belem.yml
=> [Belem-2018] Add program and new sponsors

data/events/2018-oslo.yml
=> [oslo-2018] Add IBM as (last) sponsor

content/events/2019-seattle/sponsor.md
=> [SEA-2019] open Seattle sponsorship

data/events/2019-salt-lake-city.yml
Add Heather Walker and Curtis Salisbury as organizers for SLC
=> [SLC-2019] Update Organizers

data/events/2018-edinburgh.yml
=> [EDI-2018] Adding another bronze sponsor.

CONTRIBUTING.md
Clarifying how to prevent a difficult-to-diagnose corner-case failure detailed in https://github.com/devopsdays/devopsdays-theme/issues/652.
=> Clarifying the CRLF situation

content/events/2019-minneapolis/sponsor.md
Adding a link to @DebbieGillespie's sponsor form and correcting the days of the week displayed.
=> Add link to sponsor form and correct days.

data/events/2019-amsterdam.yml
Email to core team has been send.
=> [AMS-2019] Add Sean to local AMS organizers team

data/events/2019-amsterdam.yml
=> [AMS-2019] Fix missing Twitter handles for local organizers

data/events/2019-charlotte.yml
Added influxdata as a gold sponsor.
=> [CLT-2019] add influxdata as sponsor

content/events/2019-seattle/welcome.md
=> [SEA-2019] updated cfp and sponsor links

content/events/2018-chicago/program/donovan-brown.md, content/events/2018-chicago/program/lilia-gutnik.md, content/events/2018-chicago/program/quintessence-anx.md, content/events/2018-chicago/program/tiffany-longworth.md
Add videos for Donovan, Lilia, Quintessence, and Tiffany
=> [CHI-2018] Add some videos to Chicago 2018

data/events/2018-belem.yml
=> [Belem-2018] add new speaker and update program

data/events/2018-galway.yml
Add Chef as gold sponsor for Devopsdays Galway
=> [GAL-2018] Add Chef as gold sponsor

content/events/2018-galway/program/kenzie-woodbridge.md, content/events/2018-galway/program/paul-oconnor.md
Replace incorrect talk added for speaker and remove extraneous quotes.
=> [2018-GAL] Talk corrections

data/events/2018-oslo.yml
=> OSL-18 small adjustments to the program

data/events/2019-new-york-city.yml
=> [NYC-2019] Fix twitter handle typo

data/events/2019-new-york-city.yml
Set numbers to use for sponsorships - based on last year's actuals
=> [NYC-2019] - prep for opening up sponsorships

data/events/2018-tel-aviv.yml
[TLV=2018] add taboola as giveaway sponsor, add appsflyer as happy hour sponsor
=> [TLV=2018] add taboola as giveaway sponsor, add appsflyer as happy hour sponsor

content/events/2018-edinburgh/program/adrian-mouat.md
change abstract for adrian mouat's ignite
=> [EDI-2018] update talk abstract

content/events/2019-new-york-city/sponsor.md
=> [NYC-2019] - add sponsorship price for mixer

content/events/2018-chicago/program/aaron-kalin.md, content/events/2018-chicago/program/andrew-clay-shafer.md, content/events/2018-chicago/program/jeff-smith.md, content/events/2018-chicago/program/joshua-zimmerman.md, content/events/2018-chicago/program/morgan-meredith.md, content/events/2018-chicago/program/paul-czarkowski.md, content/events/2018-chicago/program/sonia-gupta.md
Add videos for
- Aaron Kalin
- Andrew Clay Shafer
- Jeff Smith
- Joshua Zimmerman
- Morgan Meredith
- Paul Czarkowski
- Sonia Gupta
=> [CHI-2018] Add more Chicago videos

content/events/2018-oslo/welcome.md
=> [OSL-2018] livestream for day two

content/events/2019-amsterdam/welcome.md
Fixing dates for Amsterdam 2019 and edition number.
=> [AMS-2019] Fixing AMS 2019 dates and edition number

data/events/2019-new-york-city.yml
=> [NYC-2019] Add InfluxData as sponsor

data/events/2018-galway.yml
=> [GAL-2018] Add Google Developers Group Galway as community sponsor

content/events/2019-nashville/propose.md, content/events/2019-nashville/welcome.md
also, include twitter link on welcome page
=> [BNA-2019] update proposal link on proposal page

content/events/2019-washington-dc/propose.md, content/events/2019-washington-dc/registration.md, content/events/2019-washington-dc/sponsor.md
=> [DC-2019] Fix some typos

data/events/2019-amsterdam.yml
Fixing dates on the banner for AMS 2019
=> [AMS-2019] Fix dates on banner for AMS 2019

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Microsoft Azure as a sponsor

data/events/2019-indianapolis.yml
registration and cfp dates still under discussion, removing for now
=> [INDY-2019] registration and cfp dates still under discussion, removing for now

content/events/2018-rio-de-janeiro/program/vanessa-almeida.md
=> [RJ-2018] talk description update

data/events/2019-new-york-city.yml
=>  [NYC-2019] Add Gitlab as sponsor

content/events/2018-tel-aviv/program.md
[tlv-2018]add fiverr to event program
=> [tlv-2018]add fiverr to event program

data/events/2019-nashville.yml
=> [Nashville 2019] Capitalize the city name

content/events/2019-vancouver/policies.md
I noticed a page with incorrect years. /cc @rmkbow
=> [Vancouver 2019] Updating dates on vancouver site

content/events/2018-edinburgh/postevent.md, data/events/2018-edinburgh.yml
=> [EDI-2018] Add post event links to the slides and videos.

content/events/2019-victoria/conduct.md, content/events/2019-victoria/contact.md, content/events/2019-victoria/location.md, content/events/2019-victoria/propose.md, content/events/2019-victoria/registration.md, content/events/2019-victoria/sponsor.md, content/events/2019-victoria/welcome.md, data/events/2019-victoria.yml
Initial pull request.
location.md, propose.md, registration.md, and sponsor.md added as templates although not used yet.
=> [VIC-2019] initial pull request

data/events/2019-new-york-city.yml
=> [NYC-2019] Add New Relic as a sponsor

data/events/2018-warsaw.yml
Adding navigation link to local site, to make it easier for people to find the Warsaw 2018 program.
/cc @mazek @maciej-lasyk
=> [Warsaw 2018] Adding link to Warsaw local site

content/events/2019-copenhagen/conduct.md, content/events/2019-copenhagen/contact.md, content/events/2019-copenhagen/location.md, content/events/2019-copenhagen/propose.md, content/events/2019-copenhagen/registration.md, content/events/2019-copenhagen/sponsor.md, content/events/2019-copenhagen/welcome.md, data/events/2019-copenhagen.yml
I created the new event for 2019 and added new team members.
=> [CPH-2019] Create new Copenhagen event

data/events/2019-washington-dc.yml
=> [DC-2018] trevor trevor trevor

data/events/2019-washington-dc.yml
=> [DC-2019] Add a bio for Holly Bazemore

data/events/2018-galway.yml
=> [GAL-2018] - update venue for Monday evening event

data/events/2019-washington-dc.yml
Add Greg Elin information to DevOpsDays DC contact page for 2019.
=> [DC-2019] Add Greg Elin info

data/events/2019-salt-lake-city.yml
Just adding a link to papercall
=> [SLC-2019] Add CFP dates and links

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Location & Pagerduty as a sponsor

content/events/2019-zurich/registration.md, data/events/2019-zurich.yml
Registration is now open for Zurich 2019.
=> [ZRH-2019] Open registration

content/events/2019-new-york-city/location.md, content/events/2019-new-york-city/sponsor.md, content/events/2019-new-york-city/welcome.md
=> [NYC-2019] Location details, sponsorship updates

content/events/2018-tel-aviv/program.md, content/events/2018-tel-aviv/program/amir-shevat.md, content/events/2018-tel-aviv/program/debbie-levitt.md
=> [tlv-2018] workshop keynote updates

content/events/2019-ghent/conduct.md, content/events/2019-ghent/contact.md, content/events/2019-ghent/location.md, content/events/2019-ghent/propose.md, content/events/2019-ghent/registration.md, content/events/2019-ghent/sponsor.md, content/events/2019-ghent/welcome.md, data/events/2019-ghent.yml
=> [GHENT-2019] Initial PR 

data/events/2009-ghent.yml, data/events/2014-belgium.yml, data/events/2016-ghent.yml, data/events/2019-ghent.yml
=> Adding Ghent event group

content/events/2018-philadelphia/program/aaron-aldrich.md, content/events/2018-philadelphia/program/alan-koch.md, content/events/2018-philadelphia/program/garima-sharma.md, content/events/2018-philadelphia/program/jason-yee.md, content/events/2018-philadelphia/program/jay-gordon.md, content/events/2018-philadelphia/program/julia-duimovich.md, content/events/2018-philadelphia/program/katy-farmer.md, content/events/2018-philadelphia/program/matt-westgate.md, content/events/2018-philadelphia/program/matty-stratton.md, content/events/2018-philadelphia/program/mauricio-linhares.md, content/events/2018-philadelphia/program/mike-rothman.md, content/events/2018-philadelphia/program/nicholas-canzoneri.md, content/events/2018-philadelphia/program/ryn-daniels.md
=> [PHILLY-2018] Add youtube links.

content/events/2018-florianopolis/welcome.md, data/events/2018-florianopolis.yml
=> [FLN-2018] Fix TYPO

content/events/2019-zurich/sponsor.md, content/events/2019-zurich/welcome.md, data/events/2019-zurich.yml
=> [ZRH-2018] Open sponsorship page

content/events/2019-zurich/sponsor.md
=> [ZRH-2019] Correction sponsoring page urgent

data/events/2019-berlin.yml
=> [BER-2019] Removes Ingmar from organizer list

content/events/2019-vancouver/sponsor.md, data/events/2019-vancouver.yml
- Add CFP details
- ... and turned on / fixed our sponsor page
=> [VAN-2019] Add CFP details

content/events/2019-stockholm/conduct.md, content/events/2019-stockholm/contact.md, content/events/2019-stockholm/location.md, content/events/2019-stockholm/propose.md, content/events/2019-stockholm/registration.md, content/events/2019-stockholm/sponsor.md, content/events/2019-stockholm/welcome.md, data/events/2019-stockholm.yml
I've added the new team members for the Stockholm event in 2019
=> [STH-2019] New stockholm team

data/events/2019-houston.yml
[HOUSTON-2019] Adding contact information for organizers
=> [HOUSTON-2019] Adding contact information for organizers

content/events/2019-vancouver/location.md, content/events/2019-vancouver/welcome.md, data/events/2019-vancouver.yml
Updated and enabled these pages:
- Location page
- Sponsor page
- Add extra CFP link
=> [VAN-2019] Enable other pages

content/events/2019-raleigh/conduct.md, content/events/2019-raleigh/contact.md, content/events/2019-raleigh/location.md, content/events/2019-raleigh/propose.md, content/events/2019-raleigh/registration.md, content/events/2019-raleigh/sponsor.md, content/events/2019-raleigh/welcome.md, data/events/2019-raleigh.yml
[RDU-2019] added new raleigh 2019 event
=> [RDU-2019] added new raleigh 2019 event

content/events/2019-new-york-city/registration.md, content/events/2019-new-york-city/welcome.md, data/events/2019-new-york-city.yml
=> [NYC-2019] Add Sponsor and Registration on Welcome page.

data/events/2019-new-york-city.yml
=> [NYC-2019] Add codefresh as a sponsor

content/events/2018-london/program/alexandra-moore.md, content/events/2018-london/program/andrew-bean.md, content/events/2018-london/program/damon-edwards.md, content/events/2018-london/program/denise-yu.md, content/events/2018-london/program/emma-button.md, content/events/2018-london/program/euan-finlay.md, content/events/2018-london/program/jamie-tanna.md, content/events/2018-london/program/jeff-sussna.md, content/events/2018-london/program/kate-whalen.md, content/events/2018-london/program/louise-paling.md, content/events/2018-london/program/markos-rendell.md, content/events/2018-london/program/matt-turner.md, content/events/2018-london/program/philipp-krenn.md, content/events/2018-london/program/ramez-hanna.md, content/events/2018-london/program/richard-marshall.md, content/events/2018-london/program/tomasz-tarczynski.md
added youtube id's to talks
added sides to ignite talks, slides already pushed and merged todevopsdays-assets.
=> [LON-2018] add videos and slides

data/events/2019-amsterdam.yml
Gerard was wrongly deleted, added him back to the list.
=> [AMS-2019] Re-add Gerard to the local organiser team

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Chef as a sponsor

content/events/2018-belem/program/alessandra-martins.md, content/events/2018-belem/program/artur-tupiassu.md, content/events/2018-belem/program/camilla-martins.md, content/events/2018-belem/program/carlos-souza.md, content/events/2018-belem/program/iago-cavalcante.md, content/events/2018-belem/program/leandro-pantoja.md, content/events/2018-belem/program/lucas-mousinho.md, content/events/2018-belem/program/rafael-gomex.md, content/events/2018-belem/program/thomaz-leite.md, data/events/2018-belem.yml
=> [Belem-2018] add slides

content/events/2019-washington-dc/sponsor.md
=> [DC-2019] Open early sponsorship tickets

content/events/2018-porto-alegre/program/cassio-almeida.md
=> [POA-2018] Add Cassio Almeida talk slides

data/events/2019-chicago.yml
=> [CHI-2019] Add Brian Devlin bio

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Chaossearch as a sponsor

content/events/2019-berlin/registration.md, data/events/2019-berlin.yml
=> [BER-2019] Open registration

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Puppet as a sponsor

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Verizon as a sponsor

data/events/2019-indianapolis.yml
=> [INDY-2019] Open up CFP, registration and slack

content/events/2019-boise/conduct.md, content/events/2019-boise/contact.md, content/events/2019-boise/location.md, content/events/2019-boise/propose.md, content/events/2019-boise/registration.md, content/events/2019-boise/sponsor.md, content/events/2019-boise/welcome.md, data/events/2019-boise.yml
=> DevOpsDays Boise 2019

content/events/2019-new-york-city/sponsor.md, data/events/2019-new-york-city.yml
=> [NYC-2019] Add Rancher and F5 as sponsors

content/events/2018-tel-aviv/program.md, content/events/2018-tel-aviv/program/hyde-park.md, content/events/2018-tel-aviv/program/open-source.md, content/events/2018-tel-aviv/speakers/adi-shacham-shavit.md
[tlv-2018]more program changes
=> [tlv-2018]more program changes

content/events/2019-minneapolis/sponsor.md, data/events/2019-minneapolis.yml
=> [MSP-2019] Add f5 networks as gold and alacarte sponsor

content/events/2018-tel-aviv/program.md, data/events/2018-tel-aviv.yml
[tlv-2018] automat_it sponsor, schedule swap aaron and karen
=> [tlv-2018] automat_it sponsor, schedule swap aaron and karen

content/events/2019-sao-paulo/sponsor.md, data/events/2019-sao-paulo.yml
=> [SP-2019] Added sponsor page

data/events/2018-tel-aviv.yml
=> [tlv-2018] wix sponsor

content/events/2018-galway/program/adrian-ryan.md, content/events/2018-galway/program/desy-kristianti.md, content/events/2018-galway/program/jason-gwartz.md, content/events/2018-galway/program/joe-nuspl.md, content/events/2018-galway/program/kenzie-woodbridge.md, content/events/2018-galway/program/rich-archbold.md, content/events/2018-galway/program/shane-galvin.md
=> [GAL-2018] Add slides for speakers who have responded (so far)

content/events/2019-copenhagen/sponsor.md, data/events/2019-copenhagen.yml
=> [CPH-2019] add sponsor packages

data/events/2019-new-york-city.yml
=> [NYC-2019] Add rundeck as sponsor

content/events/2019-new-york-city/sponsor.md
* Remove email option for gold
* Strike out live captioning entirely
=> [NYC-2019] Updates to sponsorships

content/events/2019-new-york-city/sponsor.md
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Blah Blah Black Sheep Company as a sponsor`*
=> [NYC-2019] pretty align of stuff - fix earlier bug

data/events/2019-charlotte.yml
=> [CLT-2019] add gitlab and red ventures as sponsors

data/events/2019-ghent.yml
=> [GENT-2019] Adding Mine Heck to the team

content/events/2019-london/sponsor.md, data/events/2019-london.yml
I made a number of mistakes copying across the information from last year. This PR fixes those along with removing the footnotes which are no longer relevant.
=> [LDN-2019] Correct mistakes copied from previous year

content/events/2019-washington-dc/sponsor.md
=> [DC-2019] Do not overcommit on video streaming

content/events/2019-washington-dc/sponsor.md, data/events/2019-washington-dc.yml
=> [DC-2019] - Add live captions sponsor option

content/events/2019-washington-dc/sponsor.md
=> [DC-2019] Green check marks for things sponsors get

data/events/2019-minneapolis.yml
=> [MSP-2019] Add appdynamics as a gold sponsor

data/events/2017-washington-dc.yml, data/events/2018-washington-dc.yml, data/events/2019-washington-dc.yml
=> [DC-2019] Add ga_tracking_id

data/events/2019-seattle.yml
=> [SEA-2019] added AppDynamics at Gold

data/events/2019-stockholm.yml
Adding the organizers initially tried in https://github.com/devopsdays/devopsdays-web/pull/5954
=> [Stockholm-2019] Add organizers for Stockholm

content/events/2019-london/accessibility.md, data/events/2019-london.yml
We've got some CFP dates now so I've added those but not enabled the
page as of yet. I've also enabled the accessibility page as it's
worthwhile having this after discussing in our weekly meeting.
=> [LDN-2019] Enable accessibility and input CFP dates.

content/events/2019-new-york-city/program/alex-hidalgo.md, content/events/2019-new-york-city/program/amitai-schleier.md, content/events/2019-new-york-city/program/anton-babenko.md, content/events/2019-new-york-city/program/david-ayers.md, content/events/2019-new-york-city/program/dominica-degrandis.md, content/events/2019-new-york-city/program/eva-parish.md, content/events/2019-new-york-city/program/gaurav-gargate.md, content/events/2019-new-york-city/program/heidi-waterhouse.md, content/events/2019-new-york-city/program/jaclyn-damiano.md, content/events/2019-new-york-city/program/jay-gordon.md, content/events/2019-new-york-city/program/jessica-kerr.md, content/events/2019-new-york-city/program/jody-lent.md, content/events/2019-new-york-city/program/liz-fongjones.md, content/events/2019-new-york-city/program/matty-stratton.md, content/events/2019-new-york-city/program/mohammed-salah-adawi.md, content/events/2019-new-york-city/program/peter-chestna.md, content/events/2019-new-york-city/program/quintessence-anx.md, content/events/2019-new-york-city/program/rob-boll.md, content/events/2019-new-york-city/program/robert-conley-rogers.md, content/events/2019-new-york-city/program/tiffany-longworth.md
Use descriptions submitted to papercall as default.
=> [NYC-2019] Add talk descriptions

content/events/2019-new-york-city/welcome.md
=> [NYC-2019] Enable Program link

content/events/2019-boise/registration.md, data/events/2019-boise.yml
Adding eventbrite widget to the registration page and notice to contact organizers for student discount.
=> [Boise 2019] Adding registration details

data/events/2019-new-york-city.yml
=> [NYC-2019] Open Space clarification

content/events/2019-charlotte/program.md, content/events/2019-charlotte/sponsor.md, data/events/2019-charlotte.yml
=> [CLT-2019] Add program embed and sponsor.

content/events/2019-copenhagen/location.md, content/events/2019-copenhagen/welcome.md, data/events/2019-copenhagen.yml
I added the venue and location details
=> [CPH-2019]add venue

content/events/2019-copenhagen/sponsor.md
=> [CPH-2019] Update sponsors page

data/events/2019-baltimore.yml, data/sponsors/wortech.yml
* Platinum
* AppDynamics
* Silver
* WorTech
=> [BALT-2019] First sponsors

data/events/2019-tokyo.yml
Checking to see if this fixes a date issue
=> Correcting date display

content/events/2019-houston/sponsor.md, data/events/2019-houston.yml
[HOU-2019] Adding 'Pay Now' buttons for sponsors
=> [HOU-2019] Adding 'Pay Now' buttons for sponsors

data/events/2019-minneapolis.yml
=> [MSP-2019] Add Circle CI as Gold sponsor

data/events/2019-washington-dc.yml
=> [DC-2019] CircleCI is a Gold Sponsor

data/events/2019-los-angeles.yml
- Adding a new team member
**Testing:**
- n/a
=> [LA-2019] Adding a new team member

content/events/2018-des-moines/sponsor.md, content/events/2019-des-moines/sponsor.md, data/events/2019-des-moines.yml
Add sponsorship page for Des Moines 2019
=> [DSM-2019] Add sponsorship page

data/events/2019-houston.yml
[HOU-2019] Added first bronze sponsor: fearless
=> [HOU-2019] Added first bronze sponsor: fearless

content/events/2019-buffalo/conduct.md, content/events/2019-buffalo/contact.md, content/events/2019-buffalo/location.md, content/events/2019-buffalo/propose.md, content/events/2019-buffalo/registration.md, content/events/2019-buffalo/sponsor.md, content/events/2019-buffalo/welcome.md, data/events/2019-buffalo.yml
=> BUF-2019 Requesting to add DoD Buffalo to the repo

data/events/2019-ghent.yml
=> [GENT-2019] Adding Toshaan as organiser

data/events/2019-london.yml
We've got an event event sponsor already so lets get them added to the site.
=> [LDN-2019] Add F5 Networks as evening event sponsor

data/events/2019-los-angeles.yml
[LA 2019] add Sumologic as a sponsor
=> [LA 2019] add Sumologic as a sponsor

content/events/2019-sao-paulo/cfp.md, data/events/2019-sao-paulo.yml
* Added ticket and CFP pages
* Added 10Deploys podcast as community sponsor.
=> [SP-2019] Added tickets and cfp pages

content/events/2019-los-angeles/propose.md
- Change talk submissions link to Google Form
- Made content more consistent w/ that is on the form
- removed html in favor of markdown
=> Update 2019-los-angles propose.md

data/events/2019-minneapolis.yml
=> [MSP-2019] Add Datadog as Silver sponsor

data/events/2019-los-angeles.yml
[la 2019] add datadog as sponsor
=> [la 2019] add datadog as sponsor

data/sponsors/whitesource.yml
=> [NYC-2019] Correcting whitesource sponsor link

content/events/2019-denver/conduct.md, content/events/2019-denver/location.md, content/events/2019-denver/sponsor.md, content/events/2019-denver/welcome.md, data/events/2019-denver.yml
* Added new organizers
* Added location information
* Added dates
* Added sponsor prospectus link
* Added CFP and reg dates
=> [DEN-2019] Additions for Denver's Upcoming Event

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Wavefront as a sponsor

data/events/2019-new-york-city.yml
fix sponsor level for wavefront
=> [NYC-2019] fix sponsor level

data/events/2019-los-angeles.yml
[la2019] add codefresh as sponsor
=> [la2019] add codefresh as sponsor

content/events/2019-boise/welcome.md, data/events/2019-boise.yml
Adding more registration information and exposing the link to register.
=> [Boise 2019] Updating registration information again

data/events/2019-los-angeles.yml
=> [la 2019] add dynatrace

content/events/2019-seattle/conduct.md, content/events/2019-seattle/contact.md, content/events/2019-seattle/location.md, content/events/2019-seattle/propose.md, content/events/2019-seattle/registration.md, content/events/2019-seattle/welcome.md, data/events/2019-seattle.yml
[SEA-2019] - Turn on registration, turn off CFP
=> [SEA-2019] - Turn on registration, turn off CFP

data/events/2019-atlanta.yml
adding gold sponsors pagerduty, contino, signalfx, appdynamics
=> [ATL-2019] adding gold sponsors: pagerduty, contino, signalfx, appdynamics

content/events/2019-vancouver/welcome.md, data/events/2019-vancouver.yml
Add in the link for registration and uncomment the logo
=> [VAN-2019] Add registration link and uncomment logo

data/events/2019-denver.yml
* Added Joe back in - miscommunication there
* Adjusted workplace
* Adjusted CFP to include Global Diversity CFP Day
=> [DEN-2019] Adjuments for CFP and Organizers

content/events/2019-denver/sponsor.md
* Changed the URL to the prospectus to be a PDF instead of just a slides link.
(sorry for the branch name, trying to do something quickly via UI)
=> [DEN-2019] Update prospectus to be PDF

data/events/2019-sao-paulo.yml
Added Adaptnow as bronze sponsor
=> [SP-2019] - Added Adaptnow as sponsor

content/events/2019-geneva/program.md
=> [GENEVA-2019] Added Julien Pivotto to program

content/events/2019-geneva/program.md
=> [GENEVA-2019] TypoCorrection + add julien pivotto company

data/events/2019-amsterdam.yml
=> [AMS-2019] Change propose and registration to open

content/events/2019-denver/welcome.md
* Aint no free lunch in this world - URLs don't auto link themselves.
=> [DEN-2019] Adding usable links

data/events/2019-seattle.yml
=> [SEA-2019] Adding REI as gold sponsor

content/events/2019-denver/welcome.md, data/events/2019-denver.yml
Fixing the CFP link & adding to menu
=> [Denver 2019] denver cfp

content/events/2019-los-angeles/welcome.md
simple fix to remove "lighting" from cfp text on welcome page
=> [la 2019] Fix CFP text on welcome page

data/events/2019-geneva.yml
=> [GENEVA-2019] Changed Mazzeri info

content/events/2019-baltimore/registration.md, content/events/2019-baltimore/sponsor.md, content/events/2019-baltimore/welcome.md, data/events/2019-baltimore.yml
=> [bmore-2019] Fixing registration links; adding onyx-point sponsor, fixing year in copy

data/sponsors/pure-storage.yml
older events were already updated yesterday
=> [NYC-2019] Update link to sponsor

.travis.yml, hugoserver.sh, metadata.json, netlify.toml
=> Use latest Hugo - v0.53

data/events/2019-charlotte.yml
=> [CLT-2019] Add sponsor

data/events/2019-indianapolis.yml
=> [INDY-2019] Add Dynatrace as a gold sponsor

content/events/2018-galway/program/brian-scanlan.md
=> [GAL-2018] Add slides for Brian Scanlan

content/events/2019-denver/location.md, content/events/2019-denver/sponsor.md, data/events/2019-denver.yml
* Added circleci as a sponsor
* Added some commented data for later publishing
* Added fix to case-sensitive "page type"
=> [DEN-2019] Added CircleCI as a sponsor

data/events/2019-bogota.yml
Hi, @devopscolombia - I fixed some things on your site - you will need to pull these changes in - thanks.
=> [2019 Bogota] Typo corrections

data/events/2019-denver.yml
* Added another sponsor
* Added rename to supporter sponsorship
=> [DEN-2019] Additions to sponsors

data/events/2019-los-angeles.yml
=> [la 2019] add launch darkly

data/events/2019-minneapolis.yml
=> [MSP 2019] Adding HtG

data/events/2019-minneapolis.yml
Adding Software Defined Talk as a community sponsor.
=> [MSP 2019] adding SDT

data/events/2019-new-york-city.yml
=> [NYC-2019] Add Social Sponsors

data/events/2019-seattle.yml
=> [SEA-2019] 2019 seattle sponsors

content/events/2019-denver/sponsor.md
* Added links for self-pay
* Added messaging for expectations
=> [DEN-2019] Added links and email

content/events/2019-seattle/sponsor-info.md
=> [SEA-2019] Adding 2019 sponsor info

content/events/2019-denver/registration.md, data/events/2019-denver.yml
=> [DEN-2019] Adding tickets!

content/events/2019-new-york-city/welcome.md, data/events/2019-new-york-city.yml
1) program update for social time
2) increase/size spacing of main info section for improved readability
3) signup link for nycdevops slack
=> [NYC-2019] program fix

data/sponsors/appdynamics-before-20190121.yml, data/sponsors/sonatype-before-20190121.yml
Can't hurt to add the missing files
=> Missing sponsor files

bin/netlify-production.sh, netlify.toml
=> Mattstratton patch 1

content/events/2019-stockholm/sponsor.md
* Link to prospectus for stockholm. The prospectus is uploaded to devopsdays-assets
=> [STO-2019]  link to sprospectus for stockholm

data/events/2019-raleigh.yml
[RDU-2019] added platinum sponsor dynatrace
=> [RDU-2019] added platinum sponsor dynatrace

content/events/2019-new-york-city/location.md, content/events/2019-new-york-city/welcome.md
Updates margin/grid on welcome page and fixes map on location page
=> [NYC-2019] Format Tweak + Loc page update

data/events/2019-los-angeles.yml
[la2019] new sponsors: redgate, sonatype, newrelic
=> [la2019] new sponsors: redgate, sonatype, newrelic

content/events/2019-seattle/stem-sponsor.md
=> [SEA-2019] 2019 STEM sponsor page

data/events/2019-minneapolis.yml
I think the missing datetime string wasn't caused by this (since it seemed to be from Jakarta); retrying.
=> [MSP 2019] Adding full datetime strings

data/events/2019-charlotte.yml
=> [CLT-2019] Add a sponsor

data/events/2019-denver.yml
=> [DEN-2019] Added sponsor and organizer

content/events/2019-denver/sponsor.md
=> [DEN-2019] Remove silver sponsorship paypal link.

data/events/2019-kansas-city.yml
adding Chris Fisher linkedin profile
=> [KC-2019] - linkedin add

data/events/2019-copenhagen.yml
I've added Praqma and made arresteddevops visible because I think it will help us to sign sponsors if they see that they are not the first ones ;)
=> [CPH-2019] add-sponsor

data/events/2019-amsterdam.yml
=> [AMS-2019] Add developers.nl as sponsor

content/events/2019-new-york-city/welcome.md
=> [NYC-2019] Open Space schedule

data/events/2019-vancouver.yml
=> [VAN-2019] Added Gold sponsor Launch Darkly

data/events/2019-los-angeles.yml
- Updating CFP dates
- Modified 2019-los-angeles.yml
**Testing:**
- n/a
=> [LA-2019] Updating CFP dates

data/events/2019-minneapolis.yml
=> [MSP 2019] Add Minnestar

content/events/2019-houston/welcome.md
=> [HOU-2019] Fixed layout for the LinkedIn button

content/events/2019-london/registration.md, content/events/2019-london/welcome.md, data/events/2019-london.yml
We're now selling tickets! We use tito so it's got a JS and CSS embed.
=> [LDN-2019] Add Tito ticket sales embed and registration links.

content/events/2019-boise/welcome.md
Show the proposal link on the main event page
=> [Boise 2019] CFP Link

content/events/2019-amsterdam/propose.md
=> [AMS-2019] Fixing the propose page

content/events/2019-houston/sponsor.md, data/events/2019-houston.yml
[HOU-2019] Adding Dynatrace as platinum sponsor
=> [HOU-2019] Adding Dynatrace as platinum sponsor

data/events/2019-amsterdam.yml
=> [AMS-2019] Add NewRelic as sponsor

data/events/2019-raleigh.yml
[RDU-2019] added techtown and microsoft as sponsor
=> [RDU-2019] added techtown and microsoft as sponsor

data/events/2018-warsaw.yml
=> [WAW-2018/2019] Remove Piotr Szwed from organizers

data/events/2019-raleigh.yml
[RDU-2019] added happy hour sponsorship tier
=> [RDU-2019] added happy hour sponsorship tier

data/events/2019-houston.yml
=> [HOU-2019] Added DataDog as Gold sponsor

content/events/2019-des-moines/sponsor.md
=> [DSM-2019] Updated payment link

data/events/2019-zurich.yml
YAY nine will sponsor us again 🎉
=> [ZRH-2019] Add nine as bronze sponsor

content/events/2019-seattle/program/burns-kromhout.md, content/events/2019-seattle/speakers/brendan-burns.md
=> [SEA-2019] add twitter for Brendan

data/events/2019-seattle.yml
=> [SEA-2019] fixed program dates

content/events/2019-portugal/registration.md, data/events/2019-portugal.yml
Registration page - tito integration.
=> [PT2019] Registration page

data/events/2019-portugal.yml
Adding propose url to papercall
=> [PT2019] Adding propose url to papercall

content/events/2019-detroit/propose.md, data/events/2019-detroit.yml
- new propose.md 
- set to open cfp next week
=> [DET-2019] Initializing Detroit 2019

content/events/2019-portugal/sponsor.md
=> [PT2019] Sponsors page

content/events/2019-portugal/conduct.md
[PT2019] DevOpsDays Portugal CoD version
=> [PT2019] DevOpsDays Portugal CoD version

data/events/2019-boise.yml
Simple PR, just adds HP as sponsor
=> [2019 Boise] Add HP as sponsor

content/events/2019-montevideo/conduct.md, content/events/2019-montevideo/contact.md, content/events/2019-montevideo/location.md, content/events/2019-montevideo/propose.md, content/events/2019-montevideo/registration.md, content/events/2019-montevideo/sponsor.md, content/events/2019-montevideo/welcome.md, data/events/2019-montevideo.yml
Initial PR for Montevideo 2019 event
=> [MVD-2019] initial PR

data/events/2019-seattle.yml
=> [SEA-2019] added catchpoint

content/events/2019-seattle/sponsor-info.md
=> [SEA-2019] updated sponsor info

data/events/2019-los-angeles.yml
=> [la 2019] more sponsors

data/events/2019-minneapolis.yml
=> [MSP-2019] Add SignalFx as Platinum sponsor

content/events/2019-edinburgh/location.md, content/events/2019-edinburgh/welcome.md, data/events/2019-edinburgh.yml
[EDI-2019] Added dates and location
=> [EDI-2019] Added dates and location

data/events/2019-houston.yml
[HOU-2019] Added InfluxData as Gold sponsor
=> [HOU-2019] Added InfluxData as Gold sponsor

data/events/2019-denver.yml
* Added sponsors
* Fixed extra register button on header
=> [DEN-2019] Sponsor additions

data/events/2019-minneapolis.yml
=> [MSP-2019] Add Red Hat as a platinum sponsor

content/events/2019-des-moines/sponsor.md, data/events/2019-des-moines.yml
=> [DSM-2019] Added sponsor images and registration link

data/events/2019-seattle.yml
=> [SEA-2019] move redhat to silver

data/events/2019-sao-paulo.yml
=> [SP-2019] Extend call for papers

content/events/2019-geneva/program/raphael-hiet.md
=> [GVA-2019] Corrected Raphael Hiet Talk Info

data/events/2019-berlin.yml
Adding the link for the CfP, making "Conduct" more prominent, fixing CfP dates.
=> [BER-2019] Call for papers is open from February 12th

content/events/2019-sao-paulo/sponsor.md, data/events/2019-sao-paulo.yml
* Added New Relic and vbrownbagbrasil as sponsors
* Changed sponsor quotes
=> [SP-2019] Added new sponsors

data/events/2019-houston.yml
[HOU-2019] Added GitLab as silver sponsor
=> [HOU-2019] Added GitLab as silver sponsor

data/events/2019-austin.yml
Golds:
* nVisium
* Contrast Security
Media:
* DevOps.com
=> [ATX-2019] Add gold and media sponsors

data/events/2019-raleigh.yml
[RDU-2019] added ahead as sponsor
=> [RDU-2019] added ahead as sponsor

data/events/2019-seattle.yml
Added puppet and launch darkly
=> [SEA-2019] added sponsors

data/events/2019-victoria.yml
=> [2019-victoria] added sponsors

content/events/2018-jakarta/speakers/abdurrachman-mappuji.md
Noticed a broken image link (there is no image for that speaker).
=> [Jakarta 2018] Fixing broken image link

content/events/2019-cape-town/propose.md, data/events/2019-cape-town.yml
To explain to people what the CFP is about, before sending them to
papercall
=> [Cape Town 2019] Use the propose page

content/events/2019-denver/sponsor.md, data/events/2019-denver.yml
* Removed platinum - got feedback value was not there - Merged in parts of platinum to gold in prospectus
* Adjusted counts for silver and gold level sponsorship
=> [DEN-2019] Adjustments made to levels of sponsorship

data/events/2019-buffalo.yml
Adding the dates of the event, the location, and map information. Had dates wrong (Thanks, Bridget for catching that and saving us from ourselves). Also updated the CFP which is now open.
=> Buffalo-2019 - Correcting Dates, Adding Location info and CFP information

data/events/2019-houston.yml
[HOU-2019] Adding MondoDB as Gold Sponsor
=> [HOU-2019] Adding MongoDB as Gold Sponsor

content/events/2019-denver/sponsor.md
Pricing was incorrect - now it matches the prospectus
=> [DEN-2019] Fixed pricing for happy hour

data/events/2019-denver.yml
=> [DEN-2019] Sponsor Addition

content/events/2019-los-angeles/welcome.md, data/events/2019-los-angeles.yml
- Remove CFP is open
- Update announce date
- Update schedule
=> [LA-2019] CFP updates

data/events/2019-raleigh.yml
[RDU-2019] Added talk proposal form
=> [RDU-2019] Added talk proposal form

content/events/2019-raleigh/propose.md
=> [RDU-2019] talk topics

data/events/2019-minneapolis.yml
=> [MSP-2019] Add vmware and AHEAD platinum sponsors

data/events/2019-raleigh.yml
[RDU-2019] added appdynamics as sponsor
=> [RDU-2019] added appdynamics as sponsor

content/events/2019-amsterdam/welcome.md, data/events/2019-amsterdam.yml
We decided to switch from a 4 day event to 3 day event. Hence the change in dates.
=> [AMS-2019] Update AMS 2019 dates

data/events/2019-zurich.yml
=> [ZRH-2019] Add entrance, coffee and planet sponsor into platinum

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Valtech as Silver

data/events/2019-amsterdam.yml
=> [AMS-2019] Add s0l1dheroes as Bronze

data/events/2019-raleigh.yml
[RDU-2019] Update 2019-raleigh.yml
=> [RDU-2019] add logdna as gold sponsor

content/events/2019-copenhagen/speakers/aubrey-stearn.md, data/events/2019-copenhagen.yml
=> [CPH-2019] Add xebia as sponsor

data/events/2019-raleigh.yml
[RDU-2019] removed andrew sullivan as organizer
=> [RDU-2019] removed andrew sullivan as organizer

data/events/2019-nashville.yml
Mike Noe left the Nashville team, added multiple sponsors
=> [bna-2019] added sponsors; removed organizer

data/events/2019-denver.yml
=> [DEN-2019] Adding Instana Sponsor

content/events/2019-jakarta/program.md, data/events/2019-jakarta.yml
This PR adds the initial program
=> [JKT-19] Add program

data/events/2019-raleigh.yml
[RDU-2019] add propose link on main nav section
=> [RDU-2019] add propose link on main nav section

content/events/2019-jakarta/speakers/christian-hermanus.md, data/events/2019-jakarta.yml
This PR:
- adds a speakers page
- fixes the image of one speaker
=> [JKT-19] Update speakers

content/events/2019-des-moines/sponsor.md, data/events/2019-des-moines.yml
=> [DSM-2019] Update social sponsor and remaining sponsor counts

data/events/2019-ghent.yml
Update the sponsor levels and maximum numbers to be the same as the sponsor doc
=> [GHENT-2019] update sponsor levels and max

data/events/2019-zurich.yml
YAY we got Zühlke as bronze Sponsor :D
=> [ZURICH-2019] Add Zuehlke as bronze sponsor

data/events/2019-istanbul.yml
All three dates need to be set. I picked an arbitrary date later than the close date for the reveal (as they aren't displaying that on the site anyhow).
=> [Ist 2019] Trying setting all three dates

data/events/2019-minneapolis.yml
=> [MSP-2019] Add sysdig as a silver sponsor

data/events/2019-minneapolis.yml
=> [MSP-2019] Mark platinum sponsorships as closed

data/events/2019-porto-alegre.yml
=> [POA-2019] Add registration link

content/events/2019-houston/sponsor.md
=> [HOU-2019] Marked Gold as sold out, put limits on Silver and Bronze

content/events/2019-austin/sponsor.md, data/events/2019-austin.yml
* Also mark sponsorships as sold out.
=> [ATX-2019] CFP announce date is now 3/11

content/events/2019-houston/sponsor.md, content/events/2019-houston/welcome.md
=> [HOU-2019] Reformatted Sponsor FAQ. Added program link to welcome page.

content/events/2019-ghent/location.md, data/events/2019-ghent.yml
* add location page with location info
* add location and coordinates to welcome page
* update twitter handle to @devopsdaysghent
=> [GHENT-2019] update location info

content/events/2019-minneapolis/sponsor.md
We have no further Platinum spots for 2019.
=> [MSP 2019] Clarifying that platinum is sold out for MSP 2019.

content/events/2019-minneapolis/sponsor.md
Make Platinum being sold out (and Gold still available) more clear.
=> [MSP 2019] Platinum sold out

content/events/2019-houston/program/sagar-karmarkar.md, data/events/2019-houston.yml
=> [HOU-2019] Added details about Sagar Karmarkar's talk

content/events/2019-minneapolis/sponsor.md, data/events/2019-minneapolis.yml
=> [MSP-2019] Add sps_commerce as platinum and lanyard sponsor

data/events/2019-raleigh.yml
[RDU-2019] added triangledevops as sponsor
=> [RDU-2019] added triangledevops as sponsor

content/events/2019-raleigh/propose.md, data/events/2019-raleigh.yml
[RDU-2019] change propose page and remove direct link to form
=> [RDU-2019] change propose page and remove direct link to form

content/events/2019-buffalo/welcome.md
Correct markdown for Propose link
=> [Buffalo 2019] Corrected proposal link

data/events/2019-minneapolis.yml
=> [MSP-2019] Add influxdata as a gold sponsor

data/events/2019-chicago.yml
Small tweak to bio (also to test build)
=> [CHI-2019] - Update Matty Stratton bio

data/events/2019-copenhagen.yml
=> [CPH-2019] adding atlassian

data/events/2019-baltimore.yml
=> [BMORE-2019] Adding a ton of platinum sponsors

content/events/2019-houston/sponsor.md, data/events/2019-houston.yml
=> [HOU-2019] Added two more sponsors AWS and Microsoft

content/events/2019-columbus/conduct.md, content/events/2019-columbus/contact.md, content/events/2019-columbus/location.md, content/events/2019-columbus/sponsor.md, content/events/2019-columbus/welcome.md, data/events/2019-columbus.yml
This is the initial creation of the Columbus 2019 Event. This is just a bare minimum to get it in there with the dates (which were very limited unfortunately). Will need the 2019 emails created, please copy the organizer email list from last time and keep slack the same.
=> [Columbus 2019] Creating event

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Pivotal as Gold sponsor

content/events/2019-houston/program/lee-barnes.md, data/events/2019-houston.yml
=> [HOU-2019] Added Lee Barnes talk to the schedule

data/sponsors/quartech-systems.yml
=> [2019-Victoria] updated Sponsor Name

data/events/2019-minneapolis.yml
=> [MSP-2019] Add pivotal as a gold sponsor

content/events/2019-montreal/conduct.md, content/events/2019-montreal/contact.md, content/events/2019-montreal/location.md, content/events/2019-montreal/propose.md, content/events/2019-montreal/registration.md, content/events/2019-montreal/sponsor.md, content/events/2019-montreal/welcome.md, data/events/2019-montreal.yml
=> [YUL-2019] Creation of 2019 Montreal event

content/events/2019-vancouver/program/laura-maguire.md, content/events/2019-vancouver/program/tiffany-longworth-ignite.md, content/events/2019-vancouver/program/tiffany-longworth.md, content/events/2019-vancouver/speakers/kris-nova.md, data/events/2019-vancouver.yml
[VAN-2019] Update the schedule times, adds two more talks, fixes the name of Tiffany Longworth's talk, and adds ignite talks to the schedule.
=> [VAN-2019] update schedule times and add ignite talks to schedule

data/events/2019-ghent.yml
add first sponsor : inuits - bronze level
=> [GHENT2019] add first bronze sponsor

data/events/2019-minneapolis.yml
=> [MSP-2019] Add pagerduty as gold sponsor

data/events/2019-indianapolis.yml
=> [INDY-2019] Extend CFP two weeks

data/events/2019-vancouver.yml
removing tasktop from silver sponsorship
=> [VAN-2019] removing tasktop from silver

data/events/2019-vancouver.yml
Just a small speaker swap - they've both been notified. Thanks!
=> [VAN-2019] Swap Adron and Nisan's talks

content/events/2019-tampa/sponsor.md, content/events/2019-tampa/welcome.md
=> [TPA-2019] - Updated Welcome Message

content/events/2019-sao-paulo/speakers/amanda-mattos.md
Fixed bio and removed temporarily photo by speakers request. She'll send new picture soon
=> [SP-2018] Fixed Amanda Mattos bio

content/events/2019-tampa/sponsor.md
Added Paypal link for sponsors
=> [TPA-2019] - Added Paypal link for sponsors

content/events/2019-denver/sponsor.md, data/events/2019-denver.yml
* Sponsor additions and update to sponsor page
=> [DEN-2019] Sponsors and Updates

data/events/2019-zurich.yml
YAY we got Google as platinum Sponsor 🎉
=> [ZRH-2019] Add Google as platinum sponsor

data/events/2019-nashville.yml
=> [bna-2019] added newrelic sponsorship

data/events/2019-houston.yml
=> [HOU-2019] Added Mesosphere as gold sponsor.

data/events/2019-toronto.yml
=> [TOR-2019] Add Slalom Build as gold sponsor

data/events/2019-atlanta.yml
adding new relic and rancher as gold sponsors
=> [ATL-2019] adding new relic and rancher as gold

data/events/2019-seattle.yml
=> [SEA-2019] added sponsor

content/events/2019-tampa/location.md, content/events/2019-tampa/registration.md, data/events/2019-tampa.yml
[TPA-2019] - Added Location and Registration
=> [TPA-2019] - Added Location and Registration

data/events/2019-portland.yml
=> [PDX-2019] Add sponsors, open CFP.

content/events/2019-denver/sponsor.md
=> [DEN-2019] Added updates to site

data/events/2019-seattle.yml
=> [SEA-2019] adding vmware

content/events/2019-baltimore/welcome.md, data/events/2019-baltimore.yml
=> [BMORE-2019] Adding sponsors; disabling proposal submissions

data/events/2019-baltimore.yml
Cleaning up yaml with some advice from https://github.com/devopsdays/devopsdays-web/pull/6559
=> [BMORE-2019] Add contrast_security sponsor, clean up comments

data/events/2019-minneapolis.yml
=> [MSP-2019] Add rancher as silver sponsor

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Portworks as silver

data/events/2019-chattanooga.yml
This PR enables location for CHA 2019 and adds the address for the event.
=> [CHA-2019] Updates event location

data/events/2019-santa-maria.yml
=> [SM-19] Update Calendar

content/events/2019-victoria/registration.md
=> [victoria-2019] updated registration page

content/events/2019-houston/speakers/chris-black.md, data/events/2019-houston.yml
=> [HOU-2019] Minor fixes to speaker bio and program

data/events/2019-austin.yml
* Red-gate
* Electric Cloud
* Pivotal
=> [ATX-2019] New gold sponsors

data/sponsors/nielsen.yml
The event using this sponsor has specified SSL.
=> Switching sponsor to SSL

data/events/2019-tampa.yml
[TPA-2019] - Added Dynatrace and GitLab
=> [TPA-2019] - Added Dynatrace and GitLab

data/events/2019-minneapolis.yml
=> [MSP-2019] Add dynatrace as platinum sponsor

content/events/2017-amsterdam/propose.md, content/events/2017-amsterdam/welcome.md, content/events/2017-atlanta/propose.md, content/events/2017-beijing/propose.md, content/events/2017-charlotte/propose.md, content/events/2017-dallas/program/inspec.md, content/events/2017-dallas/welcome.md, content/events/2017-kansascity/propose.md, content/events/2017-paris/propose.md, content/events/2017-portland/propose.md, content/events/2017-salt-lake-city/propose.md, content/events/2018-charlotte/sponsor.md, content/events/2019-charlotte/sponsor.md
Reducing the issues described in https://github.com/devopsdays/devopsdays-web/issues/6599.
=> Moving shortcodes out of ToC

content/events/2019-des-moines/sponsor.md, data/events/2019-des-moines.yml
=> [DSM-2019] All Sponsorships sold

data/events/2019-minneapolis.yml
=> Adding community sponsor

content/events/2019-vancouver/welcome.md, data/events/2019-vancouver.yml
Program and speakers are available; CFP is closed.
=> [Vancouver 2019] Updating menus

content/events/2019-copenhagen/welcome.md, data/events/2019-copenhagen.yml
CFP is closed; program and speakers are posted.
=> [Copenhagen 2019] Update menus

content/events/2019-denver/welcome.md, data/events/2019-denver.yml
Since the CFP date has passed - /cc @endzyme
=> [Denver 2019] CFP is closed

data/events/2019-denver.yml
=> [DEN-2019] Adjusting organizers

content/events/2019-vancouver/program/adron-hall.md, content/events/2019-vancouver/program/amin-yazdani.md, content/events/2019-vancouver/program/callum-styan.md, content/events/2019-vancouver/program/courtney-eckhardt.md, content/events/2019-vancouver/program/don-burks.md, content/events/2019-vancouver/program/garland-kan.md, content/events/2019-vancouver/program/jay-gordon.md, content/events/2019-vancouver/program/jessie-ye.md, content/events/2019-vancouver/program/jj-asghar.md, content/events/2019-vancouver/program/kenzie-woodbridge.md, content/events/2019-vancouver/program/kris-nova.md, content/events/2019-vancouver/program/laura-maguire.md, content/events/2019-vancouver/program/nisan-haramati.md, content/events/2019-vancouver/program/quintessence-anx.md, content/events/2019-vancouver/program/shane-gearon.md, content/events/2019-vancouver/program/sonia-gupta.md, content/events/2019-vancouver/program/tiffany-longworth-ignite.md, content/events/2019-vancouver/program/tiffany-longworth.md, content/events/2019-vancouver/speakers/shane-gearon.md
Adds in the descriptions for the talks and ignites as well as adding in one speakers picture
=> [VAN-2019] add talk descriptions and image for one speaker

data/events/2019-london.yml
We've got influxdata sponsoring gold this year.
Signed-off-by: Chris M <me@christophermills.co.uk>
=> [LDN-2019] Add Influxdata as sponsor

content/events/2019-houston/program.md, content/events/2019-houston/speakers/chris-black.md, content/events/2019-houston/sponsor.md, data/events/2019-houston.yml
=> [HOU-2019] Minor tweaks to program and sponsor pages.

content/events/2019-minneapolis/propose.md, content/events/2019-minneapolis/welcome.md, data/events/2019-minneapolis.yml
=> [MSP 2019] Close MSP cfp

content/events/2019-minneapolis/sponsor.md, data/events/2019-minneapolis.yml
=> [MSP-2019] Add country financial as ala-carte

content/events/2019-atlanta/leadershipsummit.md
I should have specified the width on all the pics the 1st time : D
=> [ATL-2019] changed sizing of David's pic

themes/devopsdays-theme/layouts/partials/speaking.html
Fix for the speaking page issue
=> FIX issue #6625 - investigate speaking page issue

data/events/2019-denver.yml
per a request from the sponsor
=> [DEN-2019] Added a sponsor

content/events/2019-copenhagen/program/kenneth-boegh.md
There was a bug from the program to the speaker link
=> [CPH-2019] Fix Kenneth link

data/events/2019-london.yml
Datadog are sponsoring us this year as a silver sponsor. This commit
solves this!
Signed-off-by: Chris M <me@christophermills.co.uk>
=> [LDN-2019] Add datadog as silver sponsor

content/events/2019-ghent/sponsor.md
=> [Ghent 2019] Adding Ghent prospectus

data/events/2019-oslo.yml
* Adding dates and link to CfP for Oslo 2019
=> [OSL-2019] cfp for Oslo 2019

data/events/2019-nashville.yml
=> [bna-2019] switched to original twitter account

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Inuits as Bronze

data/events/2019-indianapolis.yml
=> [INDY-2019] Add AppDynamics as a gold sponsor

CONTRIBUTING.md, README.md
Related to the theme repo being deprecated.
=> Updating docs for theme move

data/events/2019-minneapolis.yml
=> [MSP-2019] Add nutanix as gold sponsor

content/events/2019-tampa/sponsor.md
[TPA-2019] - Updated Sponsor Page - Sold Out Platinum
=> [TPA-2019] - Updated Sponsor Page - Sold Out Platinum

content/events/2019-atlanta/leadershipsummit.md
added reception and a little more on the description.
=> [ATL-2019] added reception to leadership summit

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Chef as Gold

data/events/2019-atlanta.yml
=> [ATL-2019] adding victorOps as gold

data/events/2019-chicago.yml
=> [CHI-2019] Add Pagerduty as gold

content/events/2019-stockholm/registration.md, data/events/2019-stockholm.yml
Add the Tito registration widget.
=> [STH-2019] open registration

content/events/2019-buffalo/welcome.md
Fixed an incorrectly formatted link to the proposal page.
cc @aspleenic
=> [BUFFALO-2019] Fix proposal link in front matter

data/events/2019-dallas.yml
=> [DFW-2019] Minor update to Welcome page.

content/events/2019-poznan/program.md, content/events/2019-poznan/program/keynote.md, content/events/2019-poznan/program/talk.md, content/events/2019-poznan/speakers/tbd.md, data/events/2019-poznan.yml
[POZ-2019] Create the program page
=> [POZ-2019] Create the program page

content/events/2019-nashville/welcome.md
=> [bna-2019] removed CFP link, updated program/speakers link

content/events/2019-seattle/stem-sponsor.md
=> [SEA-2019] update stem sponsorship

data/events/2019-baltimore.yml
Just change the sponsor to use the proper logo
=> [BMORE-2019] Fix collabnet logo

data/events/2019-tampa.yml
[TPA-2019] - Adding Accenture as Platinum Sponsor - TY!
=> [TPA-2019] - Adding Accenture as Sponsor - TY!

data/events/2019-poznan.yml
=> POZ-2019 - add registration link

data/events/2019-raleigh.yml
[RDU-2019] added sponsor and updated propose deadline
=> [RDU-2019] added sponsor and updated propose deadline

content/events/2019-copenhagen/location.md
=> [CPH-2019] add free parking

content/events/2019-seattle/sponsor-info.md
=> [SEA-2019] added drayage info

data/events/2019-portland.yml
=> [PDX-2019] Added additional gold sponsors

content/events/2019-portugal/sponsor.md
*  sponsorship program upgrade: number of tickets increase
=> [PT2019] sponsorship program upgrade: number of tickets increase

.circleci/config.yml
Temporary fix for https://github.com/lovell/sharp/issues/1632
=> Temporary patch for Sharp issue

content/events/2019-austin/welcome.md, data/events/2019-austin.yml
* also updates to the welcome page links
=> [ATX-2019] Cyberark and Riverbed sponsors

content/events/2019-jakarta/program/steve-shirkey.md
Update talk abstract and title
=> [JKT-19] Update talk abstract

content/events/2019-jakarta/speakers/budi-kusmiantoro.md, data/events/2019-jakarta.yml
=> [JKT-19] Update speaker bio

data/events/2019-washington-dc.yml
=> [DC-2019] Adding myself to the list of organizers for Washington DC 2019

content/events/2019-houston/speakers/brad-dausses.md
=> [HOU-2019] Added social media info for Brad Dausses

data/events/2019-istanbul.yml
=> [IST-2019] Adding sponsors

.circleci/config.yml
Reverts devopsdays/devopsdays-web#6744
=> Revert "Temporary patch for Sharp issue"

data/events/2019-denver.yml
=> [DEN-2019] Added Oracle Coffee Sponsorship

data/events/2019-sao-paulo.yml
=> [SP-2019] Changed program

content/events/2019-ghent/welcome.md
add a mailing list option through mailchimp
=> [GHENT-2019] add mailchimp link

data/events/2019-seattle.yml
=> [SEA-2019] added bronze sponsors

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Saucelabs as silver

content/events/2019-houston/sponsor.md, data/events/2019-houston.yml
=> [HOU-2019] Added VMWare as a sponsor

data/events/2019-boise.yml
=> [2019 Boise] Update sponsors

data/events/2019-jakarta.yml
=> [JKT-19] Add sponsor

data/events/2019-zurich.yml
Awright we have cloudbees on board as silver sponsor 🎉
=> [ZRH-2019] Add cloudbees as silver sponsor

content/events/2019-amsterdam/welcome.md, data/events/2019-amsterdam.yml
- Clean up welcome page
- Remove arcade sponsorship
=> [AMS 2019] - Cleanup welcome page, remove arcade sponsor

content/events/2019-minneapolis/sponsor.md, data/events/2019-minneapolis.yml
=> [MSP-2019] Add google cloud as gold and ala-carte sponsor

content/events/2019-washington-dc/location.md, content/events/2019-washington-dc/propose.md, content/events/2019-washington-dc/registration.md, content/events/2019-washington-dc/sponsor.md, content/events/2019-washington-dc/welcome.md, data/events/2019-washington-dc.yml
=> [DC-2019] We have dates, a location, and are open for business!

data/events/2019-tokyo.yml
=> [2019-Tokyo] Correct typos in sponsor IDs

content/events/2019-london/propose.md
and make the submission links more noticable
=> [LDN-2019] Add more CFP details

data/events/2019-washington-dc.yml
Removing "Deltek" and adding my LinkedIn URL.
=> [DC-2019] Update 2019-washington-dc.yml Modifying DelNegro info

content/events/2019-houston/program/dan-kirkpatrick.md, content/events/2019-houston/speakers/dan-kirkpatrick.md, data/events/2019-houston.yml
=> [HOU-2019] Adding Ignite speaker: Dan Kirkpatrick

content/events/2019-cape-town/sponsor.md
Thanks Chicago for the inspiration
=> [Cape Town 2019] Make sponsorship page nicer

content/events/2019-seattle/speakers/dawn-parzych.md
=> [SEA-2019] Update bio for dawn

content/events/2019-portland/welcome.md
I really wish I understood Hugo enough to do this right. Anyone who
wants to help me use the cfp_link content instead of duplicating it
here, that would be rad. :shrug:
=> [PDX-2019] Add a propose link to welcome page

content/events/2019-houston/location.md, content/events/2019-houston/program.md, content/events/2019-houston/program/angel-rivera.md, content/events/2019-houston/program/brad-dausses.md, content/events/2019-houston/program/eddie-zaneski.md, content/events/2019-houston/program/mike-rothman.md, data/events/2019-houston.yml
=> [HOU-2019] Added workshop prerequisites

data/events/2019-minneapolis.yml
=> [MSP-2019] Add logzio as gold sponsor

data/events/2019-sao-paulo.yml
* Added Rancher as sponsor
* Changed program by speaker requested.
=> [SP-2019] Added Rancher as sponsor

content/events/2019-salt-lake-city/program.html
Adding link to our schedule, so that we are no longer receiving a 404
=> [SLC-2019] Add link to our program to site

content/events/2019-des-moines/location.md, data/events/2019-des-moines.yml
=>  [DSM-2019] Update hotel information

content/events/2019-houston/speakers/ipsito-banerjee.md, data/events/2019-houston.yml
=> [2019-Houston] Added speaker LinkedIn URL and MicroFocus as bronze sponsor

content/events/2019-houston/sponsor.md
=> [HOU-2019] Reduced number of available bronze sponsorships

data/events/2019-philadelphia.yml
=> [DOD-PHILLY-2019] Add contrast security as platinum sponsor.

data/events/2019-campinas.yml
Add estabilis and infoq as sponsors
=> [CAMP-2019] Add estabilis and infoq as sponsors

data/events/2019-raleigh.yml
[RDU-2019] added xmatters as sponsor
=> [RDU-2019] added xmatters as sponsor

data/sponsors/taos-before-20190405.yml
The update in https://github.com/devopsdays/devopsdays-web/pull/6833 missed a file. /cc @MikeRosTX
=> Adding missing file

data/events/2019-charlotte.yml, data/events/2019-los-angeles.yml, data/events/2019-new-york-city.yml, data/events/2019-vancouver.yml, data/sponsors/sonatype-before-20190405.yml
Adding missing elements for update in https://github.com/devopsdays/devopsdays-web/pull/6835 - /cc @MikeRosTX
=> Finishing Sonatype update

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Monkeys With Buttons as bronze

data/events/2019-baltimore.yml
=> [BMORE-2019] add aws as silver sponsor

data/events/2019-seattle.yml
=> [SEA-2019] added split.io logo

data/events/2019-seattle.yml
=> [SEA-2019] add victorops

content/events/2019-cape-town/welcome.md
Forgot it in https://github.com/devopsdays/devopsdays-web/pull/6859
=> [Cape Town 2019] Add "Propose to talk" button on front page

content/events/2019-portugal/program/antonio-cobo.md
=> [PT2019] antonio cobo fix talk title

content/events/2019-zurich/conduct.md, content/events/2019-zurich/contact.md, content/events/2019-zurich/location.md, content/events/2019-zurich/program.md, content/events/2019-zurich/welcome.md, data/events/2019-zurich.yml
And remove some spurious whitespace.
=> [ZRH-2019] Add evening event to program

content/events/2019-seattle/quick-links.md
=> [SEA-2019] added link page

content/events/2019-detroit/sponsor.md
=> [DET-2019] Add platinum sponsorship

data/events/2019-washington-dc.yml
Updating my biography for DevOpsDays DC 2019 website.
=> [DC-2019] biography update

data/events/2019-raleigh.yml
[RDU-2019] added rancher as sponsor
=> [RDU-2019] added rancher as sponsor

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Google as Gold sponsor

data/events/2019-raleigh.yml
[RDU-2019] added codefresh as sponsor
=> [RDU-2019] added codefresh as sponsor

content/events/2019-seattle/speakers/jane-miceli.md, content/events/2019-seattle/speakers/jen-peck.md
=> [SEA-2019] updated twitter handles

content/events/2019-baltimore/sponsor.md
Sponsors, they have questions. We have answers!
=> [Bmore-2019] Add link to Sponsor FAQ

data/events/2019-bogota.yml
=> Bogotá-2019 Added Pagerduty Sponsor logo

content/events/2019-seattle/sponsor-info.md
=> [SEA-2019] update sponsor info

content/events/2019-houston/faq.md, content/events/2019-houston/sponsor.md, content/events/2019-houston/welcome.md, data/events/2019-houston.yml
=> [HOU-2019] Added FAQ page and Slack Channel Invite

data/events/2019-baltimore.yml
=> [Bmore-2019] Mike DelNegro joins the organizing team.

data/events/2019-portland.yml
As suggested by @bridgetkromhout  in #6815
=> [PDX-2019] Add propose link, remove speakers and schedule

data/events/2011-bangalore.yml, data/events/2012-india.yml, data/events/2014-bangalore.yml, data/events/2015-bangalore.yml, data/events/2016-bangalore.yml, data/events/2017-bangalore.yml, data/events/2018-bengaluru.yml
I investigated and Delhi 2012 was run by the same team, so I'm expanding the event group. (We'll need to revisit this if we get a different team running these in India.)
=> Including Delhi in this group

data/events/2019-kiev.yml
=> [Kyiv 2019] Linking to local site

content/events/2019-poznan/location.md, data/events/2019-poznan.yml
=> [POZ-2019] location change

data/events/2019-hartford.yml
We want to capitalize city names so they show up correctly when used.
=> [Hartford 2019] Capitalize city name

data/events/2019-amsterdam.yml
=> [AMS-2019] Add Leaseweb as recharge sponsor

data/events/2019-chattanooga.yml
Updates the nav elements so that registration and cfp proposals are open.
=> [CHA-2019] Update nav

content/events/2019-kansas-city/location.md, data/events/2019-kansas-city.yml
[KC-2019] Kansas City location page and Google Analytics slug
=> [KC-2019] Kansas City location page and Google Analytics slug

content/events/2019-columbus/contact.md, data/events/2019-columbus.yml
Need Bill Schwanitz slack reactivated
Need slack account created for Carmen Deardo
Opened both CFP and Registration.
=> [Columbus 2019] New Organizers, Registration and CFP.

data/events/2019-chicago.yml
adding repeat sponsors to Chicago website. Yay thanks Chef and F5
=> [CHI 2019] added Chef and F5 as gold

data/events/2019-kansas-city.yml
Not setting the registration end date when using a reg button causes this:
3:02:17 PM: ERROR 2019/04/16 20:02:17 Unable to locate template for shortcode 'param' in page propose
3:03:54 PM: ERROR 2019/04/16 20:03:54 theme/partials/events/cta.html template: theme/partials/events/cta.html:24:73: executing "theme/partials/events/cta.html" at <time $e.registration...>: error calling time: Unable to Cast <nil> to Time
=> [KC 2019] Need to set both dates

content/events/2019-tampa/location.md
Added hotel information for Marriott Courtyard Tampa Oldsmar
=> [TPA-2019] - Added Hotel Information

data/events/2019-buffalo.yml
=> [BUF-2019] Enable speaker menu item

content/events/2019-porto-alegre/program/jorge-leite.md
=> Fix speaker title - DevOpsDays Porto Alegre Section

data/events/2019-tampa.yml
Added Amazon as sponsor, thank you Amazon!
=> [TPA-2019] - Added Amazon as sponsor - Thank you!

data/events/2019-raleigh.yml
[RDU-2019] added netapp as sponsor
=> [RDU-2019] added netapp as sponsor

data/events/2019-washington-dc.yml
=> [DC-2019] add Chef as platinum sponsor

content/events/2019-florianopolis/sponsor.md
Adding Florianópolis 2019 Prospectus.
=> [FLN-2019] Add Sponsor Prospectus

data/events/2019-seattle.yml
=> [SEA-2019] added bronze sponsor

data/events/2019-nashville.yml
=> [bna-2019] added community sponsors
