devopsdays/devopsdays-web

- themes/devopsdays/layouts/index.html
Currently this works, but @m1keil would like something more elegant in the future. This works for now however. Connected to #34
> Fix for #34 (remove extra dash on homepage)

- README.md
- data/events/2015warsaw.yml
- data/events/2016kiel.yml
- themes/devopsdays/layouts/partials/maps.html
- wercker.yml
this should fix #58 and #35 
didn't see anything breaks with 0.15
> fixes #58 & #35

- themes/devopsdays-legacy/layouts/event/single.html
When comparing the legacy layout with the output of the devops-webby, I
found we are missing the year in the new template. This is useful when
navigating the same event or any event across multiple years as the
header did not show it.
> layouts: add year to event page header

- themes/devopsdays-legacy/layouts/event/single.html
For #108 
I'm not sure this is the "right" way to do this compared to changing the width of the div, but reducing the total size of the logos by 5px makes them 3 wide on desktop browsers.
> reduced total logo width from 100px to 95px

- data/events/2016-chicago.yml
- themes/devopsdays-legacy/layouts/event/single.html
- yyyy-city.yml
This fundamentally changes the structure of the navigation links in the event configuration file. See the sample data file for an example. The "old" style data file is still functional for backwards compatibility.
> Added offsite nav links. Fixes #76

- content/page/organizing.md
From the discussion today in Slack.
> Add section on devopsdays logo to organizing.

- content/events/sample-event/location.md
- layouts/shortcodes/event_map.html
We've already got the event lat+lon and a location name. I figured it would be nice if we used these to generate a map on each event's location page via a shortcode.
Organizers will just need to ensure their lat+lon and location (venue name) are correct in the YAML, then uncomment the event_map shortcode in location.md.
> Added event_map short code

- themes/devopsdays-legacy/layouts/partials/twitterfeed.html
This changes from the old, spam-filled search, into a twitter widget based on a whitelisted list of accounts.
This is causing weird overlap with the blue footer, which will need to be resolved.
> Change from twitter search to twitter list widget

- content/events/2016-toronto/program.md
- content/events/2016-toronto/proposals/Agile databases.md
- content/events/2016-toronto/proposals/Are YOU the Change Agent your Organization is Looking For.md
- content/events/2016-toronto/proposals/Being an introvert and at a conference not as hellish as you think it is.md
- content/events/2016-toronto/proposals/Containers will not fix your broken culture (and other hard truths).md
- content/events/2016-toronto/proposals/Devops Evolution at Nulogy.md
- content/events/2016-toronto/proposals/Feeling the burn.md
- content/events/2016-toronto/proposals/From Commit To Production And Beyond - The Continuous Delivery Pipeline.md
- content/events/2016-toronto/proposals/How Brazil's government kept us up at night.md
- content/events/2016-toronto/proposals/Public Postmortem on After Hours Maintenance Gone Awry.md
- content/events/2016-toronto/proposals/Scaling out Continuous Delivery.md
- content/events/2016-toronto/proposals/Supporting Developers Through DevOps.md
- content/events/2016-toronto/proposals/Waterboy - our robot coworker.md
- content/events/2016-toronto/proposals/Why We Threw 5 Months of Work in the Trash or How we Failed at adopting DevOps.md
- content/events/2016-toronto/proposals/Why we should be excited about Azure Stack.md
- content/events/2016-toronto/proposals/dotfiles.CI.md
- content/events/2016-toronto/proposals/keynote.md
The new site is now in sync with the live site.
> Migrate Toronto 2016 program to new site.

- themes/devopsdays-legacy/layouts/index.html
- themes/devopsdays-legacy/layouts/partials/footer.html
- themes/devopsdays-legacy/layouts/partials/future.html
- themes/devopsdays-legacy/layouts/partials/past.html
- themes/devopsdays-legacy/static/css/style.css
Please note two bugs this introduces that will need to be fixed later:
1. The "past" footer is still data-driven. This means that we need to migrate the past events to the new format. Or we hard-code them into the template and have to manually move events after they occur. As this entire UX in the footer is being revamped, I think we will do the latter. This is tracked in #146
2. The year "2016" is hard-coded into the headline on the "future.html" partial for now :) This is tracked in #147
> Rework the past and future bottom footers

- data/events/2016-chicago.yml
- themes/devopsdays-legacy/layouts/partials/event_header.html
When I refactored out the event_header partial, I didn't bring over the offsite link capability. This commit fixes this. The commit that broke it was dfc9062. This was identified in #76 by @davidasnider.
> Fix event header to re-implement offsite links. Fixes #76 (again)

- themes/devopsdays-legacy/layouts/partials/future.html
Added code to determine current year and account for future events in the following year.
See issue #147
> Fix hard-coded year.

- data/events/2016-portland.yml
- layouts/shortcodes/list_organizers.html
- yyyy-city.yml
- New YAML key for "team_members".
- Supports name (required), twitter (optional, with or without @),
and employer (optional).
- Maintains compatibility with simpler "team" list method.
See issue #75
> Support adding more info for organizers

- themes/devopsdays-legacy/layouts/partials/event_footer.html
- themes/devopsdays-legacy/static/css/style.css
Following up on the discussion in #88 this adds CSS borders and specifies the dimensions for the sponsor logos (legacy theme).
`r?` @mattstratton
> add borders and force dimensions for logos

- themes/devopsdays-legacy/layouts/partials/past.html
The year in the past events looks terrible and makes it wrap a lot. Presumably we could replace it if we need it in a re-design, but for now it would be nice for it to not be cluttering a space we're working in.
> Remove year from the past events.

- themes/devopsdays-legacy/layouts/_default/single.html
The Past and Future are showing up twice because they are in the past / future partials as well as the _default layout - for #207
> remove duplicate header

- README.md
> Update README with large file guidelines

- layouts/shortcodes/event_logo.html
Changed the CSS style on the logo from `width: 90%` to `max-width`, so that smaller logos are not upscaled.
> fix for stretchy logos

- data/events/2016-ohio.yml
- themes/devopsdays-legacy/layouts/partials/future.html
It's somewhat sloppy, and has the year 2016 hardcoded into it for now, but it works. This removes the issue with the "events on the same date" (only for future footer; the issue still exists for past events for now) and it also takes care of the "year in quotes" issue.
Resolves #247
Resolves #246
Resolves #233
> Refactor future footer

- README.md
- config.toml
- wercker.yml
Hey, @mattstratton - I think this is where we want to change the URLs before the DNS change.
> Change URL for cutover

- themes/devopsdays-legacy/layouts/partials/past.html
Reverts devopsdays/devopsdays-web#279
Since the past has been bulk-migrated, although cosmetic issues remain, I don't think we need to say this any longer.
> Revert "Past under construction"

- data/events/2016-amsterdam.yml
- themes/devopsdays-legacy/layouts/partials/event_footer.html
- yyyy-city.yml
Introduces a new option: `sponsor_link_ask' to have the ability to turn off the "Become a XXX Sponsor!" feature. 
As this is an "opt_in" feature, as "it doesn't change default behavior", only those events that want to use the option will see its benefit.
> Ability to remove sponsor link form "Become a XXX Sponsor!"

- README.md
I think this covers the ulimit issue well enough to let someone get started.
> ulimit, ugh.

- content/events/2016-kansascity/welcome.md
Heads up to @barkerd427 - there's an open issue about this (https://github.com/devopsdays/devopsdays-web/issues/259) but for now, you don't want it to look like this (Kansas City twice in one line):
> Fixes display issue

- content/events/2016-london/program/test-user.md
- data/speakers/2016/london/test-user.yml
- themes/devopsdays-legacy/layouts/talk/single.html
There's an issue right now where "past" events need their year set as a non-string, but "current" events need it as a string. This raises hell on the template for a talk. This fixes that.
> Fix talk page

- content/events/2016-amsterdam/program.md
- content/events/2016-amsterdam/propose.md
Initial draft of program.
This is a WIP hence why nav elements are still disabled.
> devopsdays Amsterdam 2016 - Initial Draft of program

- content/events/2016-kiel/welcome.md
- data/events/2016-kiel.yml
- data/events/2016-seattle.yml
Note for https://github.com/devopsdays/devopsdays-web/issues/33 - right now it's not possible to have two events with the same start date show up in the "past" footer. Only the alphabetically-last one shows up.
I worked around this by changing Kiel's start date to a day earlier. This is terri-bad, but gives the display we want. That commit should be reverted when this is fixed.
> Moving Kiel and Seattle to past

- content/events/2016-amsterdam/program.md
A two column/two page was not looking optimal. Mostly as on day #1 we have a separate track on security. 
Its still in a WIP (all program pages will be added in the next 24 - 48 hours), but no nav to the actual site for now. 
Yvo
> devopsdays Amsterdam 2016 -  Single Column Program

- data/events/2016-amsterdam.yml
Sponsor is bronze, not silver.
> Adjust sponsor level for Workiva

- content/events/2016-amsterdam/program/will-button.md
- content/events/2016-amsterdam/sponsor.md
Moves the prospectus out of the github repo (addresses #401).
> devopsdays 2016 AMS - Move prospectus into a S3 bucket

- content/events/2016-nashville/sponsor.md
Repairs a stray URL that made its way in via https://github.com/devopsdays/devopsdays-web/pull/447.
> [BNA-2016] removing stray URL from sponsor

- content/events/2016-amsterdam/registration.md
* Registration page had a double (unclosed) `<div>` that was causing havoc.
> devopsdays 2016 AMS - Fix Registration Page

- content/page/organizing.md
For my first Ignite, I asked the organizer 15 minutes before stage time
where I'd be able to see my notes.  I was then informed that Ignite talks
don't get Presenter Notes, which was quite a surprise.
Letting the Ignite presenters know this ahead of time, as well as reminding
them on the day of, should help eliminate future surprises.
Also mentioned that animations and videos do not work either
> Remind Ignite presenters that there are no presenter notes

- content/events/2016-nashville/propose.md
- data/events/2016-nashville.yml
This PR adds the necessary text for proposing a talk to DevOpsDays BNA.
/cc @jcockhren
> [2016-BNA] adding propose info to DevOpsDays website

- content/events/2016-singapore/welcome.md
The upper case 'S' letter prevented the redirect to take effect.
Now the redirect from `2016-singapore/` to `2016-singapore/welcome`
works as expected.
> SIN-16 welcome: Fix redirect to welcome page

- themes/devopsdays-responsive/layouts/index.html
I found myself accidentally scrolling to the lower right a lot and then wondering where the sorted-by-date, not-all-even-on-map event list was. This is the minimum viable "fix that". /cc @kmugrage @mattstratton
> Adds link to future & past events where expected.

- themes/devopsdays-responsive/layouts/partials/head.html
The logic to override, or to specify a custom title, per page was already set in the template.
However the Params was improperly used as all Params have to be lower case (per: https://gohugo.io/templates/variables/#page-params). In this case it was `.Params.Heading` instead of `.Params.heading`.
I've added two spaces to it for readability. To anyone that now comes across head.html they'll see that it can either be set by Params.heading or .Title; both can be set in side of the md files in content/
This, to me, fixes #259 as it provides non-breaking change (no one is using "heading" in content in their .md file) to those that want to set custom titles.
> Fix head template to allow custom titles

- themes/devopsdays-responsive/layouts/speakers/single.html
- themes/devopsdays-responsive/layouts/talk/single.html
Add a hugo parameter check prior to displaying twitter handle. By default if the parameter is not set (0 byte content) it pass the if statement. (ref: https://gohugo.io/templates/go-templates/#conditionals)
This fixed #366
> Don't display Twitter "@" when handle isn't set

- content/events/2016-baltimore/welcome.md
- content/events/2016-bangalore/welcome.md
- content/events/2016-boise/welcome.md
- content/events/2016-boston/welcome.md
- content/events/2016-capetown/welcome.md
- content/events/2016-chicago/welcome.md
- content/events/2016-dallas/welcome.md
- content/events/2016-detroit/welcome.md
- content/events/2016-ghent/welcome.md
- content/events/2016-kansascity/welcome.md
- content/events/2016-madison/welcome.md
- content/events/2016-nashville/welcome.md
- content/events/2016-newyork/welcome.md
- content/events/2016-newzealand/welcome.md
- content/events/2016-ohio/welcome.md
- content/events/2016-oslo/welcome.md
- content/events/2016-philadelphia/welcome.md
- content/events/2016-portland/welcome.md
- content/events/2016-portoalegre/welcome.md
- content/events/2016-raleigh/welcome.md
- content/events/2016-siliconvalley/welcome.md
- content/events/2016-singapore/welcome.md
- content/events/sample-event/welcome.md
This changes the front page for most current events only in that it updates the spacing.
I checked with @peterjshan about the Philly content update.
> Moving table to div for improved layout.

- content/events/2016-amsterdam/welcome.md
This addresses #533 in which the new theme recommends using CSS over tables to create your website. 
This is AMS successfully transitioned to the new format. 
* `welcome.md` gets an overhaul
> devopsdays 2016 AMS - Convert welcome.md from tables to CSS. CSS all the things

- content/events/2016-amsterdam/conduct.md
- content/events/2016-amsterdam/contact.md
- content/events/2016-amsterdam/location.md
- content/events/2016-amsterdam/program.md
- content/events/2016-amsterdam/proposals.md
- content/events/2016-amsterdam/propose.md
- content/events/2016-amsterdam/registration.md
- content/events/2016-amsterdam/speakers.md
- content/events/2016-amsterdam/sponsor.md
- content/events/2016-amsterdam/workshops.md
* All pages but welcome (see #536) now use `heading` option.
> devopsdays 2016 AMS - Set page titles

- content/events/2016-amsterdam/program.md
- content/events/2016-amsterdam/welcome.md
- content/events/2016-amsterdam/workshops/andrew-farley.md
- content/events/2016-amsterdam/workshops/dave-van-herpen.md
- content/events/2016-amsterdam/workshops/philipp-krenn.md
- content/events/2016-amsterdam/workshops/remi-bergsma.md
- data/events/2016-amsterdam.yml
* Fix twitter link in new `welcome.md`
* Remove underline in Security Talk on Melanie's talk. 
* Fix page title for Remi's talk
* Fix Arjan -> Arjen
* Remove trailing `"` from two pages
* Remove extra `<`
> devopsdays 2016 AMS - Fix minor typos

- README.md
Please don't merge this until @mattstratton has a chance to confirm it actually worked :)
> Add persistent sysctl changes to documentation

- themes/devopsdays-responsive/layouts/partials/past.html
- themes/devopsdays-responsive/layouts/speakers/single.html
- themes/devopsdays-responsive/layouts/talk/single.html
The chomp function doesn't work quite as expected in 0.16. Per https://discuss.gohugo.io/t/errors-with-type-template-html-should-be-string-with-hugo-0-16-0/3470/4?u=mattstratton, i have wrapped the chomp stuff and it seems to work fine now under 0.16.
This handles the defect mentioned in #543
> Add string function to work around hugo 0.16 bug

- wercker.yml
So it seems that the way I was calling/defining the version of Hugo in the build config was being ignored, so it was building to latest. This is making the site use hugo 0.16 in production, which causes some errors. This should fix that.
> Fix string in hugo version in build

- content/events/2016-washington-dc/location.md
- content/events/2016-washington-dc/sponsor.md
- content/events/2016-washington-dc/welcome.md
- data/events/2016-washington-dc.yml
This advice in content/data/2016-washington-dc.yml appears to be
incorrect with regard to the quotes:
year: "2016" # The year of the event. Make sure it is in quotes.
With quotes there, the event does not appear in the "past" partial.
Without quotes, it does. Thus I've removed the quotes, but feel free to
tell me how to fix this another way if that breaks anything.
> [DC 2016] Closing out DC 2016

- content/events/2016-amsterdam/welcome.md
- data/events/2016-amsterdam.yml
* Updated `status` to past
* Updated `year` to not be in quotes (to show up in past events)
* Hid registration link in navigation & on site
* Changed text thanking attendees
> devopsdays 2016 AMS - Closing the event

- content/events/2016-portland/propose.md
CFP is closed. Removing the submission button.
> PDX 2016: Remove CFP proposal button

- themes/devopsdays-responsive/layouts/talk/single.html
LinkTitle defaults to Title unless linktitle is specified in the md file
> allow special/international characters in speaker name

- themes/devopsdays-responsive/layouts/partials/sponsors.html
- yyyy-city.yml
Got around to addressing the need to control the sponsor level CTA per issue #93 
Basically using $.Scratch to setup a counter, so we can count how many sponsors get iterated per level, then comparing it to the level "max" property (if it exists or is non-zero)
> Max sponsors

- README.md
- data/events/2016-chicago.yml
- themes/devopsdays-responsive/layouts/partials/event_header.html
- themes/devopsdays-responsive/layouts/partials/future.html
- themes/devopsdays-responsive/layouts/partials/past.html
- themes/devopsdays-responsive/layouts/partials/upcoming_headline.html
This PR adds support for the (optional) `displayname` parameter in the event data file. If the `displayname` is set, this is what will be shown when the event is referenced (on the navigation menus, as well as on the main headers for the event page).
You should use the `displayname` parameter if your city has non-URL friendly characters, such as accented characters or spaces (i.e., "Zürich" or "Salt Lake City"). The name parameter should be set as `2016-zurich` or `2016-salt-lake-city` for example. Please also make sure that the "city" parameter is set with non-accented or space characters in this case as well.
> Add displayname functionality

- content/events/2016-philadelphia/welcome.md
Much like https://github.com/devopsdays/devopsdays-web/pull/780, this removes a misleading link (as proposals are closed). CCing @peterjshan for approval.
> Removing link to closed proposals.

- content/events/2017-baltimore/conduct.md
- content/events/2017-baltimore/contact.md
- content/events/2017-baltimore/location.md
- content/events/2017-baltimore/program.md
- content/events/2017-baltimore/sponsor.md
- content/events/2017-baltimore/welcome.md
The conference was postponed until 2017.
This change makes all of the old 2016 URLs redirect to the 2017 pages.
For example, /events/2016-baltimore/welcome/ now redirects to /events/2017-baltimore/welcome/.
> Add aliases for Baltimore 2016

- themes/devopsdays-responsive/layouts/speakers/single.html
- themes/devopsdays-responsive/layouts/talk/single.html
Still doesn't handle special characters. Should fix via event slug. But at least this band-aids the current badness with slightly less badness.
Specifically, this allows speaker data to show up on speaker pages and talk pages if the city has a multi-word name. It doesn't introduce regression for single-word names as far as my checks show.
> Allowing multiple-word cities to work with speakers/talks

- content/events/2016-ghent/welcome.md
I moved the Eventbrite iframe down in the content to make sure everyone reads the note about the TVA id *before* they start booking tickets.
> Better signalling of the TVA id *before* ordering the tickets

- content/page/contact.md
- layouts/shortcodes/list_core.html
Per discussion with the core team, redefining roles and add @mattstratton plus @phrawzty.
> Updating core team

- data/events/2016-portland.yml
Alas, @jyee - because of the bug in https://github.com/devopsdays/devopsdays-web/issues/247 this is necessary.
> Ensure Portland shows on past events

- themes/devopsdays-responsive/layouts/partials/footer.html
DO NOT MERGE until #877 is resolved.
1. Change email envelope icon to point to “Contact” page instead of Google Group
2. Remove LinkedIn group link/icon
3. Add RSS icon pointing to feed
Fixes #859
> Update footer links/icons

- .gitignore
I always have to copy-n-paste out ulimit fixes out of the README
I've added a local bash script that will do this for me but not sure if
everyone wants this in the repo.
Here's what the script contains, I'm happy to add it if there's
interest:
```
#!/bin/bash
sysctl -w kern.maxfiles=65536
sysctl -w kern.maxfilesperproc=65536
ulimit -n 65536 65536
```
> Ignore a script that updates the ulimit

- layouts/shortcodes/list_core.html
Clarify that @mattstratton leads the devopsdays.org web team.
> clarify Matt's web team role

- CONTRIBUTE.md
- README.md
This is a first pass at addressing #879 (CONTRIBUTE.md). I *basically* just split out the various Contrib-related portions to their own document. I say basically, because I also made some improvements (hopefully) to the documentation, too. 😄
> move contribution info to CONTRIBUTE.md; #879

- themes/devopsdays-responsive/layouts/partials/map.html
This still doesn’t fix the mixed-mode error, but it’s the way Google says to do it.
> Set google maps url to SSL version

- content/events/2016-chicago/contact.md
- layouts/shortcodes/email_organizers.html
- layouts/shortcodes/email_proposals.html
The `email_proposals` and `email_organizers` shortcodes now take an optional parameter of “subject”, which will be the subject of the email.
See the Contact page for 2016-Chicago for an example.
Fixeds #262
> Add subject capability to email shortcodes

- themes/devopsdays-responsive/layouts/index.html
Moving embedded tweets to @devopsdays.
* No longer requires data-widget-id
* Now can be maintained by all core organizers
> Moving embedded tweets to @devopsdays.

- data/events/2012-newyork.yml
- data/events/2013-newyork.yml
- themes/devopsdays-responsive/layouts/partials/future.html
- themes/devopsdays-responsive/layouts/partials/past.html
Do not merge this yet - the /events page is displaying oddly,and it’s somehow due to the two New Yorks. If you change the startdate of New York (Winter) to be in 2012, everything lays out properly.
Fixes #882
> Refactor past and future to use date fields

- utilities/add_speakers.sh
- utilities/examples/speakers/speaker-full-name.md
Adding `linktitle` per https://gohugo.io/templates/variables/ instead of only having `title`, because of the possibility of special characters in the title. This is set and working correctly for http://www.devopsdays.org/events/2016-chicago/program/abejide-ayodele/.
> Speakers can have special characters in names.

- themes/devopsdays-responsive/layouts/talk/single.html
How this works (based on discussion in https://github.com/devopsdays/devopsdays-web/issues/708):
Previously, it was checking to see if the speaker-name filename of the speaker data file matched the urlized "Speaker Name" in the title frontmatter of the talk file - nothing was using linkdata.
Now, it's checking to see if the speaker-name filename of the speaker data file is _in_ the linkdata (which may be the urlized "Speaker Name" in the frontmatter of the talk file, but can also be a collection of as many speaker names as is desired), and all their bios will show up.
Example:
filename:
content/events/2016-city/program/name-one-name-two.md
frontmatter:
title = "Name One & Name Two"
linktitle = "name-one, name-two"
aliases = ["/events/2016-newyork/program/name-one/", …
> Multiple speakers

- CONTRIBUTING.md
- utilities/make_new_event.sh
Some basic doc cleanup based on me trying to get this working locally. 
Note, for the `make_new_event.sh` changes, I changed the copy locations based on running the script from the top level directly, as the `cp` destinations were correct if that's the place we are assuming the script is run from.
Please let me know if you require any alterations
> Script cleanup

- themes/devopsdays-responsive/layouts/partials/head.html
This shouldn’t break anything. But if it does, it’s just commented out in `themes/devopsdays-responsive/partials/head.html`
fixes #969
> remove base href tag

- content/events/2016-nashville/propose.md
This PR adds a note to the Propose page for 2016-BNA that the CFP has ended.
> [2016-BNA] Removing CFP for event

- data/events/2016-raleigh.yml
* Adding link to volunteer page as discussed with @jzb in https://github.com/devopsdays/devopsdays-web/pull/999.
* Updating team list so they can add Twitter handles and employers as desired.
> Added link to volunteer page; updated team list.

- themes/devopsdays-responsive/layouts/event/single.html
- themes/devopsdays-responsive/layouts/partials/event_metadata.html
- utilities/examples/yyyy-city.yml
Howdy!
This change puts in the basics for JSON-LD metadata on an event page, with
a little bit of logic for if the city has been duplicated into the location.
Concatenating the image URL together took far longer than I want to admit.
Are there other types of metadata that y'all would want included?  If the
address was available in the event yaml, that might surface up better in 
search results?
Example output on what would be https://www.devopsdays.org/events/2016-chicago/welcome/:
```
<script type="application/ld+json">
{
"@context": "http://schema.org",
"@type": "ExhibitionEvent",
"name": "DevOpsDays Chicago 2016",
"startDate": "2016-08-30",
"endDate": "2016-08-31",
"url": "https://devopsdays.org/events/2016-chicago/welcome/",
"image": …
```
> Add basic structured metadata to event pages for Google

- data/events/2016-nashville.yml
This commits adds NetApp as a silver sponsor to the 2016 DevOpsDays Nashville conf.
> [2016-BNA] Adding NetApp as sponsor

- utilities/create_sponsors.sh
This is useful when storing files on Google Drive for example:
~/Google\ Drive/DOD/sponsors/example.png
The whitespace issue hit me when I was dragging a file from Google Drive onto the terminal to set the logo path – the script just crashed  :collision:
> create_sponsors.sh: Support logo paths with whitespace

- data/events/2016-cuba.yml
The US Embargo does not permit U.S. companies to sponsor conferences in Cuba at this time.
> Remove Chef as Honorary Sponsor of Havana

- content/events/2016-nashville/program/nathen-harvey.md
It's "Nathen" with an "e" not "Nathan" with an "a".
* The latter is like almost every other Nathan on the planet.
* The former is my father's attempt to ensuring all of his children have
globally unique identifiers.
> [2016-nashville] Correct the spelling of my name.

- hugoserver.ps1
> Add powershell script for dockering all the things

- content/events/2016-nashville/program/stephen-yeargin.md
I had this way, way wrong. A better stat:
>Colour (color) blindness (colour vision deficiency, or CVD) affects approximately 1 in 12 men (8%) and 1 in 200 women in the world.
Source: http://www.colourblindawareness.org/colour-blindness/
/cc @jfryman
> [2016-Nashville] Fix stat on Ignite talk

- content/events/2016-nashville/program.md
- content/events/2016-nashville/program/andrew-clay-shafer.md
Due to some scheduling conflicts, this PR updates our schedule to swap out Keynotes on Nov 10/11.
> [2016-BNA] Swapping Keynotes due to scheduling conflicts

- data/events/2016-nashville.yml
This PR updates the sponsor list for Nashville to add Comcast as a WiFi sponsor in the event.
> [2016-BNA] Adding Comcast as WiFi sponsor

- layouts/shortcodes/list_core.html
Adding Mike Rosado (@MikeRosTX) to the core team listing, as we invited him to the core team and he accepted!
> Add Mike to core team

- appveyor.yml
- config.toml
- layouts/shortcodes/cfp_dates.html
- layouts/shortcodes/email_organizers.html
- layouts/shortcodes/email_proposals.html
- layouts/shortcodes/event_end.html
- layouts/shortcodes/event_link.html
- layouts/shortcodes/event_location.html
- layouts/shortcodes/event_logo.html
- layouts/shortcodes/event_map.html
- layouts/shortcodes/event_start.html
- layouts/shortcodes/list_organizers.html
- themes/devopsdays-responsive/layouts/partials/event_header.html
- themes/devopsdays-responsive/layouts/partials/event_metadata.html
- themes/devopsdays-responsive/layouts/partials/googleanalytics.html
- themes/devopsdays-responsive/layouts/partials/sponsors.html
- themes/devopsdays-responsive/layouts/shortcodes/program_entry.html
- themes/devopsdays-responsive/layouts/speakers/single.html
- themes/devopsdays-responsive/layouts/talk/single.html
Previously the `File.Path` property would use OS dependant path seperator, back
slash on Windows and forward slash on *nix and Mac.  However as we are parsing
the event slug based on a path splitting this is problematic.
This commit changes the path splitting character to a Site level parameter which
can be changed prior to building via Hugo. The default value should be set to
`/` otherwise all of the building automation will fail, amongst other things.
A later commit will add documentation around this configuration item.
> (GH989) Fix building Hugo website on Windows

- data/events/2016-paris.yml
- data/events/2016-sydney.yml
- data/events/2016-warsaw.yml
- data/events/2017-amsterdam.yml
- data/events/2017-austin.yml
- data/events/2017-baltimore.yml
- data/events/2017-charlotte.yml
- data/events/2017-chicago.yml
- data/events/2017-minneapolis.yml
- data/events/2017-moscow.yml
- data/events/2017-paris.yml
- data/events/2017-portland.yml
- data/events/2017-salt-lake-city.yml
- data/events/2017-seattle.yml
- data/events/2017-toronto.yml
- data/events/2017-zurich.yml
- themes/devopsdays-responsive/layouts/partials/cfp.html
- themes/devopsdays-responsive/layouts/partials/future.html
- themes/devopsdays-responsive/layouts/partials/map.html
- themes/devopsdays-responsive/layouts/partials/sponsors.html
- themes/devopsdays-responsive/layouts/partials/upcoming_headline.html
- utilities/examples/yyyy-city.yml
The reason this was worth doing is that manually setting an event to "past" in a timely fashion is annoying to have to remember.
I think I've corrected all the places that were using this parameter. I've also corrected the data file for the template (and for upcoming events - while not strictly speaking necessary, might as well work cleaner). 
There are a few subtle tradeoffs - I went into some detail in the commit messages.
I'd appreciate @mattstratton taking a look since this is a change with some scope to it.
> Deprecate the status: parameters (current & past)

- themes/devopsdays-responsive/layouts/partials/map.html
- End dates only need month if it differs from the start date month
- One-day events only need to show the one day
This fixes https://github.com/devopsdays/devopsdays-web/issues/137.
> Adding logic to display start+end dates.

- data/events/2017-amsterdam.yml
Since our CFP isn't officially open we should not have this link public yet. The page which people land on is also not up to date with how we handle proposals yet.
> We need to hide the propose page for Amsterdam

- utilities/examples/sample-event/propose.md
I wrote new language for 2016 and a number of events (aside from Minneapolis) adapted it. I'm now ready to consider this the new standard. Feedback welcome. I'll merge this in a day or two after folks who want to weigh in have done so.
- I'm clarifying that people don't propose Open Space during the CFP
- I'm clarifying the inclusivity and desire for both local voices and non-pitchy proposals (and recommending sponsorship instead, for product demos).
- I'm removing language that commits an event to something they might not have, like single-track.
- While adding guidelines, I'm removing the label of "rules".
> Updating sample proposal language.

- content/events/2017-stockholm/sponsor.md
When merging the other Stockholm changes, the unclosed `<br />` tag snuck in again. This fixes that.
> Fix unclosed br tag in stockholm sponsor file

- utilities/make_new_event.sh
Using `utilities/make_new_event`, when not entering a value for the year, it displays that it will use `2017`, but creates the event as `2016`.  
```
$ ./make_new_event.sh
Enter your event year (default: 2017):
Enter your city name: Cape Town
Enter your devopsdays event twitter handle (defaults to devopsdays): devopsdayscpt
$ git status
content/events/2016-cape-town/
data/events/2016-cape-town.yml
```
Updated the bash scrip to fix this.
> [Scripts] Changing the default to 2017

- content/page/sponsor.md
* More than 40 events happened in 2016
* Full payment is a pre-requisite for any sponsor benefits
* Not every DevOpsDay records talks
> [General Update - Sponsorship] Clarify some things on the sponsorship page:

- data/events/2017-amsterdam.yml
- data/events/2017-atlanta.yml
- data/events/2017-austin.yml
- data/events/2017-baltimore.yml
- data/events/2017-beijing.yml
- data/events/2017-cape-town.yml
- data/events/2017-charlotte.yml
- data/events/2017-chicago.yml
- data/events/2017-dallas.yml
- data/events/2017-denver.yml
- data/events/2017-detroit.yml
- data/events/2017-hartford.yml
- data/events/2017-indianapolis.yml
- data/events/2017-minneapolis.yml
- data/events/2017-moscow.yml
- data/events/2017-ohio.yml
- data/events/2017-paris.yml
- data/events/2017-portland.yml
- data/events/2017-salt-lake-city.yml
- data/events/2017-sao-paulo.yml
- data/events/2017-seattle.yml
- data/events/2017-stockholm.yml
- data/events/2017-toronto.yml
- data/events/2017-vancouver.yml
- data/events/2017-washington-dc.yml
- data/events/2017-zurich.yml
- utilities/examples/yyyy-city.yml
Adding this element to the event yaml (and template for the event yaml) in preparation for using it.
> Add twitter handles to upcoming events & template.

- content/events/2017-zurich/registration.md
We added a workaround url into the registration page as it some time seems that the devopsdays.org rocketscript js intervenes with our javascript snippet.
> [ZRH-2017] Added workaround URL in case of payment page problems

- data/events/2017-amsterdam.yml
- data/events/2017-atlanta.yml
- data/events/2017-austin.yml
- data/events/2017-baltimore.yml
- data/events/2017-beijing.yml
- data/events/2017-charlotte.yml
- data/events/2017-chicago.yml
- data/events/2017-dallas.yml
- data/events/2017-denver.yml
- data/events/2017-detroit.yml
- data/events/2017-indianapolis.yml
- data/events/2017-istanbul.yml
- data/events/2017-minneapolis.yml
- data/events/2017-moscow.yml
- data/events/2017-portland.yml
- data/events/2017-salt-lake-city.yml
- data/events/2017-seattle.yml
- data/events/2017-stockholm.yml
- data/events/2017-tokyo.yml
- data/events/2017-toronto.yml
- data/events/2017-vancouver.yml
- data/events/2017-zurich.yml
This adds the line necessary to resolve https://github.com/devopsdays/devopsdays-web/issues/1499#issuecomment-277351274. tl;dr: the new theme uses a version of an event's logo which must be square; in this variable, it's defined as to what it's called. (Makes it much easier to use it.)
> Adding logo square for new theme to yaml.

- data/events/2017-vancouver.yml
Reverts devopsdays/devopsdays-web#1682
Sorry for the miss! Fixed.
> Revert "Revert "[VAN-2017] adding Kyle to organizers list""

- content/events/2017-paris/welcome.md
- data/events/2017-paris.yml
* Add date for the October "Rex" event, like last year.
* Update the Welcome page (basically the same as last year).
* Adjust the long/lat ever so slightly (it's actually on the venue now).
* Remove old employer for an organiser.
* Link the CoC.
* Fix Twitter handle.
* Fix email addresses.
`r?` @jooooooon
> [paris-2017] add date and update welcome page

- data/sponsors/acesinc.yml
- data/sponsors/bookerdimaio.yml
- data/sponsors/cloudpassage.yml
- data/sponsors/columntech.yml
- data/sponsors/fearless.yml
- data/sponsors/ns1.yml
- data/sponsors/opsgenie.yml
- data/sponsors/pivotal.yml
- data/sponsors/puppet.yml
- data/sponsors/que-technology-group.yml
- data/sponsors/redhat.yml
- data/sponsors/sdtp.yml
* @acesinc
* @bookerdimaio
* @cloudpassage
* @columnit
* @fearlesssol
* @nsoneinc
* @opsgenie
* @pivotal
* @puppetize
* @quetechnology
* @redhatsoftware
* @softwaredeftalk
> [Baltimore-2017] Add twitter handles for sponsors

- data/events/2017-paris.yml
All devopsdays events use official @devopsdays.org email contact addresses.
cc @jooooooon @bridgetkromhout
> [paris-2017] standardise the contact email address

- themes/devopsdays-responsive/layouts/partials/future.html
This prevents the past events from overlapping the future events.
Resolves #1833
> Increase the height of the future events div

- data/events/2017-washington-dc.yml
> [DC-2017] "CAVA" should be uppercase

- data/events/2017-atlanta.yml
Twitter is not a person :)
Remember, the names of people on the organizer page must be real people.
Also, trying to get the twitter handle to show up on the page this way is going to go really south in the new theme :)
> [ATL-2017] Remove "twitter" as an organizer for Atlanta

- .gitignore
- CONTRIBUTING.md
- config-windows.toml
- config.toml
When the `config.toml`is in `.gitignore`, it means that folks who do a `git pull` won't get any updates. This is going to be a big problem when we release the new theme.
However, my concern is with people making changes to this file. We need to watch for changes on this file before merging PR's.
I need a couple 👍  from maintainers before this gets merged.
> Remove config.toml from .gitignore

- data/events/2017-atlanta.yml
Atlanta's coordinates were in Chicago.
> [ATL-2017] fixed Atlanta coordinates

- content/events/2017-baltimore/welcome.md
- data/events/2017-baltimore.yml
These are the correct dates so that the event will show up properly in
the archive.
Had to munge them because of #1949
This resolves #1951
> Reset Baltimore dates

- CONTRIBUTING.md
Fixes #1868
This change, when implemented, will update the contributing guidelines based upon the new theme. 
This PR should not be merged until we release the new `devopsdays-theme` into this repo.
This change is open for comments/feedback from the @devopsdays/website team please :)
> Update CONTRIBUTING.md for new theme

- content/events/2017-paris/welcome.md
The default style for `##` auto-capitalises each word, which looks horrendous in French. 😉  This makes it hurt less.
`r?` @jooooooon
> [Paris-2017] adjust style to avoid auto-caps

- content/events/2017-atlanta/welcome.md
This keeps the image from being too huge
> [ATL-2017] Change Atlanta to use logo shortcode

- content/events/2017-denver/welcome.md
- data/events/2017-amsterdam.yml
- data/events/2017-atlanta.yml
- data/events/2017-denver.yml
- data/events/2017-istanbul.yml
- data/events/2017-minneapolis.yml
- data/events/2017-oslo.yml
- data/events/2017-salt-lake-city.yml
- data/events/2017-seattle.yml
- data/events/2017-stockholm.yml
- data/events/2017-toronto.yml
- data/events/2017-vancouver.yml
- data/events/2017-washington-dc.yml
- data/events/2017-zurich.yml
For events that have open CFP's and registrations, i have updated their data files which will make the CTA buttons display on their event pages.
> Add CFP and Registration keys for events

- utilities/add_new_event.sh
Couldn't get the add_new_event script to work on 16.04; turned out the SEDCMD wasn't used everywhere in the script.
> Fix broken sed commands on ubuntu

- data/sponsors/opsgenie-zurich-2017.yml
Corrected URL of sponsor opsgenie-zurich-2017, HTTP:// prefix was missing.
> [ZRH-2017] Corrected URL of sponsor opsgenie-zurich-2017

- gulp/tasks/copy-static-files.js
- gulp/tasks/responsive-images.js
- gulp/tasks/revision.js
- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/layouts/events/single.html
- themes/devopsdays-theme/layouts/index.html
- themes/devopsdays-theme/layouts/partials/about.html
- themes/devopsdays-theme/layouts/partials/events/cta.html
- themes/devopsdays-theme/layouts/partials/footer.html
- themes/devopsdays-theme/layouts/partials/future.html
- themes/devopsdays-theme/layouts/partials/map.html
- themes/devopsdays-theme/layouts/partials/past.html
- themes/devopsdays-theme/layouts/partials/speaking.html
- themes/devopsdays-theme/layouts/partials/sponsors.html
- themes/devopsdays-theme/layouts/section/events.rss.xml
- themes/devopsdays-theme/layouts/section/speaking.rss.xml
- themes/devopsdays-theme/layouts/speakers/single.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.3.0...1.4.0)
**Implemented enhancements:**
- Add scripts for managing theme [\#416](https://github.com/devopsdays/devopsdays-theme/issues/416)
- Newly created events with no speakers return an error [\#426](https://github.com/devopsdays/devopsdays-theme/issues/426)
- speaker pics with .jpeg extenstion dropped from site [\#425](https://github.com/devopsdays/devopsdays-theme/issues/425)
- Replace use of $.Now.Format [\#407](https://github.com/devopsdays/devopsdays-theme/issues/407)
> Updating theme to 1.4.0

- content/events/2017-minneapolis/welcome.md
The sort order in the left sidebar is wrong again (that mapping issue). Trying to trigger a build.
> Trivial change for build

- content/events/2017-boston/speakers.md
- content/events/2017-brasilia/speakers.md
- content/events/2017-kansascity/speakers.md
- content/events/2017-philadelphia/speakers.md
- content/events/2018-kiel/speakers.md
These files aren't used yet, and now they'll be added when the event uses the script to add speakers (see https://github.com/devopsdays/devopsdays-web/pull/2125).
> Removing speakers files that aren't used yet

- content/events/2017-chicago/index.md
changed the welcome page to have the logo on the right instead of the top.
If people like this layout, we can adjust the default generated page to look more like this.
> [2017-CHI] Small cosmetic changes to Chicago homepage

- data/events/2016-kiel.yml
This is to work around the bug described in https://github.com/devopsdays/devopsdays-theme/issues/444.
> Different date to work around past events display bug.

- utilities/README.md
Sponsor updates only need to happen once if people are using the shared sponsor entry. They will affect all future events but not past ones.
> Clarifying sponsor updates

- content/events/2016-washington-dc/welcome.md
To help Googlers who are ending up on the '16 page.
> [DC 2017] link 2016 welcome page to 2017

- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/layouts/partials/events/cta.html
- themes/devopsdays-theme/theme.toml
- CTA buttons don't change color with custom masthead [\#456](https://github.com/devopsdays/devopsdays-theme/issues/456)
> Updating theme to 1.6.1

- static/_redirects
I'm not positive this is the right way to fix https://github.com/devopsdays/devopsdays-web/issues/2202 but since a local test doesn't cover the legacy URLs I'm not sure how to check.
> Fix old upload links

- content/blog/announcing-devopsdays-mountainview-2011.md
- content/blog/boston-devopsdays-7-8-march-2011.md
- content/blog/call-for-proposals-devops-us-opens.md
- content/blog/devopsday-brazil-2010-devops-go-samba.md
- content/blog/devopsdays-2009-belgium-was-a-great-succes.md
- content/blog/devopsdays-belgium-videos-and-presentations-are-online.md
- content/blog/devopsdays-europe-2010-call-for-speakers-open.md
- content/blog/dod-barcelona-2013.md
- content/blog/dod-paris-2013.md
- content/blog/final-speakers-rome-2012.md
- content/blog/mountainview-t-shirt-contest.md
At some point we rewrote old blog links, and it also appears that some changed over time. This attempts to fix the broken links that have turned up in google's tools. In local testing these rewrites work like it says on the tin.
> Old blog links got rewritten. fixing old links.

- content/events/2017-los-angeles/conduct.md
- content/events/2017-los-angeles/contact.md
- content/events/2017-los-angeles/location.md
- content/events/2017-los-angeles/program.md
- content/events/2017-los-angeles/program/amye-scavarda.md
- content/events/2017-los-angeles/program/bob-reselman.md
- content/events/2017-los-angeles/program/john-dewey.md
- content/events/2017-los-angeles/program/john-willis.md
- content/events/2017-los-angeles/program/kevin-smith.md
- content/events/2017-los-angeles/program/kiyor-cai.md
- content/events/2017-los-angeles/propose.md
- content/events/2017-los-angeles/registration.md
- content/events/2017-los-angeles/speakers.md
- content/events/2017-los-angeles/sponsor.md
- content/events/2017-los-angeles/welcome.md
The google webmaster tools showed that the incorrect URL was apparently being referenced for Los Angeles 2017 (I believe we had them add the `-` shortly after going live). This redirection ensures that any incorrect URLs for that event get rewritten to the correct ones. Tested locally.
> Redirection for incorrect LA url

- static/_redirects
The Goteberg links got hit in the last few months - best to have them all work.
> Redirects for old presentations

- config-windows.toml
- config.toml
- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/layouts/_default/baseof.html
- themes/devopsdays-theme/layouts/shortcodes/event_location.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.7.0...1.7.1)
**Implemented enhancements:**
- Disable generation of unnecessary content [\#467](https://github.com/devopsdays/devopsdays-theme/issues/467)
- Extra space in welcome pages  [\#472](https://github.com/devopsdays/devopsdays-theme/issues/472)
- removing broken-link home icon on events page [\#468](https://github.com/devopsdays/devopsdays-theme/issues/468)
> Updating theme to 1.7.1

- utilities/README.md
- utilities/add_organizers.sh
This is some basic bash that generates the entries for new organizers. I minimally updated the README too. This is MVP and doesn't prompt for every conceivable field; we could update the README to link to the relevant doc. @mattstratton, please take a look and see if this is okay to add as MVP.
> Script to generate new organizer fields (+README update)

- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/layouts/index.html
- themes/devopsdays-theme/layouts/shortcodes/event_twitter.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.7.1...1.7.2)
- adjust dates as shown on frontpage [\#481](https://github.com/devopsdays/devopsdays-theme/issues/481)
- old style event twitters not showing up [\#479](https://github.com/devopsdays/devopsdays-theme/issues/479)
> Updating theme to 1.7.2

- data/events/2017-minneapolis.yml
I think we were using last year's logo for MSP's Thoughtworks sponsorship. CCing @zruty as a heads-up, and we'll want a 👍  from @kmugrage to merge this.
> [MSP-2017] Correcting logo for Thoughtworks

- data/events/2017-salt-lake-city.yml
Hi, @davidasnider - I noticed that your 2017 event on devopsdays.org was missing links that would help people find where your info actually lives. Please 👍  this if you want these links. Thanks!
> [Salt Lake City 2017] Adding more current links

- content/events/2017-portland/welcome.md
The magic registration link (from data/events/2017-portland.yml) doesn't
show up on mobile, or at least I can't find it. Bummer :(
Ken points out that it's the person-with-a-plus-symbol icon. I didn't guess that, and at least one other person didn't either, so I'm still adding it.
> [PDX-2017] Explicitly add reg link

- data/events/2017-portland.yml
I think this is what @BillWeiss was asking for in https://github.com/devopsdays/devopsdays-web/pull/2355.
Before:
After:
If @BillWeiss gives this a thumbs up, feel free to merge.
> Adding registration button for Portland

- content/events/2017-nashville/index.md
- content/events/2017-nashville/sponsor.md
I noticed we had some failed builds. In netlify, this is the error:
In https://github.com/devopsdays/devopsdays-web/pull/2382 I noticed extra space in an `<li>` tag:
The build failed, but locally it looked like this:
Heads up to @mattstratton because this may be relevant to some testing/parsing he has done or considered.
> Fixing broken element

- bin/netlify-production.sh
- bin/netlify.sh
This change forces the use of `hugo 0.20.7` by using the embedded binary in `bin`.
The binary is 4mb which should not be too painful to the repo; we do NOT want to keep this pattern, but until we can figure out how to get Netlify to use 0.20.7 instead of 0.20, we need this to prevent a defect.
> Change to use embedded hugo

- bin/netlify-production.sh
- bin/netlify.sh
- netlify.toml
This change removes the dependency on the embedded hugo binary and uses the mappings in `netlify.toml`.
> Use binrc for hugo

- content/page/about.md
There isn't a good reason for the "/about" page to use a slightly-outdated, special-cased version of the "future" partial to provide individually clickable links to the contact pages for each event (and it doesn't scale well or look particularly good).
This is the data-side cleanup for the issue noted in https://github.com/devopsdays/devopsdays-theme/issues/532.
> Standardizing the "about" page.

- content/events/2017-boston/sponsor.md
gold sponsors get a 3x3 table, not sharing with other golds
> [BOS-2017] - mistake in the description of gold tables

- .travis.yml
- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/layouts/welcome/single.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.10.2...1.10.3)
- Stray curly brace on welcome pages [\#550](https://github.com/devopsdays/devopsdays-theme/issues/550)
> Updating theme to 1.10.3

- content/events/2017-singapore/conduct.md
- content/events/2017-singapore/contact.md
- content/events/2017-singapore/index.md
- content/events/2017-singapore/location.md
- content/events/2017-singapore/propose.md
- content/events/2017-singapore/registration.md
- content/events/2017-singapore/sponsor.md
- data/events/2017-singapore.yml
This commit creates the initial event page with a basic set of pages. 
The goal is to have a landing page for the event that we can use when reaching out to sponsors or speakers.
No changes on the global scope are made and the event is not yet added to the list of upcoming events as we are still waiting for a final confirmation of the venue.
> [SIN-17] Initial version of event page

- .travis.yml
This change causes the travis build job to use Docker, which will allow us to control the version of hugo.
> Change travis tests to use Docker

- hugoserver.ps1
- hugoserver.sh
Updates both scripts to use the latest version of hugo, as well as add caching to make things (hopefully) better on OS X.
> Update docker scripts for hugo 0.21

- .mention-bot
- data/core.toml
This is required for https://github.com/devopsdays/devopsdays-theme/pull/555
This is a backwards-compatible change - the file will not be used until the new theme is released.
> Add core.toml file for new theme capability

- gulp/tasks/responsive-images.js
Fixes devopsdays/devopsdays-theme#485
This handles the issue where different sized speaker images act weird.
Do not merge this change until https://github.com/devopsdays/devopsdays-theme/issues/485 has been approved.
> Resize speaker images properly

- utilities/examples/templates/program.md
We used to have this in the program page; since the content of the file displays above the generated program now, it seemed prudent to put it in again.
> Add content about open spaces to program template

- utilities/add_speakers.sh
Speaker creation shouldn't ask for data it doesn't use. The "datestamp" frontmatter field no longer exists in those templates, so this sed command is a no-op.
This is meant to address https://github.com/devopsdays/devopsdays-web/issues/2559 - we can bikeshed over there as to whether it solves what that issue was meant to solve.
> Remove unneeded requests

- data/events/2017-oslo.yml
Add twitter handle for DevOps Days Oslo 2017 organiser Hans Kristian Flaatten.
CC @steinim @sveinung
> [OSL-2017] Add twitter handle for Hans Kristian Flaatten

- content/events/2016-nashville/welcome.md
This is an example change of creating a proper title for older events, to help prevent google conflicts.
> [BNA-2016] Change Nashville's welcome page for 2016

- content/events/2017-cape-town/propose.md
Our proposals are in a Google Form, and are private, so this sentence
makes no sense.
> [Cape Town 2017] Remove call to comment on proposals

- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/REFERENCE.md
- themes/devopsdays-theme/layouts/partials/head.html
- themes/devopsdays-theme/layouts/partials/welcome.html
- themes/devopsdays-theme/layouts/shortcodes/google_form.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.11.0...1.12.0)
**Implemented enhancements:**
- Improve title tags to remove duplication in Google [\#539](https://github.com/devopsdays/devopsdays-theme/issues/539)
- Add embedded support for Google Forms on main pages [\#230](https://github.com/devopsdays/devopsdays-theme/issues/230)
- List of other events should not say "past" [\#568](https://github.com/devopsdays/devopsdays-theme/issues/568)
> Updating theme to 1.12.0

- data/events/2017-chicago.yml
Whoops. Our CFP closed, and we forgot to remove the propose link from the menu.
> [CHI-2017] Remove propose link from Chicago 2017

- hugoserver.sh
https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/
Hugo takes a while to render the website in Docker on macOS due to slow
filesystem calls. This should speed it up.
I tested a rebuild of the site before and after the change, and got
this:
Before - 103508ms
After - 25891ms
This requires Docker 17.06.0-ce or above.
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*
> Make Docker for Mac cache filesystem calls

- CONTRIBUTING.md
- README.md
There are a few misleading/inaccurate references to Hugo versions, and contributing files. This PR should fix most of them.
> Update references to versions of Hugo

- data/events/2017-kansascity.yml
KU was incorrectly classified as Silver
> [KC-2017] - Moved KU to Community Sponsor

- content/events/2017-portland/speakers/dustin-kirkland.md
I have Dustin Kirkland speaker info in the data folder, but forgot to add his speaker information to the content folder
> [PDX-2017] added DK speaker info to content folder

- content/events/2017-minneapolis/welcome.md
Removing the livestream link which is no longer active.
> [MSP-2017] Removing livestream link (defunct).

- content/events/2017-kansascity/welcome.md
- data/events/2017-kansascity.yml
Add in links from KC to program.
We understand the program is empty at this point, this is just so that the link will be there for speaker communications.
> [Kansas City-2017]: Add program as link

- data/events/2017-nashville.yml
We already had a location page, but we had forgotten to enable it.
> [Nashville-2017] add location

- data/events/2017-nashville.yml
Jurnell is not active as an organizer any more this year.
> [Nashville-2017] Remove Jurnell from list of organizers

- data/events/2017-raleigh.yml
Hey, @chris-short - I'm removing this line because it's causing this broken link:
You can restore it if you upload that missing file - thanks!
(The other change is because my editor restores the missing newline at the end of the file.)
> Fixing broken link

- content/events/2017-auckland/sponsor.md
Added prospect link to the sponsorship page for DevOps Days Auckland 2017
> [Auckland-2017] - Adding prospect link to the sponsors page

- themes/devopsdays-theme/CHANGELOG.md
- themes/devopsdays-theme/REFERENCE.md
- themes/devopsdays-theme/layouts/shortcodes/list_organizers.html
- themes/devopsdays-theme/layouts/talk/single.html
- themes/devopsdays-theme/theme.toml
[Full Changelog](https://github.com/devopsdays/devopsdays-theme/compare/1.12.1...1.13.1)
- Extra dash on program page if speaker is blank [\#586](https://github.com/devopsdays/devopsdays-theme/issues/586)
- Talk page needs spacing below headshot and before speaker title [\#578](https://github.com/devopsdays/devopsdays-theme/issues/578)
**Implemented enhancement**
- Speaker page now supports link to GitLab profile
> Updating theme to 1.13.1

- content/events/2017-galway/sponsor.md
Missing tag was resulting in the style being applied incorrectly on the sponsors page.
> [GAL-2017] Fix sponsors display

- content/events/2017-auckland/speakers/alison-polton-simon.md
- content/events/2017-auckland/speakers/anthony-angell.md
I'm noticing that when there's an image element that's blank, we aren't getting the default. Likely a bug. It manifests thusly.
> Removing blank images

- hugoserver.sh
While running hugo under Docker, sending a Ctrl+C doesn't make it stop,
only the shell script stops.
(even thought Hugo says "Press Ctrl+C to stop")
Adding the `-i` to Docker changes this behaviour. Hitting Ctrl+C now
causes Hugo to stop, and the shell script to exit.
> Make hugo stop if you send Ctrl+C

- data/events/2017-auckland.yml
Adding RedHat and OSS as gold sponsors for event.
> [Auckland-2017] Adding RedHat and OSS as gold sponsors

- utilities/add_sponsors.sh
Remove argument after '-i' as it is being recognized as the sed script to execute
rather than as an argument to the option flag.
> Fix sed commands to use correct placeholder for file

- data/events/2017-philadelphia.yml
Temporarily sets max silver sponsors to 1, removing the Become a Sponsor message at that level.  We do in fact have one more, but it is in flight, and we don't want new proposals.
> [PHILLY-2017] Stop accepting Silver Sponsors

- utilities/add_sponsors.sh
Align sponsor logo prompt in `add_sponsors.sh` with the current guidelines.
> fix language sponsor logo requirements

- data/events/2017-paris.yml
Display Interactive is using a specific URL for sponsoring this event.
cc @jooooooon
> change display interactive to event tracking URL

- content/events/2017-cape-town/index.md
- content/events/2017-cape-town/speakers.md
- data/events/2017-cape-town.yml
DevopsDays vs DevOpsdays vs DevOpsDays
Our images all have `DevOpsDays`, so I've gone for that one.
> [Cape Town 2017] Make DevOpsDays a bit more consistent

- content/events/2018-zurich/registration.md
- data/events/2018-zurich.yml
We now start selling tickets over Tito for devopsdays Zurich-Winterthur 2018. This PR adds the menu and includes the selling form.
> [ZRH-2018] Enable DoD 2018 ZRH registration

- content/events/2017-hartford/conduct.md
Updates Hartford's code of conduct page to include the contact phone number to deal with any incidents.
> [HFD-2017] Adds contact info to Code of Conduct

- data/events/2018-los-angeles.yml
LA 2017 sponsors look to have been added on LA 2018 by mistake. I'm removing for now. we'll add new ones back in as they sign up.
> [LA 2018] remove sponsors

- data/events/2017-cape-town.yml
OfferZen want to track traffic to their site, and have requested this URL change.
> [Cape Town 2017] Change to a event specific URL

- data/events/2018-amsterdam.yml
* Sets CFP date for early Jan
* Sets close for mid April
* Sets conference dates for end of June (back at the same spot!, things never change)
* Opens up sponsorship, but no active recruiting yet.
> [AMS2018] - Set dates for CFP and event

- content/events/2018-zurich/sponsor.md
- data/events/2018-zurich.yml
Adding Pontine and Puzlle ITC as sponsors as well as the sponsor levels
There seems to be something off with the styling of the sponsor levels on our start page (Browser: Safari 10.1.2)
> [ZRH-2018] Adding Sponsors

- content/events/2018-zurich/welcome.md
- data/events/2018-zurich.yml
This corrects the issue noted in https://github.com/devopsdays/devopsdays-web/pull/3403 and also removes the offer for sponsoring the sold-out evening package. /cc @Roderick-Jonsson
> Zurich fixes

- content/events/2017-cape-town/index.md
- data/events/2017-cape-town.yml
- Turns on registration (turns out we should have done that a while back)
- Add a button pointing people at the schedule (seems like they want that, so make it clear where to find it)
> [Cape Town 2017] Open registration and add a button

- content/events/2017-kansascity/program/adam-wieberg.md
- content/events/2017-kansascity/program/alison-stanton.md
- content/events/2017-kansascity/program/chloe-condon.md
- content/events/2017-kansascity/program/dane-hammer.md
- content/events/2017-kansascity/program/dave-swersky.md
- content/events/2017-kansascity/program/david-hollinger-iii.md
- content/events/2017-kansascity/program/david-laulusa.md
- content/events/2017-kansascity/program/dustin-collins.md
- content/events/2017-kansascity/program/james-wickett.md
- content/events/2017-kansascity/program/jeffrey-sykes.md
- content/events/2017-kansascity/program/jonathan-stacks.md
- content/events/2017-kansascity/program/josh-wood.md
- content/events/2017-kansascity/program/joshua-goldman.md
- content/events/2017-kansascity/program/julie-stark.md
- content/events/2017-kansascity/program/jyoti-mittal.md
- content/events/2017-kansascity/program/kishore-jalleda.md
- content/events/2017-kansascity/program/kyle-sexton.md
- content/events/2017-kansascity/program/mark-shead.md
- content/events/2017-kansascity/program/matthew-barker.md
- content/events/2017-kansascity/program/matthew-boeckman.md
- content/events/2017-kansascity/program/michael-cote.md
- content/events/2017-kansascity/program/noah-kantrowitz.md
- content/events/2017-kansascity/program/ron-mackenzie.md
- content/events/2017-kansascity/program/scott-howell-iii.md
- content/events/2017-kansascity/program/todd-brees.md
- data/events/2017-kansascity.yml
- themes/devopsdays-theme/layouts/program/single.html
Links to slides and videos for the program.
> [KC-2017] Links to slides and videos for the program

- data/events/2017-singapore.yml
Currently the breaks show up on the wrong date. This commit fixes that.
> [SIN-17] program: Fix dates for the breaks

- content/events/2017-philadelphia/speakers/erica-windisch.md
Erica Windisch's bio contained 
```
CTO SPEAKERBIO Founder
```
Which looks like copypasta or similar.  I'm replacing it with a slash.
> [PHILLY-2017] Fix 'SPEAKERBIO' anomaly in Erica's bio

- data/events/2017-philadelphia.yml
Bad news: we clipped 5 minutes from each openspace.
Good news: we're having cookies.
> [PHILLY-2017] Update schedule to include afternoon snack

- content/events/2017-tel-aviv/program.md
Updated Ben Rockwood’s talk title on the agenda and cleaned agenda up a bit. Corey is the last one without a talk title - we are waiting for an answer on that one.
> [TLV-2017] updates to agenda talks

- CONTRIBUTING.md
- netlify.toml
This updates the version of hugo being used in preview builds to 0.30.2.
If this passes, we will update it for the production configuration.
> Upgrade builds to hugo 0.30.2

- data/events/2017-cape-town.yml
Overlap and extend the workshops.
They were too short in the previous schedule.
> [Cape Town 2017] Schedule update

- content/events/2018-charlotte/sponsor.md
- data/events/2018-charlotte.yml
Added a new organizer and added our sponsorship tier details to the sponsor page. Tested locally with hugo.
> [CLT-2018] update organizers and sponsor page

- content/events/2018-zurich/conduct.md
Updated the code of conduct to link to the contact page to see organizer profile pictures
> [ZRH-2018] Change organizer profile list to link to contact page

- data/events/2018-new-york-city.yml
Hi, @coffinnailvgd - I noticed that in https://github.com/devopsdays/devopsdays-web/pull/3595 you aren't limiting the number of venue sponsors. It's possible that's intentional, but I think it's more likely that you didn't realize you can remove the possibly misleading "become a venue sponsor":
If merged, this is the effect:
I'll mark this "do not merge" until we hear from you regarding your wishes - thanks!
> [NYC 2018] Single venue sponsor

- content/blog/2017-Brasilia-inreview.md
@mattstratton figured out that blog posts with a date in the future do not display.
> Moving date to before now

- content/events/2017-galway/program/alan-duggan.md
- content/events/2017-galway/program/antoine-voiry.md
- content/events/2017-galway/program/eoin-connaughton.md
- content/events/2017-galway/program/garima-sharma.md
- content/events/2017-galway/program/mark-walsh.md
- content/events/2017-galway/program/owen-byrne.md
- content/events/2017-galway/program/paul-oconnor.md
- content/events/2017-galway/program/tony-chapman.md
Update ignites to make use of the slideshare/speakerdeck widgets for
including the slides directly into the talk pages instead of just links.
> [GAL-2017] Use slideshare/speakerdeck widgets

- content/events/2017-galway/program/alan-duggan.md
- content/events/2017-galway/program/eoin-connaughton.md
Where a public version is available, replace the secret url shared by
the speaker with the correct public url to allow embedded to work.
Revert back to the simple link where the author forgot to make the
slides public.
> [GAL-2017] Replace use of secret urls for slideshare

- content/blog/2017-Auckland.md
Fix image url references replacing:
`/2017-Auckland/`  by ` /blog/2017-Auckland/` as relative path
> [Auckland-2017] Fix images url references in blog review

- content/events/2018-austin/sponsor.md
* PayPal images were breaking adding the `@2x` for responsive images
* Replacing PayNow buttons from PayPal with HTML buttons using bootstrap
> [ATX-2018] Convert Pay Now buttons to Bootstrap

- data/events/2010-sydney.yml
- data/events/2010-us.yml
- data/events/2011-melbourne.yml
- data/events/2011-mountainview.yml
- data/events/2012-mountainview.yml
- data/events/2012-newyork.yml
- data/events/2013-downunder.yml
- data/events/2013-mountainview.yml
- data/events/2013-newyork.yml
- data/events/2014-brisbane.yml
- data/events/2014-newyork.yml
- data/events/2014-siliconvalley.yml
- data/events/2015-melbourne.yml
- data/events/2015-newyork.yml
- data/events/2015-siliconvalley.yml
- data/events/2016-newyork.yml
- data/events/2016-siliconvalley.yml
- data/events/2016-sydney.yml
- data/events/2018-new-york-city.yml
This will have no effect until https://github.com/devopsdays/devopsdays-theme/pull/614 is in production.
> Adding event groups to data files

- content/events/2018-new-york-city/speakers/mike-fiedler.md
The organizer recommends that if speakers are local, to have a callout in their bio.
> [NYC-2018] add a local tagline to speaker bio

- content/events/2017-philadelphia/program/andre-d-henry.md
- content/events/2017-philadelphia/program/andreas-grabner.md
- content/events/2017-philadelphia/program/brian-cole.md
- content/events/2017-philadelphia/program/bridget-kromhout.md
- content/events/2017-philadelphia/program/daniel-olson.md
- content/events/2017-philadelphia/program/darwin-sanoy.md
- content/events/2017-philadelphia/program/david-grizzanti.md
- content/events/2017-philadelphia/program/erica-windisch.md
- content/events/2017-philadelphia/program/jason-m-salberblack.md
- content/events/2017-philadelphia/program/kim-crayton.md
- content/events/2017-philadelphia/program/logan-daigle.md
- content/events/2017-philadelphia/program/michael-winslow.md
- content/events/2017-philadelphia/program/nicole-forsgren.md
- content/events/2017-philadelphia/program/sam-jones.md
- content/events/2017-philadelphia/program/sonia-sarda.md
- content/events/2017-philadelphia/program/stephanie-herr.md
- content/events/2017-philadelphia/program/steve-desmond.md
- content/events/2017-philadelphia/program/tim-gross.md
- content/events/2017-philadelphia/program/tony-burns.md
In looking at my talks from 2017, I noticed that Philly has videos posted but not linked on the website. Adding - approval needed from @peterjshan to merge.
(Side note, @peterjshan - the title/description for https://www.devopsdays.org/events/2017-philadelphia/program/michael-winslow/ is wrong on youtube.)
> [Philly 2017] Adding video links to Philly 2017

- content/events/2018-vancouver/index.md
- data/events/2018-vancouver.yml
I also opened devopsdays/devopsdays-theme#617, so that I can use `cfp_link` and `registration_link` from my YAML file in my event instead of duplicating the strings. I will open another PR to make use of that, when and if I can get it merged!
> [VAN-2018] Add links for registration and CFP

- appveyor.yml
- netlify.toml
This, in theory, will keep appveyor using the last known compatible version of hugo.
> Make appveyor stuck to hugo 0.31.1

- data/events/2018-new-york-city.yml
For @TomOnTime to review after it builds - turning on the new "verbose speaker info" flag for New York City 2018.
> [New York City 2018] Turning on speakers_verbose

- content/page/about.md
- content/page/open-space-format.md
Attempting to clarify open spaces vs curated talks. The current open-space-format page doesn't set any context.
> Text changes to clarify open spaces vs curated content.

- data/sponsors/ns1.yml
NS1 has moved twitter account from @nsoneinc to @NS1. See
https://twitter.com/nsoneinc/status/958356082627313664.
> [ATX-2018] Update twitter handle for NS1

- content/events/2018-portland/conduct.md
- content/events/2018-portland/contact.md
- content/events/2018-portland/location.md
- content/events/2018-portland/propose.md
- content/events/2018-portland/registration.md
- content/events/2018-portland/sponsor.md
- content/events/2018-portland/welcome.md
- data/events/2018-portland.yml
- Opens the 2018 Portland CFP!
- Adds sponsorship prospectus link and details
- Adds first two sponsors
- Adjusts the team membership to reflect this year's crew (I'll email info@devopsdays.org with this too)
- Standardizes on camelcase DevOpsDays for this event
> [PDX-2018] Open the CFP, add sponsor info, adjust team membership

- data/events/2018-saint-louis.yml
Added: Michael Lambardi, Ken Maglio, Dan Kennedy, Bryan Koen, Steven Pritchard, Jeff McDowell
Removed: Eric Schremp, Sayam Masood, Jim Hopkins
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*
> [STL-2018] Update of Saint Louis DevOpsDays organizer list

- data/events/2018-amsterdam.yml
Set the max sponsor spots for the pre event and beer options.
> [AMS 2018] Fix max sponsor spots

- CONTRIBUTING.md
Pull request #3980 fixes the hugo incompatibility problem we were seeing
with version v0.32. Removing the warning as it is no longer necessary.
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*
> Remove the hugo version incompatibility warning

- data/events/2018-amsterdam.yml
The tekst sponsorS should be sponsor for evening/beer and coffee.
This PR changes the max setting from INT to string.
> [AMS-2018] sponsors spots should be string not int

- content/events/2018-new-york-city/welcome.md
The alias on the welcome page for NYC 2018 was wrong :)
> Fix alias for 2018 nyc

- content/events/2017-ohio/program/aaron-kalin.md
- content/events/2017-ohio/program/adarsh-shah.md
- content/events/2017-ohio/program/barbara-bouldin.md
- content/events/2017-ohio/program/barry-tarlton.md
- content/events/2017-ohio/program/chris-mcfee.md
- content/events/2017-ohio/program/jason-hand.md
- content/events/2017-ohio/program/jerry-cattell.md
- content/events/2017-ohio/program/michael-butler.md
- content/events/2017-ohio/program/michael-pinnegar.md
- content/events/2017-ohio/program/neil-primmer.md
- content/events/2017-ohio/program/preston-waller.md
- content/events/2017-ohio/program/ryan-lockard.md
- content/events/2017-ohio/program/tiffany-longworth.md
- content/events/2017-ohio/program/tom-larrow.md
- data/events/2017-ohio.yml
Hi, @kjenkins19 @mfdii etc - I noticed that your talks are posted but weren't linked on each speaker's page. I've added those links because that's usually nice to have. I also added the "speakers" link so all your speakers from 2017 are visible on one page. (I apparently also added newlines, which made it look like there are more changes than there are.)
I'll mark this "do not merge" until we hear from a Columbus organizer as to whether you want this. Thanks.
> [Columbus 2017] Adding links for talks and speakers

- data/events/2018-indianapolis.yml
The last PR passed all tests though the site has not changed in over two
hours. This is an attempt to see if the problem is due to an extra
space.
> [INDY-2018] Fix for adding a sponsor

- content/events/2018-washington-dc/conduct.md
- content/events/2018-washington-dc/contact.md
- content/events/2018-washington-dc/location.md
- content/events/2018-washington-dc/propose.md
* `devopsdays` > `DevOpsDays`
* Update copy on location page
* Update link to King Street Metro on location page
> [DC-2018] Some clean-up

- content/events/2018-washington-dc/sponsor.md
> [DC-2108] Sponsors get logo on DC site, not Baltimore

- data/sponsors/aging-2-0-baltimore.yml
- data/sponsors/datadog.yml
- data/sponsors/gitlab.yml
- data/sponsors/nutanix.yml
- data/sponsors/onyx-point.yml
- data/sponsors/perfbytes.yml
NOTE:  this is not used by the site but is handy for organizers wishing
to include the twitter handle of sponsors in various things like slides
and twitter lists.
> Add twitter handles for some sponsors

- content/events/2018-kansas-city/sponsor.md
- data/events/2018-kansas-city.yml
Updated the organizer email address to use the devopsdays.org email address provided by the core team.
> [KC-2018] Update organizers email

- data/events/2018-denver.yml
> [Denver 2018] Fixing typo

- content/events/2018-sao-paulo/cfp.md
Updating tips with the principal topics considered to rank the proposals. Now the cfp page has the same content as the papercall page.
> [SP-2018] Updating CFP page tips

- content/events/2018-chicago/welcome.md
- data/events/2018-chicago.yml
No reason to send people to `/propose` and make them click again.
> [CHI-2018] Update proposal links to papercall

- content/page/organizing.md
Clarifications:
* Clarifying that we will have a video call
* Clarifying requirements around organizers-cityname-year@devopsdays.org being the public listing
* Clarifying requirement to set up email, website, and Slack invites at the same time
* Clarifying that Slack is optional but email is not
* Clarifying that the Slack we run is only for organizers
* Clarifying we won't merge a PR with dates but no venue
* Removing link to defunct conference site and generalizing advice around picking a date
> Clarifications and updates

- data/events/2018-denver.yml
Since the Denver CFP is closed, you probably don't want this link anymore. Looking for a 👍 from @tavisto or other Denver organizer.
> [Den 2018] Removing propose link

- content/events/2018-copenhagen/welcome.md
- data/events/2018-copenhagen.yml
Hi, @mariuszbury - please let us know if you'd like this update merged.
- removes the "propose" page from the top links since it's closed now
- shows speaker, program, and location pages in the main page links
> [CPH 2018] updating links

- data/events/2018-boston.yml
Even though they're commented out, we probably want to avoid accidentally uncommenting and using outdated logos.
> [Boston 2018] Making sure we don't accidentally use past logos

- utilities/add_sponsors.sh
Without this patch the add_sponsors.sh script will add an extra space to
the yaml output which can cause the sponsor logo to not appear.
> Fix extra space in yaml

- content/events/2018-des-moines/speakers/barattas-forte.md
Apparently on some devices the map being both places was causing display issues.
> [DSM-2018] Remove map from bio to avoid duplicate/overlap

- content/events/2017-minneapolis/sponsor.md
- content/events/2017-minneapolis/welcome.md
Sponsors find 2017 instead of 2018 because of search-engine rankings and links.
> 2017 is over; point to 2018

- data/sponsors/aheadpuppet.yml
Ahead has given us the correct link.
> [MSP 2018] Correcting Ahead/Puppet link

- data/events/2018-amsterdam.yml
* One of our speakers is igniting and speaking the same day. Submitting an adjustment.
> [AMS-2018] Adjust one speaker to not speak the same day

- .travis.yml
- hugoserver.sh
Fixes #4127
Replaces https://github.com/devopsdays/devopsdays-web/pull/4401
(I deleted an re-created my fork, cause my upload bandwidth is slow, and then killed my previous branch)
> Use existing docker image

- content/events/2018-boise/registration.md
It's not longer active, early bird expired last friday (oops..)
> [Boise 2018] Remove EarlyBird discount code

- data/events/2018-boston.yml
Adding appdynamics as a sponsor for Boston, pushing from the ballroom at devops days toronto
> [BOS-2018] added appd as platinum sponsor

- data/sponsors/arresteddevops.yml
- data/sponsors/booz_allen_hamilton.yml
- data/sponsors/compuware.yml
- data/sponsors/metis-machine.yml
- data/sponsors/uspto.yml
Note, this doesn't really do anything for the site but is helpful for
organizers when building twitter lists such as
https://twitter.com/devopsdaysdc/lists/doddc-2018-sponsors/members
> [DC-2018] Add some twitter handles

- data/sponsors/stackify.yml
Fix typo that prevented hyperlink from working on new sponsor image.
> [KC 2018] - Fix typo on URL

- content/events/2018-wellington/propose.md
Have reworded submission action to only use papercall.
> [WLG-2018] Removed email process to submit CFP

- content/events/2018-montreal/propose.md
we were missing the link to talk submission, so I added it and removed the option to have people submit talks via email.
> [MTL-2018] added papercall.io link to propose page

- data/events/2018-amsterdam.yml
Update to an organizer twitter handle (my own).
Seems I missed this when I was originally added.
> [AMS-2018] update an organizer twitter handle

- data/events/2018-london.yml
When I added the surname for Velvet I made the changes in content/ but
not in data/ so the programme page wasn't showing the talk. This minor
fix corrects that
> [LDN-2018] Minor change to get Velvet back

- utilities/add_new_event.sh
- utilities/add_organizers.sh
- utilities/add_program.sh
- utilities/add_speakers.sh
- utilities/add_sponsors.sh
Hey people,
When setting up the new site for Amsterdam I noticed that `add_new_event.sh` failed with the following error:
```
./add_new_event.sh
Enter your event year (default: 2018): 2019
Enter your city name: Amsterdam
Enter your devopsdays event twitter handle (defaults to devopsdays): dodams
sed: can't read s/YYYY/2019/: No such file or directory
```
I had a look at this script and the others and noticed that it was calling `sed`, but I have `gnu-sed` installed on my Mac which when installed (via brew) will automatically change to be used by default.
There were two ways to fix this:
1) Rename the line with [sed](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_new_event.sh#L13) (and in the other files as well) to `/usr/bin/sed` which is where the default BSD …
> Add conditional for gnu-sed on MacOS

- content/events/2018-chattanooga/registration.md
- content/events/2018-chattanooga/sponsor.md
- content/events/2018-chattanooga/welcome.md
Although the registration page is not enabled (we have a link specified instead), it's currently showing up at the top of Google search results, so I'm adding a link on that page to be safe.
> [CHA-2018] Adding registration link, specifying image dimensions

- content/events/2018-chattanooga/propose.md
- content/events/2018-chattanooga/welcome.md
We had some links that weren't properly pointed to PaperCall, this attempts to fix that.
> [CHA-2018] Ensuring everything points to PaperCall for CFPs

- content/events/2018-dallas/welcome.md
- data/events/2018-dallas.yml
Suggested changes for @MikeRosTX to review - to make sure what's linked is valid. You're no longer accepting proposals, and you may want the program and speakers linked in the welcome page text.
> [Dallas 2018] Remove "Propose"; link to program & speakers

- content/events/2018-cape-town/speakers/karl-fischer.md
- content/events/2018-cape-town/speakers/marek-denis.md
- content/events/2018-cape-town/speakers/ruaan-erasmus.md
- content/events/2018-cape-town/welcome.md
- data/events/2018-cape-town.yml
And a few other tweaks.
Apparently if you leave out the `linktitle` by mistake, alphabetical order is lost.
> [Cape Town 2018] Fix speakers alphabetical order

- data/events/2018-taipei.yml
The offsite link in the nav bar should be more explicit (since just the city name alone is also the link back to the "welcome" page).
> [Taipei 2018] Adding more clear link

- content/events/2018-portland/welcome.md
I'm reusing the 2017 food cart map which is still applicable for 2018 (read: image URL is not a typo).
> [2018-PDX] Added lunch details and platinum sponsor blurb (for parity with 2017)

- themes/devopsdays-theme/layouts/speaker/single.html
Hotfix - will PR in properly to theme repo. Discussion in https://github.com/devopsdays/devopsdays-theme/issues/643#issuecomment-421098679.
> So speaker's multiple talks in a single event show

- data/events/2018-boston.yml
added the sponsor, but added them to a group that didn't exist, rather than alacarte
> [BOS-2018] managed to add ca wrong

- data/events/2018-london.yml
I needed to add a last minute sponsor (Sensu) to the site along with a
custom URL for our event event location, so those people who aren't
being led down there can find it on google maps and stuff.
> [LDN-2018] Last minute sponsor and custom url

- content/events/2017-cape-town/welcome.md
Add a temporary notice to our 2017 event welcome page, due to a paste error in a sent Mailchimp campaign.
> [Cape-Town-2018] Temporary notice on 2017 welcome page

- data/events/2018-wellington.yml
Mrinal is stepping into a speaker role this year.
> [WLG-2018] Remove Mrinal Mukherjee as organiser

- data/events/2018-galway.yml
Add Google as a silver sponsor for Devopsdays Galway 2018
> [GAL-2018] Add Google as a sponsor

- data/events/2018-montreal.yml
This entry was put in as an inside joke, but we should probably update
it so attendees see the right time =D
> 2018-montreal: Fix schedule timing

- gulp/tasks/copy-static-files.js
This is a fix for https://github.com/devopsdays/devopsdays-theme/pull/665
> Ensure older static files are properly copied

- content/events/2018-florianopolis/location.md
Netlify is complaining about mixed content on this page:
```
4:55:02 PM: Mixed content detected in: /events/2018-florianopolis/location/index.html
4:55:02 PM: --> insecure img urls:
4:55:02 PM:   - http://2.bp.blogspot.com/-iheMfVGjYGM/UPaio7dNJ-I/AAAAAAAAAfA/7nz-2ojpGsI/s1600/CamExterna+-cam+01.jpg
4:55:02 PM:   - http://2.bp.blogspot.com/-iheMfVGjYGM/UPaio7dNJ-I/AAAAAAAAAfA/7nz-2ojpGsI/s1600/CamExterna+-cam+01.jpg 1x, http://2.bp.blogspot.com/-iheMfVGjYGM/UPaio7dNJ-I/AAAAAAAAAfA/7nz-2ojpGsI/s1600/CamExterna+-cam+01@2x.jpg 2x
```
Note to the maintainers that I'm not one of the organisers of this event so apologies if this confuses anyone/causes any problems.
Signed-off-by: Chris M <millscj01@gmail.com>
> [2018-FLO] Correct mixed content

- data/events/2018-galway.yml
Add HPE as a gold sponsor for Devopsdays Galway 2018
Remove the Platinum offering as we have hit our target for funding.
> [GAL-2018] Add HPE as a sponsor

- content/events/2019-new-york-city/welcome.md
The bullet list of Dates, Sponsors, etc. should be "above the fold".  Moving the NYC logo lower so that the most important content is no longer obscured.
> [NYC-2019] Adjust welcome.md's above/below the fold placement

- data/events/2019-new-york-city.yml
Mani has moved out of the area and will no longer be an organizer for NYC-2019.
> [NYC-2019] Remove Mani Soundararajan

- content/events/2018-chattanooga/welcome.md
Hi, @robscott - I'm removing the "propose a talk" link from your event page as your CFP is long since closed. You can examine that `welcome.md` file and uncomment other sections if you want links to speakers, program, etc in the text of the page as well as in the menu.
> [Chattanooga 2018] Remove "propose a talk" link

- content/events/2018-galway/contact.md
- data/events/2018-galway.yml
Noel had to drop out a while back, but we forgot to update the list of
organizers to mark him as emeritus.
> [GAL-2018] Update organizers list

- data/events/2018-kiev.yml
- data/events/2019-kiev.yml
This adds both Kiev events to the same `event_group` thus ensuring that they're cross-referenced properly. Example:
cc @delgod 😄
> [KIEV-2019] add k[iy][ei]v events to same event_group

- data/events/2018-bengaluru.yml
- data/events/2018-tel-aviv.yml
The published organizer email addresses for Tel Aviv and Bengalaru 2018 were accidentally changed in https://github.com/devopsdays/devopsdays-web/pull/5863 to an organizer from Bengalaru. This was in error; we require the published organizer emails to be in the format organizer-cityname-year@devopsdays.org. This PR corrects it. /cc @budhram @gilzellner @phrawzty
> Email correction

- data/events/2019-london.yml
[Dominique Top](https://twitter.com/devopsdom) just joined us as a London Organizer, so I've added her to the Contact page.
> [LON-2019] Added Dominique Top to the London Contact page

- content/events/2019-london/sponsor.md
- content/events/2019-london/welcome.md
- data/events/2019-london.yml
We've started by adding the basic sponsorship packages and a bunch of clickable stuff on the main page such as sponsorship and contact.
We're still missing a bunch of stuff like prospectus, CFP dates and such but this commit initially kicks off the basic packages which we can start selling places for.
> [LDN-2019] Add basic sponsorship packages, welcome and date.

- CONTRIBUTING.md
closes #5935 
Makes clear that PRs are merged immediately, and references the workflow doc so new contributors can find alternate solutions to opening WIP PRs.
> Add merge policy to contibuting guide

- utilities/examples/data/events/yyyy-city.yml
`cfp_open` is deprecated so we should remove it from the example.
> Remove deprecated field from example config

- content/events/2019-new-york-city/sponsor.md
- data/events/2019-new-york-city.yml
silver sold out, enable signalfx victorops as gold sponsors
> [NYC-2019] sponsor update 

- data/events/2019-tokyo.yml
We want Tokyo to show up on the CFP list at https://www.devopsdays.org/speaking/ - I couldn't figure out the correct date for the announcement, though, so I left it at the closing date.
> [Tokyo 2019] Adding dates so Tokyo shows up on CFP list

- data/events/2019-los-angeles.yml
Hi, @irabinovitch - it appears that the CFP opening date was set to January when this was first listed, months ago. This prevents you from showing up (yet) in https://www.devopsdays.org/speaking/ - so I'm adjusting it to a few days ago when you recently updated the site. Please let us know if you actually don't want to be listed. Thanks!
> [Los Angeles 2019] Adjusting CFP opening

- data/events/2018-raleigh.yml
- data/events/2019-raleigh.yml
> [RDU-2019] Fixing twitter handle for Chris Bailey

- data/events/2019-amsterdam.yml
With this PR we:
- Enable the sponsors wanted link;
- Add missing sponsors options;
- Sort on investment;
- Add F5 as first sponsor.
> [AMS-2019] Add f5 as sponsor

- data/events/2019-berlin.yml
We were seeing an error in the builds:
ERROR 2019/01/03 15:18:31 theme/partials/events/cta.html template: theme/partials/events/cta.html:24:73: executing "theme/partials/events/cta.html" at <time $e.registration...>: error calling time: Unable to Cast <nil> to Time
I think this is happening because one city (Berlin) has a start date and no end date for registration. This is my attempt at fixing it.
> [Berlin 2019] Fixing missing end date

- content/events/2019-london/sponsor.md
We've got the brochure locked down and have been sending it through to
potential sponsors. We'll use the same layout as last year and link through to the new off-site assets.
***
**This PR requires https://github.com/devopsdays/devopsdays-assets/pull/52 to also be merged**
***
> [LDN-2019] Add sponsorship brochure and thumbnail

- data/events/2019-los-angeles.yml
AWS and Release team needed adjustment to show up correctly.
> [la2019] fix sponsor ids la 2019

- bin/netlify-production.sh
- netlify.toml
- package.json
Fixes https://github.com/devopsdays/devopsdays-web/issues/6157 by being more strict on the version; turns the npm/gulp processing back on in the production build.
> Updating to fix jpg/jpeg issue

- themes/devopsdays-theme/layouts/partials/future.html
This is a band-aid hotfix related to https://github.com/devopsdays/devopsdays-theme/issues/656 (because the sidebar is controlled from a different place than the front-page logos.) I'll PR it into the theme repo too, but I want to get it live for NYC's day 2. Thanks to @kmugrage for the heads-up.
> Sidebar hotfix

- data/events/2019-atlanta.yml
adding Chef as a gold sponsor for Atlanta 2019
> [ATL-2019] adding chef as gold sponsor

- content/events/2019-vancouver/welcome.md
This adds a link on the Welcome page for attendees/sponsors/etc to reach the even organizers.
> [Van-2019] email on welcome page to reach organizers

- content/events/2019-washington-dc/conduct.md
Returned an intent section, based on sentiment used by CNCF code of conduct and others, to the CoC.  Added _gender identity and expression_ to the called-out areas
> Add Intent, include gender identity and expression

- content/events/2019-boise/propose.md
- data/events/2019-copenhagen.yml
I added thoughtworks as silver sponsor.
I could not view the local website, it gave me an error message that pointed to {{< param year >}} in the Boise event. So I temporarily removed it and put it back. I did not really change anything, but this is why it shows in my commits :)
If anyone can suggest a solution to that problem, I'm interested :)
> [CPH-2019] Add thoughtworks

- content/events/2019-berlin/propose.md
Also make text on proposal page the same as the text on papercall.io.
> [BER-2019] Fix proposal page, so it points to papercall.io. 

- data/events/2019-washington-dc.yml
Excella already has an entry for [sponsor data](https://github.com/devopsdays/devopsdays-web/blob/master/data/sponsors/excella.yml) and [a square graphic](https://github.com/devopsdays/devopsdays-web/blob/master/static/img/sponsors/excella.png).
@nathenharvey @xzilla
> [DC 2019] add Excella as sponsor

- content/events/2019-seattle/sponsor.md
Turning off paypal as a soft "sold out" on sponsorship
> [SEA-2019] Turn off paypal for sponsorship

- content/events/2019-portugal/propose.md
since we are using papercall, it is better for us to have the talk submissions going to the event page there.
> [PT-2019] Fix proposal link in propose page

- content/events/2019-geneva/program/daniel-maher.md
The title and description were taken from the original presentation proposal (which was a traditional _talk_). This PR modifies the title and description to more accurately match the _workshop_.
> [GENEVA-2019] update Daniel's workshop title & description

- content/events/2019-stockholm/location.md
- data/events/2019-stockholm.yml
Tomorrow we open the CFP. The menu item is not controlled by the date as the button above the share links is. But as it opens at midnight now is a good  time to ad the ink.
> [STH-2019] Add propose menu item

- CONTRIBUTING.md
- README.md
- utilities/README.md
I revised guidelines and docs to meet the following goals:
- moving a lot of detail about large file storage to the CONTRIBUTING file, out of the initial README people would start with
- updates related to the move from Travis to CircleCI
- language changes to more accurately address the audience (often an organizer from a new event, reading the docs for the first time)
- overall consistency, clarification, and error correction
Likely we'll want @mattstratton to sign off on this since there's a fair amount of technical site-related detail. Until he gets to merging this, feel free to weigh in with opinions. :) (After it's merged, just add a new PR with your edits.)
> Updating contributor guidelines and how-to docs

- data/events/2019-london.yml
Simple change adding two sponsors to data/events/2019-london.yml. Currently in draft whilst I OK with other members of the LDN team.
> [LDN-2019] Add CircleCI and Pivotal as Sponsors

- content/events/2019-vancouver/speakers/adron-hall.md
- content/events/2019-vancouver/speakers/jay-gordon.md
- content/events/2019-vancouver/speakers/jj-asghar.md
- content/events/2019-vancouver/speakers/kenzie-woodbridge.md
- content/events/2019-vancouver/speakers/kris-nova.md
- content/events/2019-vancouver/speakers/quintessence-anx.md
- content/events/2019-vancouver/speakers/sonia-gupta.md
- content/events/2019-vancouver/speakers/tiffany-longworth.md
Adding speaker bios/twitter handles for Vancouver. approval requested from @Velutas or the rest of the team
(Note that there wasn't an obvious choice for Adron's but I asked him.)
> [Vancouver 2019] Adding Van speaker bios

- content/events/2019-detroit/propose.md
- content/events/2019-detroit/welcome.md
- data/events/2019-detroit.yml
Some minor 2019 related updates and remove custom CFP link so local propose linkage actually directs to propose page, not external submission page.
> [DET-2019] Updates for 2019 and CFP local link fix

- utilities/README.md
The simplest resolution to https://github.com/devopsdays/devopsdays-theme/issues/590: let people know that logo-square will be made square, possibly at the expense of your aspect ratio.
> Clarify logo square stretching

- themes/devopsdays-theme/layouts/events/single.html
- themes/devopsdays-theme/layouts/index.html
- themes/devopsdays-theme/layouts/partials/future.html
This corrects our end-date handling (as if we have proper datetime strings, we should no longer need to keep events on the main page until the day after they end). It also ensures that we're sorting events on the events page accurately (based on full datetime strings), which in testing seems to eliminate the sort-order changing for events with the "same" date.
> Correct end-date handling

- content/events/2018-phoenix/program/fail-stories.md
The theme doesn't support entirely blank speaker files.
> [Phoenix 2018] Blank speaker files generate errors

- content/speaking/speaking.md
- themes/devopsdays-theme/layouts/speaking/single.html
Temporary patch (affects theme) to temporarily remove this error while we debug it:
Bridgets-MacBook:devopsdays-web bridget$ hugo --theme=devopsdays-theme --buildDrafts=false --baseURL="https://www.devopsdays.org/"
Total in 84512 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: speaking/single.html:9:4: executing "main" at <partial "speaking.ht...>: error calling partial: "/Users/bridget/github/devopsdays/devopsdays-web/themes/devopsdays-theme/layouts/partials/speaking.html:12:34": execute of template failed: template: partials/speaking.html:12:34: executing "partials/speaking.html" at <dateFormat "2006-01-...>: error calling dateFormat: unable to cast <nil> of type <nil> to Time
> Patch to speaking page bug

- content/speaking/speaking.md
- themes/devopsdays-theme/layouts/speaking/single.html
Reverts devopsdays/devopsdays-web#6624
I can revert this now that https://github.com/devopsdays/devopsdays-web/pull/6637 is merged.
> Revert "Patch to speaking page bug"

- data/events/2019-montevideo.yml
Hi, @andresantoniuk and @jantoniuk - we made an error by merging https://github.com/devopsdays/devopsdays-web/pull/6608 - we do not list CFP dates until the event dates are published. The reason for this is people cannot realistically determine whether they can submit a talk until they know when your event is.
We discovered this when @jakubjakubik worked on troubleshooting the issue I opened: https://github.com/devopsdays/devopsdays-web/issues/6625
Although the failure mode was a bit confusing, we do not want to display CFP dates when there is no event date. So, please add your event dates when they are confirmed, and then we will be happy to have your CFP dates added back to the site.
I hope that makes sense. Thanks!
> [MV 2019] no cfp dates without event dates

- data/events/2019-new-york-city.yml
I know cities tend to use their past data files again, so I want to correct this error.
> [NYC 2019] Dates should be unquoted

- data/events/2019-london.yml
Simple change to add pagerduty as silver sponsors as they've paid now.
Signed-off-by: Chris M <me@christophermills.co.uk>
> [LDN-2019] Pagerduty have confirmed as Silver sponsors

- content/events/2019-cape-town/sponsor.md
Ready to be merged, just adding a link to our sponsor prospectus (devopsdays-assets hosted, already merged: https://github.com/devopsdays/devopsdays-assets/pull/57)
> [CPT-2019] Adding link for Cape Town prospectus

- data/events/2019-washington-dc.yml
[Because you can](https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#sponsor-fields)!
> [DC 2019] add Red Hat's campaign ID for this year's sponsorship

- themes/devopsdays-theme/layouts/index.html
We currently have a blank area where the map was. Taking that off the front page while we consider [resolving the map issue](https://github.com/devopsdays/devopsdays-web/issues/6918).
> Removing blank area on front page

- content/events/2019-washington-dc/sponsor.md
- data/events/2019-washington-dc.yml
- data/sponsors/dlt.yml
- data/sponsors/foodfight.yml
- data/sponsors/pyramid-systems.yml
* Add link to Sponsor FAQ
* Happy Hour sponsors get a full table
* DLT is a platinum sponsor
* Arrested DevOps is a media sponsor
* Food Fight Show is a media sponsor
* Update DLT company name and twitter
* Add twitter for Food Fight Show
* Add twitter for PyramidSystems
> [DC-2019] Sponsor cleanup and updates

- data/events/2019-campinas.yml
- Open CFP and updates the main page to contain the PaperCall link.
- Updates twitter account name
> [CAMP-2019] Add CFP link on the main page

- data/events/2019-hartford.yml
Reverts devopsdays/devopsdays-web#6945
"cfp_date_announce" means when an event plans to inform proposers of status, not when they told people the CFP was open (which is cfp_date_start).
> Revert "[HFD-2019] Set CFP announce date"

- data/events/2019-washington-dc.yml
> [DC-2019] use https in Chef's URL

- content/events/2019-columbus/location.md
Apparently I had both the old and new location on the page...oops.
> [Columbus 2019] Fix on location page: Removing old location

- data/events/2019-chicago.yml
Gitlab now as silver sponsor for Chicago
> [CHI 2019] added gitlab to silver

- data/events/2019-minneapolis.yml
Mesosphere and gitlab are new sponsors. I goofed when I added google. We
are still waiting for payment.
> [MSP-2019] Add mesosphere and gitlab, remove google

- data/events/2019-salt-lake-city.yml
easy PR
-VictorOps/Splunk wanted the vicops logo listed instead.
> [SLC-2019] Sponsor logo change.

- data/sponsors/stsi.yml
The STSI URL was redirecting to https://stsiinc.com/, let's just skip the redirect and send folks to the proper destination.
> [DC-2019] One less redirect

- data/events/2019-hartford.yml
Email to follow adding Henry as an Organizer for DevOpsDays Hartford. His information will be updated.
> [HFD-2019] Add Henry Quinn as an Organizer

- content/events/2019-london/sponsor.md
The offer has since passed and no longer needs to be displayed to users.
> [LDN-2019] Small PR to remove offer message

- content/events/2019-minneapolis/sponsor.md
- data/events/2019-minneapolis.yml
Also updates the sponsor page to indicate only 1 slot left for day 1
afternoon break and day 2 is sold out.
> [MSP-2019] Add netapp as silver and alacarte

- data/sponsors/onyx-point.yml
OnyxPoint's http url redirects to https.  Let's just link there.
> [DC-2019] No need for a redirect to https

- content/events/2019-ghent/propose.md
[GHENT2019] Change the propose page to link to pretalx
So the propose page is not really visible, however if you link directly to that, it still show older mail cfp data in place of the updated dodgent-pretalx link
> [GHENT2019] Change the propose page to link to pretalx

- content/events/2019-portugal/speakers/rhys-evans.md
We have added the first of the speaker interviews to help promote them and the event and are using the speakers page to add this content (instead of a specific landing page). no CSS changes have been made for this (though that was considered a possibility in the website slack channel discussion)
> [PT-2019] add Rhys Evans interview to speaker page

- content/events/2019-detroit/welcome.md
Detroit’s welcome page has the wrong type set.
> [DET-2019] Fix welcome type on Detroit 2019 

- content/events/2019-dallas/sponsor.md
Changed the Subject line confusion when potential sponsors email asking general questions by removing Community from Subject line.
> [DFW-2019] Clearing up confusion on Sponsor page

- data/events/2019-philadelphia.yml
> [PHILLY 2019] Remove logz.io as a sponsor.

- content/events/2019-boston/sponsor.md
Adding sponsorship descriptions and a link to the sponsorship prospectus.
Depends on devopsdays/devopsdays-assets#64.
> [BOS-2019] Add sponsorship descriptions.

- utilities/README.md
Added instructions on how to add java script to talk files for embedding videos for non-YouTube and non-Vimeo video sites.
> Added instructions for embedding other video files

- data/events/2019-ghent.yml
The tests run a little differently when running from a branch directly on the repo instead of from a fork, and I noticed this in a PR of @mattstratton's; I moved the `#` to prevent us from seeing this error (which I don't _think_ is evident otherwise):
<i>
11:27:23 AM: ERROR 2019/05/31 16:27:23 Unable to locate template for shortcode 'param' in page propose
11:27:24 AM: ERROR 2019/05/31 16:27:24 theme/partials/meta.html template: "theme/partials/meta.html" is an incomplete or empty template
11:29:17 AM: ERROR 2019/05/31 16:29:17 theme/partials/events/cta.html template: theme/partials/events/cta.html:24:73: executing "theme/partials/events/cta.html" at <time $e.registration...>: error calling time: Could not parse Date/Time format: Unable to parse date: 2019-10-28T23:59:59+01:00# close …
> Moving comment for datetime line

- data/events/2019-stockholm.yml
also fix mislabeled iZettle who are actually bronze sponsors
> [STH-2019] add Thoughtworks as silver sponsors

- data/events/2019-campinas.yml
This PR removes the "supporter sponsors" tier and estabilis from "community sponsors".
> [CAMP-2019] Updates sponsors

- data/events/2019-washington-dc.yml
@nathenharvey @xzilla 
Also remove vestigial sponsor stanza earlier in the data; that's not where we're listing them.
Confirmed to reuse existing sponsor data and image.
> [DC-2019] add Split Software as platinum sponsor

- data/events/2019-washington-dc.yml
@nathenharvey @xzilla 
Adding CapOne, reusing past sponsorship data and assets.
> [DC-2019] add Capital One as a platinum sponsor

- data/events/2019-boston.yml
Adding F5 as an a-la-carte sponsor, and Verizon as a platinum sponsor.
> [BOS-2019] Sponsor updates - 2019/06/19.

- themes/devopsdays-theme/layouts/partials/sponsors.html
Boston recently added an a-la-carte sponsorship type. The framework duly creates a grammatically incorrect "Become a a la carte sponsor" link on our page.
This change makes vowels form grammatically correct sentences. The solution is not perfect - it will screw up on things like "Become an one-day sponsor," but is generally more often correct than not.
Before:
After:
> Fix grammar for becoming a sponsor.

- data/events/2019-washington-dc.yml
- data/sponsors/collabnet-versionone.yml
* Update CollabNet | VersionOne's website to use `https`
* AppDynamics joins as a platinum sponsor
> [DC-2019] Sponsor Updates

- data/events/2019-amsterdam.yml
* one of our bronze sponsors keeps falling off the website. Re-adding.
> [AMS-2019] re-add monkeyswithbuttons... lost in a merge request somehow

- content/events/2019-amsterdam/welcome.md
The main conference logo was suffering being squashed, instead of being reactive, on Mobile Safari.
> [AMS-2019] fix main logo being squashed on Mobile Safari

- content/events/2019-washington-dc/sponsor.md
- data/events/2019-washington-dc.yml
This close to the event, we have made happy hour plans that preclude highlighting only one or two sponsors.
The sponsor data table now looks like this.
> [DC-2019] remove Happy Hour sponsor level

- data/events/2019-columbus.yml
Simple sponsor add... apparently was already there, almost added it a second time due to the odd name of the files.
> [Columbus-2019] Adding JP Morgan Chase as a sponsor.

- content/events/2019-dallas/registration.md
The Dallas registration page has major layout issues with how the sponsors were displayed:
This PR fixes it. (cc @MikeRosTX)
> [Dallas 2019] Fixing Dallas reg layout

- themes/devopsdays-theme/README.md
Fixes #7242
This removes some old dev example URLs, and should update the URL's to the proper repo.
> Update reference for theme

- content/events/2020-salt-lake-city/propose.md
- data/events/2020-salt-lake-city.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year.  @Clait please pull in from upstream/master before next time you update - thanks!
> [2020] Updating SLC email scheme

- data/events/2020-prague.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @a-vorobiev please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Prague email scheme

- content/events/2020-caceres/propose.md
- data/events/2020-caceres.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @curratore please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Cáceres email scheme

- content/events/2020-geneva/propose.md
- data/events/2020-geneva.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @deniger please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Geneva email scheme 

- data/events/2020-madrid.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @xavierportillaedo please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Madrid email scheme

- content/events/2020-new-york-city/propose.md
- data/events/2020-new-york-city.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @jaydestro please pull in from upstream/master before next time you update - thanks!
> [2020] Updating New York City email scheme

- content/events/2020-houston/propose.md
- data/events/2020-houston.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @rchillard @madblkman please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Houston email scheme

- content/events/2020-santiago/propose.md
- data/events/2020-santiago.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @MikeRosTX please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Santiago email scheme

- content/events/2020-portland-me/propose.md
- data/events/2020-portland-me.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @jlbutler please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Portland, ME email scheme

- data/events/2020-portugal.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @eduardopiairo please pull in from upstream/master before next time you update - thanks!
> [2020] Updating Portugal email scheme

- content/events/2019-medellin/propose.md
- data/events/2019-medellin.yml
The old email aliases will all still work, but we're standardizing on the city name so you won't need to get a new alias created each year. @MikeRosTX please pull in from upstream/master before next time you update - thanks!
> [2019] Updating Medellin email scheme

- content/events/2019-montreal/welcome.md
We had some problems with the host for our pretalx installation, and in the interest of time are swapping to papercall mid-way (we'll transition already submitted talks manually, we're using paper call and pretalx to collect only).
> [Montreal-2019] Swap over to papercall

- content/events/2019-chicago/program/karissa-peth.md
- themes/devopsdays-theme/REFERENCE.md
- themes/devopsdays-theme/layouts/program/single.html
- themes/devopsdays-theme/layouts/talk/single.html
This PR updates the talk and program pages to allow embedding of slides from Notist.
I have also updated the REFERENCE file with documentation.
NOTE: This PR includes a content push for 2019-Chicago, for purposes of testing (the content is not test content; but I wanted to have a talk page that included Notist)
Fixes #8070
> Add support for embedded slides from Notist

- data/events/2019-ghent.yml
- data/sponsors/cloudar.yml
- data/sponsors/skyscrapers.yml
* Fix url for Cloudar
* Fix url for Skyscrapers
(in both cases, I added them without `https://` and it caused some unhappiness)
* Add Chef, Atlassian and Netways.
> [Ghent-2019] Add moar sponsors and fix some badly formatted URLs

- data/events/2019-kansas-city.yml
It looks like we'll sell out of all of our additional sponsorships, so let's split them up on the site
> [KC-2019] split 'special' sponsors into distinct labels

- content/events/2019-sydney/welcome.md
- data/events/2019-sydney.yml
Hi, @m1keil - adding links to elements of your program; the global site generates a lot of traffic and also preserves history. (It's recommended to archive your speakers and program there, so we don't have to use the wayback machine later, but I've told archive.org to save your current URLs.)
> [Sydney 2019] Adding links

- data/events/2019-berlin.yml
Adding Oracle Linux as a sponsor for Berlin 2019. Logo already exists, as they're also sponsoring London this year.
> [BLN-2019] Add Oracle Linux as sponsor for Berlin

- content/events/2019-cape-town/welcome.md
The welcome page for Cape Town 2019 was using a CSS class that was removed in the bootstrap upgrade; this fixes that.
> Fix CSS from bootstrap upgrade for 2019 Capetown

- themes/devopsdays-theme/layouts/talk/single.html
Fixes https://github.com/devopsdays/devopsdays-web/issues/8077
https://getbootstrap.com/docs/4.0/utilities/embed/
I selected `16by9` as I assume that's the most popular aspect ratio for
slides.
This seems to work well with my testing.
> Improve Google Slides embed size

- themes/devopsdays-theme/layouts/_default/baseof.html
- themes/devopsdays-theme/layouts/partials/footer.html
"Past events" was a mislabel based on past usage - the link now leads to all events. 
"Propose a talk" needed a link - otherwise, the cities are linked, but overall speaking info is not.
> More clarity in links

- themes/devopsdays-theme/layouts/events/single.html
Changing the events page so upcoming events include years; I'm noticing that since there are lots of 2019 and also a bunch of 2020 events coming up, this makes more sense.
> Adding years to upcoming events

- content/page/sponsor.md
Hugo will automatically add id tags, allowing us to link to a specific
part of the page.
This is useful if we need to direct a sponors at a particular part of
this page.
> Use markdown heading on sponsor page

- content/page/about.md
- data/core.toml
- themes/devopsdays-theme/layouts/shortcodes/list_core.html
- themes/devopsdays-theme/layouts/shortcodes/list_core_active.html
- themes/devopsdays-theme/layouts/shortcodes/list_core_advisory.html
- themes/devopsdays-theme/layouts/shortcodes/list_core_emeritus.html
- utilities/examples/content/events/yyyy-city/contact.md
Problem:
- Some organizers aren't directly working with new events, but haven't entirely retired. Adding a new level "Advisory", to ensure organizers can be listed accurately.
- The way we've previously listed inactive past members of the core team looks clunky, confusingly listing them on the contact pages of every event, when they aren't associated with the events or familiar to the newer city teams.
- The name "Historic" also is a bit odd/confusing.
Solution:
- Changing "Historic" to the more clear "Emeritus".
- Separating out core team members who are just advising core, not actively working on website or onboarding events, and calling them "Advisory".
- Listing Advisory and Emeritus core members on the "About" page but not individual event pages.
Moving @geekle to be the first …
> Organizer refactor

- data/events/2018-belem.yml
We should not have changed the email in https://github.com/devopsdays/devopsdays-web/pull/5549. Correcting the error.
> Fixing old email

- data/events/2019-berlin.yml
Adding Redgate as a sponsor for Berlin 2019. Logo already exists, as they're also sponsoring a bunch of other cities.
> [BLN-2019] Add Redgate as sponsor for Berlin

- data/events/2019-kansas-city.yml
- data/sponsors/delltechnologies.yml
The current name in `delltechnolpagies.yml` looks silly when you hover over the image, so I split it out
> [KC-2019] add dell technologies as sponsor, tweak delltechnologies.yml

- content/page/sponsor.md
- themes/devopsdays-theme/layouts/partials/heading_link.html
- themes/devopsdays-theme/layouts/sponsor/single.html
Taken from https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/9?u=kaushalmodi
My second attempt at https://github.com/devopsdays/devopsdays-web/pull/8451
Fixes https://github.com/devopsdays/devopsdays-web/issues/8494
It doesn't look amazing, and it's only on the sponsor page. But it's a start.
> Add anchor links to headers

- content/events/2020-austin/conduct.md
- content/events/2020-austin/contact.md
- content/events/2020-austin/location.md
- content/events/2020-austin/propose.md
- content/events/2020-austin/registration.md
- content/events/2020-austin/schedule.md
- content/events/2020-austin/sponsor.md
- content/events/2020-austin/welcome.md
- data/events/2020-austin.yml
Closes #8620
Copypasta from 2019-austin and removed / hid a bunch of stuff. ch of stuff. Ran hugo serve locally and tested.
> [AUS-2020] Adding DevOpsDays Austin 2020 Base Site and Event Info

- data/events/2010-europe.yml
- data/events/2012-italy.yml
- data/events/2013-portland.yml
- data/events/2016-oslo.yml
- data/events/2016-portland.yml
- data/events/2017-oslo.yml
- data/events/2017-portland.yml
- data/events/2018-cairo.yml
- data/events/2018-florianopolis.yml
- data/events/2018-oslo.yml
- data/events/2018-portland.yml
- data/events/2019-cairo.yml
- data/events/2019-florianopolis.yml
- data/events/2019-goiania.yml
- data/events/2019-oslo.yml
- data/events/2019-portland.yml
- data/events/2019-portugal.yml
- data/events/2020-cairo.yml
- data/events/2020-madrid.yml
- data/events/2020-portugal.yml
The `event_group` is valuable in cases where the event city name varies (but not used when the city name doesn't change). In checking on data from the past I found a number of inconsistencies and potential points of confusion that I'm clearing up with this PR.
> Correcting event groups

- utilities/add_new_event.sh
This will add aliasing as described in https://github.com/devopsdays/devopsdays-web/issues/8195 for new or returning cities to have the short url of https://devopsdays.org/minneapolis (or whatever their city name is) point to the year they're setting up.
> Adding redirection

- data/events/2020-austin.yml
Hi, @richardboydii! I noticed that https://github.com/devopsdays/devopsdays-web/pull/8621 was merged with incorrect contact email info - sorry about that! For 2020 and beyond, we're not creating email addresses that are year-specific. Your email that includes all your organizers is `austin@devopsdays.org`. We're happy to offer limited-scope email lists if needed for your talk proposals, etc; if such is needed, please let us know who should be on them by emailing `info@devopsdays.org`. Thanks!
> [Austin 2020] Fixing organizer email address

- data/events/2020-buffalo.yml
Hi, @aspleenic! I noticed that https://github.com/devopsdays/devopsdays-web/pull/8658 was merged with incorrect contact email info - sorry about that! For 2020 and beyond, we're not creating email addresses that are year-specific. Your email that includes all your organizers is `buffalo@devopsdays.org`.
> [Buffalo 2020] Fixing organizer email address

- content/events/2020-chicago/sponsor.md
Change to us chicago-sponsors@devopsdays.org as the email address for interested sponsors.
> [CHI-2020] Update email address on Chi sponsor page

- data/events/2019-berlin.yml
Adding xMatters as a sponsor for Berlin 2019. Logo already exists, as they're also sponsoring a bunch of other cities.
> [BLN-2019] Add xMatters as sponsor for Berlin

- themes/devopsdays-theme/layouts/partials/head.html
The logic for setting the HTML titles on pages was missing the "program" page type.
Test it at https://deploy-preview-8747--devopsdays-web.netlify.com/events/2019-cape-town/program
> fix program HTML titles

- content/page/sponsor.md
- themes/devopsdays-theme/layouts/partials/sponsors-accepted.html
- themes/devopsdays-theme/layouts/sponsor/single.html
First attempt at https://github.com/devopsdays/devopsdays-web/issues/8683. I noticed that only one city (Vitoria) of all the upcoming cities had commented out the default-on `sponsors_accepted` item, so it's possible that this really isn't going to accomplish much: https://github.com/devopsdays/devopsdays-web/blob/master/utilities/examples/data/events/yyyy-city.yml#L74
In an effort to make it a little more useful, I have it showing the date the event starts. Presumably most events will stop accepting sponsorships at that point if not before.
> List cities accepting sponsors

- content/events/2020-vancouver/welcome.md
- data/events/2020-vancouver.yml
One organizer is added and the link for twitter is no longer commented out.
> [VAN-2020] Add one organizer and add link for event twitter

- data/events/2017-zurich.yml
- data/events/2018-zurich.yml
- data/events/2019-zurich.yml
- data/events/2020-zurich.yml
Hi, @RomanoRoth - as you've altered the city's display name for 2020, we need to use an event group to ensure that past events are linked properly.
> [Zürich 2020] Adding event group for Zürich

- content/page/organizing.md
A suggestion from [Laura Wicket](https://www.conferenceops.com/) - by default, eventbrite may not prompt events to have ticket buyers input all relevant info for each attendee, which the conference will need them to do.
> require per-attendee info

- CONTRIBUTING.md
Sometimes the `watch` command needs a restart to show specific types of changes (especially around file path, structure, and dates). Thanks to @range for reminding me this wasn't documented.
> watch command sometimes needs a hugo restart

- data/events/2020-krakow.yml
* remove Piotr Szwed
* sort all `team_members` by surnames (as it should be)
> If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.
Mail will be sent briefly.
> [Kraków 2020] Update team_members

- content/events/2020-cape-town/propose.md
- content/events/2020-cape-town/sponsor.md
- data/events/2020-cape-town.yml
NB: Please only merge once https://github.com/devopsdays/devopsdays-assets/pull/78 has been merged - it is the binary of the sponsorship prospectus.
* Enable the propose page with a link to our Sessionize CFP
* Enable and populated the sponsor page with packages.
> [CPT-2020] Adding sponsors and propose pages

- .circleci/config.yml
- config.toml
- hugoserver.sh
- netlify.toml
This updates the hugo version, and adds a configuration option to make html/markdown work properly with that version.
Please do not merge this - let Matt do it. but please *do* look through the deploy preview and test various pages, events, etc.
> Update to Hugo v0.62.1

- content/events/2020-chicago/sponsor.md
There was an extra `@devopsdays.org` in the email links on the sponsor page for Chicago. Whoops.
> [CHI-2020] Fix sponsorship email address

- content/page/organizing.md
Having an apostrophe in the title seemed to be breaking the TOC for the section "designing an local event's logo" section, so I removed it :)
> Remove apostrophe in local event logo header on organizing guide

- content/events/2020-philadelphia/sponsor.md
Markdown can be a bit tricky, without this blank line, it displays the link as plain text.
> [PHL-2020] Fix markdown for prospectus download

- hugoserver.ps1
As the title says, updating this to use the same docker image as the .sh version.
Testing on Windows 10 Pro v1903 build 18362.535
Client: Docker Engine - Community
Version:           19.03.5
API version:       1.40
Go version:        go1.12.12
Git commit:        633a0ea
Built:             Wed Nov 13 07:22:37 2019
OS/Arch:           windows/amd64
Experimental:      false
Server: Docker Engine - Community
Engine:
Version:          19.03.5
API version:      1.40 (minimum version 1.12)
Go version:       go1.12.12
Git commit:       633a0ea
Built:            Wed Nov 13 07:29:19 2019
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          v1.2.10
GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
runc:
Version:          1.0.0-rc8+dev
GitCommit: …
> updated to use the same docker image as *nix

- data/events/2020-buffalo.yml
More preparation for DevOps Days Buffalo 2020. Adding Gitlab as a Silver sponsor and opening the CFP.
> [BUF-2020] Adding Gitlab as a Silver sponsor and the CFP link

- data/events/2020-vancouver.yml
We added confirmed sponsors in good faith - but we've just learned that some sponsors require a signed contract before usage of their logo. This PR removes affected sponsors.
> [VAN-2020] Remove Sponsor until contract signing

- data/events/2020-charlotte.yml
Adding Instana as a gold sponsor for Charlotte's 2020 event.
> [CLT-2020] Add Instana as gold sponsor

- data/events/2020-vancouver.yml
Hi, @Velutas - I see that we merged https://github.com/devopsdays/devopsdays-web/pull/8873 without noticing that you're listing the CFP end date incorrectly - according to your papercall it's a month earlier. We don't want incorrect info on https://devopsdays.org/speaking so I'm fixing it here.
> [Vancouver 20202] Correcting CFP close date

- hugoserver.sh
In order to match the other deployments
https://github.com/devopsdays/devopsdays-web/commit/325acc5b43bb244a0eb1215a1307336bcdb4c817
> Update Docker to use hugo 0.62.1

- data/events/2020-eindhoven.yml
* Add three organizers to team
* Restructure contact page to emphasize local organizers first. 
An email will be sent to core in addition to this PR to add them to the relevant city mailing list & Slack group.
> [EHV-2020] Add three new organizers to the Eindhoven team

- hugoserver.sh
This reverts commit 8b6336ea40380c0b95b092a6aeedec645ae819ce.
This docker tag doesn't exist, lets revert to 0.62.0 for now.
> Revert "Update Docker to use hugo 0.62.1"

- content/events/2020-austin/conduct.md
Bringing the conduct page in line with the core organizing code of
conduct, but keeping the participate pledge we have used in Austin in
the past.
> [austin-2020] Updating conduct page

- static/_redirects
Hi @don-code - in https://github.com/devopsdays/devopsdays-web/pull/9201 since you set it up manually instead of using https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_new_event.sh you did not update the redirect for the https://devopsdays.org/boston link. I'm updating it here.
> [Boston 2020] redirect date update

- data/events/2020-seattle.yml
Adds the following as sponsors for Seattle 2020
Instana
Mattermost
Scalyr
Pulumi
Sky Kick
**Note:** We still need to upload a logo for Sky Kick, unless it's a requirement for this PR, we can submit that separately
> [SEA 2020] Add multiple sponsors

- content/events/2020-charlotte/speakers/jason-yee.md
I'm no longer at Datadog. This updates my bio to reflect my new role at Gremlin.
> [CLT-2020] Update Jason Yee Bio

- data/events/2020-toronto.yml
Suzan resigned from the organizing team last week. Email sent to the core team.
> [TOR-2020] Remove Suzan Mahboob as an organizer

- content/events/2020-boston/sponsor.md
The newer version of Hugo than I tested against renders this as a code block due to the leading whitespace.
> [BOS-2020] Remove leading whitespace.

- themes/devopsdays-theme/layouts/blog/single.html
- themes/devopsdays-theme/layouts/blog/summary.html
- themes/devopsdays-theme/layouts/partials/footer.html
Cosmetic improvements around blog display. I highlight a few examples here.
Before: 
After:
Before:
After:
> Improve blog display

- content/events/2020-portland-or/propose.md
Our CFP is not yet open. We need to need to remove the boilerplate info to prevent email submissions.
> [PDX-2020] Remove boilerplate submission info

- content/events/2020-london/sponsor.md
Evening event sponsors now get stuff like 5 tickets and a 1 minute address to delegates. 
I've not been around for a while so if anything's changed that I didn't see in the contributing guidelines when I had a quick skim through agian let me know.
> [LDN-2020] Update Evening Event sponsor benefits

- data/events/2020-buffalo.yml
Adding Stark & Wayne (gold), Torch.io (Silver), and Blue Cross Blue Shield of WNY (gold) as sponsors.
> [BUF-2020] Adding 3 sponsors

- data/events/2020-atlanta.yml
- data/events/2020-new-york-city.yml
- data/events/2020-seattle.yml
VMware requested we use the 'vmware-tanzu' logo for their events in 2020. I updated NYC, Atlanta, and Seattle since they were already configured with the regular logo.
> [NYC-2020] Update VMware logo for 2020 Events

- content/events/2020-aarhus/sponsor.md
- data/events/2020-aarhus.yml
In this pull request we update our CFP date, and add our sponsor prospectus.
I have noticed chicago links directly to assets.devopsdays.org for the link to the PDF, but could not find any documentation on this ( or how to test this locally :) ) so here goes my attempt at solving it.
Cheers!
> [Aar-2020] Aarhus prospectus

- content/events/2020-aarhus/sponsor.md
Sorry for the inconvenience - my lack of string comparison super eyes let to an extra `/events` in the URL to the sponsor prospect. 
This commit fixes it.
> [Aar-2020] Update link to prospectus

- data/events/2020-montreal.yml
Hi, @idcrosby! You probably want the right TZ; correction for https://github.com/devopsdays/devopsdays-web/pull/9501. (This fix will prevent your event from being removed from the front page mid-event, if a site build happens during your second day.)
> [Montreal 2020] Correcting time zone

- data/events/2020-salt-lake-city.yml
Remove the leading 3 for the venue's address.
> [SLC-2020] Correct typo on venue address.

- content/events/2020-berlin/welcome.md
Slight oversight, link on page text pointed to the wrong CfP page.
> [BER-2020] Point in-page CfP link to actual CfP tool

- content/events/2020-salt-lake-city/welcome.md
- data/events/2020-salt-lake-city.yml
It was a very tough decision, but our biggest reason is that many of our repeat sponsors have chosen to abstain this year due to concerns surrounding covid-19. We are working on messaging and will submit a PR shortly to get us off the global DOD site. We are planning to review the status in May and possible look to host the event in October
If you are adding or removing organizers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.
> Salt lake is Canceling

- content/events/2020-london/sponsor.md
- data/events/2020-london.yml
Logz.io have sponsored and paid for Silver
We're no longer offering discount on sponsorships due to it being past
the 15th of March 2020.
> [LDN-2020] Remove sponsorship discount/Add Sponsor

- .circleci/config.yml
- appveyor.yml
- hugoserver.ps1
- hugoserver.sh
- metadata.json
- netlify.toml
This standardized on using cibuilds/hugo instead of the normal
jojomi/hugo docker image as well as using 0.67.1 everywhere.
See https://github.com/devopsdays/devopsdays-web/pull/9638 for more history.
> Standardize on Hugo usage

- content/events/2020-washington-dc/welcome.md
We will likely not hold and event in 2020.  Planning is officially paused and we will update by 15 Apr 2020.
> [DC-2020] Planning for the 2020 DC event is paused

- static/_redirects
It appears this issue was introduced in https://github.com/devopsdays/devopsdays-web/pull/9586 - uncertain how unless tooling was removing newlines.
> Fixing newline issue

- content/events/2020-aarhus/welcome.md
We will unfortuantely post pone DevOpsDays Aarhus to 2020.
We will contact attendees, sponsors and speakers today.
Cheers
> [Aarhus-2020] Add cancellation notice

- hugoserver.sh
This is a change I've been carrying forward for some time now in my local clone.
The `cached` option is specific to Docker for Mac, and has no bearing on a Linux host. Linux hosts with SELinux enabled will end up with a container that can't read the local copy of the site data, unless Docker is told to change labels on the files beforehand.
**I did not test this on a Mac.** That is why I have the global `else` that makes any non-Linux host behave the old way.
> Let SELinux-protected hosts mount in site data.

- content/events/2020-buffalo/welcome.md
Adding a COVID-19 Statement. We aren't cancelling as of yet, but we want people to be clear on our current status and intentions.
> [BUF-2020] Adding a COVID-19 statement

- data/events/2020-minneapolis.yml
- themes/devopsdays-theme/REFERENCE.md
- themes/devopsdays-theme/layouts/index.html
- themes/devopsdays-theme/layouts/partials/footer.html
- themes/devopsdays-theme/layouts/partials/future.html
- themes/devopsdays-theme/layouts/partials/speaking.html
- themes/devopsdays-theme/layouts/partials/welcome.html
- utilities/docs/cancel-event.md
This adds support for the `cancel:` field in data files, which prevents events from showing up in the sidebar, on future lists, home page, etc.
Tested with 2020 MSP in this PR.
Fixes #9681
> Add field to event data file to keep cancelled events from showing alongside upcoming events

- content/events/2020-seattle/welcome.md
- data/events/2020-baltimore.yml
- data/events/2020-boise.yml
- data/events/2020-des-moines.yml
- data/events/2020-portland-me.yml
- data/events/2020-portland-or.yml
- data/events/2020-seattle.yml
- data/events/2020-tokyo.yml
- data/events/2020-vancouver.yml
- data/events/2020-washington-dc.yml
Setting flags for cancellation for previously-scheduled 2020 events that state they now won't run in 2020 (to remove these events from the TBD sidebar). Updating language on Seattle site based on the later Twitter update (/cc @kmugrage).
> Set cancel flags

- data/events/2020-minneapolis.yml
- data/events/2021-minneapolis.yml
Red Hat would like to carry their sponsorship forward to 2021.
> [MSP 2021] Moving sponsor to 2021

- data/events/2020-minneapolis.yml
- data/events/2021-minneapolis.yml
Moving HashiCorp's MSP sponsorship to 2021, per @solutiongeek.
> [MSP 2021] HashiCorp has moved to 2021

- content/events/2020-philadelphia/welcome.md
- data/events/2020-philadelphia.yml
Due to covid-19 we cancelled dod philly 2020. This removed it from the site and places a message.
> [PHILLY2020] Cancel event on web for 2020.

- content/events/2020-zurich/sponsor.md
- content/events/2021-zurich/sponsor.md
- data/events/2020-zurich.yml
- data/events/2021-zurich.yml
> [ZRH-2020] Removed Nine as sponsor from 2020 and 2021

- content/events/2020-medellin/welcome.md
- data/events/2020-medellin.yml
Changes in the Welcome Page and the Data file to hide the location section and indicate the evenit is going virtual
> [MDE-2020] Changes to indicate the Event in Virtual Modality

- content/events/2020-buffalo/welcome.md
- data/events/2020-buffalo.yml
DevOpsDays Buffalo 2020 has decided, with the virtualization move, to
reduce schedule to one day, from two.
> [BUF-2020] - Virtual Conference Reschedule

- data/events/2020-amsterdam.yml
A sharing image was specified in the datafile for 2020 Amsterdam, but that image does not exist. This removes the reference. If AMS 2020 would like to use this sharing image, a new PR will need to be submitted to add the image to the `/static/events/2020-amsterdam/sharing` directory.
> [AMS-2020] Remove incorrect sharing image data

- content/events/2020-amsterdam/registration.md
As we have seen issues with the crowdcast registration iframe we revert back to the Tito solution for now.
> [AMS-2020] Revert back to ti.to for registration page

- bin/netlify-development.sh
- bin/netlify.sh
this is to keep the development branch out of google
> Update dev branch with noindex

- content/events/2020-chicago/conduct.md
Small changes to the code of conduct to remove physical venue references and add some details related to the event being virtual
> [CHI-2020] Update Chicago 2020 code of conduct for virtual

- data/events/2020-medellin.yml
Linking URLto page showing the agenda in Spanish (devopsdays.io/agenda) and removing devopsdays-mde2020 as a sponsor
> [MDE-2020] Updating Program Section

- content/events/2020-buffalo/welcome.md
Rather than bounce people through a page that consists entirely of one
link to ti.to/..., just link them directly there from the main page and
skip the /registration page.
> [buf-2020] Link directly to ti.to/ reg. page

- content/events/2020-chicago/program.md
Because time zones matter for virtual events!
> [CHI-2020] Add time zone for program page

- data/core.toml
Recognizing current and likely future reality, I would like to move from 'Active' to 'Advisory'.
> [core] Nathen moves to Advisory role

- content/events/2020-chicago/program.md
the link to the livestream on the program page was messed up
> [CHI-2020] Update chicago program link

- data/events/2021-minneapolis.yml
Sponsor intends to come back in 2021.
> [MSP 2021] Sponsor adjustment

- data/events/2020-detroit.yml
Hi @rexroof - in https://github.com/devopsdays/devopsdays-web/pull/9945 you canceled the Detroit 2020 event, but you did not properly mark it so it would stop showing up as an upcoming event. This PR corrects that so it no longer displays as upcoming.
> [Detroit 2020] canceled

- .circleci/config.yml
Due to docker starting to rate-limit pulls, this is needed to keep our circleCI jobs from erroring out
> Fix circle docker hub

- content/events/2020-chicago/program.md
Points the program to the youtube link instead of the live event
> [CHI-2020] Update program with youtube link

- config.toml
Hugo supports emojis via https://www.webpagefx.com/tools/emoji-cheat-sheet/. Just needed to turn it on.
> enable rendering of emojis

- data/events/2021-zurich.yml
> [ZRH-2021] Resheduled DevOpsDays ZRH 2021 to September due to COVID

- data/events/2021-krakow.yml
In the event stub in devopsdays/devopsdays-web#10114, I've missed Janusz from the list.
> [Kraków-2021] add missing team member

- content/events/2021-boston/sponsor.md
- content/events/2021-boston/welcome.md
- data/events/2021-boston.yml
Update the site to reflect that our CFP is live.
We've dropped the explicit one-day verbiage where applicable, to take a
conservative stance on:
1. Ensuring that speakers are prepared to speak either day.
2. Not explicitly calling out that sponsorship is a two-day affair.
...as we are still in the process of evaluating whether to run a one-
or two-day event virtually this year.
> [BOS-2021] 2021 CFP

- data/events/2021-minneapolis.yml
Add Mattermost as silver sponsor for Minneapolis 2021
> [MSP 2021] Add mattermost as silver sponsor

- content/events/2021-amsterdam/sponsor.md
Remove references to in-person event and packages while we're still working on publishing a prospectus.
> [AMS-2021] Update sponsor info

- data/events/2021-seattle.yml
Adding sonatype as a silver sponsor for Seattle 2021
> [SEA-2021] Add sonatype as a silver sponsor

- data/events/2021-portland.yml
Woo! I'm not sure what the `cfp_date_announce` field does, but I don't seem to need it to get the propose link on the site.
> [2021-PDX] CFP is open!

- utilities/README.md
- utilities/add_new_event.sh
- utilities/add_organizers.sh
- utilities/add_program.sh
- utilities/add_speakers.sh
- utilities/add_sponsors.sh
- utilities/change_sponsor_logo.sh
- utilities/common_code
This script implements the process defined in the [instructions for updating a sponsor image](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor-image-or-data). I also library-ified `sedcmd`, as I wanted it in my script, but didn't want to copy-paste it.
The output of this script can be seen at #9903.
**Note that I only tested this on a Linux box.** I don't know that I haven't broken any functionality on macOS.
> Automate the process of changing a sponsor logo.

- content/events/2021-boston/sponsor.md
- data/events/2021-boston.yml
We're not going to be running the startup alley tier virtually
this year, as the value add is not there for sponsors at this tier.
> [BOS-2021] Remove Start-up Alley tier

- content/events/2021-boston/sponsor.md
We are updating our a-la-carte sponsorship tiers to be more amenable
to the needs of a fully virtual conference, where sponsors cannot
justify a $5k or $8k price tag without screen time. We are also
dropping the pre-event hangout entirely, as it is not feasible to run
virtually with a sponsor, plus the videography, which is a built-in
of the virtual platform.
> [BOS-2021] Change a-la-carte sponsorship tiers

- data/events/2021-boston.yml
Launch Darkly is sponsoring our captioning and live graphics.
> [BOS-2021] Launch Darkly sponsorship

- data/events/2021-buffalo.yml
Changed TrendMicro to Skycrafters for the silver sponsorship.
Added RedHat as a bronze sponsor.
> [BUF-2021] Fixed sponsorships

- content/events/2021-washington-dc/announcement.md
- content/events/2021-washington-dc/welcome.md
- data/events/2021-washington-dc.yml
We made a decision to push the event date from September 16-17 to November 4. We extended the CFP and added an announcement explaining the shift.
> [DC-2021] Push event date to November

- data/events/2021-boston.yml
I have not followed the usual process of changing a sponsor logo, because Boston 2021 is the _only_ sponsorship for Progress so far.
> [BOS-2021] Preferred logo for Progress

- content/events/2022-los-angeles/conduct.md
- content/events/2022-los-angeles/contact.md
- content/events/2022-los-angeles/sponsor.md
- content/events/2022-los-angeles/welcome.md
- data/events/2022-los-angeles.yml
- Updating `Description` on all pages.
- Updating `sponsor`'s content.
- Adding `cfp` to welcome page.
- Updating data in `los-angeles-2022.yml` including cfp dates, links, team members info and `sponsor_levels`
> [LA-2022] Update site pages

- data/events/2021-portland-or.yml
TrendMicro is sponsoring on behalf of Skycrafters, asked us to swap the sponsor logo/link
> [PDX-2021] Sponsor swap

- content/events/2021-portland-or/program.md
- content/events/2021-portland-or/watchlive.md
- content/events/2021-portland-or/welcome.md
- data/events/2021-portland-or.yml
One of the embeds will have to be updated once the event starts, but this gets it into place. We would appreciate if this would be merged even in the slightly ugly state before the event.
"watchlive" as a top-level link is kind of gross but works. Eh. Suggestions appreciated :)
> [PDX-2021] Adding a Watch Live page

- data/events/2022-los-angeles.yml
[la 2022] add lightstep as sponsor
> [la 2022] add lightstep as sponsor

- data/events/2022-atlanta.yml
Added Neuvector and Chef [potentially have to remove Chef] as a sponsor. 
Cheers,
-Ravi
> [ATL-2022] Added Neuvector and Chef to Gold Sponsors

- .gitignore
- data/events/2022-london.yml
We've added two new organizers to the team for 2022. These are Rob and Jessica. This will also serve as the PR for the new organizers before Sophie gets in touch about adding them.
I've also added to the .gitignore with this commit as I now use NixOS full time and have written a shell.nix file for dependencies within this project. I don't expect others to use nix and therefore probably shouldn't commit the shell.nix or .direnv. I can take this change out if required and just ignore them locally. (Please let me know on this point)
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>
> [LDN-2022] Add new organizers

- data/events/2020-buenos-aires.yml
- data/events/2020-ciudad-mexico.yml
- data/events/2020-columbus.yml
- data/events/2020-edinburgh.yml
- data/events/2020-eindhoven.yml
- data/events/2020-florianopolis.yml
- data/events/2020-lagos.yml
- data/events/2020-lima.yml
- data/events/2020-saint-louis.yml
- data/events/2020-salt-lake-city.yml
- data/events/2020-santiago.yml
- data/events/2020-singapore.yml
- data/events/2020-toronto.yml
- data/events/2020-zaragoza.yml
- data/events/2021-aarhus.yml
- data/events/2021-boise.yml
- data/events/2021-dallas.yml
- data/events/2021-guadalajara.yml
- data/events/2021-melbourne.yml
- data/events/2021-moscow.yml
- data/events/2021-new-york-city.yml
- data/events/2021-paris.yml
- data/events/2021-prague.yml
A lot of cities forgot to add the cancel tag once an event was decided to be cancelled. This flag was added in late 2020 due to the result of the cancellations of many events due to the pandemic.
> Marking old 2021 & 2022 events as cancelled

- content/events/2022-boise/propose.md
Per the title, this removes the email organizers CTA and adds the PaperCall link.
> [BOI-2022] Replace email submission with PaperCall link

- data/events/2022-atlanta.yml
Howdy buds, swapping out NeuVector for Capital One for DoD ATL 2022. 
> Added Capital One and removed NeuVector as Sponsors

- hugoserver.sh
This stems from a conversation in Slack:
https://devopsdays.slack.com/archives/C07T0BHHN/p1645462365591559
What we know so far is that Linux hosts run into a permissions issue when running `hugoserver.sh`:
```
[don@zeus ~/devopsdays-web:main] ./hugoserver.sh
hugo-server
hugo-server
Start building sites …
hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
Error: Error building site: failed to acquire a build lock: open /home/circleci/project/.hugo_build.lock: permission denied
Built in 10837 ms
```
Commit 8aa741d added the lockfile, but it may be a symptom of the lockfile being necessary to build, rather than a mistake. Removing the lockfile altogether does not result in a successful build - the lock file must be present.
Since it's not possible …
> Permissions fix on Linux

- data/events/2022-aarhus.yml
Misspelled community with a capital C which broke the link to the sponsors_levels list
> [AARHUS-2022] Fix misspelling of sponsor level

- themes/devopsdays-theme/layouts/_default/baseof.html
- themes/devopsdays-theme/layouts/event/single.html
- themes/devopsdays-theme/layouts/speaking/single.html
Mostly this should keep the sidebar consistent (which means if it’s wrong it will be wrong everywhere but…?
> Add caching of some partials

- themes/devopsdays-theme/layouts/_default/baseof.html
I was aggressivelly cachinng the HEAD partial, so all the open graph/title stuff was staying the same within a single event
> Remove weird caching

- content/events/2022-atlanta/program.md
- content/events/2022-atlanta/program/ajuna-kyaruzi.md
- content/events/2022-atlanta/program/amber-vanderburg.md
- content/events/2022-atlanta/program/andre-henry.md
- content/events/2022-atlanta/program/jj-ashgar.md
- content/events/2022-atlanta/program/john-willis.md
- content/events/2022-atlanta/program/lesley-cordero.md
- content/events/2022-atlanta/program/martin-rojas.md
- content/events/2022-atlanta/program/mason-egger.md
- content/events/2022-atlanta/program/nivia-henry.md
- content/events/2022-atlanta/program/rain-leander.md
- content/events/2022-atlanta/program/rob-richardson.md
- content/events/2022-atlanta/program/waldo-grunenwald.md
- content/events/2022-atlanta/speakers/ajuna-kyaruzi.md
- content/events/2022-atlanta/speakers/amber-vanderburg.md
- content/events/2022-atlanta/speakers/andre-henry.md
- content/events/2022-atlanta/speakers/jj-ashgar.md
- content/events/2022-atlanta/speakers/john-willis.md
- content/events/2022-atlanta/speakers/lesley-cordero.md
- content/events/2022-atlanta/speakers/martin-rojas.md
- content/events/2022-atlanta/speakers/mason-egger.md
- content/events/2022-atlanta/speakers/nivia-henry.md
- content/events/2022-atlanta/speakers/rain-leander.md
- content/events/2022-atlanta/speakers/rob-richardson.md
- content/events/2022-atlanta/speakers/waldo-grunenwald.md
- data/events/2022-atlanta.yml
Fixes the styles on the "key" for the program page, and adds speaker / talk pages.
Speakers still need images/bios, etc, and talks need descriptions.
Please do not merge without approval from ATL team
> [ATL-2022] Add custom styles to the program page for ATL

- static/_redirects
this just makes devopsdays.org/london point to the current event!
> Update London redirect

- data/events/2022-amsterdam.yml
- Vmware backed out
- Solo.io added as Gold
> Ams sponsor update

- static/_redirects
Just makes sure that the older used spelling still works, but also makes `/ukraine` point to the event
> Add ukraine and kiev redirects

- content/events/2022-washington-dc/conduct.md
- content/events/2022-washington-dc/location.md
* Fixes a year typo s/2019/2022
* Fixes a few instances of `DC` that should be `D.C.` for consistency
> [DC 2022] It's `D.C.` and 2022

- content/events/2022-boston/location.md
- content/events/2022-boston/sponsor.md
- content/events/2022-boston/welcome.md
- data/events/2022-boston.yml
Mostly adding back 2019 assets that were removed from our 2020/2021 events.
> [BOS-2022] Update sponsorship details; add location

- content/events/2022-washington-dc/sponsor.md
- data/events/2022-washington-dc.yml
Basic levels and pricing. Registration links pending.
Based on 2019 sponsor page. Keeping Media, Community, and Captions sponsorships invisible until details about them are finalized.
> [DC-2022] sponsor prospectus update

- static/_redirects
Signed-off-by: yvovandoorn <yvo.vandoorn@gmail.com>
Removes generic birmingham redirect to cancelled 2021 event.
> remove generic birmingham redirect

- data/events/2022-amsterdam.yml
Signed-off-by: yvovandoorn <yvo.vandoorn@gmail.com>
tshirt needs to be above gold, fixed.
> [AMS-2022] Put tshirt higher than gold, as its more in €

- data/events/2022-boston.yml
Opening our CFP on May 15th and adding our first two sponsors.
The Papercall CFP is not live, so it currently looks like a dead link to non-logged-in users. It will be live before the 15th.
> [BOS-2022] CFP and first sponsors

- data/events/2022-charlotte.yml
Updating our team for this year to include some new folks and remove folks that are not participating this year.
Also one last name change.
> [CLT-2022] organizing team update

- data/sponsors/googlecloud.yml
This landing page is more appropriate for the DevOpsDays community.
> [GCP Sponsor] Update URL to cloud.google.com/devops

- content/events/2022-amsterdam/registration.md
- content/events/2022-amsterdam/welcome.md
- Uncomment links on main page to program, registration, speakers
- Link to Dutch COVID policy (english language)
- Pop ticket button a bit more
- Fix 2019 to 2022 in invoice email link (every year Yvo, every year). 
Signed-off-by: yvovandoorn <yvo.vandoorn@gmail.com>
> [AMS-2022] General website tweaks

- data/events/2022-berlin.yml
> [BLN-2022] Add Linuxmagazin as media partner

- themes/devopsdays-theme/REFERENCE.md
- themes/devopsdays-theme/layouts/speaker/single.html
- themes/devopsdays-theme/layouts/talk/single.html
This pull request resolves #9784
I've got a bit of free time so pickig up a few low hanging fruit from issues:
- Added blocks for twitch in talk and speaker within the theme.
- Added reference to twitch in `REFERENCE.md`
Could possibly add this to organizers too I guess..
> [#9784] Add ability for speakers' twitch.tv

- content/events/2022-washington-dc/sponsor.md
Add PayPal buttons to pay for sponsorships. And add strikethroughs to reflect current number of available sponsorships at each level.
> [DC-2022] Add PayPal buttons for sponsorships

- data/events/2022-charlotte.yml
Updating an organizer's name. Just sent the email to core with subject Charlotte 2022 organizer update
> [CLT-2022] Organizer name update

- data/events/2016-amsterdam.yml
- data/events/2016-capetown.yml
- data/events/2017-amsterdam.yml
- data/events/2017-cuba.yml
- data/events/2017-riga.yml
- data/events/2018-amsterdam.yml
- data/events/2018-riga.yml
- data/events/2019-amsterdam.yml
- data/events/2020-amsterdam.yml
- data/events/2022-amsterdam.yml
- data/events/2022-eindhoven.yml
- themes/devopsdays-theme/layouts/partials/sponsors.html
I noticed when working on #11449 that sponsors with the `max: 1` flag set still are described as "Sponsors", rather than "Sponsor". The comparison is for the string `"1"` rather than the integer `1`. I chose to change the comparison to `1` and update events that had used `"1"`, because there are many more events using `1` than `"1"` today.
```
[don@zeus ~/devopsdays-web/data/events:main] egrep 'max: [0-9]+$' * | wc -l
738
[don@zeus ~/devopsdays-web/data/events:main] egrep 'max: "[0-9]+"$' * | wc -l
82
```
Before:
After:
> Sponsor levels with `max: 1` are suffixed with plurals

- data/events/2022-dallas.yml
> [DFW-2022] Adding Blameless as Silver sponsor

- data/events/2022-minneapolis.yml
> [MSP-2022] Added Delphix and Target as Silver sponsors

- themes/devopsdays-theme/layouts/partials/past.html
This change was spawned from a [Slack thread](https://devopsdays.slack.com/archives/C07T0BHHN/p1658539934998329) regarding why some cancelled events show up in the event lists, but some do not. (It was actually due to one event having a start date, and one not, but the bigger issue is that past events aren't respecting the cancel flag.)
Before (note presence of Philadelphia in 2020):
After (note absence of Philadelphia from 2020):
> Do not show cancelled events in the event lists

- data/events/2022-boston.yml
1. Kosli is a net-new sponsor.
2. Vivanti is misattributed as a platinum sponsor, but they're coming in
on startup alley.
3. Opscruise is a net-new sponsor.
> [BOS-2022] Sponsor true-up

- content/events/2022-detroit/speakers/chris-short.md
- content/events/2022-detroit/speakers/ell-marquez.md
- content/events/2022-detroit/speakers/fatima-sarah-khalid.md
- content/events/2022-detroit/speakers/heidi-waterhouse.md
- content/events/2022-detroit/speakers/james-hunt.md
- content/events/2022-detroit/speakers/jean-remi-beaudoin.md
- content/events/2022-detroit/speakers/jim-barton.md
- content/events/2022-detroit/speakers/matan-cohen.md
- content/events/2022-detroit/speakers/matty-stratton.md
- content/events/2022-detroit/speakers/mofi-rahman.md
- content/events/2022-detroit/speakers/nocnica-mellifera.md
- content/events/2022-detroit/speakers/rain-leander.md
- content/events/2022-detroit/speakers/ray-welker.md
- content/events/2022-detroit/speakers/rizel-scarlett.md
- content/events/2022-detroit/speakers/steve-mcghee.md
- content/events/2022-detroit/speakers/whitney-lee.md
Removing reference to sharing images until we have them to publish, don't want my mistake to throw off social posts.
> [DET-2022] Remove Sharing Images for Now

- data/events/2022-houston.yml
- data/sponsors/diamanti.yml
[HOU-2022] Adding Diamanti as a gold sponsor for Houston event in 2022
> [HOU-2022] Adding Diamanti as a gold sponsor for Houston event in 2022

- content/events/2022-washington-dc/program.md
- data/events/2022-washington-dc.yml
Add the program and schedule for the event. All of the times, talks, and speakers are in Sessionize.
DO NOT MERGE INTO MAIN YET. Need to get review and confirm one final speaker.
> [DC-2022] Add the program and schedule for the event

- content/events/2022-boston/welcome.md
- data/events/2022-boston.yml
* Add registration links for Tito 2022
* Updated GA tracking code (note: UA- codes will no longer be valid June 2023)
* Remove no longer active organizers
> [BOS-2022] Update reg links, GA code, and organizers

- content/events/2022-chattanooga/propose.md
- content/events/2022-chattanooga/registration.md
- data/events/2022-chattanooga.yml
Registration link was borked. Updating it to be correct.
Also squeezing in some proposal info.
> [CHA-2022] Fixing registration link

- data/events/2022-london.yml
I've added the remaining sponsors that've been missing for a while
(sorry sponsors).
Added:
- coralogix as platinum
- delphix as gold
- spacelift as gold
- teleport as gold
- kosli as gold
- civo as silver
- squaredup as silver
- circleci as silver
- spectro cloud as silver
- firehydrant as silver
> [LDN-2022] Add missing sponsors

- data/events/2022-boston.yml
PlanetScale had to bow out of sponsorship; we refunded them and gave this sponsorship slot to Roost.ai instead.
> [BOS-2022] Replace PlanetScale with Roost.ai

- data/events/2022-buffalo.yml
Adding F5 as gold sponsor.
I know there's already a different PR for Buffalo out there, but I wanted to keep this separate since the other one has already mostly been reviewed.
> [BUF-2022] Add F5 as gold sponsor.

- content/events/2022-berlin/speakers/andriy-bilous.md
- content/events/2022-berlin/speakers/christian-hueser.md
- content/events/2022-berlin/speakers/florian-haas.md
- content/events/2022-berlin/speakers/iris-hunkeler.md
- content/events/2022-berlin/speakers/jemma-bolland.md
- content/events/2022-berlin/speakers/jorge-castro.md
- content/events/2022-berlin/speakers/kris-buytaert.md
- content/events/2022-berlin/speakers/marcel-britsch.md
- content/events/2022-berlin/speakers/philipp-krenn.md
- content/events/2022-berlin/speakers/radovan-bacovic.md
- content/events/2022-berlin/speakers/schlomo-schapiro.md
- content/events/2022-berlin/speakers/swathi-poddar.md
First set of speakers for the Berlin 2022 event in preparation of the program.
All these speakers have confirmed the acceptance of their talk in pretalx.
> [BLN-2022] Add initial list of confirmed speakers

- data/sponsors/excella.yml
Change the URL for Excella's sponsorship to point to a new location. 
@pburkholder, I confirmed the change with Excella's marketing team.
> [DC-2022] Update target URL for Excella sponsorship

- data/events/2022-charlotte.yml
Add datadog and harness as sponsors for Charlotte 2022 at gold level
> [CLT-2022] Add sponsors for Charlotte 2022

- content/events/2022-london/sponsor.md
- data/events/2022-london.yml
We've got two new silver sponsors that we need to add. These already exist in data/sponsors and therefore I don't need to add them/update them.
- StormForge
- DoiT International
Edit: I've also moved the `Available` status on the Sponsor table to be `Not Available` due to us having no Silver, Gold, Platinum packages left.
> [LDN-2022] Add StormForge and DoIT

- content/events/2022-washington-dc/welcome.md
The link embedded in the welcome.md page was pointing to the wrong location. The top nav was correct. Changed page code to point to the right spot on Eventbrite.
> [DC-2022] Fix the registration link on the welcome page

- .github/workflows/hugo.yml
- appveyor.yml
- hugoserver.ps1
- hugoserver.sh
- netlify.toml
Netlify's build command has been updated to also take this into consideration. 
On my personal machines (Linux and Mac), I saw nothing unusual but in one instance the typical home page sort problem we have.
> bump 0.92.0 to 0.102.3. Never fall too far behind

- data/sponsors/linuxtips.yaml
- data/sponsors/linuxtips.yml
An `INFO` message from Hugo said the following:
```
INFO 2022/09/08 14:59:54 Data for key 'url' in path 'sponsors/linuxtips.yml' is overridden by higher precedence data already in the data tree
INFO 2022/09/08 14:59:54 Data for key 'name' in path 'sponsors/linuxtips.yml' is overridden by higher precedence data already in the data tree
```
This was due to the fact that there were two linuxtips files, one called `linuxtips.yaml` and the other `linuxtips.yml`. 
```
grep -ri "linuxtips" ./data/sponsors/*
./data/sponsors/linuxtips.yaml:name: "LinuxTips"
./data/sponsors/linuxtips.yaml:url: "https://linuxtips.io"
./data/sponsors/linuxtips.yaml:twitter: LINUXtipsBR
./data/sponsors/linuxtips.yml:name: "linuxtips"
./data/sponsors/linuxtips.yml:url: "https://www.linuxtips.com.br/"
```
I visited …
> Remove duplicate sponsor to get rid of hugo info message

- .github/workflows/hugo.yml
- Create variables for versions of `node` and `hugo`
- Bump node version to `16` to match that of version in `package.json`
- Format file
- use `actions/checkout@v3` everywhere
- use `actions/setup-node@v3` instead of v2
> Updates to Github Action's hugo build

- content/events/2019-tampa/welcome.md
- data/events/2019-tampa.yml
Removing the register button for 2019 and wording on register now on the main page as the event is over.
> [TPA-2019] Updating 2019 with correct messaging

- data/events/2022-almaty.yml
Hello @tabu-a (et al.). I fixed the references to your sponsors in `data/events/2022-almaty.yml` so they will display on your event page now.
> [almaty-2022] fix sponsor references

- data/events/2022-rio-de-janeiro.yml
> [RIO/2022] new organizer

- data/events/2022-buffalo.yml
Extending post-lunchtime sponsor slot from 5 min to 10 min on both conference days.
> [BUF-2022] Extend post-lunchtime sponsor slot to 10 min.

- data/events/2018-montreal.yml
- data/events/2019-montreal.yml
- data/events/2020-montreal.yml
- data/events/2021-montreal.yml
- data/events/2022-montreal.yml
Adding event group to tie together events with and without accents in the spelling. (Note: by default, cancelled events don't show up in past events, but I'm adding it to all years for completeness.)
> [Montreal 2022] Adding event group

- static/events/2018-montreal/welcome/index.html
Update archived page of 2018 so the 2022 event gets displayed in the "Other Montreal Events" section
> [MTL-2018] Update Other Montreal Events section

- themes/devopsdays-theme/layouts/partials/welcome.html
Fixes #11933 
Similar to https://github.com/devopsdays/devopsdays-web/pull/11923, we need to take into account that `.startdate` might not be defined. This pre-calculates the list of other events to display in the event page welcome block, and correctly sorts the list.
I've used variables `$otherTitle` to determine if `city` or `event_group` is used to match in the filter, and `$other` to hold the list of events to print out the links to.
> orders years in list of "other events" in event page header

- static/_redirects
I missed fixing the redirect for https://devopsdays.com/austin
> [ATX-2023] Fix redirect

- content/events/2023-amsterdam/welcome.md
Fixed a missing tag that breaks the spacing.
> [AMS-2013] close the <a> tag to fix spacing

- data/core.toml
Based on [devopsdays-policies/pull/6](https://github.com/devopsdays/devopsdays-policies/pull/6)
Add as co-chairs:  @phrawzty and @glasnt
Removes @yvovandoorn as a co-chair, remains an active organizer
Signed-off-by: Nathen Harvey <nathenharvey@google.com>
> [About] Update the list of active organizers and co-chairs

- data/core.toml
Moves Matty Stratton from co-chair to active, reinstate Yvo as co-chair
> Update core organizers

- data/events/2023-raleigh.yml
> [rdu-2023] Corrected Twitter name for Jeremy Neff

- static/_redirects
The redirect for devopsdays.org/nashville still points at the 2022 site. This fixes that.
> Fix Nashville redirect

- data/core.toml
Per email, and with thanks for their contributions over the years, moving Mine and Ken from Active to Advisory organisers.
> Move Mine, Ken to Advisory

- content/events/2023-copenhagen/propose.md
- content/events/2023-copenhagen/welcome.md
- data/events/2023-copenhagen.yml
This PR will add ticket price and registratio link to the welcome page. 
We have also closed the CFP and have moved the content from papercall to a internal page in order to avoid people leaving the website.
> [CPH-2023] Add price and registration link. Also closing CFP

- content/events/2022-chicago/sponsor.md
- data/events/2022-chicago.yml
Remove sponsor nav and also paypal link from 2022 event
> Update Chicago old sponsor page

- content/events/2023-chicago/covid-19-policy.md
- content/events/2023-chicago/welcome.md
- data/events/2023-chicago.yml
This PR:
* Updates the 2023 Covid/Health & Safety policy with our decisions for the 2023 event.
* Adds a link to the 2023 Health & Safety policy to the main welcome page
> [CHI-2023] Update 2023 covid policy

- netlify.toml
* Adds necessary redirects to Netlify in order to redirect webfinger request to where Mastodon is running.
> [core] storing Mastodon's finger redirect inside of the netlify.toml file

- data/events/2023-copenhagen.yml
Updating list of organizers in DK. Mail is also sent to info@
> [CPH-2023] Updated organizer list for 2023-copenhagen / Denmark

- data/events/2023-washington-dc.yml
Adding 2023 Washington, D.C. registration link and dates, as well as making the Registration button visible.
> [WDC-2023] Adding 2023 Washington, D.C. registration link and button

- data/events/2023-amsterdam.yml
* Add Elastic as gold sponsor for Amsterdam
> [AMS-2023] Add Elastic as Gold sponsor

- data/events/2023-london.yml
We need to add two new organizers before we can request that they're added to Slack. The following adds Issa Long and Ethan Summer to our list of organizers. I've not asked them to provide any social links but if they wish to share them I will update in another Pull Request.
> [LDN-2023] Add new organizers

- data/events/2023-london.yml
These were misspelled in #12367. But also, thank you for having me. And I took the liberty of adding my social media handles too. (I'll let Ethan do their own ones.)
> [LDN-2023] Fix misspellings of new organizer names

- content/events/2023-washington-dc/welcome.md
Adding Kubernetes Community Day DC info to welcome page for Washington, D.C. 2023.
> [WDC-2023] Adding Kubernetes Community Day DC info to welcome page

- data/events/2023-raleigh.yml
Sumo Logic is displayed twice on our sponsors page. Removed the 2nd entry from RDU yaml.
> [rdu-2023] Removed duplicate sponsor

- content/events/2023-zurich/welcome.md
- data/events/2023-zurich.yml
> [ZRH2023] Set DevOpsDays Zurich 2023 to sold out

- content/events/2023-krakow/program.md
- content/events/2023-krakow/welcome.md
- data/events/2023-krakow.yml
- Replaced email addresses with the official one for the whole organizing group
- Added schedule and speaker links for the final schedule
- Removed links to the CFP page
> [KRK-2023] Updated schedule/speakers URLs + replaced contact email addresses

- content/events/2023-london/propose.md
- content/events/2023-london/welcome.md
- Remove old words about COVID speaker restrictions since they weren't listened to last year and we had a great event.
- Make the CfP proposals form more obvious, since as an organizer it took me a while to realise that was where to click to submit, so I'm assuming it's not obvious to others either.
- Fix rendering of the "Help with your talk" heading which was showing up as raw `### Help with your talk` text on the rendered page.
- The homepage needed some tweaks as well, see the later commits.
> [LDN-2023] Tweak wording on the CfP and Welcome pages

- README.md
- Greenkeeper was turned off in 2020, and AFAIK we haven't migrated to Synk. If we were going to migrate to something else for dependency management, might I (in a personal capacity, not mandated by my employer!) suggest Dependabot since it's integrated into GitHub?
- Either way this README badge is defunct so let's remove it.
- Also fix the build badge rendering, since it doesn't have a link it doesn't need the first `[` before the `[![Build Status]` part.
> README: Remove ancient Greenkeeper badge; fix build badge rendering

- content/events/2023-london/welcome.md
- ~This is draft until someone from the London organizing team gives some form of approval. But i~ It seems logical to me that we do want people to buy tickets without having to trawl the website for the "register" link (which is in the header, but quite small, and much like the "propose" link, people might miss it).
> [LDN-2023] Link the 2023 tickets from the homepage

- data/events/2023-caceres.yml
This PR adds a new collaborator to the event.
Closes [#20](https://github.com/neovasili/devopsdays-web/issues/20)
> [CAC-2023] DevOpsDays Caceres 2023 - apr 2023 update 2

- content/events/2023-new-york-city/welcome.md
- data/events/2023-new-york-city.yml
CFP ended a week ago, remove references from the event page.
> [NYC-2023] Remove CFP

- content/events/2023-boston/sponsor.md
- content/events/2023-boston/welcome.md
- data/events/2023-boston.yaml
Publishing sponsorship info for 2023. This depends on devopsdays/devopsdays-assets#158.
> [BOS-2023] Sponsorship info

- content/events/2022-london/welcome.md
- data/events/2020-london.yml
- data/events/2022-london.yml
I'd forgotten to close down the previous year and provide links to the videos and photography.
This PR should suffice in correcting that mistake.
Further to this I also noticed a duplicate key in 2019: `masthead_background` which I've also corrected (though this'll make very little difference to anything other than suppressed warnings).
> [LDN-2023] Close down London 2022

- data/events/2023-boston.yaml
Josh is joining the Boston oranizing team. I will also send a message to info@devopsdays.org.
Note that there was a [discussion in Slack](https://devopsdays.slack.com/archives/CDCDD7319/p1684255997324589) about organizing on a first-name-only / headshotless basis on the website.
> [BOS-2023] Add Josh as organizer

- data/sponsors/sym.yml
missed the `https://` initially so its treating it as a relative url
> [NYC-2023] fix url for sponsor sym

- content/events/2023-zurich/welcome.md
- content/events/2024-zurich/welcome.md
> [ZRH-2023] Fixed the video headline from 2022 to 2023

- data/events/2023-amsterdam.yml
- data/sponsors/atcomputing.yml
Made an typo with the AT computing url. This fixes that ( com -> nl ).
Using an custom url for Kabisa as they have a diferent brand that they want to point to.
> [AMS-2023] Fix some sponsor url's

- content/events/2023-atlanta/welcome.md
I completely missed the rescheduling message on the welcome page. This removes that message.
> [ATL-2023] Remove rescheduling message on welcome page

- data/events/2023-amsterdam.yml
As requested by the AMS sponsor team, rename of the Food Trucks sponsor to singular and update to max one.
> [AMS-2023] Rename foodtrucks to singular and to max to 1

- data/events/2023-eindhoven.yml
This PR opens the ticket sales for EHV.
The registration link is disabled so we can use the `registration.md` page and the integration with Pretix there.
> [EHV-2023] Open ticket sales for EHV

- data/events/2023-rio-de-janeiro.yml
> [RIO-2023]Organizer Update

- data/events/2023-organizer-summit.yml
Reflects the starting time of the social event.
Moves introduction of the Open Spaces process to the Introduction. I reviewed the time we have on the schedule to switch from session to session, which seems like enough buffer time. Might need to review this if @jjasghar has wild plans for virtual.
> [ORG-2023] Update schedule

- data/events/2023-warsaw.yml
We are extending CFP time by one week to give people more time to send proposals after summer vacation time.
> [WAW-2023] Updated CFP end date

- data/events/2023-eindhoven.yml
Remove Harm from active orgs list (and update Kris' picture).
The distribution list has been updated (and I sent an email about the change).
> [EHV-2023] Update organizers

- data/events/2023-washington-dc.yml
Added LaunchDarkly and Datadog as Platinum sponsors for the event.
> [DC-2023] Add LaunchDarkly and Datadog as sponsors

- content/events/2023-montreal/welcome.md
- data/events/2023-montreal.yml
We need to cancel DOD MTL 2023 for financial reasons. 
We're already working with the venue to move it to May 2024.
> [Montreal-2023] DevOpsDays Montreal 2023 has been canceled :(

- content/events/2023-london/program/ten-years-of-dodl.md
- content/events/2023-london/speakers/dodl-organisers.md
- data/events/2023-london.yml
- We've finally got confirmation of our drinks reception and the evening event being hosted for us by a community sponsor.
- Also convert the "10 years of DevOpsDays London" item into a talk and add some blurb.
> [2023-LDN] Add actual details about the evening events

- content/events/2024-london/location.md
- content/events/2024-london/propose.md
- content/events/2024-london/welcome.md
- data/events/2024-london.yml
We're going to shout out that there's a CFP for 2024 and start to get talks early (they'll probably age quite well lol)
- Added `content/events/2024-london/propose.md` even though it's not needed as we link with `cfp_link` but sometimes we alias to this page.
- Added location page as we know it's QEII
- Added accessibility page that was missing.
> [LDN-2024] Add CFP for 2024

- content/events/2024-raleigh/sponsor.md
- data/events/2024-raleigh.yml
- static/_redirects
- Adds sponsorship levels (Siamond,Platinum, Gold, Silver.....) to `2024-raleigh.yml` (followup that enables https://github.com/devopsdays/devopsdays-web/pull/13423 to be closed)
- Updates organizers
- Updated CFP for 2024
> [rdu-2024] Adding Sponsorship levels, updating organizers, opening CFP

- content/events/2024-amsterdam/speaker-info.md
- content/events/2024-amsterdam/sponsor-info.md
These pages are placeholders for the sponsor and speaker info so the team can fill it in with the GitHub editor.
> [AMS-2024] Add (empty) info pages for sponsors and speakers

- data/events/2024-berlin.yml
We received confirmation that Cloudsmith payed the sponsorship fee and are now officially a sponsor for the Berlin 2024 event.
> [BER-2024] Add Cloudsmith as platinum sponsor

- static/_redirects
This makes devopsday.org/chicago/cfp redirect to the NOT YET PUBLISHED cfp page for the event; just setting this up to not have to do it later!
> [CHI-2024] Add redirect to CFP

- data/sponsors/skylounge.yaml
> [DEN-2024] Update skylounge link

- content/events/2024-halifax/propose.md
- data/events/2024-halifax.yml
This PR makes the necessary changes for the CfP page of DevOpsDays Halifax 2024 as we make the CfP live.
> [Halifax-2024] Open CfP for Halifax-2024

- data/core.toml
Clarify Matty and Yvo's terms as co-chairs (in the style of Bridget and Patrick), and fix a minor formatting issue.
> Clarify Matty and Yvo's terms as co-chairs

- static/_redirects
Put the explicit ref _before_ the splat so that the redirect works as expected (see #13579).
> [REC-2024] fix redirect (oops)

- data/events/2024-montreal.yml
- utilities/add_speakers.sh
I rebased and the only difference should be the `data/events/2024-montreal.yml` file but I don't know why I still see an list of commits in the PR :(
> [MTL-2024] Extend CFP one more week

- data/events/2024-amsterdam.yml
CfP closed. Remove the url on the event page.
> [AMS-2024] remove cfp url

- static/_redirects
Change the splat (redirect) for `/london` to point to the 2024 event.
> [LON-2024] redirect /london to the 2024 event

- data/events/2024-houston.yml
Adding CFP announce date so that CFP shows up on the devopsdays.org site.
> [HOU-2024] Adding CFP announce date

- data/events/2024-vancouver.yml
We are hoping to get a few more lightning talks, so we've modified our submission form to only allow lightning talks and we will extend the CFP by about a week.
> [VAN-2024] Extend CFP by a bit to get more lightning talks

- data/events/2024-ghent.yml
Changing the email address to belgium@devopsdays.org
> [2024-Ghent] Changing the email address to belgium@devopsdays.org

- config.toml
- themes/devopsdays-theme/layouts/shortcodes/event_map.html
- themes/devopsdays-theme/reference.md
- utilities/examples/data/events/main.yml
This has been broken for a long time apparently...and yet it's in use :)
You can compare https://deploy-preview-13701--devopsdays-web.netlify.app/events/2024-singapore/location to https://devopsdays.org/events/2024-singapore/location to test :)
Fixes #8458
Fixes #13115
> Fix event map shortcode

- static/_redirects
The Krakow redirect still points to the 2023 event. This points it at the 2024 event.
> [Krakow-2024] redirect krakow splat to 2024

- data/events/2024/raleigh/main.yml
Change Jit.io from Gold Sponsor to Happy Hour Sponsor.
> [RDU-2024] Changed Jit from Gold to Happy Hour

- hugoserver.sh
With the new version hugo server changed some flags, also it will fail if we don't use the image user (circleci) or root
> Update hugo server command at hugoserver.sh

- data/events/2024/tampa/main.yml
Removing Organizer and updating base inkind sponsorships and community sponsorships.
Email was sent to info@devopsdays.org to remove name from the distribution list.
Thanks!
> [TPA-2024] Update Tampa event details and sponsor levels

- data/events/2024/amsterdam/main.yml
Stackstate is joining Amsterdam as a Gold level sponsor!
> [AMS-2024] Add stackstate as Gold sponsor

- data/events/2024/berlin/main.yml
Just settled the agreement with JFrog on a Gold sponsorship for the Berlin event
> [BER-2024] Adding JFrog as Gold sponsor

- data/events/2024/raleigh/main.yml
Removed Mel's info from raleigh.yml
She resigned from our group. After this is merged, an email will be sent to remove from the distros.
Thanks!
> [Raleigh-2024] Remove Mel Cone from Organizers

- data/events/2024/amsterdam/main.yml
Adds Fly.io as a food truck sponsor for Devopsdays Amsterdam.
> [AMS-2024] Fly.io Food truck sponsor

- data/events/2024/berlin/main.yml
Adding stickermule as partner sponsor, overriding common url for them
> [BER-2024] Adds stickermule as sponsor with local URL

- data/events/2024/amsterdam/main.yml
Adding Google Cloud as a gold sponsor.
> [AMS-2024] add gold sponsor

- content/events/2024-amsterdam/speakers.md
- content/events/2024-amsterdam/speakers/matteo-bianchi.md
Adding my links and fixing two small typos related to year and city name (capital letter)
> [AMS-2024] Added speaker links and fixed year typo

- data/events/2024/amsterdam/main.yml
Adding ATComputing as Bronze level sponsor for Amsterdam
> [AMS-2024] Add Bronze sponsor ATComputing

- data/events/2024/raleigh/main.yml
Adds [Clickhouse](https://clickhouse.com/) as a community sponsor for RDU2024
> [RDU-2024]: add Clickhouse as community sponsor

- hugoserver.sh
I was running into a new issue where hugo could not access my local files because of the containers user. This fix runs hugo as the uid/gid of the current user to avoid that.  Moving the workdir to a different directory than default is also required as the current folder is a volume and already has user access perms on it.
> [INFRA] Hugoserver Updates

- data/events/2024/london/main.yml
- We have more sponsors.
- Elastic are Gold sponsors.
- GitHub are my employer, so get a free Bronze sponsorship as a perk of letting me do conference things on work time.
> [LDN-2024] Add Elastic 🥇 and GitHub 🥉 as sponsors

- data/events/2024/berlin/main.yml
Adding DoIt as Silver sponsor for the Berlin event.
> [BER-2024] Add DoIt as Silver sponsor

- data/events/2024/berlin/main.yml
Adding Splunk as Sponsor for the Berlin event.
> [BER-2024] Add Splunk as Platinum sponsor

- data/events/2024/dallas/main.yml
Removed RackN from sponsor list as they have not provided payment yet
Add LaunchDarkly as Gold sponsor
> [DFW-2024] remove RackN and add LaunchDarkly

- content/events/2024-seattle/location.md
- content/events/2024-seattle/program/nathen-harvey.md
- data/events/2024/seattle/main.yml
- Add Nathen Harvey Talk info
- Add link to venue map in assets https://github.com/devopsdays/devopsdays-assets/pull/204
> [SEA-2024] map and keynote updates

- data/events/2024/amsterdam/main.yml
Updates the Google Cloud sponsorship link for 2024 Amsterdam event.
> [AMS-2024] New link for Google Cloud sponsorship

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE
Create a new group by which we can add people who have done this before
and know what content is OK and what needs core to approve.
> Allow content reviewers to review common changes

- content/events/2024-seattle/program/nathen-harvey.md
There are four lines that should be bullets but were being displayed as one long sentence. This change fixes that.
> [SEA-2024] Updates talk description formatting

- data/events/2024/caceres/main.yml
This PR adds some already existing sponsors to our page.
> [CAC-2024] DevopsDays Cáceres 2024 - Sponsors

- data/events/2024/london/main.yml
MacStadium have decided to sponsor the London event at Silver. Hurray!
> [2024-LDN] Add MacStadium as 🥉 sponsor

- data/events/2024/amsterdam/main.yml
Removed the recharge station sponsor option because of purchasing deadlines.
> [AMS-2024] update sponsorships

- data/events/2024/minneapolis/main.yml
Sorry for the mixup - correcting the sponsorship tier (gold, not plat)
ref: #14118
> [MSP-2024] Correct sponsorship tier for Solarwinds

- data/events/2024/london/main.yml
Update to add a couple of sponsors for London. Images exist from previous years.
> [London-2024] Add dxw and syntasso as bronze sponsors

- content/events/2024-washington-dc/sponsor.md
- content/events/2024-washington-dc/welcome.md
- data/events/2024/washington-dc/main.yml
- Added new sponsorship types for breakfast, lunch, and breaks
- Marked the lanyard sponsorship sold (strikethrough)
- Updated available gold sponsorships from 4 to 3
- Added call for sponsorships on Welcome page
> [DC-2024] Add new sponsorship types

- content/events/2025-chicago/sponsor.md
- data/events/2025/chicago/main.yml
Added the sponsors page, copy from 2023, added updated paypal links
I'm on the fence about this ~strikethrough~ styling to show the 1k discount but open to thoughts from the chicago organizers team.
Prospectus uploaded here https://github.com/devopsdays/devopsdays-assets/pull/207
> [CHI-2025] add sponsor page

- content/events/2025-chicago/sponsor.md
- content/events/2025-chicago/welcome.md
This pull request includes updates to the event details for DevOpsDays Chicago, changing the event year from 2023/2024 to 2025 in the `sponsor.md` and `welcome.md` files. 
* [`content/events/2025-chicago/sponsor.md`](diffhunk://#diff-6611d2e6b4b2ae4ec618a42d03ad00742cf1321145aa035add8e4d1b6ce2ad79L4-R4): Updated the description to reflect the new event year, changing "Sponsor DevOpsDays Chicago 2023" to "Sponsor DevOpsDays Chicago 2025".
* [`content/events/2025-chicago/welcome.md`](diffhunk://#diff-32f78196245b96bf94b0fc0ca8af7c47e0e9110d4a058847269824e160165432L20-R20): Updated the event year in the paragraph about accessibility, changing "we are dedicated to making the 2024 event as accessible as possible" to "we are dedicated to making the 2025 event as accessible as possible".
> [CHI-2025] Chore of updating event year to 2025

- content/events/2024-washington-dc/sponsor.md
- content/events/2024-washington-dc/welcome.md
* DevOpsDays DC and Kubernetes Community Day DC (KCD) team up. 
* The KCD website is now live.
* This links to the KCD site from the home and sponsor pages
Preview links:
* [home page](https://deploy-preview-14188--devopsdays-web.netlify.app/events/2024-washington-dc/welcome/)
* [sponsor page](https://deploy-preview-14188--devopsdays-web.netlify.app/events/2024-washington-dc/sponsor)
> [DC-2024] Link to Kubernetes Community Day DC

- data/events/2024/los-angeles/main.yml
Followup to https://github.com/devopsdays/devopsdays-web/pull/14198 to ensure the old logo appears in the one place needed.
> [MSP 2024] LA 2024 had the old solarwinds logo

- data/events/2024/tampa/main.yml
We are thrilled to announce that DNSimple is joining us as a valued sponsor for DevOpsDays Tampa Bay 2024! Their support and commitment to the DevOps community help make events like ours possible, fostering innovation, collaboration, and growth.
Want to be a sponsor for our event? Please visit our website: [DevOpsDays Tampa Bay 2024 Sponsorship](https://devopsdays.org/events/2024-tampa/sponsor).
Stay tuned for more updates as we gear up for an amazing DevOpsDays Tampa Bay 2024!
> [TPA-2024] Added DNSimple as Platinum Sponsor

- data/sponsors/seventhlab.yml
- static/events/2024-caceres/main.css
- static/events/2024-caceres/main.js
This PR essentially fixes one sponsor link typo. It also removes some no longer used code for hiding C4P buttons before it started.
> [CAC-2024] DevopsDays Caceres - broken sponsor link

- utilities/common_code
When I tried to use the [add_speakers script](https://github.com/devopsdays/devopsdays-web/blob/main/utilities/add_speakers.sh) on my mac, I ran into the issue in https://github.com/devopsdays/devopsdays-web/issues/13876. This patch allows adding speakers (conference speakers, not audio devices) on a mac to work.
Fixes https://github.com/devopsdays/devopsdays-web/issues/13876
> Fix mac sed issue

- themes/devopsdays-theme/reference.md
We don't use the old year-based addresses anymore.
> [doc] update example contact email address

- data/events/2024/caceres/main.yml
This PR adds the latest confirmed event sponsors. All of them are sponsors from previous editions.
> [CAC-2024] DevopsDays Cáceres - add recent sponsors

- data/events/2024/birmingham-al/main.yml
* Adding Fetch as a Host sponsor for the Birmingham, AL 2024 event
> [BHM-AL-2024] Adding Fetch as Host sponsor

- data/events/2024/halifax/main.yml
We currently do not have sponsors for the Platinum, Bronze, Lunch, Lanyard, and Coffee levels. To avoid a bleak appearance on the event page, I have temporarily commented out these sections in the `data\events\2024\halifax\main.yml` file. As we secure sponsors for these levels, we can re-enable the sections accordingly.
> [HAL-2024] Temporarily hide empty sponsor sections

- data/events/2024/halifax/main.yml
This pull request adds a new link to the top navigation menu of the DevOpsDays Halifax 2024 event page. The new link directs users to the external event agenda page.
> [HAL-2024] Add agenda link to navigation menu

- content/events/2024-halifax/sponsor.md
This pull request removes the outdated sponsorship prospectus link from the SPONSOR.md file for DevOpsDays Halifax 2024.
> [HAL-2024] Remove outdated sponsorship prospectus link

- utilities/change_sponsor_logo.sh
The sponsor logo script can no longer find sponsor logo usages under the `data` directory, as of #13686. Running it will produce output like:
```
grep: 2009: Is a directory
grep: 2010: Is a directory
grep: 2011: Is a directory
grep: 2012: Is a directory
grep: 2013: Is a directory
grep: 2014: Is a directory
grep: 2015: Is a directory
grep: 2016: Is a directory
grep: 2017: Is a directory
grep: 2018: Is a directory
grep: 2019: Is a directory
grep: 2020: Is a directory
grep: 2021: Is a directory
grep: 2022: Is a directory
grep: 2023: Is a directory
grep: 2024: Is a directory
grep: 2025: Is a directory
```
It is now looking for all files underneath `data/events` recursively, instead of just directly underneath it.
> Make sponsor logo script compatible with new directory structure

- data/events/2024/antwerp/main.yml
This change  complements https://github.com/devopsdays/devopsdays-web/pull/14314 which publishes the program but doesn't enable it yet.
> [ANTWERP-2024] Enabling the program for Antwerpen 2024

- content/events/2024-halifax/sponsor.md
This PR adds a new Silver sponsorship tier to the DevOpsDays Halifax 2024 sponsor page. Also, a minor update was made to change number of community sponsor tickets from 5 to 2. Reordering of Special Sponsorships table content was done for better view
> [HAL-2024] Add Silver sponsorship tier to sponsor page

- themes/devopsdays-theme/layouts/partials/sponsors.html
- themes/devopsdays-theme/reference.md
The possiblitiy to add ```sponsors_showempty``` to the data yaml file
This options hides the sponsor levels with no sponsors
See #14322  for more details
> [SITE] add possibility to hide sponsorlevels without sponsors #14322

- data/events/2024/halifax/main.yml
This PR adds SUSE as a gold sponsor for the DevOpsDays Halifax 2024 event.
> [HAL-2024] Add SUSE as a Gold Sponsor

- themes/devopsdays-theme/layouts/program/single.html
Fixes #14359 
Sponsors have been left off the program page template as an oversight. This brings the program template in line with every other event page template.
> Add sponsors to program page template 

- content/events/2024-boston/health-and-safety.md
- data/events/2024/boston/main.yml
Add a health and safety statement for Boston 2024.
I used an awkward workaround to get the title of this page to render as "Health and Safety", rather than "Health-and-Safety". Let me know if there's a better way to do this.
> [BOS-2024] Health and safety statement

- data/events/2024/london/main.yml
Probably useful to review this discarding whitespace (`?w=1`) because I added the sponsors in alphabetical order.
> [LONDON-2024] Add CAST and Honeycomb as sponsors; alphabetize

- data/events/2024/minneapolis/main.yml
Sponsorships are now closed with the event around the corner. 
Improving/Confluent should be the last one :+1:
> [MSP-2024] Add improving-confluent as a sponsor and close sponsorship

- content/events/2024-halifax/welcome.md
- content/events/2024-halifax/workshop.md
- data/events/2024/halifax/main.yml
This PR introduces a new page for the Preconference Workshop at DevOpsDays Halifax 2024.
Changes include:
- Added `workshop.md` under `content/events/2024-halifax/` detailing the workshop.
- Updated `data/events/2024/halifax/main.yml` to include the workshop page in the navigation.
- Add button for Preconference Workshop to welcome page
> [HAL-2024] Add Preconference Workshop Page

- content/events/2024-chattanooga/sponsor.md
- data/events/2024/chattanooga/main.yml
- Use canva view link instead of edit link for sponsors.
- Bump CFP close out by one week.
> [CHATTANOOGA-2024] Update sponsors and CFP

- data/events/2024/dallas/main.yml
Added the following sponsors:
- Datadog - Gold
- Capital One - Silver
> [DFW-2024] added sponsors: datadog gold and capitalone silver

- data/events/2024/london/main.yml
- Heroku have gone for Gold and paid.
> LDN-2024: Add Heroku to sponsors; alphabetize

- content/events/2024-london/program/hannah-foxwell.md
- I got this wrong in #14480, whoops, I thought an ignite was a thing by itself but nope, it's still a "talk". I hope this will make the speaker info and the talk abstract link together, because right now Hannah's photo and bio don't show up?
> [LDN-2024] Ignites are still "talk" types

- data/events/2024/halifax/main.yml
This PR adds Harness as a raffle sponsor for the DevOpsDays Halifax 2024 event.
> [HAL-2024] Add Harness as a Raffle Sponsor

- content/page/open-space-format.md
From an issue @themightymuppet raised in Slack (see #general channel).
The word "Sponsor" here is confusing and was intended to mean the person facilitating or originating the open space.
I've also changed the "to work" to clarify what's expected of participants.
> [SITE] - Update Open Spaces Wording

- data/events/2024/london/main.yml
We wanted to update the wording as it could be interpretated that we're still to announce/arrange one - when we infact do, but will be announcing during keynotes
> [LDN-2024] Adjusting Evening avent wording

- content/events/2024-london/program/john-willis.md
- content/events/2024-london/speakers/john-willis.md
- data/events/2024/london/main.yml
Add John Willis as speaker to 2024 London's program and speaker page. Added to ignite last slot second day.
We don't currently have an image yet for this speaker.
> [LDN-2024] Add john willis to speakers/program

- content/events/2024-des-moines/sponsor.md
DSM - 2024 Remove the pay button for Platinum Sponsor, since it is taken
> DSM - 2024 Remove the pay button for Platinum Sponsor, since it is taken

- data/events/2024/london/main.yml
We need to swap speakers in our program due to speaker availabilities and commitments
> [LDN-2024] Swapping Ignite Speakers around

- content/events/2024-denver/welcome.md
The livestream link on the welcome page is currently pointing at the 2023 recording. This PR updates it to the current live stream underway for 2024.
> [DEN-2024] Update livestream link to 2024

- data/events/2024/london/main.yml
Raffle's done on the second day, not the first as we've not got lego coming out of our ears.
> [LDN-2024] removing incorrect info for first day

- .phlow
- This was added six years ago in fe6859c27b676376b65c7b449adb20e921b37cc5 with no context.
- And whatever its purpose was (someone's local development environment config?) won't work now because the branch changed to `main`.
- This doesn't seem to be used, and there are no docs about its use in this repo, so 🚮.
> .phlow: delete

- data/events/2024/goiania/main.yml
Update `SaveInCloud` URL only for Goiânia's event
> [GYN-2024] Update sponsor URL

- data/events/2024/tel-aviv/main.yml
As there are problems with the links in the navbar for Tel Aviv 2024, they are still pointing to 2023
> [TELAVIV-2024] change the menu items to the correct year

- content/events/2024-boston/sponsor.md
We decided that adding an open space sponsorship was a terrible idea, and are removing it from the menu of sponsorship options now that people are asking about it.
> [BOS-2024] Remove open space sponsorship

- data/events/2024/chattanooga/main.yml
Add's the "partner" level. We added partner level sponsors in #14653 but didn't add the actual level.
> [CHATTANOOGA-2024] 

- data/events/2024/boston/main.yml
Oodle coming in at Startup Alley instead of Platinum.
> [BOS-2024] Change Oodle's sponsorship level

- config/_default/hugo.yml
- themes/devopsdays-theme/layouts/partials/google_analytics.html
* this updates the google analytics config
* this also stop using the builtin depricated key
This is required from hugo 0.135.x and higher and should solve the deprication problem
> [SITE] update google analytics

- data/events/2024/boston/main.yml
Day two keynote speaker has been moved up to day one; day two schedule has been reorganized to include lightning talks in the missing slot.
> [BOS-2024] Schedule updates

- content/events/2025-austin/welcome.md
- data/events/2025/austin/main.yml
Adds the registration link to the site and turns on the proposal link in the top nav
> [ATX-2025] Open registration, fix proposal link

- content/page/organizing.md
Currently the sustainability donation info is nested under the Budget section. It should be a top level section. While the donation should be accounted for in budgeting, just like venue, food, AV, etc. costs, it should be an separate section. This will also help ensure that it is not overlooked.
> [SITE]: Moves the sustainability section in the org guide up one level

- content/events/2025-austin/sponsor.md
- data/events/2025/austin/main.yml
Adding a link to the prospectus, cleaning up the sponsor us page, and adding a couple of sponsor tiers.
Depends on https://github.com/devopsdays/devopsdays-assets/pull/220
> [ATX-2025] Adds prospectus and final sponsor tier updates

- content/events/2025-amsterdam/sponsor.md
- https://github.com/devopsdays/devopsdays-assets/pull/218 is merged so we can use it now.
> [AMS-2025] Link the sponsor prospectus PDF

- data/events/2025/raleigh/main.yml
Commented out CFP link
(Edit - Removed boilerplate for you - LAS)
> [Raleigh-2025] Commented out CFP link

- content/events/2025-amsterdam/sponsor.md
Updating the link for the Amsterdam sponsorship prospectus to a new version. Goes with the following [PR](https://github.com/devopsdays/devopsdays-assets/pull/223) in the asstes repo.
> [AMS-2025] Updated link to new Ams sponsorship prospectus

- content/events/2025-eindhoven/registration.md
- content/events/2025-eindhoven/welcome.md
- data/events/2025/eindhoven/main.yml
> [EHV-2025] enable registration

- static/_redirects
Tokyo redirect was for 2022; setting to 2025.
> [tokyo-2025] set _redirect to current event

- content/events/2025-amsterdam/registration.md
- content/events/2025-eindhoven/registration.md
- We want this so that prospective buyers know all the details of which ticket types there are and when the event is, etc.
> [2025-{amsterdam,eindhoven}] Show ticket shop blurb in embeds

- data/events/2025/des-moines/main.yml
Des Moines - 2025 Call for Speakers
> DES MOINES - 2025 - Call for speakers

- data/events/2025/atlanta/main.yml
This removes the twitter link for GH.
> [ATL-2025] Remove twitter link for organizer

- utilities/README.md
Updating the documentation to avoid conflicting messaging and the fact that we do not use gulp any more
Based upon feedback from @rennerocha in #14922
> [DOCS] update documentation to indicate png file and no gulp

- themes/devopsdays-theme/layouts/shortcodes/asset.html
- themes/devopsdays-theme/reference.md
shortcode to link to the devopsdays asset url
- `file` : create a href link in a new tab
- `image` : embeds an image with alt name on the page
> [SITE] add asset link for url and images

- data/events/2025/amsterdam/main.yml
- This matches the prospectus.
- Also, to match the prospectus, rename "Captioning" to "Accessibility".
> [2025-AMS] Remove Platinum sponsorship tier

- config/_default/hugo.yml
1. Change to a non-deprecated format for `pagination` (current version of it breaks hugo 145)
2. Fix typo in language name (we don't use this, but might as well get it right)
> [SITE] Two small config changes

- themes/devopsdays-theme/layouts/program/single.html
The previous font awesome icons were...not right
videos worked, but this is the preferred icon
slides didn't work at all
I also added text to make this easier to read/understand
> [SITE] Update icons for slides in program file

- content/events/2025-chicago/program.md
- content/events/2025-chicago/program/heather-thacker.md
- content/events/2025-chicago/program/henrietta-dombrovskaya.md
- content/events/2025-chicago/program/paul-czarkowski.md
- content/events/2025-chicago/program/peter-zaitsev.md
- content/events/2025-chicago/program/reid-savage.md
- content/events/2025-chicago/program/robert-hafner.md
- content/events/2025-chicago/program/robert-snyder.md
- content/events/2025-chicago/program/tracey-barrett.md
> [CHI-2025] Add more speaker slides

- data/events/2025/amsterdam/main.yml
With X being dead, I've migrated to BlueSky.
This PR reflects this change and adds my GitHub handle.
> [AMS-2025] Update orga details for Daniel Paulus

- content/events/2025-atlanta/speakers/nathen-harvey.md
Nathen no longer uses Twitter. This change removes it from his speaker bio for the 2025 DevOpsDays Atlanta event.
Preview - https://deploy-preview-15089--devopsdays-web.netlify.app/events/2025-atlanta/speakers/nathen-harvey/
There should not be a twitter link.
> [ATL-2025] Nathen no longer uses Twitter

- data/events/2025/atlanta/main.yml
It's `Academy`, not `Academny`
Preview - https://deploy-preview-15114--devopsdays-web.netlify.app/events/2025-atlanta/welcome/
/cc @ecology-chris
> [ATL-2025] Fix misspelling

- content/events/2025-atlanta/program/nathen-harvey.md
The slides from Nathen's talk are available, link to them.
Preview - https://deploy-preview-15135--devopsdays-web.netlify.app/events/2025-atlanta/program/nathen-harvey
cc: @ecology-chris
> [ATL-2025] Add link to Nathen's slides

- content/events/2025-des-moines/registration.md
- data/events/2025/des-moines/main.yml
Des Moines 2025 Add Embedded Eventbrite Registration
> DSM-2025 Add Embedded Registration

- content/events/2025-washington-dc/location.md
- content/events/2025-washington-dc/sponsor.md
- data/events/2025/washington-dc/main.yml
* Adding digital sponsorship level to DC-2025 event
* Adding Bluesky as a social media platform for DC-2025 in Sponsorship levels
* Fixing a few typos on sponsorship page of DC-2025
* Fix year on location page for DC-2025
> [DC-2025] Adding Digital Sponsorship Level

- data/events/2025/istanbul/main.yml
- Changed employer from Logo to Innovance.
> [IST-2025] Update employer for Dogukan Turan

- data/events/2025/washington-dc/main.yml
- add Excella as a Lanyard sponsor for 2025 DC event
- add Groundcover as a Gold sponsor for 2025 DC event
> DC-2025 - Sponsor Updates

- data/events/2025/amsterdam/main.yml
Adding Google as a Bronze sponsor for the 2025 Amsterdam event.
> [AMS-2025] Add Google as Bronze sponsor

- data/events/2025/amsterdam/main.yml
I'm clearly feverish putting `google` instead of `googlecloud`...
> [AMS-2025] Add googlecloud

- content/events/2025-sao-paulo/registration.md
- content/events/2025-sao-paulo/welcome.md
- data/events/2025/sao-paulo/main.yml
We enable tregistration page and add tickets sales information in welcome page
> [SP-2025] Add ticket sales information and activate registration page

- content/events/2025-amsterdam/speakers.md
Pretalx had some updates to the schedule view (https://github.com/pretalx/pretalx/blob/main/src/pretalx/api/views/speaker.py) that needs to be handled when grabbing a list of speakers to render on a page.
> Fix javascript retrieving speakers from Pretalx

- data/events/2025/lima/main.yml
This pull request updates the navigation elements for the DevOpsDays Lima 2025 event website. It introduces new links for "WebPeru" and "Registration" while removing commented-out entries for "Registration" and "Program."
Updated navigation elements:
* [`data/events/2025/lima/main.yml`](diffhunk://#diff-419afd7be7a3132ef252b3ac5397061f53ec3ffb0f9d6a37482c9f677880a63dL41-R44): Added "WebPeru" with a link to `https://devopsdays.pe/` and "Registration" with a link to `https://devopsdays.pe/entradas`. Removed commented-out entries for "Registration" and "Program."
> [LIMA-2025] add menu options

- data/events/2025/lima/main.yml
This pull request updates the list of sponsors for the Lima 2025 event by adding a new gold-level sponsor.
Event sponsors update:
* [`data/events/2025/lima/main.yml`](diffhunk://#diff-419afd7be7a3132ef252b3ac5397061f53ec3ffb0f9d6a37482c9f677880a63dR122-R124): Added `fluidattacks` as a gold-level sponsor with the URL `https://www.fluidattacks.com/`.
> [LIMA-2025] add new sponsor

- data/events/2025/kyiv/main.yml
We weren't able to prepare for the event in time, so we're moving to September
> [KYIV-2025] move date

- content/events/2025-halifax/welcome.md
Added the 2024 highlight video to the DevOpsDays Halifax 2025 welcome page. The video appears above the 2024 photo album link and uses the existing responsive layout styling.
> [Halifax-2025] Add a link to DevOpsDays Halifax 2024 highlights.

- data/events/2025/london/main.yml
- Add DXW and GitHub as Logo-only sponsors (the "free" companies of organizers ones).
- Budget constraints mean no breakfast this year, just coffee and snacks in the mornings.
> [2025-LDN] Add sponsors and say we won't have breakfast

- data/events/2025/london/main.yml
- Oops, I put this in the wrong place.
> [2025-LDN] Puppet is a Logo sponsor, not Standard
