devopsdays/devopsdays-web

CONTRIBUTING.md

This is a bit of documentation on how to share local changes using `netlify dev` if you want to show another organizer or sponsor without commiting the changes or opening a PR.
Note for reviewers:
This isn't a _normal_ PR with changes to the `content/data` folders 👍 Not sure if CONTRIBUTING.md is protected but just thought I'd make this note 😃

[DOCS] Netlify Dev Local Preview

---

themes/devopsdays-theme/layouts/partials/head/seo/open_graph.html
themes/devopsdays-theme/layouts/partials/head/seo/schema.html
themes/devopsdays-theme/layouts/partials/head/seo/twitter_cards.html

Update sharing image for fqdn

---

content/events/2019-sao-paulo/program/antonio-muniz.md
content/events/2019-sao-paulo/program/daniel-requena.md
content/events/2019-sao-paulo/program/diogo-nicoleti.md
content/events/2019-sao-paulo/program/edson-celio.md
content/events/2019-sao-paulo/program/eduardo-ximenes.md
content/events/2019-sao-paulo/program/jonatan-baraldi.md
content/events/2019-sao-paulo/program/lucas-santos.md
content/events/2019-sao-paulo/program/marco-junior.md
content/events/2019-sao-paulo/program/miguel-mattos.md
content/events/2019-sao-paulo/program/rafael-gomes.md
content/events/2019-sao-paulo/program/rafael-zago.md
content/events/2019-sao-paulo/speakers/antonio-muniz.md
content/events/2019-sao-paulo/speakers/jonatan-baraldi.md
content/events/2019-sao-paulo/speakers/marco-junior.md
content/events/2019-sao-paulo/speakers/miguel-mattos.md
content/events/2019-sao-paulo/speakers/rafael-zago.md
data/events/2019-sao-paulo.yml

* Added Ignite talks in the program
* Added presentation links of some speakers.

[SP-2019] Added Ignite talks

---

content/events/2019-seattle/livestream.md

[SEA-2019] added live stream

---

data/events/2019-chicago.yml

Updating my last name to my married name

[CHI-2019] Add update last name to married one.

---

content/events/2019-philadelphia/propose.md
data/events/2019-philadelphia.yml

[PHILLY19] Add CFP info

---

data/events/2019-washington-dc.yml

Signed-off-by: Nathen Harvey <nathen@devopsdays.org>

[DC-2019] Update bio for Chuck Mountz

---

content/events/2019-montevideo/sponsor.md

[MVD-2019] clarify exposition area sponsor conditions

---

content/events/2019-des-moines/program/christopher-hunt.md
content/events/2019-des-moines/program/eric-hendricks.md
data/events/2019-des-moines.yml

[DSM-2019] Program updates

---

data/events/2019-nashville.yml

[bna-2019] added last of the tier sponsors

---

data/events/2019-ghent.yml

GHENT-2019 open cfp

---

data/events/2019-montevideo.yml

[MVD-2019] Add Elastic as gold sponsor

[MVD-2019] Add Elastic as gold sponsor

---

content/events/2019-porto-alegre/program/mateus-prado.md
content/events/2019-porto-alegre/speakers/mateus-prado.md

DevOpsDays Porto Alegre 2019 - Adding Mateus Prado talk.

Adding Mateus Prado talk

---

content/events/2019-salt-lake-city/program.md
data/events/2019-salt-lake-city.yml
data/sponsors/fidelitycareers.yml

Add employer for Maria
Update sponsors
Update Fidelity's sponsor info
Update program page to keep site flow

[SLC-2019] Update employer for Maria, update program page

---

content/events/2019-kansas-city/sponsor.md

Update the sponsor page with new pricing and tiers for 2019

[KC-2019] - Update Sponsor Page

---

data/events/2019-victoria.yml

[victoria-2019] updated program

---

content/events/2019-houston/program.md
content/events/2019-houston/program/aaron-aldrich-ignite.md
content/events/2019-houston/program/aaron-aldrich.md
content/events/2019-houston/program/erik-peterson.md
content/events/2019-houston/program/h-waldo-grunenwald.md
content/events/2019-houston/program/jay-gordon.md
content/events/2019-houston/program/lee-barnes.md

[HOU-2019] Added links to slides for 6 talks

---

data/events/2019-amsterdam.yml

Matty Stratton was on the wrong day.

[AMS2019] Switch Matty to Friday

---

content/events/2019-chicago/sponsor.md
data/events/2019-chicago.yml

[CHI-2019] new gold sponsor Solarwind and clarified 'meal and snack' sponsor to be more accurate lunch sponsor info

[CHI-2019] added solarwind and clarified lunch sponsor

---

content/events/2019-buffalo/welcome.md

[BUF-2019] Fixing the welcome.md reg link

---

themes/devopsdays-theme/REFERENCE.md

[BUF-2019] Updating reference.md for reg linking

---

data/events/2019-london.yml

We've now got Capital One as a sponsor 🎉

[LDN-2019] Add Capital One as silver sponsors.

---

data/events/2019-minneapolis.yml

[MSP-2019] Add Merrill Corporation as Gold

---

data/events/2019-porto-alegre.yml

Adding new sponsor to DevopsDays Porto Alegre

---

content/events/2019-london/accessibility.md

Update the accessibility information for the venue

[LDN-2019] Accessibility information update

---

content/events/2019-ghent/registration.md
content/events/2019-ghent/welcome.md
data/events/2019-ghent.yml

* update sponsor levels
* add twitter follow button on welcome page
* open registration

[GHENT-2019] add registration, update sponsor levels

---

data/events/2019-chicago.yml

[CHI-2019] Fix name of company

---

content/events/2019-ghent/registration.md

[GENT-2019] Fixing a typo

---

content/events/2019-houston/program/john-esser.md
content/events/2019-houston/program/kevin-crawley.md
content/events/2019-houston/program/margaret-valtierra.md
content/events/2019-houston/program/ramesh-podila.md
content/events/2019-houston/program/robert-reeves.md

[HOU-2019] Added slideshare to 5 more talks

---

content/events/2019-florianopolis/registration.md
data/events/2019-florianopolis.yml

I'm including infos about tickets and CFP.

[FLN-2019] Update infos about Tickets and CFP

---

content/events/2019-edinburgh/registration.md
content/events/2019-edinburgh/welcome.md
data/events/2019-edinburgh.yml

[Edi-2019] Open registrations

---

data/events/2019-tampa.yml

[TPA-2019] - Adding Verizon as Diamond Sponsor... Thank you Verizon!

[TPA-2019] - Adding Verizon as Diamond Sponsor

---

data/events/2019-chicago.yml

[CHI-2019] added splunk to chicago

---

content/events/2019-portland/welcome.md
data/events/2019-portland.yml

I'm doing this via a comical stack of connectivity and hardware, so I haven't seen the render. I'll look at the netlify output and leave a +1 or -1 to say if I'm happy with it. :/

[Pdx-2019] registration is up, cfp is down

---

content/events/2019-washington-dc/welcome.md

We are offering scholarships through diversitytickets.org and should mention that on the home page.

[DC-2019] Apply for a diversity scholarship

---

data/events/2019-washington-dc.yml

It helps to actually source the image to update a profile.

[DC-2019] Image update

---

data/events/2019-amsterdam.yml

[AMS-2019] Add Microsoft as sponsor

---

data/events/2019-minneapolis.yml

[MSP-2019] Add VictorOps as gold sponsor

---

content/events/2019-houston/program/dan-kirkpatrick.md

[HOU-2019] Added another link to slides

---

data/events/2019-boise.yml

- Microsoft as Happy Hour Level
- Update for JG employer
- Update for RM Github

[BOI-2019] Microsoft Sponsor, Planning committee personal detail update. 

---

content/events/2019-washington-dc/propose.md
content/events/2019-washington-dc/welcome.md
data/events/2019-washington-dc.yml

[DC-2019] - Call for proposals is closed

---

data/events/2019-chicago.yml

[CHI-2019] Remove propose link 

---

content/events/2020-seattle/welcome.md
data/events/2020-seattle.yml

[SEA-2020] Welcome page updates

---

data/events/2019-chicago.yml

[CHI-2019] added google as gold

---

data/events/2019-boise.yml

- Chef added to Silver Sponsors.

[BOI-2019] Adding Chef to Silver Sponsors

---

content/events/2019-portugal/program.md
content/events/2019-portugal/program/allegra-cooper.md
content/events/2019-portugal/program/diogo-oliveira.md
content/events/2019-portugal/program/grace-chang.md
content/events/2019-portugal/program/hugo-amorim.md
content/events/2019-portugal/program/joao-vale.md
content/events/2019-portugal/program/ken-mugrage.md
content/events/2019-portugal/program/manuel-pais.md
content/events/2019-portugal/program/pedro-torres.md
content/events/2019-portugal/program/pierre-vincent.md
content/events/2019-portugal/program/pranjal-deo.md
content/events/2019-portugal/program/rhys-evans.md
data/events/2019-portugal.yml

[PT-2019] Schedule definition

---

data/events/2019-santa-maria.yml

[SM-2019] Add Sponsor: JetBrains

[SM-2019] Add Sponsor: JetBrains, RevDebug

---

content/events/2019-houston/program/oleg-atamanenko.md

[HOU-2019] Adding another slides link

---

data/events/2019-raleigh.yml

[RDU-2019] Remove codefresh as sponsor

[RDU-2019] Remove codefresh as sponsor

---

content/events/2020-caceres/conduct.md
content/events/2020-caceres/contact.md
content/events/2020-caceres/location.md
content/events/2020-caceres/propose.md
content/events/2020-caceres/registration.md
content/events/2020-caceres/sponsor.md
content/events/2020-caceres/welcome.md
data/events/2020-caceres.yml

This PR includes:
- Team members
- Location
- Dates

[CC-2020] Initial 2020 Caceres

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] - fix typos

---

data/events/2019-kansas-city.yml

[KC-2019] - add gitlab as premium sponsor

---

content/events/2019-indianapolis/speakers/paul-meharg.md

[INDY-2019] Update speaker bio

---

content/events/2019-houston/program/sagar-karmarkar.md
content/events/2019-houston/program/shaun-ladewig.md

[HOU-2019] Added another two links to slides

---

content/events/2019-ghent/location.md

add more information based upon citcon recommendations
https://github.com/thinkinglabs/citcon-europe-2019-ghent/blob/master/README.md

[GHENT-2019] update location page

---

content/events/2019-galway/location.md
data/events/2019-galway.yml

[GAL-2019] Post venue location and dates

---

content/events/2019-bogota/sponsor.md

Changes in sponsors prices tables

[BOG-2019] Changes in sponsors prices tables

---

content/events/2019-tampa/program/dave-meurer.md
content/events/2019-tampa/program/marklyton-holmes.md
content/events/2019-tampa/speakers/dave-meurer.md
content/events/2019-tampa/speakers/marklyton-holmes.md
data/events/2019-tampa.yml

[TPA-2019] - Added Pivotal - Thank you!

[TPA-2019] - Added Pivotal

---

data/events/2019-raleigh.yml

[RDU-2019] added clearwater as sponsor.

[RDU-2019] added clearwater as sponsor.

---

content/events/2019-houston/program/donovan-brown.md
content/events/2019-houston/program/jj-asghar.md

[HOU-2019] Added slides for the last two talks

---

content/events/2019-indianapolis/welcome.md
data/events/2019-indianapolis.yml

[INDY-2019] Add info about training day

---

content/events/2019-washington-dc/sponsor.md

We know when it is and that there are two of them now.

[DC-2019] update Happy Hour details

---

content/events/2019-tampa/speakers/dave-meurer.md

[TPA-2019] - Updated Speakers

---

data/events/2019-chicago.yml

[CHI-2019] added appdynamics

---

content/events/2019-montevideo/sponsor.md
data/events/2019-montevideo.yml

* Add stickermule as sponsor
* add link to sponsor prospectus .pdf

[MVD-2019] Add stickermule as sponsor

---

data/events/2019-ghent.yml

[GHENT2019] Add pagerduty as gold sponsor

[GHENT2019] Add pagerduty as gold sponsor

---

content/blog/2019-ghent.md

[GHENT-2019] Add blog entry announcing 2019 ghent

---

content/events/2019-poznan/speakers/jakub-jakubik.md

[POZ-2019] Update Jakub Jakubik Bio

---

data/events/2019-raleigh.yml

[RDU-2019] added optum as sponsor

[RDU-2019] added optum as sponsor

---

content/events/2019-tampa/sponsor.md

[TPA 2019] Updated Sponsor Information

[TPA 2019] Updated Sponsor Information

---

data/events/2019-victoria.yml

[victoria-2019] added gitlab as a sponsor

---

content/events/2019-detroit/welcome.md
data/events/2019-detroit.yml

[DET-2018] Add chef to sponsors

---

content/events/2019-campinas/welcome.md
data/events/2019-campinas.yml

This PR adds the registration link and updates the event description.

[CAMP-2019] Adds registration link and updates the event description

---

content/page/organizing.md

Change to organizing doc to encourage default program

---

data/events/2019-raleigh.yml

[RDU-2019] added cloudbees as sponsor

[RDU-2019] added cloudbees as sponsor

---

content/events/2019-london/propose.md

It is too late to really provide submission help now.
Say that we will help if the talk is accepted.

[LDN-2019] Remove submission help

---

data/events/2019-amsterdam.yml

* Disable entries that do not confirm to the standard of payment received, than added to site.

[AMS-2019] bring in line agreed payment policy for devopsdays Amsterdam.

---

content/events/2019-porto-alegre/program/valdomiro-bilharvas.md

[POA-2019] Adjusting Valdomiro talk

---

content/events/2019-minneapolis/sponsor.md
data/events/2019-minneapolis.yml

[MSP-2019] Add cargill as ala-carte sponsor

---

content/events/2019-amsterdam/program/debra-dejong.md

[AMS-2019]  Update of a talk description

[AMS-2019] Updated talk description for Debra de Jong

---

data/events/2019-philadelphia.yml

[PHILLY] Add new organizer.

---

data/events/2019-minneapolis.yml

We have now received payment, so safe to add logo to our site.

[MSP-2019] Add back google cloud

---

data/events/2019-toronto.yml

[TOR-2019] Add sponsors

---

data/events/2019-portugal.yml

* program update: ignite talks

[PT-2019] program update

---

data/events/2019-bogota.yml

{BOG-2019] Cosmetic change for sponsors

---

content/events/2019-seattle/welcome.md
data/events/2019-baku.yml

[BAKU-2019] update Baku email address

---

data/events/2019-montreal.yml

Addition of date and location for MTL2019

[MTL-2019] Date and location change

---

data/events/2019-amsterdam.yml

- Add Microsoft
- Add Thoughtworks (Services)

[AMS-2019] add Microsoft and Thoughtworks

---

data/events/2019-kansas-city.yml

[KC-2019] - add dynatrace as premium sponsor

---

content/events/2019-houston/program/aaron-aldrich.md
content/events/2019-houston/program/donovan-brown.md
content/events/2019-houston/program/h-waldo-grunenwald.md
content/events/2019-houston/program/kevin-crawley.md

[HOU-2019] First attempt to embed SlidesLive into talk page(s)

---

data/events/2019-indianapolis.yml

[INDY-2019] Add StackRox as a silver sponsor

---

content/events/2019-portugal/speakers/ken-mugrage.md
content/events/2019-portugal/speakers/pierre-vincent.md
content/events/2019-portugal/speakers/rhys-evans.md

This will add a couple more Q&As with the event speakers for promotion

[PT-2019] add speaker inteviews 

---

data/events/2019-minneapolis.yml

[MSP-2019] Add overops as silver sponsor

---

content/events/2019-houston/program/aaron-aldrich-ignite.md
content/events/2019-houston/program/aaron-aldrich.md
content/events/2019-houston/program/chris-black.md
content/events/2019-houston/program/dan-kirkpatrick.md
content/events/2019-houston/program/donovan-brown.md
content/events/2019-houston/program/erik-peterson.md
content/events/2019-houston/program/h-waldo-grunenwald.md
content/events/2019-houston/program/jay-gordon.md
content/events/2019-houston/program/jj-asghar.md
content/events/2019-houston/program/john-esser.md
content/events/2019-houston/program/kevin-crawley.md
content/events/2019-houston/program/lee-barnes.md
content/events/2019-houston/program/margaret-valtierra.md
content/events/2019-houston/program/oleg-atamanenko.md
content/events/2019-houston/program/ramesh-podila.md
content/events/2019-houston/program/robert-reeves.md
content/events/2019-houston/program/sagar-karmarkar.md
content/events/2019-houston/program/shaun-ladewig.md

[HOU-2019] Embedded slideslive videos into all talks

---

content/events/2019-minneapolis/propose.md
content/events/2019-minneapolis/welcome.md

[MSP 2019] Ignites closed

---

content/events/2019-sydney/conduct.md
content/events/2019-sydney/contact.md
content/events/2019-sydney/location.md
content/events/2019-sydney/propose.md
content/events/2019-sydney/registration.md
content/events/2019-sydney/sponsor.md
content/events/2019-sydney/welcome.md
data/events/2019-sydney.yml

Adding sydney 2019 event to the list. :fireworks:

[SYD-2019] kickoff

---

content/events/2019-portugal/speakers/manuel-pais.md

one more interview (possibly the last in this event)

[PT-2019] add manuel pais interview on speaker page

---

content/events/2019-baku/registration.md
data/events/2019-baku.yml

The Baku team has decided to postpone the event to give them more time for planning. This PR removes the dates and registration links from the website.

[BAKU-2019] Postpone Baku event

---

static/events/2016-amsterdam/custom-workshops.css
themes/devopsdays-theme/static/scss/custom.scss

Removed some commented out code and new lines.

Theme CSS Cleanup

---

data/events/2019-amsterdam.yml

Add Eficode
Reduce Food truck to 3
Reduce Silver to 7

[AMS-2019] add Eficode, reduce foodtruck and silver

---

content/events/2019-montevideo/welcome.md
data/events/2019-montevideo.yml

Changed welcome site for MVD-2019 event.

[MVD-2019] Add description to welcome page

---

content/events/2019-aracaju/program/diego-oliveira.md
content/events/2019-aracaju/program/igor-macedo.md
content/events/2019-aracaju/program/rene-soares.md
content/events/2019-aracaju/speakers/diego-oliveira.md
content/events/2019-aracaju/speakers/igor-macedo.md
content/events/2019-aracaju/speakers/rene-soares.md
data/events/2019-aracaju.yml

Program Adjustments - 2019/05/27
- Speaker removal
- New speaker added
- New Ignite talks added

[DodAju-2019] Program Adjustments

---

data/events/2019-campinas.yml

This PR add AWS as a gold sponsor.

[CAMP-2019] Add new gold sponsor

---

data/events/2019-columbus.yml

A simple addition of a couple sponsors.

[Columbus 2019] Adding two sponsors

---

content/events/2019-london/propose.md
data/events/2019-london.yml

Remove link to submit and say our CFP is closed and set `cfp_open` to
false

[LDN-2019] The London 2019 CFP is now closed

---

content/events/2019-chicago/speakers/nathen-harvey.md

[Chi-2019] Nathen Harvey has a bio

---

data/events/2019-columbus.yml

Adding 3 existing sponsors
Adding 1 bio. Note that this one has a couple external links, I hope that is ok. If there is a better way of doing this, let me know, or if you don't want them, let me know and I can take them out.
Updating 1 bio.

[Columbus 2019] Adding three sponsors, and updating two bios.

---

content/events/2019-victoria/program.md

[2019-victoria] Correct punctuation on names

---

data/events/2019-tampa.yml

[TPA 2019] - Updated Program

---

content/events/2019-tampa/program.md

[TPA-2019] Fix frontmatter title on program page 

---

data/events/2019-sydney.yml

Adding a **working** cfp link :tada:

[SYD-2019] add CFP details

---

data/events/2019-minneapolis.yml

[MSP-2019] add xmatters as silver sponsor

---

content/events/2019-minneapolis/welcome.md
data/events/2019-minneapolis.yml

[MSP 2019] Revision update

---

content/events/2019-minneapolis/propose.md

[MSP 2019] CFP is closed

---

content/events/2019-minneapolis/program/emma-sax.md

Adding additional speaker details

[MSP 2019] Speaker details update

---

data/events/2019-chicago.yml

[CHI-2019] added slalom for chicago

---

data/events/2019-washington-dc.yml

[DC-2019] Launch the program

---

data/events/2019-indianapolis.yml

[INDY-2019] Add Blacks in Technology as a sponsor

---

content/events/2019-indianapolis/speakers/baruch-sadogursky.md
content/events/2019-indianapolis/speakers/ian-alford.md
content/events/2019-indianapolis/speakers/ramin-keene.md

[INDY-2019] Fix speaker links

---

data/events/2019-kansas-city.yml

Adding Contrast Security as premium sponsor

[KC-2019] add contrast security as sponsor

---

data/events/2019-minneapolis.yml

[MSP-2019] Add Contrast Security as silver sponsor

---

content/events/2019-minneapolis/program/megan-tischler.md

Title change for ignite speaker

[MSP 2019] Title change

---

content/events/2019-tampa/sponsor.md
content/events/2019-tampa/welcome.md

[TPA 2019] Site Updates

---

content/events/2019-minneapolis/speakers/carolyn-van-slyck.md

Fixing speaker twitter handle.

[MSP 2019] Fixing speaker twitter handle

---

content/events/2019-indianapolis/welcome.md

[INDY-2019] Add Tiffany as Ignite Karaoke host

---

data/events/2019-amsterdam.yml

[AMS-2019] Add CyberArk as sponsor

---

content/events/2019-minneapolis/sponsor.md
data/events/2019-minneapolis.yml

[MSP 2019] Gold sponsorships sold out

---

data/events/2019-indianapolis.yml

[INDY-2019] Add VictorOps as a gold sponsor

---

data/events/2019-washington-dc.yml

[DC-2019] add Palantir as platinum sponsor

---

content/events/2019-kansas-city/sponsor.md
content/events/2019-kansas-city/welcome.md

Made a few edits to the sponsor and welcome pages.

[KC-2019] - update sponsor and welcome page

---

data/events/2019-columbus.yml

[Columbus-2019] Adding three sponsors.

---

content/events/2019-chicago/program.md
data/events/2019-chicago.yml

Adding program/schedule for Chicago 2019

[CHI-2019] - Preliminary program

---

data/events/2019-dallas.yml

[DFW-2019] Exchanging VictorOps logo

---

data/events/2019-salvador.yml

[2019-SSA] Add Call for Papers

---

data/sponsors/securecodewarrior.yml
data/sponsors/statefarm.yml

[DFW-2019] Updating URL for 2 sponsors

---

data/events/2019-boston.yml

[BOS-2019] Replacing splunk with VictorOps

---

data/events/2019-amsterdam.yml

[AMS-2019] Re-enable vmware as sponsor

---

data/events/2019-washington-dc.yml

@nathenharvey @xzilla 
Both sponsors are Already Known™

[DC-2019] add SignalFX and GitLab as sponsors

---

content/events/2020-portland-me/conduct.md
content/events/2020-portland-me/contact.md
content/events/2020-portland-me/location.md
content/events/2020-portland-me/propose.md
content/events/2020-portland-me/registration.md
content/events/2020-portland-me/sponsor.md
content/events/2020-portland-me/welcome.md
data/events/2020-portland-me.yml

Initial integration for Portland, ME 2020 event.

[PWM-2020] Initial setup for Portland, ME 2020

---

data/events/2019-minneapolis.yml

[MSP-2019] Add target as gold sponsor

---

data/events/2019-chattanooga.yml

Forgot to add the speakers to the site nav for CHA

[CHA-2019] Add speakers to site nav

---

content/events/2019-amsterdam/program/nathen-harvey.md

[AMS-2019] Update formatting of SLO workshop

---

data/events/2019-dallas.yml

[DFW-2019] Adding Pagerduty as a sponsor

---

data/events/2019-philadelphia.yml

[PHILLY 2019] Add two sponsors.

---

data/events/2019-columbus.yml

Columbus 2019: Adding Liatrio as a sponsor.

---

data/events/2019-amsterdam.yml

[AMS-2019] Add Xebia as sponsor

---

data/events/2019-washington-dc.yml

[DC-2019] add Dynatrace as gold sponsor

---

content/events/2019-washington-dc/sponsor.md

@nathenharvey @xzilla 
Looks like:

[DC-2019] mention 5 min pitch during happy hour for HH sponsors

---

content/events/2019-chicago/registration.md
content/events/2019-chicago/welcome.md
data/events/2019-chicago.yml

Add registration information for Chicago 2019

[CHI-2019] Add registration link

---

content/events/2019-minneapolis/sponsor.md
data/events/2019-minneapolis.yml

We are out of space with several companies on a waiting list.

[MSP-2019] Mark silver as sold out

---

content/events/2020-new-york-city/conduct.md
content/events/2020-new-york-city/contact.md
content/events/2020-new-york-city/location.md
content/events/2020-new-york-city/propose.md
content/events/2020-new-york-city/registration.md
content/events/2020-new-york-city/sponsor.md
content/events/2020-new-york-city/welcome.md
data/events/2020-new-york-city.yml

Initial integration for New York City 2020 event.

[NYC-2020] - adding nyc 2020

---

data/events/2019-boston.yml

CircleCI is coming in at platinum.

[BOS-2019] Sponsor updates - week of 2019/06/16.

---

content/events/2019-washington-dc/location.md

[DC-2019] Fix a typo

---

content/events/2019-auckland/sponsor.md

[AKL-2019] Update sponsor page to include prospectus

---

data/events/2019-amsterdam.yml

This adds the rooms to our schedule.

[AMS-2019] Add workshop locations

---

data/sponsors/acellere.yml

[AMS-2019] fix url for Acellere

---

data/events/2019-galway.yml

Added Avaya as a silver sponsor for 2019

[GAL-2019] Add Avaya as silver sponsor

---

data/events/2019-salvador.yml

[SSA-2019] Add propose link

---

data/events/2019-taipei.yml

[TPE-2019] Add CFP link to Devopsdays Taipei

[TPE-2019]Add CFP link

---

data/events/2019-amsterdam.yml

[AMS-2019] re-enable Cap as sponsor

---

data/events/2019-boston.yml

[BOS-2019] Correcting Boston CFP close date.

---

data/events/2019-boston.yml

Adding LogDNA as a gold sponsor.

[BOS-2019] Sponsor updates - 2019/06/20.

---

data/events/2019-washington-dc.yml

Confirmed to reuse existing logo.
@xzilla @nathenharvey

[DC-2019] add New Relic as gold sponsor

---

data/events/2019-columbus.yml

Adding Jack Maher as an organizer. Ping on Slack to get his email to sign him up for Slack.

[Columbus-2019] Updating sponsor to a different level, adding Organizer

---

content/events/2019-amsterdam/speakers/suzanne-meerdink.md

[AMS-2019] Fix a typo in Suzanne her bio

---

data/events/2019-chattanooga.yml

Adds TVA & Appdynamics as gold sponsors.

[CHA-2019] Adds TVA & Appdynamics as sponsors

---

data/events/2019-dallas.yml

[DFW-2019] Adding Verizon as a sponsor

---

content/events/2019-dallas/contact.md

[DFW-2019] Adding Emeritus organizers missed

---

data/events/2019-minneapolis.yml

[MSP-2019] Add logdna to website as silver sponsor

---

data/events/2019-washington-dc.yml

[DC-2019] Adds Collabnet/VersionOne as Gold Sponsor

---

data/events/2019-campinas.yml

This PR adds Elastic as a bronze sponsor

[CAMP-2019] Add elastic as bronze sponsor

---

data/events/2019-berlin.yml

[Berlin-2019] add evening sponsor noris network

---

data/events/2019-minneapolis.yml

[MSP-2019] Add sumologic as gold sponsor

---

data/events/2019-chattanooga.yml

Adds BCBST as a gold sponsor for CHA.

[CHA-2019] Adds BCBST as sponsor

---

content/events/2019-auckland/registration.md
content/events/2019-auckland/welcome.md

[AKL-2019]  Update to early bird

---

data/events/2019-edinburgh.yml

[EDI-2019] Update bio for Michal Bryxí

---

content/events/2019-amsterdam/program/emile-vanhaaren-susanne-meerdink.md
content/events/2019-amsterdam/program/matteo-pierro-nelis-boucke.md
content/events/2019-amsterdam/speakers/nelis-boucke.md

Modify text as per request of speaker.

[AMS-2019] modify workshop text per request of speaker

---

data/events/2019-tel-aviv.yml

We have added the Gold Sponsor Big Panda - thanks!

[2019-TLV] New Sponsor - Big Panda

---

content/events/2019-florianopolis/speakers/diogo-beato.md
data/events/2019-florianopolis.yml

[FLN-2019] Update program and speaker name

---

data/events/2019-portland.yml

Chef and Instana are sponsoring

[Pdx-2019] 06-25 sponsor adds

---

data/events/2019-cairo.yml

Kindly replace mrashid@dxc.com by Sherien.sayed@dxc.com in organizers email: organizers-cairo-2019@devopsdays.org

[CAI-2019] Update event date & Organizer

---

data/events/2019-minneapolis.yml

[MSP-2019] Add chef as gold sponsor

---

content/events/2019-galway/registration.md
data/events/2019-galway.yml

One organizer has been unable to find time
Update an organizer employer
Open registration

[2019-GAL] Update organizers and Open Registration

---

data/events/2019-indianapolis.yml

[INDY-2019] Add Nutanix as a gold sponsor

---

content/events/2019-oslo/registration.md
data/events/2019-oslo.yml

Ready to open ticket sales for Devopsdays Oslo

[OSL-2019] ticket sales for Devopsdays Oslo

---

content/events/2019-philadelphia/sponsor.md

[PHILLY19] Fix sponsor language.

---

content/events/2018-indianapolis/sponsor.md
content/events/2019-indianapolis/sponsor.md

[INDY-2019] Fix typo

---

content/events/2019-indianapolis/speakers/martez-reed.md

[INDY-2019] New job for Martez

---

content/events/2019-chicago/sponsor.md

took out paypal gold link 
removed wifi and lanyard options - @mattstratton can you double check i didnt mess with the table format?

[CHI-2019] Sponsor update

---

content/events/2019-amsterdam/program/charity-majors.md

[AMS-2019] Add slides from Charity Majors

---

content/events/2019-amsterdam/program/yan-cui.md

[AMS-2019] Add slides from Yan Cui

---

content/events/2019-minneapolis/speakers/martez-reed.md

Updating bio for speaker who got a new job.

[MSP 2019] New job for speaker

---

data/events/2019-fortaleza.yml

FOR - 2019 - Add CFP dates and registration

---

data/events/2019-washington-dc.yml

OK to reuse existing logo and website URL.

[DC-2019] add Comcast as Silver sponsor

---

content/events/2019-tel-aviv/propose.md
data/events/2019-tel-aviv.yml

We have onboarded an additional sponsor and opened our call for papers.

[2019 -TLV] New Sponsor & CFP Open

---

content/events/2019-galway/registration.md

Adding a form that can handle registering user and email via ti.to interested list without leaving
the website.

[GAL-2019] Embedded ticket widget tweak and register interest form

---

data/events/2019-dallas.yml

[DFW-2019] Adding Sysdig as a sponsor

---

content/events/2019-galway/sponsor.md

[GAL-2019] Fixed typo in the sponsor page

---

content/events/2020-santiago/conduct.md
content/events/2020-santiago/contact.md
content/events/2020-santiago/location.md
content/events/2020-santiago/propose.md
content/events/2020-santiago/registration.md
content/events/2020-santiago/sponsor.md
content/events/2020-santiago/welcome.md
data/events/2020-santiago.yml

[SCL-2020] Placeholder for Santiago

---

content/events/2019-galway/propose.md
data/events/2019-galway.yml

[GAL-2019] Open CFP

---

data/events/2019-chicago.yml

[CHI-2019] tempus

---

content/events/2019-washington-dc/sponsor.md
data/events/2019-washington-dc.yml

* GovReady is captioning sponsor
* We are sold out of (or out of time for) the following sponsor types
* captioning
* media
* community

[DC-2019] Sponsor updates

---

content/events/2019-chicago/sponsor.md
data/events/2019-chicago.yml

We are sold out of Gold and Silver - remove CTA links and also make bronze button line up properly now :)

[CHI-2019] Update to remove gold and silver sponsorship options

---

content/events/2019-washington-dc/sponsor.md

Because rubber stamp effect is cool.

[DC-2019] add a rubber stamp effect to unavailable sponsorships

---

data/events/2019-raleigh.yml

[RDU-2019] Added signalfx and chef and set cloudbees correctly

[RDU-2019] Added signalfx and chef and set cloudbees correctly

---

content/events/2019-sydney/welcome.md

[SYD-2019] fix link

---

data/events/2019-minneapolis.yml

[MSP 2019] Adding newrelic

---

data/events/2020-santiago.yml

[SCL-2020] Updating website for Daniel

---

data/events/2019-indianapolis.yml

[INDY-2019] Add training workshop to program

---

content/events/2019-minneapolis/sponsor.md

[MSP 2019] Remaining a la carte sponsorships

---

data/events/2019-kansas-city.yml

[KC-2019] - add justification section

---

data/events/2019-indianapolis.yml

[INDY-2019] Use OracleCloud instead of Oracle

---

data/events/2019-dallas.yml

[DFW-2019] Adding Rundeck as a sponsor

---

content/events/2019-medellin/conduct.md
content/events/2019-medellin/contact.md
content/events/2019-medellin/location.md
content/events/2019-medellin/propose.md
content/events/2019-medellin/registration.md
content/events/2019-medellin/sponsor.md
content/events/2019-medellin/welcome.md
data/events/2019-medellin.yml

[MDE-2019] Adding placeholder for Medellin

---

data/events/2019-indianapolis.yml

[INDY-2019] Be clear that the expo hall is not open during breakfast

---

data/events/2019-dallas.yml

Reverts devopsdays/devopsdays-web#7614

Revert "[DFW-2019] Adding Rundeck as a sponsor"

---

content/events/2019-philadelphia/welcome.md
data/events/2019-philadelphia.yml

Add sponsors and ticket sales widget.

---

data/events/2019-ghent.yml

[Ghent-2019] Add Sentia as gold sponsor

---

data/events/2019-indianapolis.yml

[INDY-2019] Add Sonatype as a silver sponsor

---

data/events/2019-minneapolis.yml

[msp 2019] Adding wwc

---

data/events/2019-fortaleza.yml

FOR - 2019 - Add sponsor

---

data/events/2019-chicago.yml

[CHI-2019] Add ActiveCampaign as a silver sponsor

---

data/events/2019-minneapolis.yml

[MSP 2019] Adding MSFT

---

data/events/2019-minneapolis.yml

[MSP 2019] adding bit

---

data/events/2019-dallas.yml

[DFW-2019] Adding Chef as a sponsor

---

content/events/2020-madrid/conduct.md
content/events/2020-madrid/contact.md
content/events/2020-madrid/location.md
content/events/2020-madrid/sponsor.md
content/events/2020-madrid/welcome.md
data/events/2020-madrid.yml

location and dates added

---

content/events/2019-montevideo/program/donovan-brown.md
content/events/2019-montevideo/program/jessica-deen.md
content/events/2019-montevideo/speakers/jessica-deen.md

[MVD-2019] Add Donovan and Jessica talk description.

---

content/events/2019-edinburgh/sponsor.md
data/events/2019-edinburgh.yml

[EDI-2019] Update organiser details and correct sponsorship package prices

---

data/events/2019-cape-town.yml

* Adding Equal Experts as gold sponsor
* Updating my (Cobus) bio

[CPT 2019] Adding Equal Experts and fixing my bio

---

data/events/2019-dallas.yml

[DFW-2019] Adding NewRelic as a sponsor

---

content/events/2019-fortaleza/speakers/valdomiro-bilharvas.md

FOR - 2019 Update valdomiro-bilharvas.md

---

data/events/2019-boston.yml

[BOS-2019] Sponsor updates - 2019/07/16.

---

data/events/2019-raleigh.yml

[RDU-2019] added instana as sponsor

[RDU-2019] added instana as sponsor

---

data/events/2019-ghent.yml

[Ghent 2019] Add Elastic and Puppet as sponsors

---

data/events/2019-dallas.yml

[DFW-2019] Adding Scott Purgerson as a organizer

---

content/events/2019-galway/contact.md
data/events/2019-galway.yml

Unfortunately one of our organizers has to step back.

[GAL-2019] Update organizers

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] add chef as premium sponsor

---

data/events/2019-raleigh.yml

[RDU-2019] added community sponsor devopsinstitute

[RDU-2019] added community sponsor devopsinstitute

---

content/page/sponsor.md

Thanks to @ThePVD for the idea: https://github.com/devopsdays/devopsdays-web/issues/7644

Adjusting number of events.

---

content/events/2019-auckland/registration.md
content/events/2019-auckland/welcome.md
data/events/2019-auckland.yml

[AKL-2019] Close CFP, update registration and contact, add sponsor

---

data/events/2019-dallas.yml

[DFW-2019] Adding Mesosphere as a sponsor

---

data/events/2019-minneapolis.yml

Microsoft decided to sponsor at gold.

[MSP 2019] sponsorship update

---

data/events/2019-chicago.yml

Moved around timing on some stuff

[CHI-2019] Update program with new schedule for sponsor giveaways

---

content/events/2019-indianapolis/welcome.md

[INDY-2019] Update workshop pre-req's

---

data/events/2020-portugal.yml

Hi @eduardopiairo - welcome back! I fixed a few things in your PR (https://github.com/devopsdays/devopsdays-web/pull/7718) so please make sure you pull in upstream before editing again.

[Portugal 2020] Corrections

---

data/events/2019-chattanooga.yml

Updates to sponsors for Chattanooga's event.

[CHA-2019]Update sponsors w/ Compuware & Saucelabs

---

data/events/2019-indianapolis.yml

[INDY-2019] Update organizer info

---

data/events/2019-galway.yml

[GAL-2019] Add IBM as gold sponsor

---

data/events/2019-london.yml

Chef paid for Gold
Buildkite went for Bronze

[LDN-2019] Add Buildkite and Chef

---

content/events/2019-galway/sponsor.md

Add highlighting to sponsors table
Include FAQ ahead of expected questions

[GAL-2019] Update sponsors page

---

data/events/2019-raleigh.yml

[RDU-2019] added puppet as sponsor

[RDU-2019] added puppet as sponsor

---

data/events/2019-indianapolis.yml

[INDY-2019] Remove Byron as an organizer

---

content/events/2019-minneapolis/program/chaos-engineering.md
content/events/2019-minneapolis/speakers/ana-margarita-medina.md

[MSP 2019] Updating Ana

---

data/events/2019-minneapolis.yml

Title change with new job role.

[MSP 2019] Bridget bio

---

CONTRIBUTING.md

Add the commands needed to use latest Hugo on OS X

Update docs with OS X fix for hugo

---

content/events/2019-philadelphia/speakers/daniela-vieira.md
content/events/2019-philadelphia/speakers/karoline-leite.md

[PHILLY-2019] Add speaker bios for workshop speakers.

---

content/events/2019-edinburgh/welcome.md

Link to a third party website that is arranging accommodation.

[EDI-2019] Accommodation options for Edinburgh

---

content/events/2019-edinburgh/sponsor.md

cc: @mjslane - noticed that we never changed the number of tickets in the bronze package on website

[EDI-2019] - Change in number of tickets in bronze package

---

data/events/2019-chicago.yml

[CHI-2019] Remove volunteer form from Chicago and update evening event

---

data/events/2019-columbus.yml

[Columbus-2019] Adding stickermule as a community sponsor.

---

data/events/2019-stockholm.yml

Moving Daniel Maher (me) to the second day, as per email exchange between myself and @lsc. 😄

[Stockhom-2019] move Daniel Maher to 2nd day

---

content/events/2019-edinburgh/welcome.md

As title says. Currently the link is some weird "internal" link hybrid that does not work.

[EDI-2019] - fix accomodation link

---

data/events/2019-cairo.yml

[CAI-2019] Extending CFP closure date

[CAI-2019] Extending CFP closure date

---

data/events/2019-dallas.yml

[DFW-2019] Adding Beyondsoft as a sponsor

---

content/events/2019-montreal/propose.md
content/events/2019-montreal/registration.md
content/events/2019-montreal/welcome.md
data/events/2019-montreal.yml

add link to registration form.
add some french links
add link to twitter

[MTL-2019] Add registration link

---

content/events/2019-medellin/welcome.md

[MDE-2019] Updating Title of Welcome.md

---

content/events/2019-dallas/program/dana-finster.md

[DFW-2019] Updating Dana's abstract

---

content/events/2019-washington-dc/program/marianne-bellotti.md

[DC-2019] Add audio version of Marianne's talk

---

content/events/2019-dallas/program.md
content/events/2019-dallas/speakers/aaron-mell.md
data/events/2019-dallas.yml

[DFW-2019] Updating Speaker Bio & Program

---

content/events/2019-paris/welcome.md
data/events/2019-paris.yml

Replace stub with actual information.
cc @jooooooon

[Paris-2019] The event is happening!

---

content/events/2019-dallas/sponsor.md

[DFW-2019] Correcting mistake for Platinum

---

content/events/2019-dallas/sponsor.md

[DFW-2019] Updating Coffee Bar sponsorship

---

content/events/2019-ghent/welcome.md

Added more text to the Ghent Welcome page.

[GENT-2019] Updating Ghent welcome page

---

content/events/2019-dallas/speakers/bjorn-edwin.md

[DFW-2019] Updating Bjorn's bio

---

data/events/2019-raleigh.yml

[RDU-2019] Sponsorship cloudbees bump up

[RDU-2019] Sponsorship cloudbees bump up

---

data/events/2019-fortaleza.yml

FOR 2019 - Update 2019-fortaleza.yml

---

content/events/2019-dallas/program/ross-clanton.md

[DFW-2019] Adding Ross Clanton's abstract

---

data/events/2019-tel-aviv.yml

Added three new sponsors - thanks!

[2019-TLV] New Sponsors Added

---

content/events/2019-belo-horizonte/registration.md
data/events/2019-belo-horizonte.yml

Changelog:
- CFP and tickets inclusion

BHE-2019-new-tickets

---

content/events/2019-raleigh/program/dave-stanke.md
content/events/2019-raleigh/speakers/ben-bleything.md

[RDU-2019] Corrected ben bleything's name

[RDU-2019] Corrected ben bleything's name

---

data/events/2019-raleigh.yml

[RDU-2019] removed adam ignite on first day

[RDU-2019] removed adam ignite on first day

---

content/events/2019-philadelphia/program/zero-to-hero.md

Update zero-to-hero.md with details of the workshop.

[PHI-2019] Updating workshop info

---

data/events/2019-paris.yml

[Paris-2019] update sponsors and organisers

---

data/events/2019-raleigh.yml

[RDU-2019] Added Google Analytics tracking code

[RDU-2019] Added Google Analytics tracking code

---

content/events/2019-columbus/sponsor.md
data/events/2019-columbus.yml

Simple sponsor add. Removing gold paypal link

[Columbus 2019] Adding Gitlab sponsor, removing gold paypal links.

---

data/events/2019-dallas.yml

[DFW-2019] Making Program Swap Changes

---

data/events/2019-dallas.yml

[DFW-2019] Adding Sonatype as a sponsor

---

data/events/2019-dallas.yml

[DFW-2019] Adding GitLab as a sponsor

---

content/events/2019-dallas/program/adrian-cockcroft.md

[DFW-2019] Adding Adrian's Keynote Abstract

---

data/events/2019-dallas.yml

[DFW-2019] Adding Program Updates

---

content/events/2019-dallas/welcome.md
data/events/2019-dallas.yml

[DFW-2019] Removing Propose menus

---

data/events/2019-kansas-city.yml

[KC-2019] add sonatype as premium sponsor

---

content/events/2019-minneapolis/program/heidi-waterhouse.md
content/events/2019-minneapolis/program/jenn-strater.md
content/events/2019-minneapolis/program/liz-fong-jones.md
content/events/2019-minneapolis/program/serena-tiede.md

[MSP 2019] Adding slides

---

data/events/2019-dallas.yml

[DFW-2019] Adding VMware as a sponsor

---

data/events/2019-raleigh.yml

[RDU-2019] added stackrox

---

content/events/2019-dallas/sponsor.md

[DFW-2019] Updating Coffee Bar sponsors 

---

data/events/2019-kansas-city.yml

[KC-2019] add TGS as supporting sponsor

---

content/events/2020-prague/propose.md
content/events/2020-prague/sponsor.md
content/events/2020-prague/welcome.md
data/events/2020-prague.yml

Just some recent updates for DevOpsDays Prague 2020.

[PRG-2020] Sponsorship update and CFP release.

---

data/events/2020-seattle.yml

[SEA-2020] update dates for Seattle 2020

---

data/events/2019-cape-town.yml

Adding Microsoft and Nedbank as sponsors. Ready for merging.

[CPT-2019] Adding Microsoft and Nedbank

---

data/events/2019-galway.yml

[GAL-2019] Add gold sponsor to website

---

data/events/2019-kansas-city.yml

[KC-2019] add nutanix as premium sponsor

---

data/events/2019-auckland.yml

[AKL-2019] Added sponsors: GCP, Hashicorp, PagerDuty, Gitlab, and Sonatype

---

data/events/2019-tel-aviv.yml
data/sponsors/newrelic.yml

[2019-TLV] New Sponsor added

---

data/events/2019-galway.yml

[GAL-2019] Add HPE to Gold sponsors

---

data/events/2019-galway.yml

Adding our latest gold sponsor

[GAL-2019] Add Google Cloud to Gold sponsors

---

data/events/2019-dallas.yml

[DFW-2019] Updated Program

---

data/events/2019-dallas.yml

[DFW-2019] Adding Qualia last sponsor

---

data/events/2019-chicago.yml

A BHE PR edited this file for some reason and removed Jessie Frazelle.

CHI-2019] Add fraz back to chicago

---

data/events/2019-stockholm.yml

[STH-2019] add Gitlab as sponsor

---

.circleci/config.yml
hugoserver.sh
netlify.toml
themes/devopsdays-theme/theme.toml

I have tested the build with this version and it seems to work fine.

Upgrade Hugo to 0.57.1

---

content/events/2019-columbus/sponsor.md

Removing silver paypal Button.

[Columbus-2019] Removing silver paypal button

---

data/events/2019-tel-aviv.yml

[2019 TLV] New Sponsor Added

---

data/events/2019-buffalo.yml

Adding App Dynamics as a Silver Sponsor

[BUF-2019] Adding App Dynamics as a Silver Sponsor

---

content/events/2019-kansas-city/program.md
data/events/2019-kansas-city.yml

We'll slot speakers as we get their acceptances and we come up with the schedule

[KC-2019] Publish initial schedule

---

data/events/2019-kansas-city.yml

[KC-2019] Add circleci as a sponsor

---

data/events/2019-kansas-city.yml

[KC-2019] consolidate open spaces in schedule

---

data/events/2019-columbus.yml
data/sponsors/2015-covermymeds.yml

App Dynamics gold
VMWare gold
Ahead silver
Checkpoint bronze
CoverMyMeds requested the URL update.

[Columbus-2019] Sponsor updates.

---

content/events/2019-edinburgh/welcome.md
data/events/2019-edinburgh.yml

[EDI-2019] enable some main menu items

---

data/events/2019-chicago.yml

[CHI-2019] Update objective sponsor URL for 2019 Chicago event only

---

content/events/2019-kansas-city/program/clay-thomas.md
content/events/2019-kansas-city/program/joel-tosi.md
content/events/2019-kansas-city/program/justin-james.md
content/events/2019-kansas-city/program/kate-wardin.md
content/events/2019-kansas-city/program/mofizur-rahman.md
content/events/2019-kansas-city/program/rich-mogull.md
content/events/2019-kansas-city/program/sasha-rosenbaum.md
content/events/2019-kansas-city/program/steph-hicks.md
content/events/2019-kansas-city/program/steve-grossman.md
content/events/2019-kansas-city/program/tom-cudd.md
data/events/2019-kansas-city.yml

[KC-2019] - add rooms to workshops

---

data/events/2019-amsterdam.yml
data/events/2019-minneapolis.yml
utilities/README.md
utilities/examples/content/events/yyyy-city/propose.md
utilities/examples/data/events/yyyy-city.yml

Changing cityname in the templates and the cities requesting it.

Updating cityname

---

data/events/2019-stockholm.yml

[STH-2019] set same start time as on posters

---

utilities/add_new_event.sh
utilities/examples/data/events/yyyy-city.yml

Make sure email address for cities is generated correctly

Edits for generator scripts

---

content/events/2019-minneapolis/program/jessica-kerr.md
content/events/2019-minneapolis/program/liz-fong-jones.md
content/events/2019-minneapolis/program/nivia-henry.md
content/events/2019-minneapolis/program/yolonda-smith.md

Adding the first four talk videos.

[MSP 2019] Adding MSP talk videos

---

data/events/2018-florianopolis.yml

This date issue was leading to this event showing up in "coming, date TBD".

Fixing date issue

---

content/events/2020-madison/conduct.md
content/events/2020-madison/contact.md
content/events/2020-madison/location.md
content/events/2020-madison/propose.md
content/events/2020-madison/registration.md
content/events/2020-madison/sponsor.md
content/events/2020-madison/welcome.md
data/events/2020-madison.yml

Pushing Madison to 2020 as I'm given to understand it cannot be scheduled in 2019. (Please let me know if I'm mistaken!)

Madison 2020

---

data/events/2019-baku.yml

Updating this TBD event for new email format. Removing location, as date isn't set.

[Baku] Updating email for TBD event

---

content/events/2020-geneva/propose.md
data/events/2020-geneva.yml

* add cfp dates
* add menus for location and propose

[GE-2020] Add CFP Dates

---

data/events/2019-portland.yml

[PDX-2019] Begin training sessions one hour later than previously planned

---

content/events/2019-montreal/propose.md

Finishing updating all locations we link to CFP (hopefully all them, now)

[MTL-2019] Added other papercall links to landing

---

data/events/2019-montreal.yml

AKA The I'm an idiot merge, and didnt realize how many places this appears.

[MTL-2019] Swap over to papercall #3

---

data/events/2019-cape-town.yml

Day is too long and we haven't filled them

[Cape Town 2019] Remove two extra speaking slots

---

content/events/2019-chicago/program/adam-shake.md
content/events/2019-chicago/program/baron-schwartz.md
content/events/2019-chicago/program/heidi-waterhouse-2.md
content/events/2019-chicago/program/holly-allen.md
content/events/2019-chicago/program/karissa-peth.md
content/events/2019-chicago/program/pete-cheslock.md

[CHI-2019] Add some Chicago slides

---

content/events/2019-amsterdam/program/daniel-maher.md

Add noti.st link for Daniel Maher's workshop (see #8072)
cc @mattstratton for verification on proper usage

[AMS-2019] Add noti.st link for Daniel Maher

---

content/events/2019-chicago/program/aaron-blythe.md

I'm going to try to batch these up, I promise :)

[CHI-2019] Add slides for Aaron Blythe

---

content/events/2017-minneapolis/program/kristen-womack.md
themes/devopsdays-theme/layouts/talk/single.html

Possible partial fix for https://github.com/devopsdays/devopsdays-web/issues/6542. Minimally tested but seems to help in this case.

PDF fix test (with test PDF re-added).

---

content/events/2019-chicago/program/holly-allen.md
content/events/2019-chicago/program/pete-cheslock.md

Adding some PDF links for @mattstratton.

[Chicago 2019] Adding Chi PDFs

---

data/events/2019-kansas-city.yml

[KC-2019] add c2fo as premium sponsor

---

content/events/2019-minneapolis/program/brianna-mccullough.md
content/events/2019-minneapolis/program/chelsey-mckinney.md
content/events/2019-minneapolis/program/emma-sax.md
content/events/2019-minneapolis/program/heidi-waterhouse.md
content/events/2019-minneapolis/program/jason-yee.md
content/events/2019-minneapolis/program/jenn-strater.md
content/events/2019-minneapolis/program/megan-tischler.md
content/events/2019-minneapolis/program/peg-mickelson.md
content/events/2019-minneapolis/program/steve-pereira.md
content/events/2019-minneapolis/program/steve-persch.md

Adding video links for Ignites.

[MSPP 2019] Adding links to videos

---

themes/devopsdays-theme/layouts/partials/sponsors.html

Improvement beyond https://github.com/devopsdays/devopsdays-web/pull/7468 to correct https://github.com/devopsdays/devopsdays-web/issues/7524.

sponsorship wording fix

---

content/events/2018-amsterdam/program/matt-stratton-ig.md
content/events/2018-amsterdam/program/matt-stratton.md
content/events/2018-indianapolis/program/matt-stratton.md
content/events/2018-kansas-city/program/matty-stratton.md
content/events/2018-kansas-city/program/matty-stratton2.md
content/events/2018-minneapolis/program/incident-response.md
content/events/2018-philadelphia/program/matty-stratton.md
content/events/2018-silicon-valley/program/matt-stratton.md
content/events/2018-toronto/program/matty-stratton.md
content/events/2019-amsterdam/program/matty-stratton.md
content/events/2019-copenhagen/program/matty-stratton.md
content/events/2019-minneapolis/program/blameless-postmortems.md
content/events/2019-new-york-city/program/matty-stratton.md

MSP-2019
AMS-2019
AMS-2018
INDY-2018
KC-2018
MSP-2018
PHL-2018
SV-2018
TOR-2018
CPH-2019
NYC-2019

Add notist slide embeds for a bunch of Matt Stratton talks

---

content/events/2019-kansas-city/speakers/roger-noah.md

There is no image for Roger Noah. This change replaces the broken image with the default speaker image.
@aaronblythe please check this out.

[KC-2019] Fix broken image for Roger Noah

---

data/events/2020-atlanta.yml

[ATL-2020] adding 2nd H to Lac(h)hman.

---

content/events/2019-kansas-city/program/joel-tosi.md

[KC-2019] adjust room for speaker

---

content/events/2019-chicago/program/jennifer-petoff-nathen-harvey.md

This also makes a minor formatting change to the description of the workshop

[CHI-2019] Embed slides for the SLO workshop

---

data/events/2019-portland.yml

I somehow set this up and didn't PR it a week ago? Geez.

[PDX-2019] Ading RedisLabs, Invoca, CircleCI, and Puppet!

---

content/events/2019-kansas-city/sponsor.md
content/events/2019-kansas-city/welcome.md

[KC-2019] Remove PayPal link for Premium sponsorship + welcome page updates

---

content/events/2020-salt-lake-city/propose.md
content/events/2020-salt-lake-city/welcome.md
data/events/2020-salt-lake-city.yml

-Open CFP
-Update dates and text around CFP

[SLC-2020] Opening CFP and updating associated dates

---

data/events/2019-cairo.yml

[CAI-2019] Add sponsor

---

content/events/2019-cape-town/program/daniel-maher.md

Minor adjustment to the description.
cc @adrianmoisey

[Cape Town-2019] update Daniel Maher's talk description

---

content/events/2019-stockholm/speakers/marcus-olsson.md

[STH-2019] update Marcus' bio with new employer

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] add stackify as premium sponsor

---

content/events/2019-philadelphia/speakers/tim-gross.md

Belatedly updating my bio for Philly 2019.
cc @peterjshan

[PHILLY-2019] updated bio for Tim Gross

---

content/events/2019-portland/program/blameless-postmortems.md
content/events/2019-portland/program/stacy-watts.md
data/events/2019-portland.yml

[PDX-2019] Add description to Git 201 training, fix Matty's postmortem training

---

data/events/2019-london.yml

We've got jfrog as a sponsor now so lets add that.

[LDN-2019] Add jfrog as gold sponsor

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] add New Context as evening social sponsor

---

data/events/2019-chattanooga.yml

Updating our site data to include Unum.

[CHA-2019]Adds Unum as 2019 sponsor

---

content/events/2019-berlin/program/steffen-siering.md

I am very good at finding mistakes once it actually is too late :/

[BER-2019] Clarify in program that Steffen Siering is offering a Workshop

---

data/events/2019-buffalo.yml

Moved Stacey Jenkins to an earlier time slot per his request.
Added headshot credit for Quintessence's bio per her request.

[BUF-2019] Changing a speakers time, Adjusting organizers bio

---

content/events/2019-stockholm/program/waldo-g.md

[STH-2019] update Waldo's talk title

---

data/events/2019-raleigh.yml

[RDU-2019] split.io sponsor

---

data/events/2019-montreal.yml

[MTL-2019] Add sponsors: AWS, Dynatrace, GitLab, and Sonatype.

---

themes/devopsdays-theme/REFERENCE.md

Fixes #8170
This adds documentation around some additional shortcodes. Not that anyone asked for it, but I felt like being a completionist.

Add shortcodes to REFERENCE.md

---

data/events/2019-cape-town.yml

[Cape Town 2019] Have less breaks between closing and first open space

---

content/events/2019-ghent/program/ant-stanley.md
content/events/2019-ghent/program/blerim-sheqa.md
content/events/2019-ghent/program/bridget-kromhout.md
content/events/2019-ghent/program/chris-corriere.md
content/events/2019-ghent/program/george-miranda.md
content/events/2019-ghent/program/jason-yee.md
content/events/2019-ghent/program/jj-asghar.md
content/events/2019-ghent/program/jody-wolfborn.md
content/events/2019-ghent/program/joshua-zimmerman.md
content/events/2019-ghent/program/ken-mugrage.md
content/events/2019-ghent/program/matty-stratton.md
content/events/2019-ghent/program/michael-ducy.md
content/events/2019-ghent/program/nigel-kersten.md
content/events/2019-ghent/program/patrick-debois.md
content/events/2019-ghent/program/sasha-rosenbaum.md
content/events/2019-ghent/program/stephen-nelson-smith.md

[Ghent 2019] Add talk descriptions

---

content/events/2019-raleigh/program/eric-d-schabell.md

[RDU-2019] updated workshop info

[RDU-2019] updated workshop info

---

content/events/2019-detroit/welcome.md

Making sure the updates from https://github.com/devopsdays/devopsdays-web/pull/8187 are linked on the welcome page. /cc @archieco

[Detroit 2019] Menu updates

---

content/events/2018-cape-town/program/cari-liebenberg.md
content/events/2018-cape-town/program/christo-goosen.md
content/events/2018-cape-town/program/darin-morris.md
content/events/2018-cape-town/program/graeme-glass.md
content/events/2018-cape-town/program/gunter-grodotzki.md
content/events/2018-cape-town/program/jaco-greyling.md
content/events/2018-cape-town/program/jared-naude.md
content/events/2018-cape-town/program/joe-nuspl.md
content/events/2018-cape-town/program/karl-fischer.md
content/events/2018-cape-town/program/keegan-carruthers-smith.md
content/events/2018-cape-town/program/marek-denis.md
content/events/2018-cape-town/program/mark-derman.md
content/events/2018-cape-town/program/mpho-mphego.md
content/events/2018-cape-town/program/pieter-breed.md

Just a bit of time travelling here.
Looks like the full YouTube URL is incorrect, so these never worked.

[Cape Town 2018] Fix 2018 videos

---

content/page/open-space-format.md

I'm not entirely convinced that it's been added in the best location, using the best description, but I can't figure out how to improve it.
Suggestions welcome!
Relates to https://github.com/devopsdays/devopsdays-web/issues/8191

Add Dan's slide-deck to openspaces page

---

themes/devopsdays-theme/layouts/partials/head/seo.html

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
Fixes #8189

Add Event and Dates to the Slack unfurl

---

data/events/2019-stockholm.yml

[STH-2019] add Vatech as sponsor

---

netlify.toml

We don't need this on the deploy previews, and this will speed things up

Skip post processing on deploy previews

---

content/events/2019-columbus/program/nathen-harvey-keynote.md
content/events/2019-columbus/speakers/nathen-harvey.md

* Describe the keynote that was previously 'TBD'
* Update bio for Nathen

[CBUS-2019] Details for Nathen Harvey's keynote

---

content/events/2019-ghent/program/sasha-rosenbaum.md

[2019-Ghent] Remove takeways in Sasha her talk

---

content/events/2020-geneva/newsletter.md
content/events/2020-geneva/welcome.md
data/events/2020-geneva.yml

* add a new page with newsletter subscription form
* add a link to this new page in the welcome page

[GE-2020] Add newsletters form

---

data/events/2019-raleigh.yml

[RDU-2019] Updated happy hour schedule

---

data/events/2019-raleigh.yml

[RDU-2019] updated ignite schedule

[RDU-2019] updated ignite schedule

---

content/events/2019-ghent/program/joshua-zimmerman.md

Updating my talk description for Ghent. Was told by Rudy Gevaert that I could just submit the PR.

[Ghent-2019] Updates to Joshua Zimmerman's talk for devopsdays Ghent.

---

data/events/2019-portland.yml

Probably not the best way to do it, but, 🤷‍♂

[PDX-2019] Adding party details

---

data/events/2019-stockholm.yml

[STH-2019] switch Chris and Aubrey due to flight plans

---

content/events/2019-stockholm/program/daniel-maher-2.md
data/events/2019-stockholm.yml

Kris had to cancel but we had already asked Daniel to be backup for him - so here we go.

[STH-2019] replace Kris with Daniel

---

content/events/2019-chicago/program/aaron-blythe.md
content/events/2019-chicago/program/adam-shake.md
content/events/2019-chicago/program/baron-schwartz.md
content/events/2019-chicago/program/garima-sharma.md
content/events/2019-chicago/program/heidi-waterhouse-2.md
content/events/2019-chicago/program/heidi-waterhouse.md
content/events/2019-chicago/program/holly-allen.md
content/events/2019-chicago/program/j-paul-reed.md
content/events/2019-chicago/program/jason-yee.md
content/events/2019-chicago/program/jay-gordon.md
content/events/2019-chicago/program/jeff-smith.md
content/events/2019-chicago/program/jennifer-petoff-nathen-harvey.md
content/events/2019-chicago/program/jessie-frazelle.md
content/events/2019-chicago/program/joshua-zimmerman.md
content/events/2019-chicago/program/karissa-peth.md
content/events/2019-chicago/program/kevin-harriss.md
content/events/2019-chicago/program/lakshmi-baskaran.md
content/events/2019-chicago/program/martez-reed.md
content/events/2019-chicago/program/michael-stahnke.md
content/events/2019-chicago/program/nick-petrovits-allen-nelson.md
content/events/2019-chicago/program/pete-cheslock.md
content/events/2019-chicago/program/veronica-hanus.md

Videos are live!
Also changed Aaron Blythe's slides to an https link to get rid of those netlify messages :)

[CHI-2019] Add all videos from 2019 event

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] add teksystems and azul systems as sponsors

---

content/events/2020-tampa/welcome.md

[TPA-2020] Modified welcome page order and added twitter info

[TPA-2020] Modified welcome page order and added twitter info

---

data/events/2019-stockholm.yml

[STH-2019] shorten event dinner

---

data/events/2019-boston.yml

[BOS-2019] VMware as sponsor.

---

content/events/2019-ghent/program/julie-gunderson.md

Julie submitted an update abstract

[2019-Ghent] Update talk Julie Gunderson

---

package-lock.json
package.json

Upgrade version of netlify cli

Greenkeeper/netlify cli 2.15.0

---

content/events/2019-stockholm/registration.md
data/events/2019-stockholm.yml

[STH-2019] we're sold out

---

content/events/2019-stockholm/location.md

[STH-2019] update venue links

---

data/events/2019-salvador.yml

[SSA-2019] Add Solutis as gold sponsor

---

content/events/2019-baltimore/sponsor.md

This fixes an ongoing shortcode issue cropping up here. (See https://github.com/devopsdays/devopsdays-web/issues/6599 for details.)

Fixing rebuild issue

---

data/events/2019-raleigh.yml

[RDU-2019] Fixed afternoon times

---

content/events/2019-raleigh/program/wendy-raschke-talk.md
data/events/2019-raleigh.yml

[RDU-2019] fixed Wendy talk

---

utilities/README.md

Updating docs to match change from https://github.com/devopsdays/devopsdays-web/pull/8289.

Updating per new convention

---

content/events/2019-cape-town/program/gareth-mccumskey.md
content/events/2019-cape-town/program/rory-preddy.md

- Change Gareth's talk to be embedded
- Add Rory's talk

[Cape Town 2019] More talk slides

---

data/events/2019-raleigh.yml

[RDU-2019] added contrast security as sponsor

[RDU-2019] added contrast security as sponsor

---

content/events/2019-oslo/welcome.md

[OSL-2019] New welcome page layout

---

data/events/2019-raleigh.yml

swapped 
anne-hungate
ann-marie-fred

[RDU-2019] schedule updates anne - ann swap

---

data/events/2019-buffalo.yml

[BUF-2019] Adding sponsor slots and schedule fixes

---

data/events/2019-salvador.yml

[SSA-2019] Change location

---

data/events/2019-kansas-city.yml

[KC-2019] add AppDynamics as Premium sponsor

---

data/core.toml

Adding new core team member

---

content/events/2019-belo-horizonte/speakers/juliano-silveira.md
content/events/2019-belo-horizonte/speakers/marco-mendes.md
content/events/2019-belo-horizonte/speakers/sergio-passos.md
content/events/2019-belo-horizonte/speakers/zandler-oliveira.md

Four speakers' images aren't in the repo - this fixes the broken images. @devopsdaysbh @gomex @MikeRosTX this is what I was talking about here: https://github.com/devopsdays/devopsdays-web/pull/8341#issuecomment-533665709

[BH 2019] Fixing broken images

---

utilities/README.md

Fixes https://github.com/devopsdays/devopsdays-web/issues/8162.

Adding explanation for sponsor updates

---

data/events/2011-melbourne.yml

I discovered the listed date was inaccurate.

Correcting dates for past event

---

content/page/organizing.md

As noted in https://github.com/devopsdays/devopsdays-web/issues/8192 there are some places the organizer guide needed updates and clarifications. (Please submit more if desired.)

Updates and clarifications for organizer guide

---

content/events/2019-oslo/program/ambreen-sheikh.md
content/events/2019-oslo/program/henrik-stene.md
content/events/2019-oslo/program/johan-abildskov.md
content/events/2019-oslo/program/kat-liu.md
content/events/2019-oslo/program/mike-long.md
content/events/2019-oslo/program/pia-fak-sunnanbo.md
content/events/2019-oslo/program/rafa-maanij.md
content/events/2019-oslo/program/renata-rocha.md
content/events/2019-oslo/program/ulf-mansson.md
data/events/2019-oslo.yml

Added more program, and program types.

[OSL-2019] Added more program

---

content/events/2019-fortaleza/speakers/eduardo-cavalcanti.md

FOR - 2019 - Update eduardo-cavalcanti.md

---

content/page/organizing.md

Adding budgeting reminder discouraging extravagant organizer expenses.

Organizing update

---

data/events/2019-oslo.yml

Ignite texts aren't showing up in the program as they should.

[OSL-2019] Fix date format to link up with ignites

---

data/events/2019-oslo.yml

With the previous version, we got two October 22nds and two October 23rds. Maybe this will fix both.

[OSL-2019] Fixing it again, so we get a single 22nd of October and not two.

---

data/events/2019-oslo.yml

Typo in names, broken links. This fixes it.

[OSL-2019] Fixed typos.

---

content/page/organizing.md

As pointed out by @phrawzty, currencies and local prices vary, so we want to be less dollar/euro-centric about typical costs.

Clarifying ticket costs

---

data/events/2019-fortaleza.yml

FOR - 2019 - Update 2019-fortaleza.yml

---

content/events/2019-philadelphia/program/arrested-devops.md
data/events/2019-philadelphia.yml

Approval requested from @peterjshan.

[Philly 2019] Adding ADO episode

---

content/events/2020-geneva/propose.md

[GE-2020] Activate proposal form

---

data/events/2019-oslo.yml

[OSL-2019] Swapped a couple of Ignite speakers

---

data/events/2019-kansas-city.yml

[KC-2019] add googlecloud and signalfx as premiums sponsors

---

data/events/2019-oslo.yml

[OSL-2019] Updated program

---

data/core.toml

Adding Yvo and Mine

---

data/events/2019-galway.yml

Add lanyard and sticker sponsors as support level.

[GAL-2019] Add support sponsors

---

data/events/2019-raleigh.yml

[RDU-2019] Added Docker as sponsor

[RDU-2019] Added Docker as sponsor

---

content/events/2020-amsterdam/conduct.md
content/events/2020-amsterdam/contact.md
content/events/2020-amsterdam/location.md
content/events/2020-amsterdam/propose.md
content/events/2020-amsterdam/registration.md
content/events/2020-amsterdam/sponsor.md
content/events/2020-amsterdam/welcome.md
data/events/2020-amsterdam.yml

We're doing another event next year. Who could have guessed?
This PR initializes the devopsdays Amsterdam 2020 event.
Created with `utilities/add_new_event.sh` and only added organizers for next year.
Let me know if anything else needs to be added.

[AMS2020] Let's get this party started

---

data/events/2020-denver.yml

Added Erin and Twitter for Jason Sharp

[DEN-2020] Added Team Info

---

data/events/2019-ghent.yml

[2019-ghent] Add stickermule as sponsor, stop accepting sponsors

---

data/events/2020-madrid.yml

[MAD-2020] CFP dates change

---

content/events/2019-ghent/sponsor.md

[2019-ghent] no drinks by sponsors

---

content/events/2019-ghent/program/julie-gunderson.md
content/events/2019-ghent/speakers/kimball-johnson.md

* Change Julie's talk title per request
* Change Kimball's bio per request

[GHENT2019] Modify talk title and bio per requests

---

content/events/2019-belo-horizonte/speakers/juliano-silveira.md
data/events/2019-belo-horizonte.yml

Hi @gomex , I need fix link for Juliano Silveira, and fix position workshop in program.

Bhe 2019 updates

---

content/events/2019-stockholm/program/johan-abildskov.md

[STH-2019] add Johan's slides

---

content/events/2020-geneva/contact.md
content/events/2020-geneva/propose.md
content/events/2020-geneva/sponsor.md

* update sponsor.md with sponsor details
* add default subject for email links

[GE-2020] update sponsors page with details

---

content/events/2019-raleigh/location.md

[RDU-2019] Location page update

[RDU-2019] Location page update

---

content/events/2020-houston/sponsor.md

Added initial sponsorship details.

[HOU-2020] Added sponsorship details

---

content/events/2019-ghent/program.md

* Add content to program page regarding October 28.

[GHENT-2019] - Be specific about October 28

---

data/core.toml

core team update

---

content/events/2019-kansas-city/sponsor.md
data/events/2019-kansas-city.yml

[KC-2019] add google cloud as coffee sponsor

---

content/events/2019-kansas-city/speakers/joel-tosi.md

[KC-2019] people don't need to know that joel needs travel assistance

---

content/events/2020-columbus/conduct.md
content/events/2020-columbus/contact.md
content/events/2020-columbus/location.md
content/events/2020-columbus/propose.md
content/events/2020-columbus/registration.md
content/events/2020-columbus/sponsor.md
content/events/2020-columbus/welcome.md
data/events/2020-columbus.yml

Ran the add event script
Minor updates (mostly copy/paste). 
Setup dates.
More incoming in increments over the next week.

[Columbus-2020] Base Start, setting dates

---

content/blog/salvador-2019-note.md

[SSA-2019] Add organization annoucement as blog post

---

content/events/2019-ghent/speakers/jody-wolfborn.md
data/events/2019-ghent.yml

* Fix bio per request of speaker
* Add 3 platinum sponsors

[GHENT2019] - Fix bio, add sponsors

---

content/events/2019-chattanooga/program.md
content/events/2019-chattanooga/program/chantee-boykin.md
content/events/2019-chattanooga/program/chris-rimondi.md
content/events/2019-chattanooga/program/dave-karow.md
content/events/2019-chattanooga/program/dion-stewart.md
content/events/2019-chattanooga/program/james-wen.md
content/events/2019-chattanooga/program/jamie-phillips.md
content/events/2019-chattanooga/program/jennifer-davis.md
content/events/2019-chattanooga/program/jj-asghar.md
content/events/2019-chattanooga/program/john-cotton.md
content/events/2019-chattanooga/program/michael-jolley.md
content/events/2019-chattanooga/program/mike-rothman.md
content/events/2019-chattanooga/program/veer-muchandi.md
data/events/2019-chattanooga.yml

Publishes the CHA-2019 program as it currently exists.

[CHA-2019] Publish program

---

content/events/2019-london/welcome.md
data/events/2019-london.yml

Close off conference, we're still waiting for the videos on youtube but
we'll put those up once they're signed off.

[LDN-2019] Close off conference! 🎉

---

content/events/2019-raleigh/welcome.md

[RDU-2019] updated presentation slide links and add linkedin

[RDU-2019] updated presentation slide links and add linkedin

---

data/events/2019-galway.yml

[GAL-2019] Added ITAG Skillnet as sponsor

---

data/events/2019-salvador.yml

[SSA-2019] Add vmware as sponsor

---

data/events/2019-galway.yml

[GAL-2019]] Added Red Hat as sponsor

---

data/events/2019-recife.yml

[REC-2019] - add registration date and links

---

content/events/2020-guadalajara/propose.md
content/events/2020-guadalajara/welcome.md
data/events/2020-guadalajara.yml

Add CFP related sites:
content/events/2020-guadalajara/propose.md
content/events/2020-guadalajara/welcome.md
Dates updated in:
data/events/2020-guadalajara.yml

[GDL-2020] Add CFP site

---

data/events/2019-baku.yml

[Baku-2019] Added propose button

---

data/events/2019-philadelphia.yml

[PHILLY--2019] Add two more sponsors.

---

content/events/2019-montreal/program/catherine-proulx.md
content/events/2019-montreal/program/charles-abondo.md
content/events/2019-montreal/program/christian-couder-ws.md
content/events/2019-montreal/program/christian-couder.md
content/events/2019-montreal/program/chuck-mountz-jr.md
content/events/2019-montreal/program/gareth-greenaway.md
content/events/2019-montreal/program/james-shubin.md
content/events/2019-montreal/program/martin-deslongchamps.md
content/events/2019-montreal/program/philippe-lafoucriere.md
content/events/2019-montreal/program/richard-fontana.md
content/events/2019-montreal/program/steve-pereira-ws.md
content/events/2019-montreal/program/steve-pereira.md
content/events/2019-montreal/program/yannick-brosseau.md
content/events/2019-montreal/speakers.md
content/events/2019-montreal/speakers/catherine-proulx.md
content/events/2019-montreal/speakers/charles-abondo.md
content/events/2019-montreal/speakers/christian-couder.md
content/events/2019-montreal/speakers/chuck-mountz-jr.md
content/events/2019-montreal/speakers/gareth-greenaway.md
content/events/2019-montreal/speakers/james-shubin.md
content/events/2019-montreal/speakers/martin-deslongchamps.md
content/events/2019-montreal/speakers/philippe-lafoucriere.md
content/events/2019-montreal/speakers/richard-fontana.md
content/events/2019-montreal/speakers/steve-pereira.md
content/events/2019-montreal/speakers/yannick-brosseau.md
data/events/2019-montreal.yml

[MTL-2019] adding initial schedule and speakers

---

data/events/2019-washington-dc.yml

[DC-2019] Updates Chuck Mountz's bio

---

data/events/2019-ghent.yml

[Ghent-2019] Updated schedule 

---

utilities/README.md

Be explicit that static files may need to be updated.

update README to reflect that static files may need to be updated

---

content/events/2019-ghent/program/sasha-rosenbaum.md

Adding a blank line makes the markdown render as an unordered list.
/cc @DivineOps

[Ghent-2019] Sasha's talk includes a bulleted list

---

content/events/2019-philadelphia/welcome.md

The front page had an old CFP link I'm removing. /cc @peterjshan

[Philly 2019] Philly CFP is closed

---

content/events/2019-galway/speakers/wesley-faulkner.md

Add additional social links for Wesley

[GAL-2019] Add social links for speaker

---

data/events/2019-philadelphia.yml

[Philly-2019] Two more sponsors.

---

data/events/2020-seattle.yml

[SEA-2020] Open Seattle CFP

---

content/events/2019-auckland/speakers/jacob-ivester.md

Fixes an error with Jacob's name spelt incorrectly.

[AKL-2019] Fixed error in speaker name

---

data/events/2019-paris.yml

[Paris-2019] add more sponsors

---

content/events/2019-galway/location.md

Add some details on the location with some helping info

[GAL-2019] Add location info

---

content/events/2019-montreal/program/gareth-greenaway.md

montreal: fixup talk

---

content/events/2019-montreal/welcome.md
data/events/2019-montreal.yml

- Update schedule
- add sponsor
- minor adjustment in welcome page.

[mtl-2019] schedule update1, add sponsor

---

content/events/2020-caceres/sponsor.md

Signed-off-by: Maria Jesús Ruiz <mariajesusruiz@gmail.com>

[CAC-2020] Update bronze sponsor benefits

---

content/events/2020-caceres/sponsor.md

Signed-off-by: Maria Jesús Ruiz <mariajesusruiz@gmail.com>

[CAC-2020] Update room names sponsors

---

content/events/2020-seattle/sponsor.md

Adding Sponsorship payment buttons for Seattle 2020.

Seattle 2020 Sponsor Payment Buttons

---

content/events/2020-buenos-aires/conduct.md
content/events/2020-buenos-aires/contact.md
content/events/2020-buenos-aires/location.md
content/events/2020-buenos-aires/propose.md
content/events/2020-buenos-aires/registration.md
content/events/2020-buenos-aires/sponsor.md
content/events/2020-buenos-aires/welcome.md
data/events/2020-buenos-aires.yml

Buenos Aires DevOpsDays Placeholder.

[BAI-2020] Buenos Aires DevOpsDays PlaceHolder.

---

content/events/2019-paris/welcome.md
data/events/2019-paris.yml

[Paris-2019] add videos link; remove unused sponsor level

---

data/events/2019-ghent.yml

[GHENT2019] remove Microsoft as a silver sponsor

---

content/events/2019-galway/program.md
content/events/2019-galway/program/danese-cooper.md
data/events/2019-galway.yml

First pass at the program for Devopsdays Galway 2019

[GAL-2019] Provisional Program

---

content/events/2019-recife/sponsor.md

[REC-2019] Add sponsor page

---

data/events/2019-kansas-city.yml

[KC-2019] small schedule updates

---

data/events/2020-vitoria.yml

Change employer Rafaella and Leo Hackin

[VIX-2020] Change employer Rafaella and Leo Hackin

---

content/events/2020-chicago/welcome.md
data/events/2020-chicago.yml

Add some fancy stuff to the front page for Chicago 2020

[CHI-2020] Update welcome page for 2020 Chicago

---

data/events/2019-ghent.yml

* Add Red Hat as platinum sponsor

[GHENT-2019] Add Red Hat

---

content/events/2019-ghent/program/bridget-kromhout.md

As the talks are now 15 minutes, and as this proposal was originally intended to be two-speaker, and as much of that wording was meant to be explanatory. :) /cc @rgevaert @yvovandoorn @KrisBuytaert 
[Needs approval from local organizer for merge]

[Ghent 2019] Shorter talk description

---

data/events/2020-portugal.yml

* official venue
* official dates

[PT-2020] Adding official venue and dates

---

data/events/2019-ghent.yml

[GHENT2019] fix schedule

---

data/events/2019-galway.yml

[GAL-2019] Add CodingGrace as community sponsor

---

content/events/2019-galway/registration.md

Remove comment markers accidentally left

[GAL-2019] Include mention of venue discount

---

content/events/2020-vitoria/welcome.md

New link meetups in welcome.md

[VIX-2020] New link meetups

---

data/events/2020-kyiv.yml

[Kyiv-2020] fix CPF date

---

data/events/2020-geneva.yml

[GE-2020] add sponsors: oracle, dbi-services

[GE-2020] add sponsors: oracle, dbi-services

---

content/events/2020-zurich/welcome.md
data/events/2020-zurich.yml

[ZRH2020] New location and date

---

content/events/2020-charlotte/sponsor.md
data/events/2020-charlotte.yml

Update sponsorship tiers and add two sponsors.

[CLT-2020] update sponsorship levels

---

data/core.toml

- @KrisBuytaert becomes Advisory
- @somatorio becomes Active

Core updates

---

content/events/2020-caceres/welcome.md

Signed-off-by: Maria Jesús Ruiz <mariajesusruiz@gmail.com>

[CAC-2020] Add end call for talks date

---

content/events/2020-vitoria/welcome.md

[VIX-2020] Add CFP link in welcome page

---

content/events/2019-montreal/program/christian-couder-ws.md
content/events/2019-montreal/program/gareth-greenaway.md
data/events/2019-montreal.yml

- Fix sponsor level
- update workshop details.
Thanks :-)

[mtl2019] fix sponsor, workshop

---

data/events/2019-montreal.yml

openspace reviewed, opening during all attendees period, then 3 openspace slots during workshop period.

[mtl2019] last min sched changes: openspace revamp

---

content/events/2019-chattanooga/speakers/mike-rothman.md

Updating per core team suggestion.

[CHA-2019] Updating Mike Rothman bio

---

content/events/2020-vitoria/welcome.md

[VIX-2020] spelling correction

---

data/events/2019-galway.yml

[GAL-2019] Add WWCodeBelfast as community sponsor

---

data/events/2019-montreal.yml

[MTL-2019] Minor sched update

---

data/events/2019-berlin.yml

add chef as another plain sponsor

[Berlin-2019] Add sponsor chef

---

data/events/2020-geneva.yml

[GE-2020] add serial as silver sponsor

[GE-2020] add serial as silver sponsor

---

content/events/2020-los-angeles/sponsor.md

[LA 2019] Update Sponsor Details

[LA 2019] Update Sponsor Details

---

data/events/2019-galway.yml

Add community sponsor Devops Galway

[GAL-2019] Add local Devops community sponsor

---

data/events/2020-poznan.yml

[POZ-2020] Update Artur pic

---

content/events/2020-vitoria/welcome.md
data/events/2020-vitoria.yml

add cfp in navbar.
add link telegram group.
remove sponsor.

[VIX-2020] add cfp, add link telegram, remove sponsor

---

static/_redirects

Testing a redirect for a city. Relevant to https://github.com/devopsdays/devopsdays-web/issues/8195.

Testing redirect

---

static/_redirects

Expands on https://github.com/devopsdays/devopsdays-web/pull/8704.

More generalized redirection

---

content/events/2020-vitoria/welcome.md

[VIX-2020] change link telegram

change link telegram

---

utilities/README.md

Because the job's not done until it's documented! Documents the changes for https://github.com/devopsdays/devopsdays-web/issues/8195.

Documented current-year redirection.

---

data/events/2020-zurich.yml

[ZRH2020] Fix wrong wording of location

---

data/events/2020-chicago.yml

chicago ugroups as sponsors too

[CHI-2020] Chicago ugroups

---

content/events/2020-madrid/welcome.md
data/events/2020-madrid.yml

[MAD-2020] CFP extended

---

content/events/2020-minneapolis/propose.md
content/events/2020-minneapolis/registration.md
content/events/2020-minneapolis/sponsor.md
content/events/2020-minneapolis/welcome.md
data/events/2020-minneapolis.yml

Opens CFP, registration, and sponsorships.

[MSP 2020] Open CFP, registration, sponsorships

---

data/events/2019-berlin.yml

Add sticker mule as "parter sponsor".

[Berlin-2019] Add sponsor sticker mule

---

data/events/2019-berlin.yml

I've misplaced them by accident as platin sposor but they are only gold.

[Berlin-2019] fix sponsor chef

---

data/events/2019-galway.yml

[GAL-2019] Correct Program

---

data/events/2019-galway.yml

[GAL-2019] Add WWCodeDublin as community sponsor

---

data/events/2020-dallas.yml

[DFW-2020] Updating Scott's bio

---

content/events/2020-new-york-city/location.md
content/events/2020-new-york-city/welcome.md
data/events/2020-new-york-city.yml

Adding in venue details and event dates for NYC 2020

[NYC-2020] Adding venue information and event dates

---

content/events/2019-berlin/program.md

Argh. That was unlucky timing, the last PR was closed a few seconds before I could push this change. Sorry!

[BER-2019] Remove 'draft' from program page

---

data/events/2020-guadalajara.yml

- add Maria Pinedo as organizer
- update CFP end date to Dec 31st
- accept max 4 platinum sponsors

[GDL-2020] add Maria Pinedo as organizer

---

data/events/2020-houston.yml

[HOU-2020] Added first two gold sponsors: gitlab and launch darkly

---

content/events/2020-zurich/contact.md
content/events/2020-zurich/location.md
content/events/2020-zurich/propose.md
content/events/2020-zurich/welcome.md
data/events/2020-zurich.yml

[ZRH2020] Added CFP and some minor changes

---

content/events/2020-houston/sponsor.md

[HOU-2020] Fixed a few typos on sponsor page

[HOU-2020] Fixed a few typos on sponsor page

---

content/events/2020-des-moines/sponsor.md
data/events/2020-des-moines.yml

[DSM-2020] Add sponsorship page

---

data/events/2020-zurich.yml

[ZRH2020 CFP] changed the date

---

data/events/2020-houston.yml

[HOU-2020] Adding Two Sigma as Gold sponsor

---

content/events/2020-vitoria/sponsor.md
data/events/2020-vitoria.yml

[VIX-2020] add sponsor proposal

---

data/events/2020-poznan.yml

[POZ-2020] add CFP link

---

data/events/2020-atlanta.yml

[ATL-2020] open cfp

---

content/events/2019-moscow/location.md
content/events/2019-moscow/sponsor.md
content/events/2019-moscow/welcome.md
data/events/2019-moscow.yml

[MSK-2019]: upd location, sponsor,welcome page a bit

---

content/events/2020-geneva/propose.md

[GENEVA-2020] Changed CFP proposal method

---

content/events/2020-zurich/sponsor.md

[ZRH2020] Added Sponsor Kit

---

data/events/2020-portugal.yml

[PT-2020] diana bio update

---

content/events/2020-zurich/sponsor.md
data/events/2020-zurich.yml

[ZRH-2020] Changed the Email for sponsoring and CFP Announcement Date

---

content/events/2020-vancouver/sponsor.md

- Format from last year's sponsor page used

[VAN-2020] Sponsor prospectus linked

---

content/events/2020-zurich/propose.md

[ZRH2020] Add link to sessionize and changed text

---

content/events/2019-berlin/speakers/mario-konschake.md

Forgot to also update the speaker's bio.

[BER-2019] Change Biography for Mario

---

data/events/2020-los-angeles.yml

add new sponsors - xmatters and launch darkly

[la2019] add new sponsors - xmatters and launch darkly

---

data/events/2020-seattle.yml

Reuse information and logo from 2019

[SEA-2020] Add LaunchDarkly sponsorship

---

data/events/2020-charlotte.yml

Cleaning up commented out sponsors and adding f5 and launch-darkly at gold

[CLT-2020] Add 2 sponsors

---

content/events/2020-zurich/welcome.md
data/events/2020-zurich.yml

[ZRH-2020] Added a link to homepage

---

data/events/2020-poznan.yml

[POZ-2020] open registration

---

content/events/2019-berlin/speakers/laura-hofmann.md

Update Lauras speaker bio as requested

[Berlin-2019] update lauras bio

---

data/events/2020-portugal.yml

[PT-2020] cfp open

---

data/events/2020-portugal.yml

* adding google analytics tracking code

[PT-2020] adding google analytics tracking code

---

content/events/2020-portugal/propose.md
content/events/2020-portugal/welcome.md

* welcome page update with cfp; 
* propose page addition.

[PT-2020] welcome page update with cfp; propose page addition

---

data/events/2020-zurich.yml

[ZRH-2020] Update CFP Dates

---

content/events/2020-toronto/location.md
content/events/2020-toronto/propose.md
content/events/2020-toronto/welcome.md
data/events/2020-toronto.yml

We're happy to welcome Amy Mansell back as an organizer

[TOR-2020] Add dates, venue, CFP and an organizer

---

content/events/2020-des-moines/sponsor.md
data/events/2020-des-moines.yml

[DSM-2020] update sponsorship information

---

content/events/2020-tokyo/welcome.md
data/events/2020-tokyo.yml

December site updates - Based on more information that has come in.
Updated Eventbrite link in MD and YAML

DevOps Days Tokyo 2020 - December

---

data/events/2020-vitoria.yml

[VIX-2020] Add sponsor inflor

---

data/events/2020-zurich.yml

[ZRH-2020] Add bio of David Kilchemann

---

data/events/2020-zurich.yml

[ZRH-2020] Add employer to carsten

---

content/events/2020-tokyo/sponsor.md

Updated Sponsorship Prices for conference
Updated cost of sponsorship for conferences.

Updated Sponsorship Prices

---

data/events/2017-denver.yml
data/events/2018-denver.yml
data/events/2019-denver.yml
static/events/2017-denver/contact/index.html
static/events/2018-denver/contact/index.html

Changing name for 2017-2019 as well

Name change of Ryan Koch to Lilith Moon Cohen for past events

---

data/events/2020-vitoria.yml

[VIX-2020] add sponsor globalsys

---

content/events/2020-new-york-city/registration.md
content/events/2020-new-york-city/welcome.md
data/events/2020-new-york-city.yml

Enables registration for NYC 2020 event

[NYC-2020] Setup Registration

---

content/events/2020-philadelphia/sponsor.md
data/events/2020-philadelphia.yml

[PHILLY-2020] Fix prospectus url and add sponsor.

---

content/events/2019-galway/program/brendan-o-reilly.md
content/events/2019-galway/program/giulio-vian.md
content/events/2019-galway/program/jorge-dionisio.md
content/events/2019-galway/program/michele-pegoraro.md
content/events/2019-galway/program/nathen-harvey.md
content/events/2019-galway/program/pierre-vincent.md

[GAL-2019] Add slideshare links for talks

---

content/events/2020-seattle/registration.md
data/events/2020-seattle.yml

Adding event admission widget to the registration page and making the registration link visible on the nav.

[SEA-2020] Adding event admission

---

CONTRIBUTING.md

GitHub has specific directions we can link here.

Clarify how to set upstream

---

content/events/2019-tel-aviv/program.md
content/events/2019-tel-aviv/program/brian-murphy.md
content/events/2019-tel-aviv/program/daniel-mittelman.md
content/events/2019-tel-aviv/program/elazar-leibovich.md
content/events/2019-tel-aviv/program/erik-zaadi.md
content/events/2019-tel-aviv/program/lev-andelman-andrei-burd.md
content/events/2019-tel-aviv/program/michael-arenzon-avishai-ishshalom.md

Hi, @shar1z! These fixes are mostly for issues around the way your program file is constructed. You have a good example of a multi-track event, which we could support better - the down side to manually building the program, of course, is less in the way of automated cross-checks.

[TLV 2019] Fixes to issues with program

---

content/events/2020-baltimore/sponsor.md

[bmore] Fix sponsor link

---

content/events/2020-des-moines/program.md
content/events/2020-des-moines/welcome.md
data/events/2020-des-moines.yml

[DSM-2020] Adding sponsor and proposal links

---

data/events/2020-chicago.yml

[CHI-2020] Enable sponsorship for chicago 2020

---

content/events/2020-vancouver/location.md
content/events/2020-vancouver/welcome.md
data/events/2020-vancouver.yml

1, Update location to display map 
2. Open links to call for papers
3. Move twitter link to be directly below email link
4. Commented out the cfp_date_announce for now

[VAN-2020] - update location and open call for papers

---

data/events/2020-los-angeles.yml

[la2020] add influxdata

---

content/events/2020-denver/sponsor.html

[DEN-2020] Fixing sponsor table labels.

---

data/events/2020-poznan.yml

[POZ-2020] update cfp dates

---

data/events/2020-paris.yml

We have a confirmed date for 2020!
cc @jooooooon

[Paris-2020] set the date for the event 🎉

---

data/events/2020-vitoria.yml

Remove temporarily logo sponsor Inflor

[VIX-2020] Remove temporarily logo sponsor Inflor

---

content/events/2020-buenos-aires/sponsor.md

[BAI-2020] Sponsorship packages updated.

---

data/events/2020-charlotte.yml

[CLT-2020] Add influxdata sponsorship

---

content/events/2020-vancouver/welcome.md
data/events/2020-vancouver.yml

Open Registration for Vancouver 2020

[VAN-2020] open registration

---

content/events/2020-istanbul/conduct.md
content/events/2020-istanbul/contact.md
content/events/2020-istanbul/location.md
content/events/2020-istanbul/propose.md
content/events/2020-istanbul/registration.md
content/events/2020-istanbul/sponsor.md
content/events/2020-istanbul/welcome.md
data/events/2020-istanbul.yml
static/_redirects

[Istanbul 2020] Add devopsdays istanbul 2020 event

---

data/events/2020-vitoria.yml

inflor official return on devopsdays Vitoria

[VIX-2020] inflor official return on devopsdays Vitoria

---

data/events/2020-seattle.yml

Adds influx data as gold sponsor.

[SEA-2020] Add InfluxData sponsorship

---

data/events/2020-houston.yml

[HOU-2020] Added ABS as corporate sponsor

---

content/events/2020-baltimore/registration.md
content/events/2020-baltimore/welcome.md
data/events/2020-baltimore.yml

Opening registration for Baltimore 2020

[BMORE-2020] Open registration for Baltimore 2020

---

content/events/2019-tel-aviv/program.md

The link to my talk was 404 :)

[2019-TLV] Fix link to Matt Stratton talk

---

data/events/2020-des-moines.yml

[DSM-2020] Adding config for cfp

---

content/events/2020-charlotte/program/josh-stella.md
content/events/2020-charlotte/speakers/josh-stella.md
content/events/2020-charlotte/welcome.md
data/events/2020-charlotte.yml

[CLT-2020] update program

---

data/events/2020-los-angeles.yml

[la2020] add appdynamics

---

content/events/2020-dallas/welcome.md
data/events/2020-dallas.yml

Updating Russell Black's Bio and removing the Program link for now since we don't have a program to display

[DFW-2020] Update to Bio and Remove Program Link until we have a program

---

data/events/2020-dallas.yml

Remove the diamond level sponsership link from the sponsership page

[DFW-2020] remove diamond level sponser link

---

data/events/2020-zurich.yml

[ZRH-2020] Removed Sponsors Pearl and Jazoon

---

data/events/2020-houston.yml

[HOU-202] Added DataDog as Gold Sponsor

---

content/events/2020-dallas/sponsor.md

Removing diamond level sponsor package for DFW

[DFW-2020] removing diamond level from sponsor.md 

---

content/events/2020-zurich/sponsor.md
data/events/2020-zurich.yml

[ZRH-2020] Add Nine as sponsor of the evening event

---

data/events/2020-zurich.yml

[ZRH-2020] Fixed removal of Zuhlke

---

content/events/2020-madrid/program.md
content/events/2020-madrid/speakers/pablo-chico.md

[MAD-2020] speaker name fixed

---

content/events/2020-vitoria/meetups.md
content/events/2020-vitoria/speakers.md
data/events/2020-vitoria.yml

[VIX-2020] adding meetups images

---

data/events/2020-zurich.yml

[ZRH-2020] fix spelling of sponsor package friends

---

data/events/2020-charlotte.yml

Adding AppDynamics at gold for Charlotte 2020

[CLT-2020] Add a sponsor

---

data/events/2020-raleigh.yml

[RDU-2020] Dates are set - Oct 18-20

---

data/events/2020-atlanta.yml

adding Jonette Jones as an organizer.

[ATL-2020] Adding a new organizer.

---

data/events/2020-charlotte.yml

[CLT-2020] Add Manning as sponsor for Charlotte

---

data/events/2020-vitoria.yml

* changed location dod-vix UVV to Grand Hall

[VIX-2020] changed location dod-vix UVV to Grand Hall

---

content/events/2020-portugal/registration.md
data/events/2020-portugal.yml

[PT-2020] registration form

---

data/events/2020-houston.yml

[HOU-2020] Adding Microsoft as Platinum sponsor

[HOU-2020] Adding Microsoft as Platinum sponsor

---

content/events/2020-boise/registration.md
content/events/2020-boise/welcome.md
data/events/2020-boise.yml

Eventbrite is up and running, this adds registration options to the page

[Boise 2020] Add registration information
