content/events/2020-porto-alegre/propose.md, content/events/2020-porto-alegre/sponsor.md, data/events/2020-porto-alegre.yml
[Porto Alegre-2020] Add new community sponsors and plan of sponsorship
=> [Porto Alegre-2020] Add new community sponsors and plan of sponsorship

data/events/2020-vitoria.yml
=> [VIX-2020] New sponsor AutoGlass

data/events/2020-seattle.yml
=> [SEA-2020] added Microsoft as gold

hugoserver.sh
Just a little disclaimer that the docker image isn't ours
=> Add disclaimer about the jojomi image

data/core.toml
=> Update core membership

data/events/2020-charlotte.yml
Adding Gitlab at gold for Charlotte 2020
=> [CLT-2020] Add sponsor for clt 2020

data/core.toml
=> re-add by request

data/events/2020-los-angeles.yml
=> [la2020] add codefresh as sponsor

data/events/2020-porto-alegre.yml
[Porto Alegre-2020] Adding new sponsor for DevOpsDays Porto Alegre 2020
=> [Porto Alegre-2020] Adding new sponsor

data/events/2020-geneva.yml
=> [GE-2020] first day start at 8:30

content/events/2020-madrid/sponsor.md
=> [MAD-2020] fix new hugo version bugs

content/events/2020-toronto/propose.md, data/events/2020-toronto.yml
Changes:
- Add video to propose page
- Change propose header link
=> [TOR-2020] Add video to propose page

data/events/2020-porto-alegre.yml
Adding registration page from DevOpsDays Porto Alegre 2020
=> [Porto Alegre-2020] Adding registration page

content/events/2020-minneapolis/conduct.md
Update for https://github.com/devopsdays/devopsdays-web/issues/9006.
=> Code of Conduct language update - MSP

content/events/2020-dallas/conduct.md
updated conduct.md based on core organization recommendation
=> [DFW-2020] updated conduct.md based on core organization recommendation

content/events/2020-aracaju/sponsor.md
=> [Aju-2020] Sponsor Modifications

data/events/2020-vancouver.yml
Add in the first 7 gold sponsors for Vancouver 2020
=> [VAN-2020] Add in the first confirmed sponsors for Vancouver 2020

content/events/2020-amsterdam/sponsor.md, data/events/2020-amsterdam.yml
We start to accept sponsors for AMS 2020.
=> [AMS-2020] Open the sponsor possibilities for 2020

content/events/2020-geneva/conduct.md
Hi,  @matemaz and @deniger! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Geneva 2020] Suggested update

content/events/2020-guadalajara/conduct.md
Hi, @estebancrw and @RaulEsMas - We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Guadalajara 2020] Suggested update

data/events/2020-amsterdam.yml
Opening Call for Participation for Amsterdam 2020
=> [AMS-2020] Open CfP

content/events/2020-madrid/conduct.md
Hi, @xavierportillaedo! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Madrid 2020] Suggested update

data/events/2020-minneapolis.yml
=> [MSP 2020] Add sponsor

content/events/2020-charlotte/conduct.md
Hi, @alfonso-cabrera! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Charlotte 2020] Suggested update

data/core.toml
=> Adding Katie

content/events/2020-vancouver/location.md, content/events/2020-vancouver/welcome.md, data/events/2020-vancouver.yml
Update Organizers list
Add CFP date to Proposals link
Update Location Information and add in Accessibility Information
=> [VAN-2020] update organizers, CFP date, and location information

data/events/2020-paris.yml
=> [Paris-2020] Update venue address to be more specific

content/events/2020-los-angeles/conduct.md
Hi, @irabinovitch! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Los Angeles 2020] Suggested update

content/events/2019-galway/program/eoin-nugent.md
Including the link to one of the speakers slides.
=> [GAL 2019] Add Slideshare links - Eoin

content/events/2020-atlanta/welcome.md, data/events/2020-atlanta.yml
I added Cox Automotive as platinum along with Instana and Harness as gold. 
I also updated the welcome page with more info on our theme.
=> [ATL-2020] added sponsors, updated Welcome page

content/events/2020-caceres/conduct.md
Hi, @mariajruizsue! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Caceres] Suggested update

content/events/2019-galway/program/how-chaos-monkey-went-from-feared-foe-to-trusted-friend.md
Add link to Sid and Colm's slides
=> [GAL 2019] - Add slideshare link to talk

content/events/2020-buffalo/propose.md, content/events/2020-buffalo/welcome.md, data/events/2020-buffalo.yml
Ensuring the propose link is on the front page, updating the dates to be UTC, and making sure the proposal info is clear
=> [BUF-2020] Adding propose link to main page, updating submission info

data/events/2020-minneapolis.yml
Adding SPS_Commerce as a gold / alacarte sponsor for 2020
=> [MSP-2020] adding sponsor sps_commerce

content/events/2020-prague/conduct.md
Hi @EtssMM!  We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Prague 2020] Suggested update

data/events/2020-berlin.yml
Add our confirmed partner sponsors for 2020
=> [BER-2020] Add partner sponsors

content/events/2020-vancouver/conduct.md
Hi, @Velutas! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Vancouver 2020] Suggested update

content/events/2020-new-york-city/conduct.md
Hi @kuritz @jaydestro @russCompass! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [New York City 2020] Suggested update

data/events/2020-zurich.yml
=> [ZRH-2020] Add sponsor VSHN

content/events/2020-vitoria/conduct.md
Hi, @sprt-balarini! We have updated the suggested language for the code of conduct - see https://github.com/devopsdays/devopsdays-web/issues/9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Vitoria 2020] Suggested update

content/events/2019-galway/program/frank-farrell.md
=> [GAL 2019] - Add Slideshare link

data/events/2020-chicago.yml
=> [CHI-2020] Add LaunchDarkly as a gold sponsor

data/events/2020-charlotte.yml
=> [CLT-2020] Add New Relic as gold sponsor

content/events/2020-berlin/conduct.md
Upgrade to COC 2020 referencing https://github.com/devopsdays/devopsdays-web/issues/9006
=> [BER-2020] Upgrade Code of Conduct

content/events/2020-atlanta/conduct.md
Hi, @cacorriere! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Atlanta 2020] Suggested update

content/events/2020-houston/conduct.md
Hi,  @skryukova! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Houston 2020] Suggested update

data/events/2020-minneapolis.yml
=> [MSP 2020] Adding Red Hat as sponsor

data/events/2020-toronto.yml
Email will be sent to Core team with email addresses.
=> [TOR-2020] Add new Toronto organizers

content/events/2020-tokyo/conduct.md
Hi, @ngannon! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Tokyo 2020] Suggested update

content/events/2020-denver/conduct.md
Hi @mattk42 @tavisto! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. [Your local contact numbers remain in the document.] Thanks.
=> [Denver 2020] Suggested update

data/events/2020-los-angeles.yml
=> [la 2020] add sponsors

content/events/2020-chicago/conduct.md
Hi @mattstratton! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Chicago 2020] Suggested update

content/events/2020-raleigh/conduct.md
Hi @normalfaults! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Raleigh 2020] Suggested update

content/events/2020-saint-louis/conduct.md
I'm just merging this one, as I set up the original PR.
=> [Saint Louis 2020] Suggested update

content/events/2020-ciudad-mexico/conduct.md
As @MikeRosTX put this template in place, I'm making this update.
=> [Ciudad De México] Suggested update

content/events/2020-medellin/conduct.md
As @MikeRosTX put this template in place, I'm making this update.
=> [Medellín 2020] Suggested update

content/events/2020-des-moines/conduct.md
Hi, @jessiepuls! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Des Moines 2020] Suggested update

content/events/2020-zurich/conduct.md
Hi @RomanoRoth! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Zürich 2020] Suggested update

content/events/2020-santiago/conduct.md
As @MikeRosTX put this template in place, I'm making this update.
=> [Santiago 2020] Suggested update

content/events/2020-zaragoza/conduct.md
As @MikeRosTX put this template in place, I'm making this update.
=> [Zaragoza 2020] Suggested update

data/events/2020-minneapolis.yml
Adding Hack the Gap - community sponsor
=> [MSP 2020] Adding Hack the Gap - community sponsor

data/events/2020-minneapolis.yml
=> [MSP 2020] Adding SDT

content/events/2020-los-angeles/location.md, content/events/2020-los-angeles/program.md, content/events/2020-los-angeles/speakers/alvaro-leiva.md, content/events/2020-los-angeles/speakers/clint-byrum.md, content/events/2020-los-angeles/speakers/francis-potter.md, content/events/2020-los-angeles/speakers/julie-gunderson.md, content/events/2020-los-angeles/speakers/laura-santamaria.md, content/events/2020-los-angeles/speakers/murriel-perezmccabe.md, content/events/2020-los-angeles/speakers/robert-treat.md, content/events/2020-los-angeles/speakers/tyler-auerbeck.md, data/events/2020-los-angeles.yml
[la 2020] add program, social media and location
=> [la 2020] add program and social media info

content/events/2020-kyiv/conduct.md
Hi @delgod! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Kyiv 2020] Suggested update

content/events/2020-austin/registration.md, data/events/2020-austin.yml
Also includes these changes:
* Update bio for Bailey
* Link to justification letter
=> [austin-2020] Add chaossearch as platinum sponsor

content/events/2020-geneva/program/jerome-van-der-linden-and-bashar-al-fallouji.md
[GE-2020] change talk description
=> [GE-2020] change talk description

content/events/2020-buenos-aires/conduct.md
Hi @diegows! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Buenos Aires 2020] Suggested update

content/events/2020-cape-town/conduct.md
Hi @adrianmoisey! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Cape Town 2020] Suggested update

data/events/2020-amsterdam.yml
=> [AMS-2020] Add missing sponsorships and re-arrange based on value

content/events/2020-baltimore/conduct.md
Hi, @jaumann! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Baltimore 2020] Suggested update

content/events/2020-portland-me/conduct.md
Hi, @jlbutler! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Portland, ME 2020] Suggested update

content/events/2020-buffalo/conduct.md
Hi @aspleenic! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Buffalo 2020] Suggested update

content/events/2020-philadelphia/conduct.md
Hi @peterjshan! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Philadelphia 2020] Suggested update

content/events/2020-madison/conduct.md
Hi @jazimmerman! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Madison 2020] Suggested update

content/events/2020-bogota/conduct.md
Hi @devopscolombia! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Bogotá 2020] Suggested update

data/events/2020-los-angeles.yml
[la 2020] add site24x7 as sponsor
=> [la 2020] add site24x7 as sponsor

content/events/2020-portugal/conduct.md
Hi @MiguelAlho & @eduardopiairo! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. I have tried to keep your local modifications - please submit suggestions to this PR if you'd like it to be different. Thanks.
=> [Portugal 2020] Suggested update

data/events/2020-madrid.yml
=> [MAD-2020] agenda updated

content/events/2020-berlin/registration.md, data/events/2020-berlin.yml
=> [BER-2020] Add registration to Berlin 2020

content/events/2020-columbus/conduct.md
Hi, @kjenkins19! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Columbus 2020] Suggested update

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Fullstaq as T-shirt sponsor

data/events/2020-minneapolis.yml
=> [MSP 2020] Adding sponsor

content/events/2020-poznan/conduct.md
Hi @jakubjakubik & @mazek! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Poznań 2020] Suggested update

data/events/2020-charlotte.yml
Adding Delphix at silver and site24x7 at gold
=> [Charlotte 2020] Adding 2 sponsors

content/events/2020-cairo/conduct.md
Hi @aameen79! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Cairo 2020] Suggested update

content/events/2020-aarhus/conduct.md
Hi @RandomSort! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Aarhus 2020] Suggested update

content/events/2020-istanbul/conduct.md
Hi @aybuke! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Istanbul 2020] Suggested update

data/events/2020-guadalajara.yml
=> [GDL-2020] Added New Relic as sponsor

content/events/2020-seattle/conduct.md
Hi, @kmugrage! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Seattle 2020] Suggested update

data/events/2020-philadelphia.yml
=> [Philly-2020] add appdynamics as silver

content/events/2020-edinburgh/conduct.md
Hi @mjslane! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Edinburgh 2020] Suggested update

data/events/2020-charlotte.yml
adding sonatype at gold for charlotte 2020
=> [Charlotte 2020] Add a sponsor

content/events/2020-jakarta/conduct.md
Hi @mademulia! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Jakarta 2020] Suggested update

content/events/2020-amsterdam/conduct.md
Hi @dpnl87 & @vikingops! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Amsterdam 2020] Suggested update

content/events/2020-caceres/program.md, content/events/2020-caceres/welcome.md, data/events/2020-caceres.yml, data/sponsors/edd.yml
Signed-off-by: Maria Jesús Ruiz <mariajesusruiz@gmail.com>
=> [CAC-2020] Update conference format text and collaborators order

content/events/2021-birmingham/conduct.md
Hi @TomTucka! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Birmingham 2021] Suggested update

content/events/2020-lagos/conduct.md
Hi  @haroldsphinx! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Lagos 2020] Suggested update

content/events/2020-krakow/conduct.md
Hi, @kgadek! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Kraków 2020] Suggested update

content/events/2020-salt-lake-city/conduct.md
Hi @Clait! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. And you will want to make the updates on https://www.slcdevopsdays.org/code-of-conduct/ as well, since you are linking to that. Thanks.
(Here's a link to the diff: https://github.com/devopsdays/devopsdays-web/pull/9165/files?short_path=9c3e461#diff-9c3e461b151c9b51ca040d9ae52e69ba)
=> [Salt Lake City 2020] Suggested update

data/events/2020-atlanta.yml
added pager duty, full story, contrast security, and app dynamics as gold sponsors
=> [ATL-2020] added pager duty, full story, contrast sec, and app D as gold sponsors.

utilities/examples/content/events/yyyy-city/location.md
Added sample text from MN to the location page to encourage events to include information about accessibility.
=> added sample accessibility text

content/events/2020-singapore/conduct.md
Hi @sergiubodiu! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Singapore 2020] Suggested update

content/events/2020-paris/conduct.md
Hi @phrawzty, we'll want to ensure you also get the updates from https://github.com/confcodeofconduct/confcodeofconduct.com/blob/master/index-fr.html when you update your .fr site, but meanwhile please take a look at this update and approve if desired. (See #9006 for background.)
=> [Paris 2020] Suggested update

data/events/2020-krakow.yml
Changing from Paulina Wędrychowska to Paulina Tomaszewska
=> [Kraków-2020] Update team_members

data/events/2020-new-york-city.yml, data/sponsors/ssc.yml
corrected issues with lunch value sponsor name
=> NYC-2020 - corrected issue with value for lunch

content/events/2020-seattle/location.md, data/events/2020-seattle.yml
Added a couple hotel links and enable location page link
=> [SEA-2020] added hotel links

content/events/2020-tampa/conduct.md
Hi, @jmgress! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.
=> [Tampa Bay 2020] Suggested update

data/events/2020-los-angeles.yml
[la 2020] add gitlab and spotinst as sponsors
=> [la 2020] add gitlab and spotinst as sponsors

data/events/2020-austin.yml
* Site24x7
* Contrast Security
=> [austin-2020] new platinum sponsors

utilities/examples/content/events/yyyy-city/conduct-pt-br.md
=> [template] Add CoC pt-br translation

content/page/organizing.md
Added swag vendor recommendations based on past experience in Chicago, Seattle
=> Add swag vendor recommendations to organizing.md

content/events/2020-zaragoza/welcome.md, data/events/2020-zaragoza.yml
Hi, @manuelbcd - I noticed a few problems with your site. The twitter handle wasn't registered on twitter, and there were images being loaded/links that didn't work. This PR corrects those errors.
=> [Zaragoza 2020] corrections

content/events/2020-sao-paulo/sponsor.md, data/events/2020-sao-paulo.yml
[SP-2020] - QuotasAjustments - Changed the categories and benefits for sponsors.
=> [SP-2020] - QuotasAjustments

content/events/2020-madrid/welcome.md
=> [MAD-2020] sold out

data/events/2020-los-angeles.yml
[la 2020] adjust Eliassen to silver.
=> [la 2020] adjust Eliassen to silver.

data/events/2020-los-angeles.yml
=> [la 2020] fix phoenixnap

data/events/2020-sao-paulo.yml
[SP-2020] - Fixing menu content by adding the locale option
=> [SP-2020] - Fixing menu content by adding the locale option

data/events/2020-belo-horizonte.yml
Hello!
I fixed some links.
Thanks!
=> [BHE-2020] Fix link for current year.

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Secure Code Warrior as Lanyard and silver sponsor

data/events/2020-amsterdam.yml
=> [AMS-2020] Add KPN ICT as gold

data/events/2020-charlotte.yml
=> [CLT-2020] Add rancher as silver sponsor for 2020 charlotte

content/events/2020-zurich/conduct.md
=> [ZRH-2020] Change code of conduct

content/events/2020-melbourne/conduct.md, content/events/2020-melbourne/contact.md, content/events/2020-melbourne/location.md, content/events/2020-melbourne/propose.md, content/events/2020-melbourne/registration.md, content/events/2020-melbourne/sponsor.md, content/events/2020-melbourne/welcome.md, data/events/2020-melbourne.yml, static/_redirects
Add the skeleton details for Melbourne 2020.
=> [MEL-2020] Add 2020 Melbourne conference

content/events/2020-chicago/welcome.md
Since we decided we are celebrating "a decade of devops"...
=> [CHI-2020] Slight update to welcome page

content/events/2020-chicago/welcome.md, data/events/2020-chicago.yml
The CFP opens later this week, but figured it was good to get it in there now
=> [CHI-2020] Update with CFP dates

data/events/2020-geneva.yml
[GE-2020] modify end / start time for Registration / Welcome speech
=> [GE-2020] modify end / start  time for Registration / Welcome speech

data/events/2020-atlanta.yml
adding chef and VMware as gold
=> [ATL-2020] adding chef and VMWare as gold

data/events/2020-boise.yml
Also add Chef as Silver sponsor
=> [Boise 2020] Updating CFP dates

data/events/2020-jakarta.yml
Update the DevOpsDays Jakarta 2020 conference date as published before is incorrect (-1 day), also add new sponsor. 
Thank you
=> [JKT-2020] Update Conference Date and Add Sponsors

data/events/2020-charlotte.yml
=> [CLT-2020] Add eliassen-group as silver sponsor for charlotte 2020

content/events/2019-moscow/program.md, content/events/2019-moscow/program/alexander-vdsina.md, content/events/2019-moscow/program/andrey-shorin.md, content/events/2019-moscow/program/baruch-sadogursky.md, content/events/2019-moscow/program/igor-flant.md, content/events/2019-moscow/program/misha-ch.md, content/events/2019-moscow/program/nikita-mir.md, content/events/2019-moscow/program/pavel-selivanov.md, content/events/2019-moscow/program/rodion.md, content/events/2019-moscow/program/roman-aws.md, content/events/2019-moscow/program/sergey-fb.md, content/events/2019-moscow/program/yury-sh.md, content/events/2019-moscow/speakers/alexander-vdsina.md, content/events/2019-moscow/speakers/andrey-shorin.md, content/events/2019-moscow/speakers/baruch-sadogursky.md, content/events/2019-moscow/speakers/igor-flant.md, content/events/2019-moscow/speakers/misha-ch.md, content/events/2019-moscow/speakers/nikita-mir.md, content/events/2019-moscow/speakers/pavel-selivanov.md, content/events/2019-moscow/speakers/rodion.md, content/events/2019-moscow/speakers/roman-aws.md, content/events/2019-moscow/speakers/sergey-fb.md, content/events/2019-moscow/speakers/yury-sh.md, data/events/2019-moscow.yml
Add program. Ask for feedback. Some speakers would be updated and photos too.
Sponsors would be updated in next PR-s.
=> [MSK-2019] Add program (pre-final version)

themes/devopsdays-theme/layouts/speaker/single.html
Fixes #8198 
I *think* this fixes it. We need to do a bunch of checking on various events to make sure it looks right before merging.
For testing, please use this URL https://deploy-preview-9296--devopsdays-web.netlify.com/
=> Fix speaker image stuff

data/events/2020-boise.yml
=> [Boise 2020] Adding balsam brands as gold sponsor

content/events/2019-boise/program.md, data/events/2019-boise.yml
Some sponsors have asked to see the program from last year, making it easier to find (and in the same place as previous years.)
=> [Boise-2019] Adding 2019 program

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Sentia as gold sponsor

data/events/2020-dallas.yml
Update bio for Jessica Sabugo and add Chef and AppD to gold sponsors
=> [2020-Dallas] Update bio and add Chef and AppD to gold sponsors

data/events/2020-dallas.yml
=> [2020-DFW] fixed a typo in jessica's bio

data/events/2020-minneapolis.yml
=> [MSP 2020] Adding minnestar

data/events/2020-zurich.yml
=> [ZRH-2020] Add sponsor google cloud

content/events/2020-dallas/sponsor.md
Removed 3% paypal message
Made font larger for pay by check
Added shared for silver level for table
removed half-boot for silver level pitch to audience
=> [2020-DFW] Sponsor page updates

content/events/2020-guadalajara/program/liz-fong-jones.md, content/events/2020-guadalajara/speakers/ra-acosta.md
Updated Liz Fong Jones abstract and Ra Acosta profile
=> [GDL-2020] Updated liz fong abstract and ra profile

content/events/2020-sao-paulo/sponsor.md
[SP-2020] - Adding sponsors prospect (BR)
=> [SP-2020] - Adding sponsors prospect (BR)

data/events/2020-new-york-city.yml
=> [NYC-2020] add vmware, logz.io, circleci to sponsors

data/events/2020-seattle.yml
Add dynatrace and catchpoint as gold sponsors
=> [SEA 2020] Add dynatrace and catchpoint as gold sponsors

data/events/2020-amsterdam.yml
=> [AMS-2020] Add s0l1dheroes as bronze

content/events/2020-eindhoven/welcome.md
=> [EHV-2020] - Fix language on welcome page. 

content/events/2020-zurich/registration.md, content/events/2020-zurich/sponsor.md, content/events/2020-zurich/welcome.md, data/events/2020-zurich.yml
=> [ZRH-2020] Open registration

content/events/2020-guadalajara/program/cameron-motevasselani.md, content/events/2020-guadalajara/speakers/cameron-motevasselani.md
cameron motevasselani profile updated
=> [GDL-2020] cameron motevasselani profile updated

data/events/2020-seattle.yml
Add sponsors for Seattle 2020
Chef
VMWare
AppDynamics
StackRox
Code Fresh
D2IQ
=> [2020 SEA] Update sponsors for Seattle

content/events/2020-sao-paulo/sponsor.md, data/events/2020-sao-paulo.yml
* Fixed mediakit link
* Added English version of prospectus
=> [SP-2020] Added english version of sponsor prospectus 

content/events/2020-guadalajara/program/mike-rosado.md
=> [GDL-2020] Mike Rosado abstract updated

data/events/2020-boston.yml
=> [BOS-2020] Update Google Analytics

data/events/2020-minneapolis.yml
=> [MSP 2020] Added technovation

.circleci/config.yml, hugoserver.ps1, hugoserver.sh, netlify.toml
This seems to be okay on local testing, but we need to test the deploy preview prior to merging.
=> Update Hugo to v0.64.1

content/events/2020-guadalajara/speakers/jorge-castro.md
Added LinkedIn to Jorge Castro profile
=> [GDL-2020] Added LinkedIn to Jorge Castro profile

data/events/2020-toronto.yml
=> [TOR-2020] add sponsors

data/events/2020-salt-lake-city.yml
-add splunk as gold sponsor
-add launch darkly as gold sponsor
=> [slc-2020] Add Gold sponsors for 2020

content/events/2020-seattle/location.md
Added discount link for homewood suites
=> [SEA-2020] hotel special rate link

data/events/2020-madrid.yml
=> [MAD-2020] little update of the agenda

content/events/2020-amsterdam/registration.md, content/events/2020-amsterdam/welcome.md, data/events/2020-amsterdam.yml
Update the welcome page to make it shine and open up the registration.
=> [AMS-2020] Open registration and update the welcome page

data/sponsors/ceu.yml
=> [MAD-2020] sponsor web page

data/events/2020-amsterdam.yml
=> [AMS-2020] Put wemanity on hold for NET30

data/events/2020-berlin.yml
Add our first platinum sponsor for 2020
=> [BER-2020] Add sponsor VMWare

data/events/2020-atlanta.yml
=> [ATL-2020] added fastly as gold

content/events/2020-caceres/location.md, data/events/2020-caceres.yml
Updated sponsors logos. Added more location info.
=> [CAC-2020] Updated sponsors logos. Added more location info.

data/events/2020-los-angeles.yml
[la2020] upgrade phoenixnap to gold
=> [la2020] upgrade phoenixnap to gold

data/events/2020-geneva.yml
[GE-2020] add Gold sponsor: Techfirm
=> [GE-2020] add Gold sponsor: Techfirm

content/events/2020-tokyo/sponsor.md, data/events/2020-tokyo.yml
=> [TYO-2020] Updated sponsorship data and added program link

content/events/2020-kyiv/program/baruch-sadogursky.md
Add talk title and description
=> [Kyiv-2020] Add Baruch Sadogursky's talk

content/events/2020-portland-or/propose.md, content/events/2020-portland-or/registration.md, data/events/2020-portland-or.yml
Adding the registration and CFP links
=> [PDX-2020] Adding CFP and registration links

content/events/2020-austin/welcome.md, data/events/2020-austin.yml
=> [ATX-2020] remove propose link

data/events/2020-denver.yml
=> [DEN-2020] Adding codefresh, site24x7, appdynamic, and harness.

data/events/2020-los-angeles.yml
=> [la 2020] add pulumi

data/events/2020-caceres.yml
Updated sponsors logos enabling two of them
=> [CAC-2020] Updated sponsors logos.

data/events/2020-guadalajara.yml
Added last sponsor and program updates
=> [GDL-2020] Added last sponsor and program updates

content/events/2020-seattle/program/bella-guo.md
Update Bella Guo talk decsription per request emailed to seattle@devopsdays.org
=> [SEA-2020] Update Bella Guo talk decsription per request 

themes/devopsdays-theme/layouts/partials/head/seo.html, themes/devopsdays-theme/layouts/partials/welcome.html
=> Fix for welcome page when event spans months

content/events/2020-bogota/sponsor.md, data/events/2020-bogota.yml
=> [BOG-2020] Sponsor packages information added

content/events/2020-guadalajara/program/taylor-thomas.md
=> [GDL-2020] Taylor speak info updated

content/events/2020-porto-alegre/speakers/cristian.md
=> [Porto Alegre-2020]Change name of speaker

content/events/2020-portugal/sponsor.md
* fix the number of gold sponsors
=> [PT2020] fix the number of gold sponsors

data/events/2020-poznan.yml
=> [POZ-2020] close cfp

data/events/2020-denver.yml
=> [DEN-2020] Add Elastic as silver sponsor.

data/events/2020-denver.yml
=> [DEN-2020] Add VMWare and Armory

utilities/examples/content/events/yyyy-city/conduct-fr.md
Thank you, @phrawzty & @jooooooon for https://2019.devopsrex.fr/content/code-de-conduite and https://github.com/devopsdays/devopsdays-web/pull/9164! I am attempting to add a reasonable template en français based on your devops rex code of conduct. I'll note a few questions inline.
=> Adding template en français

data/events/2020-salt-lake-city.yml
- Add GitLab as a silver sponsor
=> [SLC-2020] Add silver sponsor for 2020

data/events/2020-dallas.yml
adding xmatters and dark launchly as sponsors
=> [2020-DFW] adding xmatters and dark launchly as sponsors

content/events/2020-caceres/speakers/manuel-morejon.md
Updated Manuel Morejón description.
=> [CAC-2020] Updated Manuel Morejón description.

data/events/2020-poznan.yml
=> [POZ-2020] show Pinis talk in the program

content/events/2020-seattle/program/emily-freeman.md
=> [SEA-2020] Update with talk title and abstract for Emily Freeman

content/events/2020-salt-lake-city/welcome.md, data/events/2020-salt-lake-city.yml
__Update location
__Update dates
__a few minor corrections.
=> [SLC-2020] Update for venue and date due to Noah's closing

data/events/2020-new-york-city.yml
- add palo alto networks, redis
- rm video column
=> [NYC-2020] Sponsor Update

data/events/2020-amsterdam.yml
=> [AMS-2020] temp disable cyso

data/events/2020-los-angeles.yml
[la2020] upgrade logz.io to gold
=> [la2020] upgrade logz.io to gold

content/events/2020-buffalo/registration.md, content/events/2020-buffalo/welcome.md, data/events/2020-buffalo.yml
Opened up Early Bird Registration and so we are adding the link to our site.
=> [BUF-2020] Adding registration link

data/events/2020-los-angeles.yml
=> [la2020] add scout

content/events/2020-detroit/location.md, content/events/2020-detroit/sponsor-registration.md, content/events/2020-detroit/sponsor.md, data/events/2020-detroit.yml
=> [DET-2020] Contract signed; location added.

data/events/2020-toronto.yml, data/sponsors/redislabs.yml
Finishing the cleanup from https://github.com/devopsdays/devopsdays-web/pull/9363.
=> The correct "Redis Labs" is redis-labs.

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Monkey With Buttons as bronze

data/events/2020-los-angeles.yml
=> [la2020] add confluent

data/events/2020-charlotte.yml
=> [CLT-2020] update program - day 2

content/events/2020-guadalajara/program/cameron-motevasselani.md, content/events/2020-guadalajara/program/daniel-cortes.md, content/events/2020-guadalajara/program/edwin-moedano.md, content/events/2020-guadalajara/program/franchesco-romero.md, content/events/2020-guadalajara/program/francisco-rodriguez.md, content/events/2020-guadalajara/program/jesus-contreras.md, content/events/2020-guadalajara/program/jorge-castro.md, content/events/2020-guadalajara/program/jose-leitao.md, content/events/2020-guadalajara/program/julian-limon.md, content/events/2020-guadalajara/program/leoswaldo-macias.md, content/events/2020-guadalajara/program/liz-fong-jones.md, content/events/2020-guadalajara/program/manuel-gutierrez.md, content/events/2020-guadalajara/program/mike-rosado.md, content/events/2020-guadalajara/program/mofizur-rahman-ignite.md, content/events/2020-guadalajara/program/mofizur-rahman.md, content/events/2020-guadalajara/program/napoleon-jones.md, content/events/2020-guadalajara/program/ra-acosta.md, content/events/2020-guadalajara/program/rex-roof.md, content/events/2020-guadalajara/program/salvador-elizarraras.md, content/events/2020-guadalajara/program/sasha-rosenbaum.md, content/events/2020-guadalajara/program/taylor-thomas.md, content/events/2020-guadalajara/program/thomas-adams.md, content/events/2020-guadalajara/program/yury-nino.md, content/events/2020-guadalajara/welcome.md, data/events/2020-guadalajara.yml
Speakers slides added and registration link removed
=> [GDL-2020] Speakers slides added

content/events/2020-denver/welcome.md, data/events/2020-denver.yml
=> [Den 2020] Add logz.io sponsor, close CFP, make dates clear

data/events/2020-caceres.yml
Added special sponsors "bronze fruit" and "bronze water" levels.
Moved Homeria and Mobbeel sponsors to those levels.
=> [CAC-2020] Added special sponsors levels

content/events/2020-medellin/location.md, content/events/2020-medellin/welcome.md, data/events/2020-medellin.yml
Adding to the Welcome Page buttons for Call for papers and Tickets. fixing Twitter name event "event_twitter" and adding date for call for papers in medellin.yml
=> [MDE-2020] Adding CFP/Tickets Button / Fixing Twitter Event

content/events/2020-houston/program/ana-margarita-medina.md, content/events/2020-houston/program/angel-rivera.md, content/events/2020-houston/program/eduardo-ruela.md, content/events/2020-houston/program/jay-gordon.md, content/events/2020-houston/program/jody-wolfborn.md, content/events/2020-houston/program/john-eldridge.md, content/events/2020-houston/program/julie-gunderson.md
=> [HOU-2020] Added or corrected Location for every workshop file

data/events/2020-minneapolis.yml
=> [MSP 2020] Extending MSP CFP

data/events/2020-tokyo.yml
Might not be best way to do it, but only have GitHub web access for now. Feel free to change/edit if there's a better way. Thanks!
=> [TYO-2020] removed dates, added cancellation notice

data/events/2020-joao-pessoa.yml
C4P and participant registration open.
=> [JPA 2020] - C4P and participant registration open.

content/events/2020-tokyo/location.md, content/events/2020-tokyo/program.md, content/events/2020-tokyo/welcome.md, data/events/2020-tokyo.yml
Adding to https://github.com/devopsdays/devopsdays-web/pull/9549 for @apxltd re: Tokyo 2020.
=> [Tokyo 2020] adding details

content/events/2020-tokyo/location.md, content/events/2020-tokyo/program.md, content/events/2020-tokyo/welcome.md
=> [TYO-2020] minor adjustment

content/events/2020-criciuma/location.md, data/events/2020-criciuma.yml
=> [CUA-2020] Criciuma - Locations

data/events/2020-stockholm.yml
=> [STH 2020] announce dates

content/events/2020-houston/program/julie-gunderson.md, content/events/2020-houston/speakers/julie-gunderson.md
A few stray fixes that were missed when Julie replaced Matty on this talk :)
=> [HOU-2020] Updates with speaker name changes 

data/events/2020-los-angeles.yml
With the concerns around travel, we are updating folks with where we are
tracking developments and where they should go for more info.
=> [LA-2020] Add a note about covid-19

content/events/2020-seattle/location.md, content/events/2020-seattle/program.md, content/events/2020-seattle/sponsor.md, content/events/2020-seattle/welcome.md, data/events/2020-seattle.yml
Please do not merge, we'd like the personal notifications to go out first but would like this ready to go.
=> [SEA-2020] postponing seattle

appveyor.yml
Pinning to the right version of hugo
=> Pin hugo version in appveyor

content/events/2020-seattle/welcome.md
=> [SEA-2020] correct typo

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Microsoft as Pre Event sponsor

data/events/2020-denver.yml
=> [DEN-2020] Add Redis-Labs as silver sponsor.

data/events/2020-dallas.yml
adding solarwinds as a platinum sponsor
=> [2020-DFW] adding solarwinds as a platinum sponsor

data/events/2020-eindhoven.yml
- Add Sarah as organizer. 
(Already added to EHV mailing list & Slack)
=> [EHV2020] - Add Sarah as organizer

data/events/2020-houston.yml
=> [HOU-2020] Added VMware as Gold Sponsor

content/events/2020-houston/sponsor.md, data/events/2020-houston.yml
[HOU-2020] Added Dynatrace as Gold sponsor, removed PayPal links
=> [HOU-2020] Added Dynatrace as Gold sponsor, removed PayPal link for Gold

data/events/2020-poznan.yml
=> [POZ-2020] rescheduling the event :(

content/events/2020-lima/conduct-fr.md, content/events/2020-lima/conduct-pt-br.md, content/events/2020-lima/conduct.md, content/events/2020-lima/contact.md, content/events/2020-lima/location.md, content/events/2020-lima/propose.md, content/events/2020-lima/registration.md, content/events/2020-lima/sponsor.md, content/events/2020-lima/welcome.md, data/events/2020-lima.yml, static/_redirects
We also sent a email to info@devopsdays.org with the organizers.
=> [LIMA-2020] Add Lima-2020 event and organizers

content/events/2020-raleigh/propose.md, content/events/2020-raleigh/sponsor.md, data/events/2020-raleigh.yml
[RDU-2020] added sponsor info and speaker submission forms and info
=> [RDU-2020] added sponsor info and speaker submission forms and info

data/events/2020-minneapolis.yml
=> [MSP-2020] Add googlecloud as gold sponsor

data/events/2020-vancouver.yml
=> [VAN-2020] remove sumologic as a sponsor

content/events/2020-minneapolis/propose.md, content/events/2020-minneapolis/welcome.md, data/events/2020-minneapolis.yml
=> [MSP 2020] Closing proposals for MSP

content/events/2020-chicago/welcome.md
Adding link to health statement to the chicago welcome page
=> [CHI-2020] Add health statement

content/events/2020-prague/welcome.md, data/events/2020-prague.yml
=> [PRG-2020] moving date and sponsor update

content/events/2020-baltimore/welcome.md, data/events/2020-baltimore.yml
=> [BMORE-2020] Cancel Event :(

data/events/2020-vancouver.yml
Add Gitlab as a silver sponsor
=> [VAN-2020] add gitlab as silver sponsor

content/events/2020-rosario/conduct.md, content/events/2020-rosario/contact.md, content/events/2020-rosario/location.md, content/events/2020-rosario/propose.md, content/events/2020-rosario/registration.md, content/events/2020-rosario/sponsor.md, content/events/2020-rosario/welcome.md, data/events/2020-rosario.yml, static/_redirects
=> [ROS-2020] Placholder for DevOpsDays Rosario

data/events/2020-dallas.yml
updating employer for jim baldwin
=> [2020-DFW] updating employer for jim baldwin

content/events/2020-berlin/welcome.md, data/events/2020-berlin.yml
Make it a bit more clear how long the CfP is running.
=> [BER-2020] Add CfP dates to front matter for transparency

content/events/2020-warsaw/conduct.md, content/events/2020-warsaw/contact.md, content/events/2020-warsaw/location.md, content/events/2020-warsaw/registration.md, content/events/2020-warsaw/sponsor.md, content/events/2020-warsaw/welcome.md, data/events/2020-warsaw.yml
=> [WAW-2020] New event added.

content/events/2020-toronto/sponsor.md, content/events/2020-toronto/welcome.md, data/events/2020-toronto.yml
Thank you to Seattle for the wording.
=> [TOR-2020] Remove Toronto 2020 from the schedule

content/events/2020-vancouver/welcome.md, data/events/2020-vancouver.yml
Remove links for day of conference information
Remove links for CFP
Remove Registration links
Add notice of conference cancellation
Remove NewRelic from sponsor list
Remove InfluxData from sponsor list
=> [VAN-2020] add cancellation notice to website

content/events/2020-portugal/welcome.md, data/events/2020-portugal.yml
=> [PT-2020] Postponing due to covid-19

content/events/2020-denver/postpone.md, content/events/2020-denver/welcome.md, data/events/2020-denver.yml
=> [Den-2020] Postponement announcement.

data/events/2020-vancouver.yml
=> [VAN-2020] Remove dates - event cancelled

data/events/2020-krakow.yml
Reschedule of Krakow DevOpsDays to 3rd Septmeber 2020
=> [KRK-2020] Reschedule KRK 2020 event to 3rd of September

content/events/2020-denver/postpone.md
=> [DEN-2020] Add timeframe for ticket refunds.

data/events/2020-amsterdam.yml
=> [AMS-2020] Add Xebia as bronze sponsor

content/events/2020-des-moines/sponsor.md, content/events/2020-des-moines/welcome.md, data/events/2020-des-moines.yml, data/sponsors/dice.yml
=> [DSM-2020] Add health statement

content/events/2020-amsterdam/cancellation.md, content/events/2020-amsterdam/welcome.md, content/events/2020-eindhoven/welcome.md
=> [EHV & AMS 2020 ] fix typo in link

content/events/2020-columbus/welcome.md, data/events/2020-columbus.yml
Adding a cancellation notice for 2020. If you have any additional suggestions for what to add, remove, etc. Let me know. We will working with the venue to assign new dates for next year.
Also removed Warner and Renee. E-mail as requested has been sent.
Thanks!
=> [Columbus-2020] Adding cancelled notice.

content/events/2020-washington-dc/welcome.md, data/events/2020-washington-dc.yml
At least not while planning is paused.
=> [DC-2020] Not accepting sponsors

content/events/2020-sao-paulo/welcome.md, data/events/2020-sao-paulo.yml
Postpone Sao Paulo evento to December.
=> [SP-2020] Postpone to December

data/events/2020-minneapolis.yml
=> [MSP-2020] Add hashicorp as gold

content/events/2020-boston/welcome.md, data/events/2020-boston.yml
Adding CFP and registration links to the Boston event.
=> [BOS-2020] CFP and registration links.

content/events/2020-cape-town/welcome.md
Publish an interim notice for Cape Town 2020 regarding COVID-19.
CC @adrianmoisey
=> [CPT-2020] COVID-19 interim notice

data/events/2020-prague.yml
=> [PRG-2020] a sponsor level change

content/events/2020-natal/program/abertura.md, content/events/2020-natal/welcome.md, data/events/2020-natal.yml
This PR updates Natal event date to Nov 14th.
We had to postpone the event due to the New Coronavirus outbreak.
=> [NAT-2020] Update event date

data/events/2020-zurich.yml, data/sponsors/swisscom.yml
=> [ZRH-2020] Add Swisscom as sponsor

content/events/2020-aracaju/welcome.md, data/events/2020-aracaju.yml
2020-aracaju.yml event date changed
=> Aju2020 - Postponing DOD

data/events/2020-atlanta.yml
This one's for Mike ya'll : D
It's already updated on Eventbrite too.
=> [ATL-2020] changing dates to July 27th & 28th

data/events/2020-zurich.yml
=> [ZRH-2020] Add SwissRe as sponsor

content/events/2020-zurich/sponsor.md
=> [ZRH-2020] Changed the package availability

content/events/2021-minneapolis/welcome.md, data/events/2021-minneapolis.yml
=> [MSP 2021] Re-opening reg with new dates

content/events/2020-london/sponsor.md, content/events/2020-london/welcome.md, data/events/2020-london.yml
- update welcome page and sponsor page to show statement on covid-19
- add gold sponsor circleci who have paid.
=> [LDN-2019] Novel Coronavirus Information + Sponsor

data/events/2020-minneapolis.yml, data/events/2021-minneapolis.yml
=> [MSP 2021] Sponsor updates 2020 -> 2021

data/events/2020-minneapolis.yml
=> [MSP 2020] Refund for 2020

data/events/2020-minneapolis.yml
=> [MSP 2020] Removing sponsor who will return in 2021

content/events/2020-portland-or/welcome.md, data/events/2020-portland-or.yml
Adding a cancellation statement and adjusting event data
=> [PDX-2020] Cancelling  :(

content/events/2020-portland-me/welcome.md, data/events/2020-portland-me.yml
We have decided to postpone our inaugural event, this PR cancels PWM 2020. Hopefully we will kick things off Spring 2021.
=> [PWM-2020] cancellation

data/events/2020-minneapolis.yml
Update - another removal for cancelled event.
=> [MSP 2020] Sponsor update

utilities/add_new_event.sh
Got the solution from https://unix.stackexchange.com/a/31955
=> Always ensure a trailing newline before appending to this file

content/events/2020-zurich/welcome.md
=> [ZRH-2020] Add COVID-19 Information

content/events/2020-washington-dc/welcome.md, data/events/2020-washington-dc.yml
Following all of the [guidance for cancelled events](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/docs/cancel-event.md)
=> [DC-2020] - More updates for cancellation.

themes/devopsdays-theme/layouts/partials/welcome.html
Microformats2 is a standard that allows marking up HTML with
machine-readable information, which allows better interoperability with
various tools, as well as improving Search Engine Optimisation.
We can use Microformats2 to mark up the important metadata for events as
an `h-event`, with the following key properties:
- the name of the event
- the start, and if present, end of the event
- if present, the full location of the event
- the URL of the event, so a parser can save it to i.e. return later
- if present, the description of the event
Closes #9505
Examples:
<details>
<summary>Microformats2 JSON: 2020 London</summary>
```json
{
"items": [
{
"type": [
"h-event"
],
"properties": {
"name": [
"devopsdays London"
],
"url": [
"http://localhost:1313/events/2020-london/welcome/"
],
"start": [ …
```
=> Mark up /welcome/ for events with Microformats2

data/events/2020-chicago.yml
Updating Sponsorship to DevOpsDays Chicago 2020
=> [CHI-2020] Add Gold Sponsors

data/events/2020-chicago.yml
The CFP for Chicago 2020 is being extended (more details coming soon on some other changes)
=> [CHI-2020] Extend CFP

data/events/2020-montreal.yml
=> [MTL-2020] removing Carol from organizers for 2020 :(

data/events/2020-raleigh.yml
[rdu-2020] extend CFP submission deadline
=> [rdu-2020] extend CFP submission deadline

data/events/2020-buffalo.yml
[BUF-2020] Extend CFP Dates / Update Organizer Bios
=> [BUF-2020] Extend CFP Dates / Update Organizer Bios

content/events/2020-kyiv/welcome.md, data/events/2020-kyiv.yml
* Updated the "Welcome" page to make it clear that the conference has moved online
* Fixed Registration link
* Updated sponsor's list (one in, one out)
=> [Kyiv-2020] Sponsors update & fixes

data/events/2020-minneapolis.yml, data/events/2021-minneapolis.yml
Moving last sponsor from 2020 to 2021.
=> [MSP 2021] Moving last sponsor off 2020 to 2021

data/events/2021-minneapolis.yml
=> [MSP 2021] Correcting order

data/events/2020-detroit.yml
=> [detroit-2020] member changes

content/events/2020-ankara/welcome.md, content/events/2020-istanbul/welcome.md, data/events/2020-ankara.yml, data/events/2020-istanbul.yml
Hi folks, we are teaming up with İstanbul and Ankara to organize an online conference. We have decided on a date and proceeding with updates to our local communities.
=> [IST-2020] and [ANK-2020] Update Ankara and İstanbul for online conference

content/events/2020-chicago/welcome.md
Just making it look a little nicer for open graph stuff
=> [CHI-2020] Change description tag for Chicago welcome page

data/events/2020-raleigh.yml
[RDU-2020] Updated deadline for propose
=> [RDU-2020] Updated deadline for propose

data/events/2020-chicago.yml
Remove Panopta as they have canceled and been refunded.
=> [CHI-2020] Sponsor update

content/blog/_index.md
Fixes #8219
This was so easy to fix I can't believe it took me this long
=> Fix issue with blog in footer

data/events/2020-ankara.yml, data/events/2020-istanbul.yml
We have updated our registration link and added a community sponsor.
=> [IST-ANK-2020] update registration link and add devnot as a community sponsor

content/events/2020-amsterdam/sponsor.md
Please check that the sponsor benefits are accurate, and the cap on attendees is correct, @PaulusTM
=> [AMS-2020] Update sponsor page

content/events/2020-buffalo/welcome.md, data/events/2020-buffalo.yml
Buffalo 2020 will be virtual, with a return to simpler times
(we hope!) in 2021.  Update verbiage to match.
=> [BUF-2020] Going Virtual!

content/events/2020-boston/welcome.md, data/events/2020-boston.yml
=> [BOS-2020] Update date and fix wording.

data/events/2020-cairo.yml
Updating date to 21 instead of 20
=> [CAI-20] Updating date to 21 instead of 20

themes/devopsdays-theme/theme.toml
This is a test PR against `development`
=> Bump theme version for PR test

utilities/add_new_event.sh
Looks like this is a typo
Fixes https://github.com/devopsdays/devopsdays-web/issues/9798
=> Fix variable name DOD_CITY

content/events/2020-amsterdam/registration.md, data/events/2020-amsterdam.yml
This PR embeds the Ti.to ticketing widget to the registration page.
WIP while we test if this is going to work.
=> WIP: [AMS-2020] embed Tito ticket widget

content/events/2020-amsterdam/registration.md
We don't do bulk tickets by invoice this year as tickets are free.
=> [AMS-2020] We don't do bulk tickets by invoice 

themes/devopsdays-theme/layouts/talk/single.html
=> Fix extra carriage returns on talk pages

content/events/2020-amsterdam/speakers/dave-van-herpen.md
Update the bio for Dave on his request.
=> [AMS-2020] Update bio Dave van Herpen

content/events/2020-amsterdam/sponsor.md
As per our last team meet, updating sponsorship packages (pricing).
=> [AMS-2020] Update sponsorship packages

data/events/2020-amsterdam.yml
Add Fullstaq as bronze sponsor.
=> [AMS-2020] Add Fullstaq as bronze sponsor

content/events/2020-goiania/cfp.md, content/events/2020-goiania/inscricao.md, content/events/2020-goiania/welcome.md, data/events/2020-goiania.yml
=> [GYN-2020] Event now will be online

data/events/2020-stockholm.yml
* yet another organizer, yay
* postpone CFP date as a virtual event doesn't require hotel and travel reservations
=> [STH-2020] postpone cfp and add beatriz

content/events/2020-buffalo/sponsor.md, content/events/2020-buffalo/welcome.md
Making sponsorship notice clear for virtual event. Also resolving some merge errors on my fork.
=> [BUF-2020] Correcting Sponsor Statement for Virtual Event

content/events/2020-boston/welcome.md
=> [BOS-2020] Remove CFP link.

data/events/2020-criciuma.yml
=> [Criciuma- 2020] Cancelling event.

content/events/2020-amsterdam/registration.md
Please hold for technology validation
=> [AMS-2020] Move registration to the video platform

content/events/2020-chicago/sponsor.md
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
We don't need to list the fees
=> [CHI-2020] Remove reference to paypal fees

content/events/2020-amsterdam/program/karen-sijbrandij.md
=> [AMS] Add talk descr for Karen Sijbrandij

content/events/2020-amsterdam/speakers/karen-sijbrandij.md
=> [AMS-2020] Add image to Karen

content/events/2020-amsterdam/program/dave-van-herpen.md
=> [AMS] Update Dave van Herpen description

content/events/2020-amsterdam/program/lian-li.md
=> [AMS] Update Lian Li talk description

utilities/docs/cancel-event.md
=> remove trailing 's' from path

content/events/2020-chicago/sponsor.md, data/events/2020-chicago.yml
=> [CHI 2020] 2020 sponsor page updates

content/events/2020-amsterdam/program/irenne-zbarsky.md, content/events/2020-amsterdam/speakers/irenne-zbarsky.md, data/events/2020-amsterdam.yml
=> [AMS-2020] Update the talk and bio from Irenne

data/events/2020-amsterdam.yml
This is a large schedule update so I have to check the preview deployment if everything looks good.
=> [AMS-2020] Schedule update

bin/netlify.sh, bin/staging-robots.txt
=> Update deploy previews to disallow robots

data/events/2020-amsterdam.yml
=> [AMS] Update schedule to align tracks and open spaces

content/events/2020-boston/sponsor.md
HTML-ified version of devopsdays/devopsdays-assets#94.
=> [BOS-2020] Sponsor prospectus update.

content/events/2020-amsterdam/registration.md
With this PR we close ticket sales and redirect people to our crowdcast page.
=> [AMS-2020] CLose registration and forward to crowdcast page

data/events/2020-amsterdam.yml
Adding last minute gold sponsor
=> [AMS-2020] Add Contrast Security as gold sponsor

content/events/2020-chicago/registration.md, content/events/2020-chicago/welcome.md, data/events/2020-chicago.yml
=> [CHI-2020] Chicago registration

content/events/2020-raleigh/welcome.md, data/events/2020-raleigh.yml
[RDU-2020] updated registration link to all things open
=> [RDU-2020] updated registration link to all things open

data/events/2020-chicago.yml
=> [CHI-2020] removed solarwinds after refund

content/events/2020-buenos-aires/location.md, content/events/2020-buenos-aires/sponsor.md, data/events/2020-buenos-aires.yml
Date undefined, we'll confirm soon. Collaborators list updated.
=> [BAI-2020] Buenos Aires 2020 update, virtual event, details TBD

data/events/2020-zurich.yml, data/events/2021-zurich.yml
=> [ZRH-2020] Add Switch as sponsor

data/events/2020-chicago.yml
Enable the link to the program for 2020 Chicago event
=> [CHI-2020] Enable program menu link

content/events/2020-chicago/speakers/sarah-aslanifar.md
Update Sarah's bio at her request
=> [CHI-2020] Update Sarah bio

content/events/2020-medellin/sponsor.md
[MDE-2020] Updating Values and Condition for Sponsorship to actual agreements
=> [MDE-2020] Updating Values and Condition for Sponsorship to actual agreements

data/events/2020-zurich.yml, data/events/2021-zurich.yml
=> [ZRH-2020] Add Google Analytics Tracking ID

content/events/2020-zurich/program/bridget-kromhout.md, content/events/2020-zurich/program/john-willis.md, content/events/2020-zurich/program/seth-vargo.md, content/events/2020-zurich/program/shelby-spees.md, content/events/2020-zurich/program/tanja-janca.md, content/events/2020-zurich/registration.md
=> [ZRH-2020] Add registration

data/events/2020-chicago.yml
=> [chi-2020] new gold sponsors

data/events/2020-chicago.yml
=> [CHI-2020] removed transcript sponsorship option

content/events/2020-buffalo/program.md, data/events/2020-buffalo.yml
Adding our full schedule for the one day virtual event.
=> [BUF-2020] Adding our schedule and program

content/events/2020-chicago/program/sherlaender-lani-phillips.md, content/events/2020-chicago/virtual-event.md, content/events/2020-chicago/welcome.md, data/events/2020-chicago.yml
This adds the title and abstract to Lani's talk, as well as the detail page for the virtual event.
=> [CHI-2020] Update Lani's talk and add virtual event info

data/events/2021-washington-dc.yml
Welcome back @robbkidd and @VictoriaGuido!
=> [DC-2020] Adding new organizers

data/events/2021-washington-dc.yml
=> [DC-2020] Peter will help co-organize again.

content/events/2020-chicago/program/rafael-gomes.md, content/events/2020-chicago/speakers/rafael-gomes.md
My bio was wrong and Sasha convinced me to change the title.
=> [CHI-2020] Change my bio and update the title of my talk

data/events/2020-fortaleza.yml
Update date events and add url c4p
=> [FOR-2020] alter date event and remove member

hugoserver.sh
See https://devopsdays.slack.com/archives/C07T0BHHN/p1597278391092100 - Hugo doesn't start up if your shell is dash, and/or you don't have some directories present in the repository with specific permissions.
```
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen: permission denied
[don@zeus ~/devopsdays-web:master] mkdir resources/_gen
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen/assets: permission denied
[don@zeus ~/devopsdays-web:master] mkdir resources/_gen/assets …
```
=> Prevent error on startup if the site hasn't been built before.

content/events/2020-cairo/sponsor.md, content/events/2020-cairo/welcome.md, data/events/2020-cairo.yml
=> [CAI-2020] Update Sponsorship packages

content/events/2020-chicago/sponsor.md
There was some weirdness here. @margaretvaltie please approve this before we merge it.
=> [CHI-2020] Remove special sponsorship text from Chicago 2020

content/events/2020-boston/program.md, content/events/2020-boston/sponsor.md, content/events/2020-boston/virtual-event.md, content/events/2020-boston/welcome.md, data/events/2020-boston.yml
Adding a virtual event page and updating welcome page to link to the new page
for easier discovery.
=> [BOS-2020] Add virtual-event page

data/events/2020-chicago.yml
=> [CHI-2020] Remove xmatters as a sponsor

data/events/2020-chicago.yml
=> [CHI-2020] Update to Add JPMC as Sponsor

content/events/2020-chicago/program.md, content/events/2020-chicago/virtual-event.md, content/events/2020-chicago/welcome.md, data/events/2020-chicago.yml
Adds an embedded livestream to the welcome page, as well as some other links and nav.
=> [CHI-2020] Add livestream to chicago 2020

content/events/2020-sao-paulo/welcome.md, hugoserver.sh
=> [SP-2020] - Adding Mailchimp Form

content/events/2020-columbus/welcome.md, data/events/2020-columbus.yml
This never got canceled properly
=> [COLUMBUS- 2020] Mark 2020 Columbus as cancel

content/events/2020-zurich/program/shelby-spees.md, data/events/2020-zurich.yml
=> [ZRH-2020] Add sponsor Microsoft

content/events/2020-chicago/sponsor.md, data/events/2020-chicago.yml
=> [CHI-2020] turn off gold for Chicago 2020

data/events/2020-chicago.yml
Add jfrog as a gold sponsor, and add the fireside chats
=> [CHI-2020] Add jfrog as sponsor & add fireside chats

data/events/2021-washington-dc.yml
Slack and mailing list have already been updated.
=> [DC-2021] Adds Dayton Williams as an organizer

data/events/2020-zurich.yml, data/events/2021-zurich.yml
=> [ZRH2020] Change organizer text of romano roth

data/events/2020-chicago.yml
Updates to our schedule after seeing how long recorded content runs
=> [CHI-2020] Update Schedule with more accurate timing

content/events/2020-cairo/speakers.md, data/events/2020-cairo.yml
=> [Cairo 2020] Fixing links

content/events/2020-cairo/welcome.md
Announcing Live Facebook link on welcome page
=> [CAI-20] Announcing Live Facebook link

data/events/2020-buffalo.yml
=> [buf-2020] Microsoft Azure to sponsor BUF

content/events/2020-buffalo/program.md
=> [buf-2020] All times in EDT, per quintessence

content/events/2020-buffalo/program/ben-ellerby.md, data/events/2020-buffalo.yml
=> [buf-2020] Ben Ellerby is speaking at DevOps Days!

content/events/2020-prague/welcome.md, data/events/2020-prague.yml
=> [PRG-2020] Prague reschedule

data/events/2020-buffalo.yml
=> [buf-2020] Add CircleCI as Silver Sponsor

content/events/2020-buffalo/welcome.md
=> [buf-2020] Link "Get Tickets" button to ti.to URL

content/events/2020-boston/program/john-willis.md, data/events/2020-boston.yml
Swapping two speakers for time-of-day optimizations, and adding a description for the keynote.
=> [BOS-2020] Session updates.

content/events/2020-buffalo/program/angel-rivera.md, data/events/2020-buffalo.yml
=> [buf-2020] Fix Angel Rivera talk meta / scheduling

data/events/2020-buffalo.yml
Just two days to go new bronze sponsor!
This also re-instates the Bronze tier
=> [buf-2020] Add PagerDuty as a Sponsor

data/events/2020-buffalo.yml
=> [2020-BUF] Add devops party games to program

content/events/2020-stockholm/location.md, content/events/2020-stockholm/program/clarissa-rodrigues.md, content/events/2020-stockholm/program/fredrik-viljesjö.md, content/events/2020-stockholm/program/gil-zellner.md, content/events/2020-stockholm/program/jay-gordon.md, content/events/2020-stockholm/program/jeremy-meiss.md, content/events/2020-stockholm/program/kristian-larsson.md, content/events/2020-stockholm/program/lars-albertsson.md, content/events/2020-stockholm/program/tommy-adams.md, content/events/2020-stockholm/welcome.md, data/events/2020-stockholm.yml
The remaining speakers have now been confirmed.
Two organizers have resigned due to time constraints.
And we have a Discord server to serve as the nexus for the event.
=> [STH-2020] Add event details

content/events/2020-sao-paulo/welcome.md, data/events/2020-sao-paulo.yml
=> [SP-2020] Fixing tickets URL

content/events/2020-sao-paulo/sponsor.md, data/events/2020-sao-paulo.yml
* Added again sponsor page with new values and benefits
=> [SP-2020] re-added sponsor page

content/events/2021-raleigh/welcome.md
Removing end date since its a one day event.
=> [RDU-2021] Update welcome.md

content/events/2020-sao-paulo/program.md, content/events/2020-sao-paulo/welcome.md, data/events/2020-sao-paulo.yml
Adding the program page and fixing typos
=> [SP-2020] Adding the program page and fixing typos

data/events/2020-sao-paulo.yml
=> [SP-2020] Added CFP announce date

data/events/2020-sao-paulo.yml
Fixed close date of call for proposals
=> [SP-2020] Fixed close date of call for proposals

data/events/2020-sao-paulo.yml
* changed cfp link into 2020-sao-paulo.yml
=> [SP-2020] Changed CFP link

.circleci/config.yml, appveyor.yml, hugoserver.ps1, hugoserver.sh, netlify.toml, themes/devopsdays-theme/layouts/partials/sponsors.html
Fixes #10059 
Fixes #10005 
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
=> Upgrade to hugo 76.5

content/events/2020-boston/welcome.md
=> [BOS-2020] Post devops boston2020 update including donation info

content/events/2020-sao-paulo/sponsor.md
=> [SP-2020] Fixed sponsor values

content/events/2020-chicago/program/aaron-aldrich.md, content/events/2020-chicago/program/amy-arambulo-negrette.md, content/events/2020-chicago/program/brendan-oleary.md, content/events/2020-chicago/program/emily-freeman.md, content/events/2020-chicago/program/henry-quinn.md, content/events/2020-chicago/program/jason-yee.md, content/events/2020-chicago/program/jeff-smith.md, content/events/2020-chicago/program/jeremy-meiss.md, content/events/2020-chicago/program/laura-santamaria.md, content/events/2020-chicago/program/quintessence-anx.md, content/events/2020-chicago/program/rafael-gomes.md, content/events/2020-chicago/program/sherlaender-lani-phillips.md
Added link for slides for (most) of the 2020 speakers
=> [CHI-2020] Add some chicago 2020 speaker slide links

content/events/2020-sao-paulo/sponsor.md
=> [SP-2020] Fixed sponsor quotas

content/events/2020-stockholm/program/fredrik-viljesjö.md, content/events/2020-stockholm/program/gil-zellner.md, content/events/2020-stockholm/program/jeremy-meiss.md, content/events/2020-stockholm/program/lars-albertsson.md, content/events/2020-stockholm/program/tommy-adams.md
Hopefully the final change for the 2020 event.
=> [STH-2020] add youtube links to talks

content/events/2020-chicago/program/richard-cook.md
=> [CHI-2020] Add Dr. Cook slides

content/events/2020-sao-paulo/sponsor.md
Commented sponsor gold benefit
=> [SP-2020] Commented sponsor gold benefit

data/events/2020-sao-paulo.yml
[SP-2020] - Adding talks to the program page
=> [SP-2020] - Adding talks to the program page

content/events/2021-houston/propose.md
=> [HOU-2021] Added papercall.io link

data/events/2021-houston.yml
=> [HOU-2021] Changing cfp_date_start to match Papercall

content/events/2020-sao-paulo/program/kelvin-silva.md, data/events/2020-sao-paulo.yml
* Added ignites talks into program
=> [SP-2020] Added ignites talks into program

content/events/2021-houston/sponsor.md
=> [HOU-2021] Added 2021 prospectus link

content/events/2020-chicago/program/aaron-aldrich.md, content/events/2020-chicago/program/amy-arambulo-negrette.md, content/events/2020-chicago/program/brendan-oleary.md, content/events/2020-chicago/program/emily-freeman.md, content/events/2020-chicago/program/henry-quinn.md, content/events/2020-chicago/program/jason-yee.md, content/events/2020-chicago/program/jeff-smith.md, content/events/2020-chicago/program/jeremy-meiss.md, content/events/2020-chicago/program/laura-santamaria.md, content/events/2020-chicago/program/quintessence-anx.md, content/events/2020-chicago/program/rafael-gomes.md, content/events/2020-chicago/program/renata-rocha.md, content/events/2020-chicago/program/richard-cook.md, content/events/2020-chicago/program/sarah-aslanifar.md, content/events/2020-chicago/program/sherlaender-lani-phillips.md
Adds videos for all talks. Do not merge until 30 Nov when the videos have been marked public on youtube!
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
=> [CHI-2020] Add videos for Chicago 2020

content/events/2021-texas/sponsor.md
[TX-2021] Added prospectus link and details about sponsorship levels
=> [TX-2021] Added prospectus link and details about sponsorship levels

static/_redirects
=> Adding redirect for Texas

content/events/2021-seattle/welcome.md, data/events/2021-seattle.yml
=> [SEA-2021] Open CFP

content/events/2021-texas/propose.md, content/events/2021-texas/registration.md, content/events/2021-texas/sponsor.md, content/events/2021-texas/welcome.md, data/events/2021-texas.yml
- Updated Karl's bio
- Updated prospectus link, added Captioning sponsorship level
- Added PayPal links for Gold, Silver and Bronze sponsorships
- Added Propose page and CFP dates and links
- Added registration page and eventbrite links
=> [TX-2021] Sponsorship & organizer updates

content/events/2021-texas/sponsor.md
=> [TX-2021] Updated prospectus links back to assets site

data/events/2021-nashville.yml
=> [NASH-2021] date change for Nashville 2021

content/events/2020-aarhus/welcome.md, content/events/2021-aarhus/welcome.md, data/events/2021-aarhus.yml
February event is postponed. 
Dates are not known yet, but the event is expected to happen in the Fall of 2021.
Please let me know if I need to change anything.
=> [AAR-2021]: Updated after postponing from Feb 2021 to Fall 2021

data/events/2021-minneapolis.yml
=> [MSP 2021] organizer bio update

data/events/2021-texas.yml
[TX-2021] Added Site24x7 as Gold Sponsor
=> [TX-2021] Added Site24x7 as Gold Sponsor

data/events/2021-seattle.yml, static/_redirects
Updates CFP close date to Feb 01 2021
Updates the redirect for /seattle to /events/2021-seattle/
=> [SEA-2021] Update CFP close date and redirect.

data/events/2021-texas.yml
[TX-2021] Added Stackhawk as Gold sponsor
=> [TX-2021] Added Stackhawk as Gold sponsor

data/events/2021-zurich.yml
=> [ZRH-2021] Add sponsor microsoft

data/events/2021-texas.yml
[TX-2021] Added LogDNA as Gold Sponsor
=> [TX-2021] Added LogDNA as Gold Sponsor

.circleci/config.yml, CONTRIBUTING.md, README.md, utilities/README.md, utilities/docs/workflow/README.md, utilities/docs/workflow/build.md
This updates various documentation after changing `master` to `main` for the default branch
=> update docs after main branch change

data/events/2021-zurich.yml
=> [ZRH-2021] Change CFP link and date

content/events/2021-zurich/propose.md
=> [ZRH-2021] fixed sessionize link in propose

content/events/2021-raleigh/registration.md, content/events/2021-raleigh/welcome.md, data/events/2021-raleigh.yml
[RDU-2021] updated registration links
=> [RDU-2021] updated registration links

data/events/2021-texas.yml
=> [TX-2021] Added StateFarm as Captioning Sponsor

content/events/2021-raleigh/welcome.md, data/events/2021-raleigh.yml
[RDU-2021] expose program and speakers in menu bar
=> [RDU-2021] expose program and speakers in menu bar

data/events/2021-zurich.yml
=> [ZRH-2021] Remove sponsor Microsoft

content/events/2021-raleigh/program.md
[rdu-2021] added program md file
=> [rdu-2021] added program md file

content/events/2021-texas/sponsor.md
=> [TX-2021] updating sponsorship tier info

content/events/2021-raleigh/program/mirza-dautbegovic.md, content/events/2021-raleigh/speakers/mirza-dautbegovic.md
=> [rdu-2021] fixed mirza name

data/events/2021-raleigh.yml
[rdu-2021] fixed mirza ignite in program
=> [rdu-2021] fixed mirza ignite in program

data/events/2021-poznan.yml
=> [POZ-2021] Company update for Jakub Jakubik

content/events/2021-dallas/welcome.md
=> [DFW-2021] Updating COVID-19 message on Welcome page

content/events/2021-zurich/sponsor.md
=> [ZRH2021] Update sponsoring table and sponsoring package link

content/events/2021-vancouver/sponsor.md
=> [VAN-2021] Update link to view Sponsorship information for 2021

content/events/2021-boston/welcome.md
We've had several folks e-mail in and ask why we don't have a CFP
link up, so I'm adding a big callout in addition to the standard
"Propose" button.
=> [BOS-2021] Bigger CFP text.

data/events/2021-raleigh.yml
[rdu-2021] changed sponsor levels and added chaossearch as sponsor
=> [rdu-2021] changed sponsor levels and added chaossearch as sponsor

data/events/2022-boise.yml
- Announcement of delay till 2022
=> [BOI-2021] Removal of resigned members

content/events/2021-zurich/diversity.md, content/events/2021-zurich/welcome.md, data/events/2021-zurich.yml
=> [ZRH-2021] Add new page for diversity

content/events/2021-vancouver/welcome.md, data/events/2021-vancouver.yml
=> [VAN-2021] add Cisco as sponsor and remove CFP

content/events/2021-prague/welcome.md, data/events/2020-prague.yml, data/events/2021-prague.yml
=> [PRG-2021] event postponement

static/_redirects
=> [DFW-2022] Updating redirect

data/events/2021-raleigh.yml
[rdu-2021] added morpheus as a sponsor
=> [rdu-2021] added morpheus as a sponsor

data/events/2021-chicago.yml
=> [CHI-2021] update Christian Herro's bio

data/events/2021-chicago.yml
=> [CHI-2021] Update Sasha's bio

data/events/2021-raleigh.yml
[RDU-2021] Added citrix as sponsor
=> [RDU-2021] Added citrix as sponsor

data/events/2021-vancouver.yml
=> [VAN-2021] add safesoftware as bronze sponsor

content/events/2021-porto-alegre/sponsor.md, content/events/2021-porto-alegre/welcome.md, data/events/2021-porto-alegre.yml
Adding Sponsor page in DOD POA 2021
=> [POA-2021] Adding Sponsor page

content/events/2021-portland/conduct-fr.md, content/events/2021-portland/conduct-pt-br.md, content/events/2021-portland/conduct.md, content/events/2021-portland/contact.md, content/events/2021-portland/location.md, content/events/2021-portland/propose.md, content/events/2021-portland/registration.md, content/events/2021-portland/sponsor.md, content/events/2021-portland/welcome.md, data/events/2021-portland.yml, static/_redirects
We're in! Still a little light on details, but we've got an organizing group and a date planned. CFP up soon!
=> [PDX-2021] Wahoo, 2021 PDX!

.circleci/config.yml, CONTRIBUTING.md, appveyor.yml, hugoserver.ps1, hugoserver.sh, netlify.toml
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
This updates the version of Hugo; it could provide better build performance as well.
=> Update to Hugo 0.81.0

content/events/2021-minneapolis/conduct.md, content/events/2021-minneapolis/contact.md, content/events/2021-minneapolis/covid-19-policy.md, content/events/2021-minneapolis/location.md, content/events/2021-minneapolis/registration.md, content/events/2021-minneapolis/sponsor.md, content/events/2021-minneapolis/welcome.md, data/events/2021-minneapolis.yml
=> MSP 2021 updates

content/events/2019-tel-aviv/speakers/elazar-leibovich.md
We were asked by a former speaker to update their bio and remove any employment references.
Thanks.
=> [2019-TLV] Update Elazar bio

content/events/2021-washington-dc/welcome.md, data/events/2021-washington-dc.yml
=> [DC 2021] Launch with dates

content/events/2021-porto-alegre/sponsor.md, content/events/2021-porto-alegre/welcome.md, data/events/2021-porto-alegre.yml
[POA-2021]  Open CFP DOD Porto Alegre.
=> [POA-2021]  Open CFP

data/events/2021-seattle.yml
add vmware-tanzu as a gold sponsor
=> [SEA-2021] add vmware-tanzu as a gold sponsor

content/events/2021-seattle/program/alan-koch.md
=> [SEA-2021] Fix the Alan Koch talk title

data/sponsors/safesoftware.yml
=> [VAN-2021] update safesoftware URL to new requested URL

content/events/2021-portugal/welcome.md, data/events/2021-portugal.yml
=> [PT-2021] Canceling event

content/events/2021-amsterdam/registration.md
Adds "Attendance is free of charge. You'll have the opportunity to register, and receive reminders about the event, shortly."
=> [AMS-2021] Add registration info

data/events/2021-vancouver.yml
=> [VAN-2021] fix program times

content/events/2021-vancouver/speakers/josh-stella.md
Added profile picture for Josh Stella speaker profile for van2021
=> [VANCOUVER-2021] added speaker photo for Josh Stella to the Vancouver 2021 event

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding 2021 sponsor

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding vmware-tanzu

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding MSP sponsor lacework

data/events/2021-minneapolis.yml
=> Adding LaunchDarkly

data/events/2021-amsterdam.yml
Add our open CFP to the website.
=> [AMS-2021] Add CFP details

content/events/2021-amsterdam/sponsor.md, data/events/2021-amsterdam.yml
This adds sponsor details for the AMS 2021 event.
Please hold till devopsdays/devopsdays-assets#110 is merged
=> [AMS 2021] Add sponsor details for Amsterdam

content/events/2021-seattle/program/emily-freeman.md
Adding Emily Freeman's talk title and abstract
=> [SEA-2021] Adding Emily Freeman's talk title and abstract

content/events/2021-seattle/speakers/emily-freeman.md
Update Emily Freeman's profile.
=> [SEA-2021] Update speaker profile.

content/events/2021-amsterdam/propose.md, data/events/2021-amsterdam.yml
Enable the CFP page on the AMS site to increase visibility
=> [AMS 2021] Add the propose page to the AMS site

content/events/2021-amsterdam/sponsor.md
The sponsor package header was wrong. This PR fixes the header.
=> [AMS 2021] Fix sponsor package header

content/events/2021-minneapolis/propose.md, content/events/2021-minneapolis/welcome.md, data/events/2021-minneapolis.yml
=> [MSP 2021] Open CFP

content/events/2021-amsterdam/sponsor.md
=> [AMS 2021] update the sponsor list to have correct values

data/events/2021-amsterdam.yml
=> [AMS 2021] Add TomTom as sponsor

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding sponsors

data/events/2021-amsterdam.yml
=> [AMS 2021] Add HeleCloud as sponor

data/events/2021-amsterdam.yml
=> [AMS 2021] Add bol.com as sponsor

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding sponsor Microsoft

data/events/2021-bogota.yml
Hello
We appreciate your help validating these changes.
=> [BOG-2021] Event date update

data/events/2021-amsterdam.yml
=> [AMS 2021] Add Schuberg Philis as sponsor

data/events/2021-medellin.yml
Updating Zivra from platinum to diamond
=> [2021-MDE] Updating Level for actual sponsor

content/events/2021-minneapolis/propose.md, content/events/2021-minneapolis/welcome.md, data/events/2021-minneapolis.yml
CFP closing; sponsor add & adjust.
=> [MSP 2021] MSP updates - sponsor and cfp

data/events/2021-amsterdam.yml
=> [AMS 2021] Close silver sponsorships

content/events/2021-amsterdam/conduct.md
Update the Code of Conduct  to reflect online interaction and add coc team contact details.
=> [AMS 2021] Update the Code of Conduct 

data/events/2021-zurich.yml
=> [ZRH2021] Remove sponsor google

data/events/2022-chicago.yml
Update Kevin Reedy's severely out of date bio
=> [CHI-2022] Update Kevin Reedy's bio

data/events/2021-zurich.yml
=> [ZRH-2021] Add sponsor basistechnolgies

data/events/2022-chicago.yml
Just changed the ordering of the organizing team
=> [CHI-2022] Add sponsor and adjust organizers

content/events/2021-medellin/speakers/matt-stratton.md
=> [MDE-2021] Updating Matt Strattin Bio

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding SPS Commerce

data/events/2021-poznan.yml
=> [POZ-2021] Update company

content/events/2020-zurich/welcome.md, content/events/2021-zurich/sponsor.md, content/events/2021-zurich/welcome.md, data/events/2020-zurich.yml
=> [ZRH-2021] Fix devopsdays.ch homepage links

data/events/2021-rio-de-janeiro.yml
=> Remove devrelate as sponsor and replace to scout

content/events/2021-houston/sponsor.md
[HOU-2021] Updated sponsor page to signal Platinum availability
=> [HOU-2021] Updated sponsor page to signal Platinum availability

content/events/2021-minneapolis/covid-19-policy.md, content/events/2021-minneapolis/program.md, content/events/2021-minneapolis/program/ian-coldwater.md, content/events/2021-minneapolis/sponsor.md, content/events/2021-minneapolis/welcome.md, data/events/2021-minneapolis.yml
=> [MSP 2021] Adding detailed MSP schedule

data/events/2021-minneapolis.yml
@bridgetkromhout please review/merge if you are cool with this.
=> [MSP-2021] Add custom url to program

content/events/2022-geneva/propose.md, content/events/2022-geneva/welcome.md
=> [GE-2022] update propose instructions

data/events/2021-minneapolis.yml
Add Chef as a sponsor for MSP.
=> [MSP 2021] Add Chef for MSP

content/events/2021-amsterdam/conduct.md
Don can no longer commit. Rayta offered to take his place.
=> [AMS 2021] Update CoC team - external member

content/events/2021-zurich/covid.md, content/events/2021-zurich/welcome.md, data/events/2021-zurich.yml
=> [ZRH-2021] Add new page with COVID information

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding Dynatrace as sponsor

data/events/2021-boston.yml
The days of the week are the same; the year is not.
=> [BOS-2021] Fix dates poorly copied from 2019 event

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding Firehydrant

data/events/2021-amsterdam.yml
Fix some times while I'm at it.
=> [AMS 2021] Add sponsor Open Spaces

data/events/2021-amsterdam.yml
Adds custom color for fail cafes as well.
=> [AMS 2021] Add Open Spaces

data/events/2021-amsterdam.yml
Sorry for the cleanup lines.
Only change is the sponsor
=> [AMS 2021] Add Paloalto as Bronze sponsor

data/events/2021-portland.yml
=> [PDX-2021] Added silver level sponsor StackHawk

content/events/2021-zurich/sponsor.md
=> [ZRH-2021] Change number of sponsor packages for foyer

content/events/2021-amsterdam/program/dan-lines.md, data/events/2021-amsterdam.yml
- Update talk from Dan to correct description
- Close Escape room signup
=> Last minute schedule fixes

content/events/2021-minneapolis/speakers/dan-woods.md, data/events/2021-minneapolis.yml
- Update speaker bio to reflect job change
- Add new sponsor
=> [MSP 2021] Update speaker details and add sponsor

content/events/2021-zurich/welcome.md, data/events/2021-zurich.yml
=> [ZRH-2021] Publish Program and Speakers

data/events/2021-minneapolis.yml
Andy's twitter account was wrong
=> [2021-MSP] Update Andy Domeier twitter

content/events/2021-minneapolis/speakers/jenessa-white.md
Heck yeah they are on the board of directors, because she is amazing! /cc @jenessawhite 
=> [MSP 2021] Bio update for MSP speaker

data/events/2021-zurich.yml
=> [ZRH2021] Add Swiss Dev Jobs as sponsor

content/events/2021-porto-alegre/speakers/michelle.md
=> [POA-2021] - Ajusting linkedin for speaker

content/events/2021-porto-alegre/speakers/marlon.md
=> [POA-2021] Adjusting speaker name

content/events/2021-minneapolis/registration.md
Adding link for online participation registration option.
=> [MSP 2021] Adding link for online participation reg

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding Target

data/events/2021-houston.yml
=> [HOU-2021] Added Carlos's bio, added ABS as lunch sponsor

content/events/2021-zurich/sponsor.md, data/events/2021-zurich.yml
=> [ZRH-2021] Add sponsor elastic

data/events/2021-minneapolis.yml
=> [MSP 2021] Adding Solace at Silver level

data/events/2021-portland.yml
The CFP is closed, so might as well pull it off of the nav
=> [2021-PDX] Remove propose link

content/events/2021-minneapolis/program/jenessa-white.md
=> [MSP 2021] Updating talk title and description

content/events/2021-minneapolis/registration.md
=> [MSP 2021] Adding slack link

content/events/2021-minneapolis/welcome.md
add slack to welcome page and larger live stream link
=> [2021-MSP] add links for msp

content/events/2021-minneapolis/welcome.md
do not merge until tuesday evening!
=> [MSP-2021] update with wednesday livestream for msp

content/events/2021-minneapolis/program.md, content/events/2021-minneapolis/welcome.md
=> Livestream link fix

content/events/2021-houston/sponsor.md
=> [HOU-2021] Added Sponsor FAQ

content/events/2021-melbourne/welcome.md, data/events/2021-melbourne.yml
- Link to ticket registration added
- Link to Call for Papers added
- Link for our dedicated Melbourne2021 website added
- COVID-19 information banner on welcome page
=> [MEL-2021] Add CfP and Registration links

content/events/2021-washington-dc/welcome.md, data/events/2021-washington-dc.yml
Modified the welcome.md with the language for this year's event and added the link to the open CFP. Also modified the .yml file with the dates and link for the CFP.
=> [DC-2021] Open up the CFP for 2021

content/events/2021-minneapolis/program.md, content/events/2021-minneapolis/registration.md, content/events/2021-minneapolis/welcome.md
=> [MSP 2021] Adjust links

data/events/2021-portland-or.yml
Linking to Busyconf schedule instead of transcribing it into the site.
=> [PDX-2021] Schedule up!

content/events/2021-zurich/hotel.md, content/events/2021-zurich/registration.md, content/events/2021-zurich/welcome.md, data/events/2021-zurich.yml
- Add links to hotels for the event
- Add company discount
- Update COVID-19 Info
=> [ZRH-2021] Changes of week 30

content/events/2021-zurich/program/andrea-giardini.md, content/events/2021-zurich/program/workshop-philipp-krenn.md, data/events/2021-zurich.yml
=> [ZRH-2021] Switch Workshops of Krenn and Giardini]

content/events/2021-zurich/hotel.md
=> [ZRH2021] Fixed the link to the hotel reservation

content/events/2021-portland-or/speakers/laura-santamaria.md
=> [PDX-2021] Update Laura's bio as requested

data/events/2021-houston.yml
[HOU-2021] Added Trendmicro as a sponsor
=> [HOU-2021] Added Trendmicro as a sponsor

content/events/2021-buffalo/welcome.md, data/events/2021-buffalo.yml
- Added TrendMicro as a sponsor
- Resized obnoxiously large ticket button
=> [BUF-2021] Added TrendMicro as a sponsor

content/events/2021-minneapolis/program/caroline-karanja.md, content/events/2021-minneapolis/program/dan-woods.md, content/events/2021-minneapolis/program/heidi-waterhouse.md, content/events/2021-minneapolis/program/ian-coldwater.md, content/events/2021-minneapolis/program/jenessa-white.md, content/events/2021-minneapolis/program/jenna-pederson.md, content/events/2021-minneapolis/program/steve-buchanan.md, content/events/2021-minneapolis/program/tess-flynn.md, content/events/2021-minneapolis/program/vanessa-huerta-granda.md
Adding links to videos and some slides.
=> [MSP 2021] Adding links to MSP (videos, some slides)

data/events/2021-buffalo.yml
Added ACV Auctions as a Silver sponsor.
=> [BUF-2020] Added ACV Auctions as a Silver sponsor

content/events/2021-minneapolis/program/chris-reid.md, content/events/2021-minneapolis/program/daniel-feldman.md, content/events/2021-minneapolis/program/nara-coldwater.md, content/events/2021-minneapolis/program/quintessence-anx.md
Adding links for Ignite videos.
=> [MSP 2021] Adding links to Ignite videos

data/events/2021-houston.yml
=> [HOU-2021] added/removed sponsors

content/events/2021-zurich/welcome.md
=> [ZRH2021] Fixed the website url

content/events/2021-houston/covid-19-policy.md, content/events/2021-houston/faq.md, content/events/2021-houston/welcome.md, data/events/2021-houston.yml
=> [HOU-2021] Added COVID Policy and FAQ

content/events/2022-chicago/welcome.md
=> [CHI-2022] Update to make covid policy look nicer

content/events/2021-zurich/speakers/courtney-heba.md
=> [ZRH-2021] Update Job Profile of Courtney

content/events/2021-portland-or/program.md, data/events/2021-portland-or.yml
add timing of open spaces as well as the spaces themselves to the schedule, also restore the open space details to the schedule page
=> [PDX-2021] add open spaces to schedule

content/events/2021-boston/sponsor.md, data/events/2021-boston.yml
=> [BOS-2021] Updated the sponsor page to include messaging about being sold out

data/events/2021-houston.yml
=> [HOU-2021] Removed a couple of sponsors, corrected times for workshops

content/events/2021-washington-dc/sponsor.md
Updating sponsor page with links to sponsorship purchase.
=> [dc-2021] add sponsorship purchase links

content/events/2021-houston/speakers/ernest-mueller.md, data/events/2021-houston.yml
=> [HOU-2021] Updated Ernest Mueller's bio

content/events/2021-houston/sponsor.md, data/events/2021-houston.yml
=> [HOU-2021] Added sponsor, removed sponsor link

data/events/2021-washington-dc.yml
=> [DC-2021] add Excella sponsorship

content/events/2021-houston/speakers/mikhail-kozorovitskiy.md
Updating Mikhail’s bio, by request.
=> [HOU-2021] Update Mikhail’s bio

data/events/2021-washington-dc.yml
=> [DC-2021] Cloudsmith is a gold sponsor

content/events/2021-houston/program/jj-asghar.md, content/events/2021-houston/speakers/jj-asghar.md
Can you double-check this @skryukova?
=> [HOU-2021] Adding JJs Abstract

data/events/2021-boston.yml
=> [BOS-2021] Update Aaron Aldrich's organizer bio

content/events/2021-portland-or/speakers/areti-panou.md
I would swear I already put this in, but, 🤷
=> [PDX-2021] Update Areti's bio

content/events/2021-boston/speakers/chris-riley.md, data/sponsors/launch-darkly.yml, data/sponsors/styra.yml
I am changing the title text of two sponsors to be human-readable, and one speaker's name to be spelled correctly.
=> [BOS-2021] Minor spelling fixes

content/events/2021-portland-or/program/ceora-ford.md, data/events/2021-portland-or.yml
=> [PDX-2021] Swapping out Ceora's talk and QA

content/events/2021-portland-or/speakers/jace-warren.md
=> [PDX-2021] Jace's Twitter link was totally wrong

data/events/2021-boston.yml
There will be further updates to the program as some of these breakouts gain titles.
=> [BOS-2021] Add breakouts to program

content/events/2022-geneva/registration.md, content/events/2022-geneva/welcome.md, data/events/2022-geneva.yml
add community sponsor and open registration
=> [GE-2022] add community sponsor and open registration

.gitpod.yml, data/events/2019-montreal.yml, data/events/2020-medellin.yml, data/events/2020-porto-alegre.yml, data/events/2021-houston.yml, data/events/2021-texas.yml, themes/devopsdays-theme/layouts/partials/events/cta.html
Latest hugo is more picky about TOML; this also is initial support for trying this with gitpod
=> Update for latest hugo compatibility and add gitpod support

content/events/2021-washington-dc/welcome.md
- Removed CFP content asking for proposals since proposals are now closed.
=> [DC-2021] fix: removed CFP content

data/events/2021-tel-aviv.yml
=> [TLV-2021] Add JFrog as sponsor

content/events/2021-cairo/speakers/pranjal-deo.md
=> [2021-CAI] Fix Pranjal Deo image

.circleci/config.yml, hugoserver.ps1, hugoserver.sh, netlify.toml
=> Update to hugo 0.88.1

content/events/2021-washington-dc/welcome.md, data/events/2021-washington-dc.yml
Add links to the program/schedule, speakers, and registration in Hopin. Also make some changes to the content on the welcome.md page.
=> [DC-2021] Add the program, open up registration, and make other content changes

data/events/2021-tel-aviv.yml
- removed sponsor and propose from the menu
- added registration start and end dates + link
=> [TLV-2021] Some late site changes

data/events/2022-chicago.yml
=> [CHI-2022] Update 2022 chicago with open sponsorship and cfp dates

content/events/2022-chicago/propose.md, data/events/2022-chicago.yml
=> [CHI-2022] Add CFP

data/events/2022-geneva.yml
=> [GE-2022] add sponsors

content/events/2022-boise/conduct-fr.md, content/events/2022-boise/conduct-pt-br.md, content/events/2022-boise/conduct.md, content/events/2022-boise/contact.md, content/events/2022-boise/location.md, content/events/2022-boise/propose.md, content/events/2022-boise/registration.md, content/events/2022-boise/sponsor.md, content/events/2022-boise/welcome.md, data/events/2022-boise.yml
[Boise-2022] Adding location, times, and additional sponsors
=> Boise DevOps Days 2022 Event Details

content/events/2022-geneva/propose.md, content/events/2022-geneva/sponsor.md, content/events/2022-geneva/welcome.md, data/events/2022-geneva.yml
[GE-2022] cfp end + silver sponsor packs sold out
=> [GE-2022] cfp end + silver sponsor packs sold out

content/events/2022-chicago/propose.md
=> [CHI-2022] Fix cfp link

content/events/2022-birmingham-uk/covid.md, content/events/2022-birmingham-uk/welcome.md, data/events/2022-birmingham-uk.yml
WE ARE ON!
We have secured our venue and paid the deposit. Nothing can stop us now.
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
=> [BIRM-UK-2022] GO LIVE - venue deposit paid

data/events/2022-geneva.yml
=> [GE-2022] add sponsor

content/events/2022-birmingham-uk/welcome.md, data/events/2022-birmingham-uk.yml
Add our CFP link to welcome page
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
=> [BIRM-UK] Add CFP link to Welcome

data/events/2022-los-angeles.yml, data/sponsors/edge-delta.yml
[la22] add edge delta as sponsor
=> [la22] add edge delta as sponsor

data/events/2022-los-angeles.yml
[LA 22] add circle ci as sponsor
=> [LA 22] add circle ci as sponsor

content/events/2022-raleigh/sponsor.md
[RDU-2022] updated link to sponsorship package pdf
=> [RDU-2022] updated link to sponsorship package pdf

data/events/2022-los-angeles.yml
[la 2022] add solo.io as sponsor
=> [la 2022] add solo.io as sponsor

content/events/2022-denver/sponsor.md
=> [DEN-2022] Updating link to prospectus

content/events/2022-geneva/program/aurelie-vache.md
=> [GVA-2022] Aurelie talk update

data/events/2017-zurich.yml, data/events/2018-zurich.yml, data/events/2019-zurich.yml, data/events/2020-zurich.yml, data/events/2021-zurich.yml, data/events/2022-zurich.yml
=> [ZRH-2022] Add new Google Analytics Tracking ID

content/events/2022-atlanta/location.md, content/events/2022-atlanta/program.md, content/events/2022-atlanta/speakers.md, data/events/2022-atlanta.yml
Added template info for Program, Speakers, and Location. 
Cheers!
-Ravi
=> [ATL-2022] - Updated Program, Speakers, and Location

content/events/2022-geneva/program/david-barbarin.md, data/events/2022-geneva.yml
[GE-2022] modify one program title and add sponsor
=> [GE-2022] modify one program title and add sponsor

data/events/2017-zurich.yml, data/events/2018-zurich.yml, data/events/2019-zurich.yml, data/events/2020-zurich.yml, data/events/2021-zurich.yml, data/events/2022-zurich.yml
=> [ZRH-2022] Fixed wrong Google Analytics ID

data/events/2022-los-angeles.yml
[la 2022] add linearb as sponsor
=> [la 2022] add linearb as sponsor

data/events/2022-chicago.yml
=> [CHI-2022] Adding Solo.io as 2022 Sponsor

content/events/2022-vitoria/zeroday.md, data/events/2022-vitoria.yml
=> [VIX-2022] Add page from zeroday

content/events/2022-tokyo/conduct.md, content/events/2022-tokyo/contact.md, content/events/2022-tokyo/location.md, content/events/2022-tokyo/welcome.md, data/events/2022-tokyo.yml
=> [TYO-2022] Add DevOpsDays Tokyo 2022

data/events/2022-raleigh.yml
=> [rdu-2022] adding sponsors

data/events/2022-chicago.yml
=> [CHI-2022] Adding Sponsor LinearB

content/events/2022-zurich/sponsor.md, content/events/2022-zurich/welcome.md, data/events/2022-zurich.yml
=> [ZRH-2022] Added the sponsoring

content/events/2022-aarhus/location.md, content/events/2022-aarhus/program.md, content/events/2022-aarhus/program/emil-holm-naurby.md, content/events/2022-aarhus/program/henning-kjaer.md, content/events/2022-aarhus/program/kasper-nissen.md, content/events/2022-aarhus/program/mathias-grund.md, content/events/2022-aarhus/program/rasmus-hald.md, content/events/2022-aarhus/speakers/emil-holm-naurby.md, content/events/2022-aarhus/speakers/henning-kjaer.md, content/events/2022-aarhus/speakers/kasper-nissen.md, content/events/2022-aarhus/speakers/mathias-grund.md, content/events/2022-aarhus/speakers/rasmus-hald.md, content/events/2022-aarhus/welcome.md, data/events/2022-aarhus.yml
This pull request changes the date to our new dates and adds the confirmed speakers to the new date. 
Ticket holders have been informed with option to refund or keep ticket.
=> [Aar/2022] Update Agenda and change date

content/events/2022-zurich/sponsor.md
=> [ZRH-2022] Add link to general sponsoring rules.

data/events/2022-los-angeles.yml
[la 22] add trilio to DOD LA 22
=> [la 22] add trilio to DOD LA 22

content/events/2022-vitoria/conduct-pt-br.md, data/events/2022-vitoria.yml
=> [VIX-2022] Add page conduct-pt-br.

data/events/2022-denver.yml
=> [DEN-2022] Add event location, sponsors, CFP

data/events/2022-boston.yml
Old date conflicted with Yom Kippur; new date is now confirmed with our venue.
=> [BOS-2022] Move conference date

content/events/2022-zurich/sponsor.md, data/events/2022-zurich.yml
=> [ZRH2022] Add sponsor basis and avega.

data/events/2022-raleigh.yml
[RDU-2022] added replicated as sponsor
=> [RDU-2022] added replicated as sponsor

content/events/2022-zurich/sponsor.md, data/events/2022-zurich.yml
=> [ZRH2022] Add Zuhlke as sponsor

themes/devopsdays-theme/layouts/partials/past.html
=> Increment year max

data/events/2022-los-angeles.yml
=> [la 2022] add confluent

data/events/2022-los-angeles.yml
=> [la22] fix gremlin

data/events/2022-los-angeles.yml
=> [la 22] New Dates

data/events/2020-austin.yml
2020 austin was canceled but still shows up on lists
=> add cancel flag to 2020 austin

data/events/2022-raleigh.yml
[rdu-2022] adding redhat as sponsor
=> [rdu-2022] adding redhat as sponsor

content/events/2022-zurich/covid.md
=> [ZRH2022] Add new COVID protection concept

data/events/2020-columbus.yml, data/events/2020-miami.yml
In my big PR to clean the TBD list, there were two that got missed.
- Columbus had a 'boolean' set for cancel, removed
- I missed Miami in my PR
This PR addresses both.
=> Fix last two cities still listed under TBD

data/events/2022-los-angeles.yml
=> [la 2022] add transposit

data/events/2022-melbourne.yml
Due to ongoing restrictions and high case numbers we've made the call to
cancel this year's event and reconvene for next year.
=> [MEL-2022] Cancelling Melbourne 2022 event

content/events/2022-zurich/sponsor.md, data/events/2022-zurich.yml
=> [ZRH2022] Add Check Point as a sponsor

content/events/2022-aarhus/program/emil-holm-naurby.md, content/events/2022-aarhus/program/karina-popova.md, content/events/2022-aarhus/program/lars-kruse.md, content/events/2022-aarhus/program/noaa-barki.md, content/events/2022-aarhus/program/thomas-krag.md, content/events/2022-aarhus/speakers.md, content/events/2022-aarhus/speakers/karina-popova.md, content/events/2022-aarhus/speakers/lars-kruse.md, content/events/2022-aarhus/speakers/noaa-barki.md, content/events/2022-aarhus/speakers/thomas-krag.md, data/events/2022-aarhus.yml
Hello lovely person, 
This pull request strives to achieve the following:
- 🎤 Add the final ( except for one ) speakers to the agenda 
- 🙈 Add speakers page so we don't just get a 404 
- 💡 Add the awesome Merkely as a silver sponsor
Thanks!
=> [Aar/2022] Finalize speakers

data/events/2022-eindhoven.yml
As discussed in the organisation meeting we slim down to 2 days for the first event in EHV.
=> [EHV-2022] Update event dates. From 3 to 2 days.

data/events/2022-raleigh.yml
=> [rdu-2022] adding new sponsor

content/events/2022-aarhus/program/justin-reock.md, content/events/2022-aarhus/speakers/justin-reock.md, data/events/2022-aarhus.yml
Hi Awesome Folks.
This convenient pull request gives the Aarhus team the following super powers:
- 🐘 Justin Reock from Gradle has been added with an awesome keynote on Developer Productivity Engineering
- 🤑 Styra has gracefully chosen to also sponsor DevOpsDays Aarhus
- 👩‍💼 Johanne has changed job, congratulations!
=> [Aar-2022] Add Styra and Justin Reock, Update Johanne
